### ISSUE TITLE
Make the Promise timeout value configurable

### ISSUE THREAD

**Issue by nraychaudhuri** [playframework/playframework#1002]
Promise.timeout right now uses a default timeout value. It will be nice to get this value from the conf file.

**Comment by bdmstyle** [comment]
what is the conf to change default promise timeout? i'm not found.

**Comment by cchantep** [comment]
@bdmstyle this issue is close. Please ask question on the [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework).

**Comment by vinitsharma87** [comment]
@jroper I am using Play 2.4.6. One of my Promise<Result> api function takes up more time in calculating data. This api does not shows any error on TEST or DEV mode, but it only shows the "Futures timed out after [10000 milliseconds]" error in PRODUCTION mode.

Can you please help me regarding how I can add for an extension of timeout for this particular api causing Future timeout problem. Any help would be appreciated.

P.S.: Since I can not access the latest Mailing list, so that's why posting my query here.

Thanks.
