### ISSUE TITLE
Failed: Akka - Detected possible incompatible versions on the classpath

### ISSUE THREAD

**Issue by renatocaval** [playframework/playframework#10047]
On CRON master

https://travis-ci.com/playframework/playframework/jobs/285313693#L752

This is flaky and odd. I have seen it before. The scripted test fails with

```
Detected possible incompatible versions on the classpath. 
Please note that a given Akka version MUST be the same across all modules of Akka 
that you are using, e.g. if you use [2.6.3+39-1b4da3d1] all other modules that 
are released together MUST be of the same version. Make sure you're using a 
compatible set of libraries. Possibly conflicting versions [2.6.3, 
2.6.3+39-1b4da3d1] in libraries [akka-actor-typed:2.6.3, akka-
actor:2.6.3+39-1b4da3d1, akka-slf4j:2.6.3, akka-protobuf-v3:2.6.3+39-1b4da3d1, 
akka-stream:2.6.3+39-1b4da3d1] (ManifestInfo.scala:206)
```

while I don't see any reason for 2.6.3 being used instead of the snapshot version. Somewhere, something is pulling 2.6.3. What is odd, is why this is not always failing.

**Comment by renatocaval** [comment]
Happened again on CRON master

https://travis-ci.com/playframework/playframework/jobs/285739395#L1013

**Comment by renatocaval** [comment]
Again https://travis-ci.com/playframework/playframework/jobs/286195049#L758

This is clearly not a flaky test anymore.

**Comment by raboof** [comment]
The diagnostics in https://travis-ci.com/playframework/playframework/jobs/287932905#L2899 show that the `com.typesafe.play:play_2.12:2.8.1+223-64a580d8` that is used in this test depends on Akka 2.6.3 instead of Akka 2.6.3+65-56c13dcd.

Do we want the cron travis build to:
* build against Akka 2.6.3 for both the main build and the scripted tests
* build against Akka snapshot for both the main build and the scripted tests
* build Play against Akka 2.6.3 but run the scripted tests with an Akka snapshot?

**Comment by ennru** [comment]
This still fails
https://travis-ci.com/playframework/playframework/jobs/289135295#L3745

**Comment by renatocaval** [comment]
I won't have much time to continue on this today. And next week I'm off. 

I will unassign myself.

**Comment by dwijnand** [comment]
> Though in any case, perhaps it's weird to have a different Play artifacts with the same version number (2.8.1+223-64a580d8) but different contents (against Akka 2.6.3 and against Akka snapshots). Perhaps we should add a marker to the version number when building against Akka snapshots?

Good call, Arnout.  The whole point of sbt-dynver is try and create stable versions (with nicer names than the hash of the contents).  But the setup doesn't take into account that TRAVIS_EVENT_TYPE=cron is changing the contents.  Let's propagate that in the version number (in dynver I use timestamp, which I think might be a good fix here).

Btw, I think this might've regressed since https://github.com/playframework/playframework/pull/10014.  The reason I believe that deleting the Play artifacts from ivy cache would avoid this, is because we run the scripted tests on sbt 1.2, which uses Ivy and its cache.  If/when Play no longer runs its tests with ivy's cache, then it would break again.

I don't have further time to spend on this today.

**Comment by jrudolph** [comment]
Failed a few more times in

https://travis-ci.com/playframework/playframework/builds/150127608
https://travis-ci.com/playframework/playframework/builds/150181900
https://travis-ci.com/playframework/playframework/builds/150238220

**Comment by raboof** [comment]
seems to have done the trick (https://travis-ci.com/playframework/playframework/builds), let's reopen when it pops up again
