### ISSUE TITLE
Upload empty file

### ISSUE THREAD

**Issue by ksv510** [playframework/playframework#10113]
We have found the following PR https://github.com/playframework/playframework/pull/8882/files#diff-20801290d88b7f6470285127f95c3f0dR559

> For obvious reasons however, uploading an empty file doesn't make a lot of sense

Why do you think that there is no sense to upload an empty file? 

For example, I have implemented TODO list based on files. And file name is something like category. In this case, I cannot create empty category.

I know that this example is far-fetched. But all file systems allow creating empty file, so I believe you should too. 

Currently, we need to upload empty files and we will make some hack to do it (((

**Comment by mkurz** [comment]
Interesting. Maybe we can make that configurable. For the multipartform body parser and globally via application.conf.
Do you use java or scala?

**Comment by ksv510** [comment]
we use Java. It would be great if we can configure it. Thank you for the fast reply.

**Comment by JoeSilentJoe** [comment]
The same problem. When can I wait for the ability to download empty files to return?

**Comment by mkurz** [comment]
I am very busy right now with other things, however maybe I can have a look in the next couple of days.

**Comment by JoeSilentJoe** [comment]
Thanks! It would be great!

**Comment by JoeSilentJoe** [comment]
Hello @mkurz !

Is there any progress on this issue?

**Comment by mkurz** [comment]
@JoeSilentJoe Not yet, sorry. Even if I would fix this today, a new Play release will take a while anyway I guess. I put it onto my TODO list, hopefully the next days.

**Comment by mkurz** [comment]
@ksv510 When you say empty category/empty file, do you mean you upload a file without body but with a filename? Or is the filename also non-existent? Can you post how the request (headers) looks like?

**Comment by mkurz** [comment]
@ksv510 @JoeSilentJoe Here is the fix: #10236
Starting with Play 2.9 you will be able to set
```
play.http.parser.allowEmptyFiles = true
```
in `conf/application.conf` to globally allow empty file uploads.

However, because of compatibility reasons that config can't be backported to 2.8.x and 2.7.x.

**But** what I did is in #10237 and #10238 I backported the needed coded so you will be able to write your own body parsers that allow empty file uploads.
I uploaded an [example app](https://github.com/mkurz/play-empty-upload-allowed):
All you need to do is define a custom body parser that extends from `BodyParser.MultipartFormData`:
https://github.com/mkurz/play-empty-upload-allowed/blob/master/app/bodyparsers/CustomMultipartFormData.java
You can then use this body parser on your actions:
https://github.com/mkurz/play-empty-upload-allowed/blob/master/app/controllers/HomeController.java#L15

This will work once Play 2.8.2 and 2.7.5 is released (again, for Play 2.9.0 this won't be necessary, the config will be enough then)

**Comment by mkurz** [comment]
Probably we can't backport to Play 2.7 because of problems its Scala 2.11 support is causing, see https://github.com/playframework/playframework/pull/10238#issuecomment-620201491

**Comment by JoeSilentJoe** [comment]
> When you say empty category/empty file, do you mean you upload a file without body but with a filename? Or is the filename also non-existent? 

Upload a file without body but with a filename
