### ISSUE TITLE
Is it better to use UTF_8 encoding than US_ASCII?

### ISSUE THREAD

**Issue by depeiwang** [playframework/playframework#10371]
source code:
https://github.com/playframework/playframework/blob/cd7a6764eeef692e4edf191e71174f9dfda941bb/core/play/src/main/java/play/mvc/BodyParser.java#L280

**Comment by raboof** [comment]
The comment above the line details that we use the specified charset when available, and otherwise fall back to https://tools.ietf.org/html/rfc6657#section-4 - so that seems correct to me? Or is there any scenario or update to the standard where UTF-8 should reasonably be allowed without specifying that charset in the content type?

**Comment by depeiwang** [comment]
Yeah, you are right, we should follow the standard.
The background of this question I raised is: When I pass a string of non-English json characters to the endpoint, the string received by the server is truncated, and the content is only part of the original payload.
like this:
payload: {"title": "哈哈", price: 123}
server received: 哈哈", price: 123}
then, json parse crashed

**Comment by raboof** [comment]
> And Now: we fixed it, we set request header: "content-type": "application/json; charset=utf-8". it works.

Great!
