### ISSUE TITLE
play.data.validation.Constraints.Email does not allow hyphen in the first letter

### ISSUE THREAD

**Issue by yamakz5555** [playframework/playframework#10622]
### Play Version

2.7

### API

Java

### Operating System

Windows 10

### JDK

1.8

### Expected Behavior

1. Implement form validation.
```
@play.data.validation.Constraints.Email
public String email;
```
2. Send the form with email.
```
email: -test@test.com
```
3. Validation is successful.

### Actual Behavior

1. Implement form validation.
```
@play.data.validation.Constraints.Email
public String email;
```
2. Send the form with email.
```
email: -test@test.com
```
3. Validation fails.

**Comment by yamakz5555** [comment]
I searched for Issue.
I read #7140 and realized that it was not fully RFC compliant.

But what I didn't understand was why word boundaries (\b) were implemented.
Word boundaries don't work properly with hyphen.

https://html.spec.whatwg.org/multipage/input.html#email-state-(type=email)
Can you see why it is implemented at word boundaries even though it says `/^ ...... $/` in this content?

**Comment by mkurz** [comment]
So it turns out we have different regex for the Scala and the Java API:
https://github.com/playframework/playframework/blob/a4b4198bf6de7bc599f869971abdf86fa16966c5/core/play/src/main/scala/play/api/data/validation/Validation.scala#L80
https://github.com/playframework/playframework/blob/a4b4198bf6de7bc599f869971abdf86fa16966c5/web/play-java-forms/src/main/java/play/data/validation/Constraints.java#L555

maybe for the next release we can just have one for both.

**Comment by cridmann** [comment]
I can take a look at fixing this for the `2.9.0` release
