### ISSUE TITLE
UnsatisfiedLinkError in loader.load should stop the server

### ISSUE THREAD

**Issue by jxtps** [playframework/playframework#10681]
### Operating System: Ubuntu 20.04

Linux ip-xyz 5.4.0-1037-aws #39-Ubuntu SMP Thu Jan 14 02:56:06 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### JDK

openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)

### Expected Behavior

1. ProdServerStart.start() calls loader.load(context)  
2. loader.load(context) throws an UnsatisfiedLinkError
3. **The java process exits**

### Actual Behavior

1. ProdServerStart.start() calls loader.load(context)  
2. loader.load(context) throws an UnsatisfiedLinkError
3. **The java process continues running but does not respond to HTTP requests**

### Reproducible Test Case

Create a play app with this custom application loader: 
```scala
package misc
class MyApplicationLoader extends ApplicationLoader {
  def load(context: Context): Application = {
    throw new UnsatisfiedLinkError("Test")
  }
}
```
In `application.conf` add
```
play.application.loader = misc.MyApplicationLoader
```

### Fix

1. [The pidfile should be cleaned](https://github.com/playframework/playframework/blob/master/transport/server/play-server/src/main/scala/play/core/server/ProdServerStart.scala#L87) for both Exceptions and Errors, so should be `case e: Throwable`, not `case NonFatal(e):`
2. [`process.exit()`](https://github.com/playframework/playframework/blob/master/transport/server/play-server/src/main/scala/play/core/server/ProdServerStart.scala#L92) should be called for both Exceptions and Errors, so should also be `case e: Throwable`, not `case NonFatal(e):`

**Comment by jxtps** [comment]
### Workaround
Inside your `MyApplicationLoader.load`, wrap your code in a `try ... catch case t: Throwable => throw new RuntimeException(t)`. 

(Not generally recommended obviously, but that will clear out the PID and stop the java process. Catch `Error` instead of `Throwable` if you prefer)

**Comment by jxtps** [comment]
Root cause is that `NonFatal` doesn't catch `LinkageError` (superclass of `UnsatisfiedLinkError`): 

```scala
object NonFatal {
   /**
    * Returns true if the provided `Throwable` is to be considered non-fatal, or false if it is to be considered fatal
    */
   def apply(t: Throwable): Boolean = t match {
     // VirtualMachineError includes OutOfMemoryError and other fatal errors
     case _: VirtualMachineError | _: ThreadDeath | _: InterruptedException | _: LinkageError | _: ControlThrowable => false
     case _ => true
   }
```
Arguably all of those should still lead to the java process exiting.

**Comment by mkurz** [comment]
I think this is a legit suggestion.
@jxtps Do you want to provide a pull request? If everyhing goes well we can include a patch in the upcoming 2.8.8 release.

I did some research to see if someone had a reason to catch `NonFatal` instead of a `Throwable`, but I could not find one:
* The pull request for the pid file deletion: #7883
* Long time ago, instead of catching `NonFatal` to exit the process, `Exception` was caught: #549 - but this looks like it was just a find + replace task, without any intention. Before that there was #478, which just fixed a compiler warning when omitting `Exception`.

I was thinking maybe this code was once shared between dev and prod server, so just catching `NonFatal` would make sense to not exit the JVM in dev mode, however because we are talking about `ProdServerStart.scala` it should be totally OK to exit the process.

**Comment by mkurz** [comment]
@jxtps I created the pull request: #10690

**Comment by jxtps** [comment]
Excellent, pull request looks great, thanks!
