### ISSUE TITLE
PlayMinimalScala?

### ISSUE THREAD

**Issue by gabrieljones** [playframework/playframework#10778]
I see there is a [PlayMinimalJava](https://github.com/playframework/playframework/blob/eedbc75256d772e9a94e65f1a7c83d4549e0518c/dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala#L56) plugin
Can we also have a PlayMinimalScala plugin?

**Comment by mkurz** [comment]
> Can we also have a PlayMinimalScala plugin?

What you want is the `PlayWeb` plugin, which is the same like `PlayMinimalJava` _minus_ the Java stuff:
https://github.com/playframework/playframework/blob/2.8.7/dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala#L38-L46
So that is basically (or _exactly_) the `PlayMinimalScala` plugin what you are looking for.

If you want even less dependencies you can use the `PlayService` plugin
https://github.com/playframework/playframework/blob/2.8.7/dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala#L18-L29
which does _not_ even depend on twirl, sbtjstask and the routes compiler. 

All this plugins come with the akka-http server by default - but you can even disable that one in `build.sbt`
```
lazy val root = (project in file("."))
  .enablePlugins(PlayService)
  .disablePlugins(PlayAkkaHttpServer)
```
I think that is the lightest you can have.

**Comment by godenji** [comment]
For stripped down Play API server (no twirl, web, etc.) you can do:
```
lazy val root =
  (project in file("."))
    .enablePlugins(PlayAkkaHttpServer)
    .enablePlugins(RoutesCompiler)
```
That pulls in the least number of dependencies (N.B. you'll need to use `src/main/scala` maven style layout).

**Comment by mkurz** [comment]
I think there is nothing more to add. Let's close this.

**Comment by mkurz** [comment]
I think there is nothing more to add, let's close this issue.

**Comment by mkurz** [comment]
I think there is nothing more to add, let's close this issue.
