### ISSUE TITLE
Evolutions broken for SQLite

### ISSUE THREAD

**Issue by schnoddelbotz** [playframework/playframework#10832]
Evolutions currently contain SQL incompatible with SQLite:
https://github.com/playframework/playframework/blob/master/persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala#L172
See:
https://stackoverflow.com/questions/3789172/sqlite-select-for-update-wait-10-compatibility

**Comment by mkurz** [comment]
The SQL in the line you are referring to only will only be executed if you set `useLocks` to `true` in application.conf (by default it is `false`). The documentation about `useLocks` [says](https://www.playframework.com/documentation/2.8.x/Evolutions#Evolutions-configuration):
> `useLocks` - ... **This will only work for Postgres, Oracle, and MySQL InnoDB. It will not work for other databases.** Defaults to false.

So I don't think there is anything wrong. When using SQLite, just don't use `useLocks`. That means if you have multiple play app instances accessing the same SQLite database, make sure actually only one runs evolutions, the other instances should disable it.

However... after reading
* https://stackoverflow.com/a/46949541/810109
* https://www.sqlite.org/transactional.html
* https://www.sqlite.org/lang_transaction.html

I think it should be OK for SQLite to "support" `useLocks` by simply ignoring it, because, given the informationin the referenced resources about how SQLite operates, it should be safe even when multiple app instances try to run evolutions against a single SQLite db.

**Comment by schnoddelbotz** [comment]
Sorry for eratically assuming a bug here :( -- but thanks a lot for your quick, awesome help!
There's only one instance in my case, so restoring the default of `useLocks=false` should work just fine.
I'm using a pre-built app that allows me to control JDBC URL via environment variables -- but (up to now) 'statically' enables `useLocks=true`.
Thanks!
