### ISSUE TITLE
Result.charset() is not set when using json

### ISSUE THREAD

**Issue by jguthriedodax** [playframework/playframework#10912]
From what I can tell, the Result.charset() optional is blank when querying a json Result.

When the content-type is set to `application/plain`, then the charset is set as utf-8, but when its `application/json`, its empty.

### Expected Behavior

1. `Result res = Results.ok(Json.toJson("[\"test\": 3]"))` 
Expect `res.charset().get()` to return 'UTF-8'

### Actual Behavior
Returns an Exception that the Optional is empty

**Comment by gmethvin** [comment]
`charset()` is referring to the `charset` parameter in the `Content-Type`. When Play sends a JSON response, it sets `Content-Type: application/json`, with no `charset` parameter, because the `charset` parameter has no meaning for the `application/json` content type. When Play sends a JSON response it is always encoded as UTF-8, as required by RFC8259.
