### ISSUE TITLE
PUBLISHED_LOCAL_COMMIT_HASH not found

### ISSUE THREAD

**Issue by raboof** [playframework/playframework#10943]
The `publishLocal` travis job should write a PUBLISHED_LOCAL_COMMIT_HASH to the workspace, and later picks them up in the jobs performing scripted tests.

This file was not found in https://app.travis-ci.com/github/playframework/playframework/builds/233575133 . The other scripted job used the same workspace (`233575133/published-local.tgz`), though, and did find it. Was it deleted somehow?

**Comment by raboof** [comment]
Same in https://app.travis-ci.com/github/playframework/playframework/builds/233838337 for master :thinking:

**Comment by raboof** [comment]
https://app.travis-ci.com/github/playframework/playframework/builds/234151598 also looks very similar

**Comment by mkurz** [comment]
This is very very strange. Especially for [this build](https://app.travis-ci.com/github/playframework/playframework/builds/234151598):

![image](https://user-images.githubusercontent.com/644927/128333712-24e03a50-d071-433b-ab50-c93f638ac8a8.png)
The first one works, but the others fail (because they can't find the file `PUBLISHED_LOCAL_COMMIT_HASH`)??? I just checked, the file `PUBLISHED_LOCAL_COMMIT_HASH` never gets deleted by by a script...
Also this error is very new and appeared out of the blue.
IMHO I think there is a problem with Travis.

**Comment by mkurz** [comment]
Since I guess this was related to Travis I am closing. We use GHA now.
