### ISSUE TITLE
[2.8.15] CVE-2020-36518 in Jackson

### ISSUE THREAD

**Issue by PromanSEW** [playframework/playframework#11217]
Looks like Maven shows problem with Jackson in 2.8.15:
https://mvnrepository.com/artifact/com.typesafe.play/play_2.13/2.8.15
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36518
https://nvd.nist.gov/vuln/detail/CVE-2020-36518
https://github.com/FasterXML/jackson-databind/issues/2816

Fix is available only for 2.12.x and 2.13.x branch, Play uses 2.11.x, there is no information for this branch
Maybe it is not affected:
https://github.com/advisories/GHSA-57j2-w4cx-62h2

**Comment by mkurz** [comment]
That is the same story as in https://github.com/playframework/play-json/issues/632 and https://github.com/playframework/play-json/issues/633.
So IMHO for the next major release it now makes sense to finally upgrade to latest Jackson for play and  play-json.
For CVE-2020-36518 however I think users should upgrade the dependency themselves when on Play 2.8.x... Since I don't want to introduce breaking changes into production apps in 2.8.x. I will write an announcement about the CVE-2020-36518 in the GitHub Discussions soon.

Jackson 2.13 PR for play-json: https://github.com/playframework/play-json/pull/740
For Play: #11219

**Comment by mkurz** [comment]
@PromanSEW I added a post on the CVE, please see #11222 how to upgrade to latest Jackson version.
I will close this issue now we have to pull request for 2.13 for the main branch.
