### ISSUE TITLE
Adding support for checking URL with protocol='bundleresource' existence

### ISSUE THREAD

**Issue by asaelitz** [playframework/playframework#11251]
Hi.

Can you please add the merged PR: [#11108 ](https://github.com/playframework/playframework/pull/11108) to the next release.

Thanks,
Asael

**Comment by mkurz** [comment]
@asaelitz Yes, we can.

**Comment by asaelitz** [comment]
Thanks!

**Comment by asaelitz** [comment]
For general knowledge, how do you decide which PR you taking for the next release?

**Comment by mkurz** [comment]
If you mean the next 2.8.x release, we usually include bug fixes. We are also not reluctant to add (small) new features, as long as they don't break binary compatibility, however every code change could possibly break other behaviour, that's why new features usually should be merged in the the main (=dev) branch, not the 2.8.x one.

**Comment by PromanSEW** [comment]
Fixed by #11252
