### ISSUE TITLE
SBT 1.9: Deprecation of itSettings, migration not possible due to missing configuration of play evolutions base directory

### ISSUE THREAD

**Issue by Nezisi** [playframework/playframework#11816]
Just a heads-up:

https://github.com/sbt/sbt/pull/7261

Deprecates itSettings and suggests moving to a subproject approach.

As I migrated to a subproject (which is prettry trivial), the play evolutions became a major blocker.

Previously:
- itSettings belonging to the project "api" owning the evolutions
- evolutions were thus read from the project folder of "api/conf/evolutions"

After migration:
- separate project "api-integration-tests"
- evolutions are now read from the project folder "api-integration-tests/conf/evolutions"

As the Play JDBC EvolutionReader directly uses the Environment.scala ( https://github.com/playframework/playframework/blob/main/core/play-configuration/src/main/scala/play/api/Environment.scala ) to read files from the "rootPath", there appears to be no possibility to configure the correct path.

After searching for related issues, I found: https://github.com/playframework/playframework/pull/3967 

As it isn't possible to change the evolutions folder, I'd guess there is no way to "properly" migrate an Play Project using Play Evolutions from itSettings to a subproject approach.

**Comment by mkurz** [comment]
Didn't look close into this right now, however was closed because the original author #3967 didn't want to continue working on it. Configuring the path where evolutions are read from sounds like a reasonable requirement, and if it helps to solve other problems we might want to look into that again.
@Nezisi you want to give it a try and see if you can make the evolutions path configurable?
