### ISSUE TITLE
Can't use custom dispatcher for akka stream in DEV mode

### ISSUE THREAD

**Issue by TheDeadOne** [playframework/playframework#11905]
I’m trying to use a custom dispatcher with akka stream like this :
```java
Source.single("qwerty").withAttributes(ActorAttributes.dispatcher("play.db.dispatcher"));
```

And it works in PROD mode, but fail with the following error in DEV :
```
akka.ConfigurationException: Dispatcher [play.db.dispatcher] not configured for path akka://play-dev-mode/system/StreamSupervisor-0/...
```

Play 2.7.8
Java API
openjdk version "1.8.0_362"

**Comment by mkurz** [comment]
I think this is because the backend server has to know about this config, but in dev  mode the backend server is not able to read application.conf because the server starts up before an application does (apps shutdown and start again if you change files but the server always runs). Please try to set the config in `build.sbt` (in addition to you application conf with:

```sbt
PlayKeys.devSettings += "play.db.dispatcher" -> ...
```

**Comment by TheDeadOne** [comment]
@mkurz you're right, It works when configured like this. Sometimes I want devserver without hot reload and all this nuances.
