### ISSUE TITLE
idea: drop CoffeeScript

### ISSUE THREAD

**Issue by mfirry** [playframework/playframework#12045]
I think it'd be a nice idea for Play 3 to also drop CoffeeScript support. To be fair it'd be interesting to have Scala.js support and/or TypeScript.

**Comment by ihostage** [comment]
There is nothing to drop in Play. CoffeeScript is supported by [sbt-web](https://github.com/sbt/sbt-web) and [sbt-coffeescript](https://github.com/sbt/sbt-coffeescript#sbt-coffeescript) plugins. 😉 

Play just has an info in docs about using CoffeeScript, nothing more 🤷‍♂️ 

FYI: We don't plan to drop something in Play 3, maybe only in the next versions. Because Play 3 should be equivalent of Play 2.9 with only one difference — Pekko instead of Akka. (For more details see https://www.playframework.com/documentation/2.9.x/General#Introducing-Apache-Pekko-and-Play-3.0)
