### ISSUE TITLE
akka migration/changes documentation

### ISSUE THREAD

**Issue by schmitch** [playframework/playframework#12206]
### Are you looking for help?

actually in play 2.9 , 3.0 the akka configuration is immutable according to https://www.playframework.com/documentation/3.0.x/Migration29?#Removed-play.akka.config-setting and it also looks like that this is the case. however this is problematic.

1. the docs actually say that it's not a good idea to have your own actor system: https://www.playframework.com/documentation/2.8.x/ScalaAkka#Configuration
2. running two actor systems for play is extremly heavyweight
3. it's not easy to create custom dispatchers , in the past you just added the config:
```
  database-dispatcher {
    type = Dispatcher
    # What kind of ExecutionService to use
    executor = "thread-pool-executor"
    # Configuration for the fork join pool
    thread-pool-executor {
      fixed-pool-size = ${play.db.prototype.hikaricp.maximumPoolSize}
    }
    throughput = 1
  }
```
now you need to create your own actor system.

I think either the docs will be changed and new examples are created for  https://www.playframework.com/documentation/2.9.x/ScalaAkka#Configuration / https://www.playframework.com/documentation/3.0.x/ScalaPekko#Configuration or the akka configuration shouldn't be immutable?

### Play Version

2.9,30

**Comment by mkurz** [comment]
I think there is a misunderstanding: The `akka.*` configuration is NOT immutable. The only thing we removed is the `play.akka.config` config, so you can not longer change the default akka key play is using. The Play actor system will always be loaded from `akka.*`, no way to change that now. Until Play 2.8 you could (in theory) change that so Play's actor system would get loaded from `foobar.*` if you set `play.akka.config = foobar`. However, as documented, this was not working correctly, because we still hardcoded Play specific actor settings to be under the `akka.*` key (even if you set `play.akka.config = foobar`), so this was just a half-baked "solution".

So, the only thing we removed in Play 2.9+ is the possibility to use another config key for the default Play actor system (because it wasn't working correctly anyway).
So if you do not made use of the `play.akka.config` config key, **absolutely nothing changes** for you.

> it's not easy to create custom dispatchers , in the past you just added the config: ...

You can still do that, like you posted. Nothing changes.

btw:

> 1. the docs actually say that it's not a good idea to have your own actor system:

It doesn't say that, it says it's recommended to just use the default (Play's) one. However this is not relevant here because you can use it anyway, as I think your report here is just a misunderstanding.

Do you think https://www.playframework.com/documentation/3.0.x/Migration29?#Removed-play.akka.config-setting is worded badly? What made you believe the akka configuration is immutable or that you can not add custom dispatchers to it anymore?

**Comment by schmitch** [comment]
hm, okay, than maybe something in akka, changed, because at the moment Dispatchers are not working anymore:

```
akka {
  login-dispatcher {
    type = Dispatcher
    # What kind of ExecutionService to use
    executor = "thread-pool-executor"
    # Configuration for the fork join pool
    thread-pool-executor {
      fixed-pool-size = ${play.db.prototype.hikaricp.maximumPoolSize}
    }
    throughput = 1
  }
  database-dispatcher {
    type = Dispatcher
    # What kind of ExecutionService to use
    executor = "thread-pool-executor"
    # Configuration for the fork join pool
    thread-pool-executor {
      fixed-pool-size = ${play.db.prototype.hikaricp.maximumPoolSize}
    }
    throughput = 1
  }
}
```

and than calling them like that: `actorSystem.dispatchers.lookup("database-dispatcher")`

**Comment by mkurz** [comment]
@schmitch and this was just by upgrading to Play 2.9 / 3.0? Did you change something else?
Maybe start with a fresh scala-seed project and try if you can reproduce so we can see if this is a Play problem?

**Comment by schmitch** [comment]
as said I found the fix, the dispatchers need to directly inside application.conf and not inside `akka {}`

**Comment by mkurz** [comment]
This is hard to believe, because Plays' default actor system will be set up from the `akka.*` key, which obviously would read any dispatchers. I need to check that.

**Comment by mkurz** [comment]
Ok wow, I can reproduce that, works in Play 2.8.21 and fails in 2.9... Both use the same akka version, so it has to be a change on our side. The question is if that is to expected and we need to upgrade the Migration guide or if we need an can restore the old behaviour. At least people run into exception, so it's not like they will deploy broken Play 2.9/3.0 applications...

**Comment by mkurz** [comment]
So the behaviour in Play 2.9 and 3.0 is actually correct (:sweat_smile:): A dispatcher is not supposed to be read from the `akka.*` / `pekko.*` key automatically. Also the official akka docs put the dispatcher in the config root, e.g. see the `my-dispatcher` [here](https://doc.akka.io/docs/akka/current/typed/dispatchers.html).
Also, we did not even document putting dispatchers inside the `akka.*`/`pekko.*` keys. E. g. in https://www.playframework.com/documentation/latest/ThreadPools we either put the dispatcher config in the root (see `my-context`) or under a custom prefix (`contexts.*` [here](https://www.playframework.com/documentation/3.0.x/ThreadPools#Many-specific-thread-pools)).

Being able to put the dispatcher in the `akka.*` / `pekko.*` key was just a Play specific side effect of the broken `play.akka.config` implemention, which was removed in
- #10845 and the relevent change is https://github.com/playframework/playframework/pull/10845/files#diff-8b115444063447c6da1cc7e935568fa50b6a5b3b479974e685db35521c6b0dc3R232-R233

@schmitch If you would put the dispatcher within the `akka.*` / `pekko.*` key in a plain Akka/Pekko application it would not work as well. So I will not revert to the old Play 2.8 behaviour but keep things how they are in 2.9+ because this is the "correct" way now.
@schmitch You could either change the lookup being `lookup("[akka|pekko].database-dispatcher")` or put your dispatcher into  a subconfig like we show in the docs, like `contexts.*`.

I will add a note in the migration guide in case people run in the same problem.

Regarding

> I think either the docs will be changed and new examples are created for https://www.playframework.com/documentation/2.9.x/ScalaAkka#Configuration / https://www.playframework.com/documentation/3.0.x/ScalaPekko#Configuration 

We do not need to change this docs. This docs are about the **default** dispatcher whose config actually does live under `[akka|pekko].actor.default-dispatcher`. Notice the `*.actor.*` sub-key. You may had the wrong assumption that you can put dispatchers under `[akka|pekko].*`, which Play unfortunately actually did support until 2.8 because of it's broken implementation of `play.akka.config`....

**Comment by mkurz** [comment]
BTW: I had the wrong assumption as well since a long time... So that why I was suprised at first that this does not work anymore in Play 2.9+. However, obviously the behaviour now is correct.

**Comment by mkurz** [comment]
Added notes to the migration guides:
- #12212
- #12213 

Thanks for your report @schmitch, I hope I could clarify things now :+1:
