### ISSUE TITLE
Add support for hidden input field template

### ISSUE THREAD

**Issue by hsn10** [playframework/playframework#1249]
often asked on stackexchange

**Comment by Facsimiler** [comment]
Could this please be re-opened? It most certainly _does_ make sense to have hidden fields...

Consider this use case: I have a database table, called `users`, that has a primary key of `id`, and string fields for `first_name` and `last_name`. I have a _Scala_ case class representing records from this table:
```scala
final case class User(id: Int, firstName: String, lastName: String)
```
I also want to be able to create and edit user names. I can create forms for the creation and editing of these values easily (ignoring constraints/validation for simplicity):
```scala
val createUserForm: Form[User] = Form {
  mapping(
    "id" -> ignored(0),
    "firstName" -> nonEmptyText,
    "lastName" -> nonEmptyText,
  )(User.apply)(User.unapply)
}

val editUserForm: Form[User] = Form {
  mapping(
    "id" -> number,
    "firstName" -> nonEmptyText,
    "lastName" -> nonEmptyText,
  )(User.apply)(User.unapply)
}
```

Note that I have to treat `id`'s mapping differently in the two cases.

In the first case, when creating a new user, I don't need an input field for the user identifier at all - it is forced to 0 and all is good.

But in the second case, things get a lot more complicated. Firstly, this field must never change, so it can't be edited by the user. But, it also has to be part of the form, and be assigned a value, so that a valid User instance can be extracted from the form when it is submitted. So it needs to have an input template.

If a hidden input was available, called say `@hiddenInput`, and if the form in the view containing the information is called `userForm`, filled with the contents `User(5, "Some", "User")` then the code necessary for this in a view template would be just:
```html
@hiddenInput(userForm("id"))
```

This could be output rendered with a label and the value (e.g. as "Identifier: 5") or completely ignored, depending upon how the user's `FieldConstructor` was implemented. But it would also need to at least include the following, so that the form contains the correct value when submitted:
```html
<input type="hidden" id="id" name="id" value="5" />
```

But, as there isn't such a useful element, I now need to coerce a input template designed for entry/editing of data to be used instead, while struggling fiercely to prevent it from actually being editable. Currently, the best I've been able to come up with is something like this boilerplate:
```hml
<dl>
    <dt>Identifier</dt>
    <dd>@userForm("id").value.get</dd>
</dl>
@input(
    userForm("id"),
    Symbol("_label") -> "Identifier", @* Ignored *@
    Symbol("_showErrors") -> false,
    Symbol("_showConstraints") -> false,
) {(id, name, value, args) =>
  <input type="hidden" id="@id" name="@name" value="@value" @toHtmlArgs(args) />
}
```

Not quite as elegant is it? And it doesn't lend itself as well to `FieldConstructor` definitions.

Unless there's a better solution that I'm completely missing?

**Comment by jroper** [comment]
Why not:

```html
<input type="hidden" id="id" name="id" value="@userForm("id").value" />
```

**Comment by Facsimiler** [comment]
Sure, that works, if I don't want to see any output at all. But as I showed in my example, it's normally nice to see the identifier's label and value—I just don't it to be editable—and so there's all that other boilerplate (the definition list).

A hidden input template would be more consistent with other form inputs, and would be conducive to improved formatting using a `FieldConstructor`.

Why not add one?

**Comment by jroper** [comment]
I don't think what you're describing there is what most people would expect to see if they used a hidden field template, people would expect that a hidden value should be hidden from the user. If we did provide a hidden field template, it would just render the input element, nothing else, anything else would be a poor developer experience because it would give people something they didn't expect.

It sounds what you want would be better described as a readonly field template. But you can do that trivially today with HTML readonly attributes:

```scala
@helper.inputText(userForm("id"), Symbol("readonly") -> "readonly")
```

If that's not what you're looking for, I think your requirements here are pretty unique, and not something that it makes sense to include in the framework. You can of course create your own custom template helper to do what you want, create a file called `readonlyText.scala.html`, with the following contents:

```scala
@(field: play.api.data.Field, args: (Symbol,Any)*)(implicit handler: helper.FieldConstructor, messages:play.api.i18n.MessagesProvider)
@helper.input(field, args:_*) { (id, name, value, htmlArgs) =>
    @value
    <input type="hidden" id="@id" name="@name" value="@value" @toHtmlArgs(htmlArgs)/>
}
```

And then you can just use that from within your templates:

```scala
@readonlyText(userForm("id"))
```
