### ISSUE TITLE
Can we remove `RequestHeader` from `addingToSession`? It doesn't seem to be used.

### ISSUE THREAD

**Issue by tanin47** [playframework/playframework#13029]
Here: https://github.com/playframework/playframework/blob/main/core/play/src/main/scala/play/api/mvc/Results.scala#L315

For context, I'm using it and am surprised `RequestHeader` is required. When I look at the source, it doesn't seem to be used. It would be great to remove it, so I won't have to pipe the request into the place where I call `addingToSession`.

Thank you!

**Comment by ihostage** [comment]
Hi, @tanin47! `RequestHeader` is implicit parameter that why you don't see an explicit using of them. But remove it isn't possible, because request is used to get current session (calling `session.data`) in the next line
https://github.com/playframework/playframework/blob/520facd1d515110f9f8562b818f0ef688742d924/core/play/src/main/scala/play/api/mvc/Results.scala#L316

**Comment by tanin47** [comment]
Oh I missed that. Thank you.
