### ISSUE TITLE
Replace the routing ref package

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#1768]
The ref package is currently optional, but I'd like to get rid of it.

First let me describe what the ref package is. When the routes are created, there is a ref package which exports methods wrapped in a callable. This is used only by Helpers.callAction (example: http://www.playframework.com/documentation/2.2.0/JavaFunctionalTest)

    package controllers.email.ref {
        class ReverseUnsubscribe {
            def unsubscribe(email:String): play.api.mvc.HandlerRef[_] = new play.api.mvc.HandlerRef(
                play.api.Play.maybeApplication.map(_.global).getOrElse(play.api.DefaultGlobal).getControllerInstance(classOf[controllers.email.Unsubscribe]).unsubscribe(email), HandlerDef(this, "controllers.email.Unsubscribe", "unsubscribe", Seq(classOf[String]), "GET", """ Email""", _prefix + """unsubscribe/$email<[^/]+>""")
            )
        }
    }

Now as to why the ref package causes problems. First off, it increases the amount of compilation because it makes routes_reverseRouting.scala depend on every controller. Secondly, it stops people from being able to export routes to other projects easily. And thirdly, it stops the views from being compiled after the models (causes problems with Lombok, etc.)

Right now, with the ref package, you have:

    Result result = callAction(controllers.routes.ref.Application.index("Kiki"));
   

Without the ref package, you would simply route the call as well:

    Result result = route(controllers.routes.Application.index("Kiki"));

This would solve the problems that we have with the ref package today and greatly simplify the code by removing a convoluted solution of generating a bunch of extra code just to call an action.

**Comment by mkurz** [comment]
@benmccann @jroper As Play 2.4 will have Java 8 support only, would it now be possible to drop the routing ref package from the `master` branch completely?
As Ben wrote it seems its only use is within the [`Helpers` class `callAction` methods](https://github.com/playframework/playframework/blob/bdb9985aa4be2eaca9ed60fc65142b2c8f5b6d86/framework/src/play-test/src/main/java/play/test/Helpers.java#L85-L103)
So, as shown by Ben, with Java 8 lambda expressions someone can now easily write

    Result result = callAction(() -> { controllers.Application.index("Kiki"); });

instead of using `callAction` [as suggested in the docs](https://github.com/playframework/playframework/blob/bdb9985aa4be2eaca9ed60fc65142b2c8f5b6d86/documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/ApplicationTest.java#L39-L43).
I am raising this issue again, because as far as I understand (and Ben pointed out as well) the routing ref package stops the views from being compiled after the models. So in case  the routing ref package gets dropped could we also make the views compile *after* the models? This would allow people to easily use lombok within the model classes - without the workaround of having a sub-project containing these models to get them compiled before the views.

Or is there any other purpose of the routing ref package I'm not aware of?

**Comment by benmccann** [comment]
My excitement to move to Java 8 just increased 10 fold!!

I'm going to reopen to ensure we make this work well with Java. @jroper please feel free to correct me if you think it doesn't make sense to look at getting rid of routes.ref now.

**Comment by jroper** [comment]
@benmccann As long as what we do is adequately documented, it sounds fine to me.
