### ISSUE TITLE
Do you want this OFormat[Map[K:Format,V:Format]] ?

### ISSUE THREAD

**Issue by refried** [playframework/playframework#2049]
I can't make it implicit without conflicting with the existing one, but:

```scala
import play.api.libs.functional.syntax._
def writesMapJsonKeys[K:Writes,V:Writes]: OWrites[Map[K,V]] = OWrites[Map[K,V]]{ map =>
  JsObject(map.toSeq.map {
    case (k,v) => {
      val k_e = Json.toJson(k) match {
        case JsString(s) => s
        case other: JsValue => other.toString
      }
      k_e -> Json.toJson(v)
    }
  })
}

def readsMapJsonKeys[K:Reads,V:Reads]: Reads[Map[K,V]] = Reads[Map[K,V]] { jsValue =>
  Json.fromJson[Map[String,V]](jsValue).flatMap{ map =>
    def stringToKey[K](s: String)(implicit rK:Reads[K]): K = {
      val parsed = try {
        Json.parse(s)
      } catch {
        case e: JsonParseException =>
          Json.parse('"' + s + '"')
      }
      parsed.as[K]
    }

    try {
      JsSuccess[Map[K,V]](map.map {
        case (s,v) => stringToKey[K](s) -> v
      })
    } catch {
      case e: Throwable =>
      JsError(e.getMessage)
    }
  }
}

def formatMapJsonKeys[K:Format,V:Format] = Format[Map[K,V]](readsMapJsonKeys, writesMapJsonKeys)
```

and

```scala
class FormatMapJsonKeysTest extends org.scalatest.FunSuite {
  def testMap[K:Format,V:Format](in: Map[K,V]) {
    val json = Json.prettyPrint(Json.toJson(in)(formatMapJsonKeys[K,V]))
    println(json)
    val out = Json.parse(json).as[Map[K,V]](formatMapJsonKeys[K,V])
    assert (in == out)
  }

  test("write and read Map[String,Boolean]") {
    testMap(Map("yes" -> true, "no" -> false))
  }

  test("write and read Map[Boolean,Boolean]") {
    testMap(Map(true -> false))
  }

  test("write and read Map[Double,Boolean]") {
    testMap(List(1d,2d,3d).map(k => k -> (k % 2 == 0)).toMap)
  }

  test("write and read Map[List[Int],Boolean]") {
    testMap(Map(List(1,2,3) -> true))
  }

  test("write and read Map[Map[String,Int],Boolean]") {
    testMap(Map(Map("ok" -> 1) -> true))
  }
}
```

**Comment by jroper** [comment]
I don't think `[K:Format,V:Format]` makes sense, because what if it converts the key to a `JsNumber`, or `JsBoolean`?  What would make more sense is:

```scala
type KeyMapper[_] = _ => String
formatMapJsonKeys[K: KeyMapper,V:Format`]: Format[Map[K, V]]
```

But I think that's beyond the scope of the json API, not something that needs to live in Play.

**Comment by refried** [comment]
Yeah, or if it converts to a `JsObject`.  The point is that they all can be stringified, and now you can export a `Map` given pieces you probably already have.

**Comment by gdelprete** [comment]
Can this be reopened and integrated? I just stumbled upon this issue.
In my case, the JSON I'm trying to write has ISO currency names (like USD, EUR, etc...) with my model using a nice Enumeration of currencies. Thus as a way to do currency name validation, I'd like to just (try and) convert the text in the JSON to and from the Enumeration.

Even if a have implicit Reads[Currency.Value] and Writes[Currency.Value] in the scope, and they are properly discovered (I know because using a single Currency works), they are ignored when I use a Map[Currency.Value, Double] of exchange rates.

Note that the very same strategy seems to work for QueryStringBindable and, for example, and Option[] of your custom type.
