### ISSUE TITLE
@Security.Authenticated annotation doesn't allow for Dependency Injection

### ISSUE THREAD

**Issue by marchaos** [playframework/playframework#2188]
In Security.java:

Authenticator authenticator = configuration.value().newInstance();

It would be nice if it delegated this to GlobalSettings in the same way that controllers are to allow for dependency injection. It would also allow for one instance to be created, rather than one for every invocation.

**Comment by marminthibaut** [comment]
+1

**Comment by jroper** [comment]
This is fixed in Play 2.4.

By the way, Java actions *must* be newly created for every invocation, since Play injects the next action into them (using the `delegate` field).  When one instance is used and shared, you end up with requests being forwarded to the wrong action when two requests are received at the same time.

**Comment by rhazn** [comment]
Is this fixed? I still have the same issue with Play 2.4.0-RC5.

**Comment by jroper** [comment]
True, it's not fixed.

**Comment by marcospereira** [comment]
This is duplicated with #4835.

**Comment by srhtcn** [comment]
Is this issue fixed in 2.4.3 and when can we use 2.4.3? If not soon, is there a way to inject a service without using inject @inject annotation? Because in Security.Authenticator if I try to create the singleton service with new keyword instead of injecting the service, created service's depended services (for instance, in my case CacheApi Service) can not be injected too. All dependency chain becomes null.

**Comment by rhazn** [comment]
I replaced the Play Security class with this: https://gist.github.com/rhazn/9c4240af244fa248843a (exactly the same but with getting the authenticator via DI) in a project I did in May. I hope that helps you if you are not able to use 2.4.3.

**Comment by jroper** [comment]
Play 2.4.3 was released yesterday.

**Comment by srhtcn** [comment]
That was quick, thank you very much :)
