### ISSUE TITLE
Custom naming convention for keys (CamelCase, under_scores...)

### ISSUE THREAD

**Issue by crumbpicker** [playframework/playframework#2333]
It would be awesome if play-json could support custom naming strategies for the keys corresponding to case class fields (as it is possible with Jackson and GSON).
I have reported a similar issue for the reactivemongo library (ReactiveMongo/ReactiveMongo#149).
Currently as a temporary workaround I'm writing my case class fields using a lower_case convention, and this is not very conventional for Java/Scala apps.

Here is a discussion about this feature in the google group:
https://groups.google.com/forum/#!searchin/play-framework/json$20camelcase/play-framework/YaKV-u-seAk/CBUQmwzwOtgJ

**Comment by angeloh** [comment]
Any update for this?

**Comment by gmethvin** [comment]
Transforming the JSON after the fact requires that the naming function is one-to-one. For example, if you have a field `resultJSON`, the underscore version would be `result_json`, but that could also map to the field name `resultJson`. So doing the transformation both ways requires that you stick to a particular camelCase naming convention.

So I think the only reliable way to do this is in the macro directly, where we can provide a function mapping case class field names to property names. This is basically the same thing Jackson does with PropertyNamingStrategy, except it does it at runtime rather than compile time.

**Comment by crumbpicker** [comment]
+1 for gmethvin

**Comment by schmitch** [comment]
Hello, currently this issue has not get many love, however I think it would be a great addition if we could transform json to the underscore versions. In scala and java people write variables as thisIsMyName while in JavaScript it is this_is_my_name

**Comment by crumbpicker** [comment]
Nice work guys !
