### ISSUE TITLE
Form.bindFromRequest should not bind all parameters by default

### ISSUE THREAD

**Issue by xerophil** [playframework/playframework#2358]
As you know, the method Form.bindFromRequest binds all parameters by default. This can be pretty dangerous for instance if your model contains an internal attribute like a boolean isAdmin or similar. In this case any attacker can set those internal fields if they only know the fields name. This catastrophic vulnerability (parameter tampering attack) is quite similar to PHPs deprecated register_globals option.

The fact that Form.bindFromRequest can have arguments at all seems to be mentioned only the in the API docs, and even there without any explanation beyond the name of the respective parameter (allowedFields). Quite apart from the close to non-existent documentation, it is a fundamental principle to make the default case the secure case - in this example, using no arguments should not bind any parameters (which makes it useless, of course), not all parameters.

Therefore I suggest to change the behavior of by making its parameter mandatory in the long run. In the short run, the parameterless version should be deprecated. At the very least, the compiler should produce a warning and the documentation should carry a prominent warning.

A more detailed Post about this was submitted in the play-framework group on google:
https://groups.google.com/forum/#!topic/play-framework/uGrSlJMo48c

**Comment by techmag** [comment]
Does you solution cover off the use case of a hidden ID field? 

The value of that field could be changed and if it is used as a "find" on a db table the write could go to the wrong record. 

While we are on the topic what is (should be) the idiomatic Play way to handle ID specific updates to/from the browser? (REST indicates that the ID might be in the URL itself -- that also could be tampered with so any solution needs to perhaps record/encode/encrypt the URL as well...)

**Comment by wsargent** [comment]
@techmag The playframework mailing list is probably the best place to look for Play idioms right now: https://groups.google.com/forum/#!forum/play-framework

**Comment by bachi76** [comment]
@techmag Our solution protects specifically against tampering with the form fields / attributes mapping to a resource / record the user has access to. 

User access and permissions to resources (here db records) on resource-level need of course to be implemented separately and are bound to user authentication/authorisation.

**Comment by julienrf** [comment]
@techmag you should never have an input containing an id.

**Comment by techmag** [comment]
@bachi76 My bigger point is/was that should't the framework have a basic mantra of "security" first?

@wsargent My apologies for dog-piling -- I saw a relevant discussion in progress and reacted instead of thinking bigger picture. I'll behave better in the future... (after this parting word of course!) 

@julienrf if you look at the code that @bachi76 offers it does contain an ID - yes it is not a parameter but it is in the return URL and that too is subject to tampering. (Just open up any browser's inspection tool and edit the page and resubmit the POST... ) 

This idea -- temp URLs -- (http://docs.rackspace.com/files/api/v1/cf-devguide/content/Create_TempURL-d1a444.html) might be a good thing to include in the CSRFAddToken and CSRFCheck process as it already has all the relevant pieces at hand.
