### ISSUE TITLE
Global onError doesn't called for FakeApplication (tests)

### ISSUE THREAD

**Issue by maqdev** [playframework/playframework#2484]
Reproduced on Play 2.2.2
1. Catch all errors and handle them in Global.scala
   
   ```
   import play.api._
   import play.api.mvc.{Results, WithFilters}
   import scala.concurrent.Future
   
   object Global extends GlobalSettings {
       override def onError(request : play.api.mvc.RequestHeader, ex : Throwable) : scala.concurrent.Future[play.api.mvc.SimpleResult] = {
               Future.successful(Results.BadRequest)
       }
   }
   ```
2. Generate exception in action
   
   ```
   package controllers
   
   import play.api._
   import play.api.mvc._
   
   object Application extends Controller {
     def index = Action {
       throw new RuntimeException("Unexpected")
       Ok
     }
   }
   ```
3. The problem is that if you call that action in browser, you'll get 400 BAD_REQUEST exactly like it's handled in Global.scala, but you can't cover it with test because this test fails with exception:
   
   @RunWith(classOf[JUnitRunner])
   class ApplicationSpec extends Specification {
     "Application" should {
       "render the index page" in new WithApplication{
         val home = route(FakeRequest(GET, "/")).get
         status(home) must equalTo(BAD_REQUEST)
       }
     }
   }

**Comment by mfarhans** [comment]
The post is very helpful. I am writing tests for controllers (for which the global exceptions are handled in the Global.onError() method), in which I want include/cover the execution of {{Global.onError method}}.

I am using play framework in java, and missing something rather basic here, and that is how do you obtain the "global" reference in the java example of routeWithOnError given above. @mohsenkashi (or someone) could share a fully functional route(), if the approached worked?

**Comment by zarinfam** [comment]
For test you can write a new Global class and send an instance of it to fakeApplication() method:

        FakeApplication fakeApplication = fakeApplication(inMemoryDatabase(),global);
        start(fakeApplication);

or you can get real global of your project using this code:

       fakeApplication.getWrappedApplication().global();

**Comment by zarinfam** [comment]
Java 8 version of routeWithOnError for play 2.4+:

    public static Result routeWithOnError(Http.RequestBuilder requestBuilder) throws InterruptedException, ExecutionException, TimeoutException {
        CompletableFuture<Result> future = CompletableFuture.supplyAsync(() -> route(requestBuilder));

        BiFunction<Result, Throwable, CompletionStage<Result>> f =
                (r, t) -> (t == null)
                        ? CompletableFuture.supplyAsync(() -> r)
                        : new CustomHttpErrorHandler().onError(null, t);

        return future.handleAsync(f).thenCompose(x -> x).get(20000, TimeUnit.MILLISECONDS);
    }

**Comment by EdgeCaseBerg** [comment]
For play scala 2.4 with an ErrorHandler bound to the application via a GuiceApplicationBuilder, you still need to call it with a helper method.

```
import play.api.http.Writeable
import play.api.mvc.{ Result, Request }
def routeWithOnError[A: Writeable](req: Request[A]): Option[Future[Result]] = {
		route(req).map { result =>
			result.recoverWith {
				case t: Throwable => errorHandler.onServerError(req, t)
			}
		}
	}
```

**Comment by scadgek** [comment]
Hi @jroper,

Just wanted to inquire whether you haven't changed your position after 3 years. I can find a few counterarguments to your claim that we don't need to test `onError()`'s behaviour when testing controllers. In my view, when I test a _controller_, what I want to accomplish is to emulate someone issuing an HTTP request to my service and test the result _he receives_, which is in this case the result on `onError()`'s execution. At the same time, if I want to test that the proper exception is thrown, I'll test the underlying controller's class, and this will also encourage decoupling of business logic from the router's logic.

Of course, the approach you suggested - writing tests for the `HttpErrorHandler` itself - would also work, but I believe this makes testing the controller either redundant or incomplete, since it does nothing besides parsing request and by itself does not throw any exceptions - instead it returns `Result` instances.

Please tell me what you think of this, and thanks in advance!

**Comment by ademshin** [comment]
6 years after same question...

**Comment by sb-yb** [comment]
It would be nice to document this lack of custome error handler as part of
https://www.playframework.com/documentation/2.8.x/JavaErrorHandling
and 
https://www.playframework.com/documentation/2.8.x/ScalaErrorHandling
