### ISSUE TITLE
allow strings as part of evolution's file name

### ISSUE THREAD

**Issue by asouza** [playframework/playframework#2813]
Nowadays is only possible to put a integer as a name of the file. This approach is not so good for a project with more than one person in the team. There is also the fact that this number is not readable :(. You have to open file to know what the migration is doing... I think that Migration implementation in Rails is better.  There will be less conflicts and you just have to read the file name to understand what the migration is doing.

**Comment by urquilla** [comment]
This would be a great improvement on this side, really, +1 on this

**Comment by jroper** [comment]
Play 2.4 introduces an `EvolutionsReader` abstraction, making it quite straight forward to customise how evolutions are read.

**Comment by mkurz** [comment]
@vr100 Thanks for sharing your implementation.
@urquilla Did you have a look at the solution @vr100 provided?

**Comment by mkurz** [comment]
Maybe we could add documentation and add an example for a custom `EvolutionsReader`.

**Comment by tg44** [comment]
Can somebody help me with it? How can I use the linked reader instead of the default?

Another thing, if you want to your evolutions avoid conflict you need to save full filenames to the evolutions table and not just map the file list to numbers. (If my commit merged before my coworkers commit and they make an evolution before me, our evolutions will collide because of the mapping (of course if we are using timestamp like filenames for example).)

Lot of framework use timestamp like filenames and migrations, my 5 min list is: yii (php), rails (ruby), entity (C#). I think this is the best way to do it.

**Comment by marcospereira** [comment]
I'm closing this in favor of #6919 because there is an example of how to create an `EvolutionsReader` there.

**Comment by mkurz** [comment]
@marcospereira I want to add docs for `EvolutionsReader` when I find some time.
