### ISSUE TITLE
2.3.0 system property config.file is ignored

### ISSUE THREAD

**Issue by timohirt** [playframework/playframework#2852]
We use several different config files to run a play app against a postgres or H2 database. Before updating to 2.3.0 I was able to select the config file to use via command line argument. As you can see below the activator script even recognizes the arguments, and now I wonder why the configuration isn't applied. As you can see below, I defined a filedb.conf configuration that overrides the db configuration so that the app runs against a H2 database.

```
./activator-1.1.3-minimal/activator -Dconfig.file=conf/local/filedb.conf -Dlogger.file=conf/local/debug-logger.xml -d
# Executing command line:
/usr/lib/jvm/java-7-oracle/bin/java
-Dactivator.home=/blah/backend/activator-1.1.3-minimal
-Xms1024m
-Xmx1024m
-XX:PermSize=64m
-XX:MaxPermSize=256m
-Dsbt.jse.engineType=Node
-Dconfig.file=conf/local/filedb.conf
-Dlogger.file=conf/local/debug-logger.xml
-jar
/blah/backend/activator-1.1.3-minimal/activator-launch-1.1.3.jar
```

In the console logging shows that the app connects to a postgres DB, which would be fine if I hadn't specify the `config.file` as it is the default in `application.conf`.

Edit: It works fine if I stage the app and then use the generated script to start the app.

```
blah/backend/target/universal/stage/bin$ ./backend -Dconfig.file=../conf/local/filedb.conf
...
2014-05-14 12:54:26,620 [info] play - database [db] connected at jdbc:h2:file:read.db
```

**Comment by wuservices** [comment]
I had this issue too when trying to set a config file in Test with something like `activator -Dconfig.file=something.conf "project play" test`. I found that disabling fork in Test fixed it since it allowed the system property to be passed through. Is this the right approach? This seems related to https://github.com/playframework/playframework/pull/654 but I'm not sure the disadvantage of disabling fork is or if there's another way to get the system property through.
