### ISSUE TITLE
Request to upgrade ebean to 4.0.2 or 4.x

### ISSUE THREAD

**Issue by gitssie** [playframework/playframework#2926]
The Ebean ORM 3.x.x has many bug.like findPagingList,L2 cache etc..

Which master can upgrade the ebean to 4.0.2 version?

please help me,thanks!

**Comment by tms** [comment]
The problem is that Play 2.4 requires Java 8, and while you [pointed out separately](https://groups.google.com/d/msg/play-framework-dev/fte3TC4rYNw/FY3GkJkW74wJ) @jroper that Play 2.3 is a stable, supported release for those forced to stick with Java 7 for the time being, the bundled version of Ebean has at least a couple rather substantial bugs that the original issue touches on.

Manually managing the lifecycle is, as you mentioned, a workaround, but it'd be nice not to have to do that. If someone were to put in the effort to update the 2.3 support to be compatible with the latest Ebean would you entertain a PR, or would that be considered too large of a change at this point in the 2.3.x development timeline? Note that I ask this without having looked in depth into all of the Ebean 3.x -> 4.x changes, it's possible that patching in backwards compatibility would be impossible which would make this a non-starter.

**Comment by jroper** [comment]
Well, since Play's ebean support now lives in its [own project](https://github.com/playframework/play-ebean), that means it can have its own release lifecycle, own branches etc, which means there's no reason why there couldn't be a Play 2.3 branch of it that supports Ebean 4, and we could cut releases from that.
