### ISSUE TITLE
java.lang.NoClassDefFoundError: play/api/libs/ws/SignatureCalculator

### ISSUE THREAD

**Issue by pichsenmeister** [playframework/playframework#3047]
I have imported

import play.api.Play.current
import play.api.libs.ws._

, as explained in the migration guide, but still getting this error.
I've also added libraryDependencies += ws, to my build file.

**Comment by cleverdeveloper** [comment]
This error will be thrown if you are using compile time dependency injection, because built-in Play injector does not know how WSAPI should be instantiated in this case.

To resolve it first extend "NingWSComponents" trait just as you, probably, previously extended "BuiltInComponentsFromContext" trait and then add the "wsApi" component into your injector.

The final code may look like following then:

    class MyLoader extends ApplicationLoader {
  
      def load(context: Context) = {
        new MyComponents(context).application
      }

    }

    class MyComponents(context: Context)
        extends BuiltInComponentsFromContext(context)
        with ...
        with NingWSComponents {
      ...
      override lazy val injector = new SimpleInjector(NewInstanceInjector) + ... + wsApi
      ...
    }
