### ISSUE TITLE
Cached Ok.sendFile

### ISSUE THREAD

**Issue by luisfurnas** [playframework/playframework#3077]
I hava an action that returns an image

``` scala
def image(path: String, file: String) = Action { request =>
   val resourceName = Play.configuration.getString("assets.path").getOrElse("./uploads").filterNot(_ == '"').trim + s"$path/$file"
    externalResourceNameAt(path, file).map { resourceName =>
      Ok.sendFile(new File(resourceName), inline = true)
    } getOrElse NotFound
}
```

It works fine, but when I wrap the Action in Cached, things go sour.

It works on the first request, and in every cached requests, but when I reload clearing the browser cache, it always returns an IO Exception - Stream Closed.

**Comment by tactoth** [comment]
Is there any utility class that helps us add cache control headers when we use 'sendFile'?

**Comment by tactoth** [comment]
Do you have any plan to provide a helper class or anything that make serving static files easier? Cache control is part of HTTP protocol, if we have to implement it ourselves it doesn't feel like we are using a web framework.

**Comment by richdougherty** [comment]
@wsargent may have been working on a utility to help with caching headers, but I'm not sure.

**Comment by jroper** [comment]
The difficulty comes in knowing what the headers should be.  Best practice is to use etags, but that would require loading the asset twice every time it was served, and once every time it was requested when not modified, doing so would be very expensive, so the etag should be stored somewhere, either cached in memory, or in a database, but then what are its expiry conditions?  That's an application concern.  So we'd have to write a trait that the application would have to implement that would load the file, calculate its etag, and then cache it, and now, instead of programming to the HTTP spec, which is open and transparent, you're writing the same amount of code, but programming to some Play interface, which would be harder to debug and understand since it would all be all Play specific and not a transparent open standard, and learning how to implement that won't transfer to other frameworks.

The problem is, HTTP caching is one of those things that sounds so simple, so people feel like they should just be able to turn it on and expect the framework to do it all for them, but it's not so simple, it can't just be turned on, you have to do a fair amount of work to get it to work, and framework support for it would just introduce a layer of indirection that only complicates things, whereas implementing the spec directly gives you more visibility and control into what you're doing.

**Comment by tactoth** [comment]
Thank you @richdougherty @jroper for the response.
I've read the answer you provide somewhere else, and I found you suggest put application images to S3 to some static hosted nginx server. I found your idea make very good sense so I decide to move to this direction.
