### ISSUE TITLE
Play 'dist' artifact includes duplicate files

### ISSUE THREAD

**Issue by arobertn** [playframework/playframework#3473]
Running the 'dist' sbt task creates a zip which is said to be the way to deploy to production.  However, this zip contains duplicate files, for example both a fully stocked /conf directory at top level, and contained within the project's jar bundled under lib.  In addition to unneccesary bloat, this can cause confusion when wanting to make a quick manual change to a server running in "production" mode (which might well be a test server or something else).  The presence of the file at top level makes one assume that editing and restarting the app will make a change, when it may not depending on the class loading order (if it is even on the classpath to begin with).  Issue #3472 was mistakenly reported due to this.

The raw files should be excluded since this is a production deploy, but if they are going to be there then they should be on the classpath first.

**Comment by chenbekor** [comment]
could not agree more with the troubles we had with this in prod. we find it very useful to change things like logger,  connection strings etc even if in production. otherwise what's the point of including the conf dir? please make conf folder operational so that we could alter it's content and restart to see the effect. this refers to both  regular conf files and logback configuration files!

**Comment by benmccann** [comment]
Yes, the `conf` is being used by people for two different things. The first is that it's a resources directory that goes on your classpath like `src/main/resources` would in a typical project. The second is that some people want a place to put external configuration files that are included in a directory packaged with the app when you run `dist`. Right now the `conf` directory gets both included into your jar and then included again a second time in the dist zip. Having it in two places as we do now is a recipe for confusion. I know folks on my team have been caught off guard by this in the past and I needed to explain to them how it worked because it was causing trouble for them.

I personally think the best solution here would be to stop using this directory for two different things. I would create a new directory called `resources` that has the resources you want to be on your classpath and use `conf` just for the external configuration. This would have to be mentioned in the migration guide to make sure folks move files from `conf` to `resources` as needed.

If we split the current `conf` directory into two like this, then there's the question of where do you want `application.conf` to be located? You can put it in either place and it will work just fine. You just need to set the command line flag accordingly to load it either as a resource or a file. I believe more people would probably want it located externally.

**Comment by coverbeckApigee** [comment]
In Play 2.3.4, is there a way to stop the conf directory from being included in the JAR? I want the external conf directory, which I have, but I do not want the files duplicated in the conf directory in the JAR.
