### ISSUE TITLE
There is not any documentation about authenticators in Play site!

### ISSUE THREAD

**Issue by zarinfam** [playframework/playframework#3510]
Play Framework site is very complete but there is not any documentation about authenticators in official Play site!
Previously there was a sample project (zentask) that speak about authenticators and authentication mechanism in play framework.

**Comment by nickroth** [comment]
+1 please. The last instance of documentation on the subject is part of 2.1 and we're now looking to 2.4.

**Comment by khajavi** [comment]
+1

**Comment by wsargent** [comment]
There are a number of authentication frameworks based on Play.  Please see http://silhouette.mohiva.com/ or https://joscha.github.io/play-authenticate/

**Comment by mkurz** [comment]
Or http://securesocial.ws

**Comment by nickroth** [comment]
I think what the original post (or at least what my request is for) is for some documentation on how to use Security.Authenticator. I'm sure those third-party frameworks are great but I'm looking for documentation on out-of-the-box features of Play.

**Comment by wsargent** [comment]
The thing is, the out of the box stuff is not great.  It doesn't timeout, sets up a username in the cookie instead of a random session id, and doesn't provide you with any framework.  

Even https://github.com/t2v/play2-auth or https://github.com/yesnault/PlayStartApp#master are better models, because they have an integrated framework instead of asking users to assemble it.

There's probably a larger discussion here about the role of authentication in Play -- I know this was a big thing in Lift, but I wasn't impressed with MegaProtoUser either.

**Comment by wsargent** [comment]
If you go to https://www.playframework.com/documentation/2.4.x/ModuleDirectory and searching for "authentication" then you see several authentication frameworks.

I think we should deprecate Security.Authenticator and point to Silhouette, but that's another bug.
