### ISSUE TITLE
WS lib: response headers do not include proper Content-Encoding and Content-Length

### ISSUE THREAD

**Issue by levinotik** [playframework/playframework#3846]
I am making a request to an API that uses gzip compression on responses. When I make a request using curl, I can see the Content-Encoding and Content-Length headers in the response are correct. However, when using the WS lib, the Content-Encoding is not present in the response and the Content-Length is the length of the uncompressed response. However, the response clearly is gzipped, because if I don't add `ws.compressionEnabled = true` to my application.conf, I cannot properly parse the response body. My guess is that somehow the underlying client is doing some magic to modify the headers before the WS future completes in order to handle compression under the hood. Am I correct? If I am, it seems a tad bit disconcerting that the "real" http response headers are not available in the WSResponse.

**Comment by jroper** [comment]
This is a feature - it would seem a tad disconcerting if you got a WSResponse that had a header that said it was gzipped, but the body wasn't gzipped, and more disconcerting if it had a header that said the content length was 1KB, but then the actual body was 10KB, don't you think?

Leaving the headers as is would cause big problems in many use cases, for example, it's common to proxy requests/responses, one common use case is when storing large files on S3.  In this case, you want to set the content length header on the downstream response, but if the incoming response from the WS client has a content length that doesn't match the content, then you can't use that, and there's no way for you to know what the actual content length is then without reading the whole response body into memory.

If some filter is going to transform the request body, it should also transform the request headers to match, otherwise how is downstream code ever expected to function properly?

**Comment by levinotik** [comment]
thanks @jroper I agree, it would be far more confusing to not properly reflect in the headers the transformations that had taken place.
