### ISSUE TITLE
Evolutions > 64kb don't apply

### ISSUE THREAD

**Issue by Kyprus** [playframework/playframework#3918]
I wanted to start using play evolutions so I put my schema and lookup table data into an evolution. I started the app but play was asking me to apply the script over and over again with no error messages. I finally figured out that the problem is the `play_evolutions` table. The type of `apply_script` is text, which in MySQL has a max length of 64kb. My schema and data is around 74k causing everything to fail. When I manually changed the type of the column to MEDIUNTEXT everything worked.

I initially tried to break up the script so every piece was small enough but since play concatenates them into a single evolution that obviously didn't help.I'm not seeing a decent workaround for this. At the very least it an error message would be helpful. Thanks

**Comment by Kyprus** [comment]
Okay I'm not sure why it didn't work before but I actually am able to break up evolutions and they apply separately. So there is a workaround at least

**Comment by megazord** [comment]
Another possible workaround is to have a `1.sql` evolution that changes the `play_evolutions` table itself, so that you can change the type of `apply_script` to whatever you want. After that, you can have a `2.sql` with more than 64kb.

Anyway, looks like is pretty easy to fix this issue since we just have to change some code around `play.api.db.evolutions.EvolutionsApi` (around [here](https://github.com/playframework/playframework/blob/master/framework/src/play-jdbc/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L308-L354) and [here](https://github.com/playframework/playframework/blob/master/framework/src/play-jdbc/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala#L233-L245)).
