### ISSUE TITLE
Long JSON serialization can lose precision

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#3958]
The `Reads`/`Writes` implementation for `Long` uses a `JSNumber`. When communicating with JavaScript this may result in lost precision because a JVM `Long`'s range is about ±2^63 but a JavaScript `number` can only store integer values in the range ±2^53. To be safe we should consider using a `JSString` for `Long` values, like we do for `BigDecimal`.

If we want to fix this issue we will need to work out how to handle backwards compatibility. Existing apps may rely on the fact that `Long` uses `JSNumber`.

**Comment by jroper** [comment]
I think that's an interoperability problem for JavaScript and JSON, and has nothing to do with play-json.  JavaScript is just one of many, many, different languages that consume and produce JSON, and in fact it would probably be fair to say that only a small portion of JSON clients are JavaScript, most JSON is used in communication between servers.  Consider the Twitter API, which uses 64 bit integers for tweet IDs.  If we used a String to represent longs, and then I wrote a Play client to talk to Twitter, and we serialised longs an Strings by default, Twitter would reject my requests.  That would be very confusing, people would start wondering why Play is serialising longs an Strings, it wouldn't make sense.

It's up to the user to ensure that when devising a protocol for communication between a client and server, that that protocol fits within the capabilities of the json implementation of both that client and server.   We should implement a counter intuitive protection by default into Play just because one possible client implementation may have a problem.

**Comment by richdougherty** [comment]
Now that I look more closely I see that `BigDecimal` also uses `JSNumber` so at least we're consistent in our formats.

**Comment by mandubian** [comment]
Yes this part of JSON pseudo standard is a bit stupid as number means "any
number, real, integer, negative, positive with exp or not".
That's why it uses BigDecimal in play-json which is not efficient at all...
When exchanging big numbers with JS, it certainly better to use strings as
you said!

Pascal
