### ISSUE TITLE
Activator run app in foreground (Docker support)

### ISSUE THREAD

**Issue by lukaswelte** [playframework/playframework#4001]
To run activator in a Development Environment inside docker it would be necessary to run activator run as command inside a docker container. 
Right now Docker would terminate when the application starts.

Would be awesome to see support for this, as live reloading during development is a absolute want feature.

Moving this from typesafehub/activator/issues/939 here

**Comment by jroper** [comment]
I'm guessing what you mean is that the Play run command should be configurable such that it doesn't wait for EOF to exit dev mode, so that it can be executed by a script not connected to any input source.

**Comment by lukaswelte** [comment]
Absolutely :+1:

**Comment by nafg** [comment]
Have you tried running docker run with -ti ?

**Comment by lukaswelte** [comment]
Yes this works @nafg. But there are tools that do not support the t as well as the i option of docker. In the same way, there might be another case not connected with docker that also waits for EOF. 
I guess it would be simpler adding an option to the play run command than to each of these tools.

**Comment by amosjyng** [comment]
+1, I second allowing this as an option

**Comment by brikis98** [comment]
+1 just hit the same issue trying to run a Play app in a Docker container in dev. 

In fact, this issue has caused problems in other settings as well, such as trying to wrap `play run` in a custom shell script, executing `play run` in the background (e.g. adding `&` at the end of the command), or running Play (yes, in dev mode) in a Hudson environment ([example SO thread](http://stackoverflow.com/questions/21322129/play-run-exits-when-triggered-through-hudson-but-works-fine-from-commandline)).

**Comment by brikis98** [comment]
Oh, and the only workaround I've seen so far for most of these problems is to run the Play app in "production mode" (another [example SO thread](http://stackoverflow.com/questions/26865487/keeping-a-play-framework-app-running-in-a-docker-container-without-a-pseudo-tty)), which of course doesn't help if you're trying to solve this issue in dev mode.

**Comment by brikis98** [comment]
I stand corrected! Looks like there is a way to solve this, at least in the docker-compose case, by adding `stdin_open: true` to your `docker-compose.yml` file:

```yaml
web:  
  image: brikis98/ping-play
  ports:
    - "9000:9000"
  stdin_open: true
```

The `brikis98/ping-play` image executes `activator run` by default, and when I do `docker-compose up`, the Play app boots up and keeps running instead of exiting immediately.

**Comment by iamsamwood** [comment]
@brikis98 I had trouble running play in production due to tty issues, and "stdin_open: true" fixed those issues. Thanks!

**Comment by wsargent** [comment]
Sounds like "stdin_open: true" is the fix in that case, as seen in 

https://github.com/brikis98/ping-play/blob/master/docker-compose.yml

I'll add a doc page for this use case and then we can close it out.

**Comment by momopranto** [comment]
I wouldn't say the stdin_open option is a fix, it's more of a workaround. In my case I am trying to deploy my Play app to AWS Elastic Beanstalk, which does not support docker-compose, so while the workaround may work locally the app server still stops when I deploy to EB. The issue still exists with how the Play web server behaves within docker containers. I think in order to create a comprehensive solution there needs to be a way to run the server in the foreground without the need for STDIN.

Note: currently, I am having to manually ssh into the EC2 instance to kill and start the container in interactive mode. Not ideal, I know, but EB doesn't provide a system to customize the way it runs docker containers.

**Comment by nafg** [comment]
You're not supposed to use Activator in production, use docker:publish to
deploy a production image.

**Comment by Plippe** [comment]
Hey,

Like stated beforehand, if you have `ENTRYPOINT/CMD sbt run/start` in your `Dockerfile`. Play will stay alive with the `-i/--interactive` flag, but will exit with the `-d/--detach` one. 

This happens because nothing  is running in the foreground to keep the container running. After trying to keep sbt or play in the foreground I decided to go for something easier, adding a foreground process. 

So for the simplest / dirties solution, just add an infinite loop to your Dockerfile after your sbt command. 
```
# Before - will terminate
ENTRYPOINT sbt start
```
```
# After - will stay alive
RUN \
  echo 'while [ true ]; do sleep 1; done' > /keep-alive && \
  chmod +x /keep-alive

ENTRYPOINT sbt start && /keep-alive
```

This works on [AWS Elastic Beanstalk](https://aws.amazon.com/elasticbeanstalk/), but I would still recommend the use the [native packager](https://github.com/sbt/sbt-native-packager) over the above cheat for production purposes.

PS: I would still love a setting to keep play in the foreground

**Comment by wsargent** [comment]
@Plippe it's generally a much better idea to work the script generated by "sbt dist" using the native packager settings if you want to use Play in the foreground.  sbt is great, but using it in docker is kind of like packaging C source code, gcc and make into a docker container -- yes, it'll work, but it's much better to have a deployable artifact.

**Comment by Plippe** [comment]
Fully agree with you
> but I would still recommend the use the native packager

My comment is only there to give a possible solution to the problem.

**Comment by wsargent** [comment]
Closing
