### ISSUE TITLE
Json reads should fail for floating points when int is expected

### ISSUE THREAD

**Issue by pathikrit** [playframework/playframework#4032]
This code should fail:
```scala
case class Person(id: Int)
object Person {
  implicit val format = Json.format[Person]
}
Json.parse("""{"id": 5.9}""").as[Person]
```

But, it produces: `Person(5)`.

The bug is caused since we call `_.toInt` in the `Reads[Int]`.  In general, if we have a default format for a simple case class, the round trip `Json.toJson(Json.parse(jsonStr).as[A])` should always produce the same `jsonStr`.

There should be a version of `Reads[Int]` that returns `JsError` if input is a floating point.

**Comment by gmethvin** [comment]
Agreed. I was originally thinking that some people might rely on this behavior to deal with rounding errors in JS (a number is `5.999` instead of `6`), but `BigDecimal#toInt` actually truncates the number instead of rounding it. So the current behavior is not only overly permissive but also potentially error-prone.

I think it's best to just change the existing implementations to check `_.isValidInt`, etc.

**Comment by pathikrit** [comment]
I think you should so same for shorts and bytes. Feel free to reopen this issue or create a new one.
