### ISSUE TITLE
Hash fragments in URL

### ISSUE THREAD

**Issue by SRGOM** [playframework/playframework#4034]
Re: RFC7231 of HTTP/1.1, which allows for server to redirect to \#fragments (more here: http://stackoverflow.com/questions/2286402/url-fragment-and-302-redirects), are you guys planning to support adding hash fragments in play.api.mvc.Call in play 3.0? Right now, to redirect, I do a `<a href="@routes.Application.index()#some-id">`. I think it would be great if there was some way to encapsulate some-id into the URL itself

I'd assume this would be very low priority for you guys, but I figured I'll point out anyway.

**Comment by jroper** [comment]
I think what you're doing makes sense.  If we added something, it would be something like:

```html
<a href="@routes.Application.index().withFragment("some-id")">
```

I think what you're doing is actually much more readable.

**Comment by mkurz** [comment]
+1

IMHO this especially makes sense with forms:
```scala
@helper.form(action = routes.Application.submit().withFragment("some-id")) {
}
```
Right now you can not add a fragment to the form helpers action param, you have to write plain html instead:
```html
<form action="@routes.Application.submit()#some-id" method="POST">
</form>
```

**Comment by SRGOM** [comment]
@mkurz I might be misunderstanding, but a `POST` form action is meant for the server, and hash fragments are meant for client, server would ignore some-id in this case.
You could use with `GET` though, although to me it would seem a slightly contrived example of an anchor tag.

**Comment by mkurz** [comment]
@SRGOM I know hash fragments are meant for client - and the example I gave completely makes sense: In one of your projects we have a form at the very end of a page where you would have to scroll down quite a bit to reach the form. Now when you submit the form and get a `400 Bad Request` response with validation errors, the client (browser) now jumps down to form (which would have `some-id` as id, based on my example). If we would not add the hash fragment to the `POST` action, the newly loaded page with the validation errors would not jump down to the form and the user would likely be confused because he/she would hardly see the form with the validation errors (he/she would have to scroll down on his/her own).

**Comment by SRGOM** [comment]
I understand you now, my mistake.

**Comment by SRGOM** [comment]
@mkurz I understand you now, my mistake.

**Comment by mkurz** [comment]
I provided an implementation at #4152
