### ISSUE TITLE
Cannot load templates in subdirectories.

### ISSUE THREAD

**Issue by cailhuiris** [playframework/playframework#4055]
![2015-03-10 4 35 59](https://cloud.githubusercontent.com/assets/2603286/6570789/b3fa888c-c743-11e4-91c6-c0dea2565c62.png)

The html structure look like this.
In the /admin/category/list.scala.html,

```
@layout {
   " This works fine, this loads /layout.scala.html file to here. "
}
```
this code works well.

```
@admin.index {

}
```
The above code occurs compilation error, once I met this error, I thought this is a trivial bug.

![2015-03-10 4 39 30](https://cloud.githubusercontent.com/assets/2603286/6570816/0ba6fb92-c744-11e4-8fb5-2087975fa1af.png)

**Comment by jroper** [comment]
The issue tracker is for reporting bugs, for asking questions or getting help, please ask on the mailing list or stack overflow.

The problem is you have a `controllers.admin` package as well as a `views.html.admin` template, since Scala imports can be relative, referencing this is ambiguous, so you need to use the fully qualified name, `views.html.admin.index`.
