### ISSUE TITLE
space in URL causes netty exception

### ISSUE THREAD

**Issue by lawrencefinn** [playframework/playframework#4077]
```
curl -v "localhost:9000/?id=m o"
* Adding handle: conn: 0x7fab49003a00
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fab49003a00) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 9000 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 9000 (#0)
> GET /?id=m o HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:9000
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```
```
[error] p.nettyException - Exception caught in Netty
java.lang.IllegalArgumentException: invalid version format: O HTTP/1.1
	at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:102) ~[netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62) ~[netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75) ~[netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191) ~[netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102) ~[netty-3.9.3.Final.jar:na]
[error] p.nettyException - Exception caught in Netty
java.lang.IllegalArgumentException: empty text
	at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:97) ~[netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62) ~[netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75) ~[netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191) ~[netty-3.9.3.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102) ~[netty-3.9.3.Final.jar:na]
```

I know a request SHOULDNT have spaces but apache seems ot handle it fine

**Comment by jroper** [comment]
Have you checked the Apache error log to see if it's handling it fine?  The http protocol spec states that the method, URL and HTTP version should be delimited by spaces.  This means, if you put a space in the URL, you're not really putting a space in the URL, what you're is you're terminating the URL and putting the HTTP version after that.

There's no real way to handle this cleanly - it's a bad request, so you could response with a 400 error, but since we haven't even successfully parsed the protocol version (`0 HTTP/1.1` is not a valid protocol version) maybe we should return a 505 error.  But, how do we know how to send the response?  Do we close the connection after sending it?  Do we add any `Connection` headers?  Both of these questions can only be answered by knowing the HTTP version, but we don't know that.  So, a request like that is indistinguishable from garbage, and the correct thing to do when we receive garbage is to close the connection, which is what we are doing.  The only change to Play that I would suggest we make is to somehow detect these particular exceptions, and log them at the trace level rather than error.

**Comment by jroper** [comment]
And, I would say what you've found there is a bug in curl, curl shouldn't be sending bad requests like that, it should either be encoding the url, or returning you an error saying it can't request that url because it's invalid.

**Comment by lawrencefinn** [comment]
Yeah, I know it is a pretty crazy situation.  We have clients writing code in god-knows what language using god-knows what libraries.  It would be nice to have for it to error to the client and then close rather than just close.  Is there a way to tap into the netty access log for debugging on my end?

Here is an example hitting apache/php. It just spits out the querystring parameters, which it trims at the first space.

```
curl -v "localhost:16011/status?id=i am a bad user"
* About to connect() to localhost port 16011
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 16011
> GET /status?id=i am a bad user HTTP/1.1
> User-Agent: curl/7.15.5 (x86_64-redhat-linux-gnu) libcurl/7.15.5 OpenSSL/0.9.8b zlib/1.2.3 libidn/0.6.5
> Host: localhost:16011
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 17 Mar 2015 04:25:26 GMT
< Server: Apache/2.2.18 (Unix)
< X-Powered-By: PHP/5.3.18
< Content-Length: 85
< Connection: close
< Content-Type: text/html; charset=UTF-8
array (
  'id' => 'i',
)
```

**Comment by jroper** [comment]
So, Apache is either parsing the status line from the right to get the version number, or is just ignoring the fact that the version is garbage.  Either way, that's an implementation detail of Apache.

If it were up to me, I would prefer to be strict - applications accepting garbage is a hackers dream, it allows them to exploit protocol injection vulnerabilities that otherwise would be impossible.  For example, let's say you enforce access permissions in a reverse proxy, and it parses the first line from the right, allowing spaces in the URL.  Then your application parses from the left, ignoring when there's a garbage HTTP version.  Your reverse proxy has validated access to a different URL than the application is now serving.  In certain situations, a hacker could exploit that.  This is why being tolerant when you receive garbage is very bad, Apache's track record here is not one that we should aspire to.  And that's just one possible vulnerability that could exist if we were to implement Apache's behaviour here, there are many, many more.

But, it's not up to me, because Play doesn't parse the header, Netty does.  So if you can convince the Netty project to implement tolerant status line parsing, then I guess I'll have to live with that.  So I'm closing this issue here, feel free to raise a new issue on the Netty project.
