### ISSUE TITLE
JsNumber refactor

### ISSUE THREAD

**Issue by kutchar** [playframework/playframework#4081]
Currently `JsNumber` is a case class with a value of `BigDecimal` which causes a lot of unnecessary conversions in API calls and in serialization/deserialization to/from JSON. BigDecimals are slow and take a lot of memory. The better approach would be to either change `JsNumber` to a trait and have case classes `JsInt`, `JsDouble`, `JsLong`, ... or change `JsNumber(BigDecimal)` to `JsNumber(java.lang.Number)`.

Please let me which option is more favorable and I will submit a PR.

**Comment by gmethvin** [comment]
@kutchar this would add some additional complexity to deserialization (figuring out the correct type) and also for comparison. i.e. `JsInt(1) === JsDouble(1)` should always be true.

**Comment by kutchar** [comment]
@gmethvin to make things easier we can use the following approach:

```
case class JsNumber private (value: Number)

object JsNumber {
	def apply(i: Int) = new JsNumber(i)
	def apply(l: Long) = new JsNumber(l)
	def apply(d: Double) = new JsNumber(d)
	def apply(bd: BigDecimal) = new JsNumber(bd)
	def apply(bi: BigInt) = new JsNumber(bi)
}

object TestJsNumber extends App {
	val intNumber = JsNumber(1)
	val longNumber = JsNumber(1l)
	val doubleNumber = JsNumber(1.0d)
	val bdNumber = JsNumber(BigDecimal.valueOf(1.0d))
	val biNumber = JsNumber(BigInt(1))

	val numbers = Seq(intNumber, longNumber, doubleNumber, bdNumber, biNumber)

	val result = numbers.map(a => numbers.map(b => a == b)).flatten.reduce((a, b) => a && b)

	println(result) //true

}
```

This approach removes the issue with equality.

As for deserialization, it's not that complex. We can just use `com.fasterxml.jackson.core.JsonParser.getNumberValue()`. Here's the implementation of `getNumberValue` from `com.fasterxml.jackson.core.base.ParserBase`

```
public Number getNumberValue() throws IOException
{
    if (_numTypesValid == NR_UNKNOWN) {
        _parseNumericValue(NR_UNKNOWN); // will also check event type
    }
    // Separate types for int types
    if (_currToken == JsonToken.VALUE_NUMBER_INT) {
        if ((_numTypesValid & NR_INT) != 0) {
            return _numberInt;
        }
        if ((_numTypesValid & NR_LONG) != 0) {
            return _numberLong;
        }
        if ((_numTypesValid & NR_BIGINT) != 0) {
            return _numberBigInt;
        }
        // Shouldn't get this far but if we do
        return _numberBigDecimal;
    }

    /* And then floating point types. But here optimal type
     * needs to be big decimal, to avoid losing any data?
     */
    if ((_numTypesValid & NR_BIGDECIMAL) != 0) {
        return _numberBigDecimal;
    }
    if ((_numTypesValid & NR_DOUBLE) == 0) { // sanity check
        _throwInternal();
    }
    return _numberDouble;
}
```

**Comment by jroper** [comment]
We could also further optimise by specialising `JsNumber`, but I doubt that optimisation would have any serious real world impact.

Before going down this route, I'd be interested in knowing what the cost of using `BigDecimal` is, eg, is it significant or negligible compared to the cost of parsing/formatting json?

**Comment by gmethvin** [comment]
Yeah, I think we should check to see what the actual performance costs are before we start making API changes.

It also might be worth it to keep the `unapply` and `value` methods that return `BigDecimal`:
```scala
final class JsNumber private (val underlyingValue: Number) extends JsValue {
  def value: BigDecimal = BigDecimal(underlyingValue.toString)
  override def equals(o: Any) = o match {
    case n: JsNumber => underlyingValue == n.underlyingValue
    case _ => false
  }
  override def hashCode() = underlyingValue.hashCode
}
object JsNumber {
  def unapply(n: JsNumber): Option[BigDecimal] = Some(n.value)

  def apply(i: Int) = new JsNumber(i)
  def apply(l: Long) = new JsNumber(l)
  def apply(d: Double) = new JsNumber(d)
  def apply(bd: BigDecimal) = new JsNumber(bd)
  def apply(bi: BigInt) = new JsNumber(bi)
}
```

**Comment by kutchar** [comment]
@gmethvin @jroper Based on the following simple micro benchmark, using BigDecimal is about 2x-10x slower than using Number https://gist.github.com/kutchar/82ad7463146d7b4886b9

Also, BigDecimal has a pretty big memory overhead and generates quite a bit of garbage compared to say a box primitive number. (Just look at the source)

But there is also another reason why using BigDecimal is causing pain. I really like Play's JSON API, so I use it to generate/parse Smile and/or MessagePack binary data too (via Jackson's appropriate formats) and when using binary formats, BigDecimal gets encoded differently than say an Int or a Double which in addition to taking more space, breaks the language interop between non JVM languages. I know this one is not a "Play" concern, but just stating it so it gives you a bit more background. Also, I don't see why Play shouldn't support other JSON-like formats supported by Jackson.

**Comment by gmethvin** [comment]
I think I agree with @kutchar here. I just want to make sure the API is still easy to use, which is why I proposed the above. `Number` as a type by itself is not that nice to work with.

There is an issue open for adding additional Jackson formats (#3880). It would be pretty easy to do technically but we'd have to discuss the appropriate API.

**Comment by jroper** [comment]
@kutchar that benchmark just shows that instantiating `BigDecimal` is expensive, which we know, but many things we do are expensive in isolation (eg, using `Option.getOrElse` vs using `match` is expensive both in garbage created and in cpu) but in the scheme of things don't matter unless in an inner loop.  What I'm interested in is how expensive using `BigDecimal` is in the context of json parsing.  `BigDecimal` may well create a lot of garbage, but I suspect that garbage is negligible compared to the amount of garbage our json combinators create (every field has a new `JsSuccess` created, which is `flatMapped` passing a new function object, and producing a new `JsSuccess`, and so on).  So, the benchmarks I want to see is something like this:

```scala
case class Foo(a: Int, b: Long, c: Double)
implicit val fooFormat = Json.format[Foo]
val foo = Foo(1, 12345l * 67890l, Math.pi)
for (i <- 1 to 10000000) yield {
  val json = Json.stringify(Json.toJson(foo))
  val parsed = Json.fromJson[Foo](Json.parse(json))
}
```

And see the performance difference.  Also would be good to test it on a more real world example, since most json bodies are not just numbers, so I'd be interested in what impact it has on the performance of parsing for example https://api.github.com/repos/playframework/playframework.  If in either case it's more than 5%, then we should consider this.  If it's less than 5%, then it gets harder to justify the API breakage.

As for different data formats, that can be addressed in the serialisers/deserialisers of `JsNumber`, they don't have to write a `BigDecimal`, they can inspect it and write other datatype if necessary.

**Comment by kutchar** [comment]
@jroper I agree with you that the cost of BigDecimal instantiation is negligible compared to other operations but I still don't see why something should be done in a less efficient way if there is an "easy" better way to do it (specially with the approach proposed by @gmethvin which doesn't change the public API, functionally). Also, these conversions do happen pretty often and the conversion of double <-> BigDecimal costs 270ms!! (see https://gist.github.com/kutchar/82ad7463146d7b4886b9)

As far as BigDecimal being handled differently in underlying serialisers/deserialisers, it's not that simple. An underlying serialiser/deserialiser would need to do "slow" BigDecimal math to determine if a the value can be converted to a long, an int or a double.

**Comment by jroper** [comment]
The double <-> BigDecimal conversion in your benchmark cost 270ns, not 270ms, since the time was how long it took to do one million conversions.  That's in the same order of magnitude as the time it takes to read/write main memory.

I'm not strongly opposed to the change, but right now we have a very simple API, this change introduces a polymorphic type to JsNumber, which brings a certain level of complexity when interacting with it, and is either a breaking change, or requires a fair amount of complexity to maintain backwards compatibility that is less than optimal because it means we can't use `value` to hold the value of the `JsNumber` (and many people would use `value` because that's the most sensible name for it, so the `BigDecimal` conversion would end up being done anyway in those cases).  Personally, I'd rather break the API than use an unintuitive field name to hold the value, much cleaner that way.

But I'd really like to see the numbers - there's no point in talking about performance without having concrete numbers.

**Comment by kutchar** [comment]
@jroper my bad, that was a typo ;) I agree that the numbers are needed if we are approaching this purely on the performance side, even though I think that the numbers won't really prove anything since the cost of doing JSON processing will hugely overshadow the BigDecimal conversion. But if we are looking at this from the angle of supporting binary formats (i.e. Smile or MessagePack), then the current approach is less than optimal.

As an example, MessagePack doesn't natively support BigDecimal, only doubles. I just created a "hacky" PR for MessagePack that tries to see if it can fit a BigDecimal into a double, if not it errors out (https://github.com/msgpack/msgpack-java/pull/205)

**Comment by gmethvin** [comment]
I think it would also be useful to know if numbers will be rounded if they're parsed by an implementation (like in JavaScript) that uses double-precision floating point numbers. If you, for example, used a Long for an ID that could not be represented in a Double, bad things might happen on the client.

**Comment by schmitch** [comment]
Currently I think that is good. Since currently I need to make a lot of work to have my decimals converted to string BEFORE i convert it to Json, since I need to keep trailing zeroes. With this I would just write a BigDecimal Writer which will convert my BigDecimals to JsString("0.00")

**Comment by cchantep** [comment]
Closing it for now. Can be reopened if any new feedback. Best regards.
