### ISSUE TITLE
[2.4.0-M3] Document play.application.loader

### ISSUE THREAD

**Issue by igmar** [playframework/playframework#4086]
The DI binder context is not available in a module. To be able to have application.conf be able to handle option dependant bindings, we need either one of those : 

- Make Configuration() available when in AbstractModule.initialise()
- Make the DI object available in the Play module

The @Inject annotation doesn't see to work inside a Module.

**Comment by richdougherty** [comment]
I think I may have answered this issue here: https://groups.google.com/d/msg/play-framework/VU6S2dZn9vM/wNMJeOquSgMJ

**Comment by jroper** [comment]
If this frustrates enough people, then I think we could make a case for injecting the environment and the configuration into the modules constructor if such a constructor exists.  We could also have a bootstrap guice injector for instantiating modules - but at this stage I'd say that's overkill.

**Comment by benmccann** [comment]
@igmar are you talking about a [Play `Module`](https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.inject.Module) or a [Guice `Module`](http://google.github.io/guice/api-docs/latest/javadoc/index.html?com/google/inject/Module.html)?

What is the `AbstractModule.initialise` that you're talking about? Play's `Module` doesn't extend an `AbstractModule`. Guice's `Module` does, but there's no `initialise` method on it. Are you saying we should introduce a new class called `AbstractModule`?

**Comment by igmar** [comment]
AbstractModule is part of Guice, and that has an initialise() method. That method however doesn't give me access to the Play context.

**Comment by benmccann** [comment]
[`AbstractModule`](http://google.github.io/guice/api-docs/latest/javadoc/index.html?com/google/inject/AbstractModule.html) doesn't have an `initialise` method, but in any case it clears up that you're talking about a Guice `Module`, which allows me to understand the question. I agree that having configuration available in the Guice `Module` is helpful. I pass configuration objects into the constructors of my modules today.

I can't tell from [the docs](https://www.playframework.com/documentation/2.4.x/JavaDependencyInjection) how to create a Guice `Module` in Play 2.4 besides having Play do it. They only say say:
>To register this module with Play, append it’s fully qualified class name to the play.modules.enabled list in application.conf:
play.modules.enabled += "modules.HelloModule"

Most if not all of the Guice modules that I use today in Play 2.3 take constructor parameters and wouldn't work with this method of setup, which I assume must require no-arg constructors. I'm not super in love with setting up modules in config in the first place (feels a bit too much like Spring's XML. I like Guice so that I can do it in code!)

From Rich's mailing list post that he linked to:
>Look at GuiceApplicationLoader and override the load method. You can use your own ApplicationLoader class by setting the "play.application.loader" config setting.
Source is here: https://github.com/playframework/playframework/tree/2.4.0-M3/framework/src/play/src/main/scala/play/api/inject/guice

We should at least document `play.application.loader` because I don't see it in [the docs](https://www.playframework.com/documentation/2.4.x/JavaDependencyInjection). I have a lot of questions about how you'd do that and would love to see an example.

**Comment by benmccann** [comment]
Really digging into see how the `GuiceApplicationLoader` works and is used. It looks like `GuiceApplicationLoader` is used by `ApplicationLoader` is used by `ApplicationProvider` is used by `Server` which is instantiated by `ServerStart.main`. Ideally I would write my own `main` which would construct a Play server with the `GuiceApplicationLoader` I provided it. I would love to construct Play apps from code and be able to embed Play in apps this way. However, the tricky part is that in dev mode, the `main` function isn't called and instead `mainDev` is called which passes in a `BuildLink` that is used to reload the application when an HTTP request is received. It'd be cool to refactor a little bit of that stuff out into play-reloader and eventually SBT, but that's another topic.

What Play's doing today all looks pretty sane. My only recommendation is to document `play.application.loader` and consider removing `play.modules.enabled` in favor of just using `play.application.loader`

**Comment by jroper** [comment]
`play.modules.enabled` is needed so that modules can automatically register themselves, ie, you only need to have a dependency on `play-jdbc`, and you'll get the Play database modules automatically.  Modules can either be Guice modules, or they can be Play modules (which do have access to the configuration and and environment).

Originally it wasn't really feasible for a Java application to create their own application loader, so we only documented it for Scala users who may be using Scala compile time DI techniques (see [here](https://www.playframework.com/documentation/2.4.x/ScalaCompileTimeDependencyInjection)), but now that we have `GuiceApplicationBuilder`, it's now much more straight forward to create an application loader from Java, so we could document it in Java.

**Comment by benmccann** [comment]
I think we're not too far off from being able to do it in Java, but we're not quite there yet. I took a stab at documenting it and found it's not quite feasible yet. Here's a PR that we can start from https://github.com/playframework/playframework/pull/4122. We'll have to take a look at improving this a bit before the release, which hopefully won't be too hard

**Comment by igmar** [comment]
Having the application + env in the module's constructor is very handy : It allows me to use a JSR compliant cache module, with the named caches specified in the application conf.
The Play default cache isn't suitable : It doesn't allow me to invalidate it at once.

The naming needs the ability to provide the list of named caches in advance, since you need to bind them all.

**Comment by benmccann** [comment]
@richdougherty thank you!! looks like you fixed this in https://github.com/playframework/playframework/commit/8ea40937928c784458bac949d9e6d9cf52df3fa6

You probably want to back out or update my change that went in at https://github.com/playframework/playframework/pull/4122, which was a placeholder for this and only half done.

**Comment by richdougherty** [comment]
@benmccann: That's right, 95fe2d116f311a0c89c09deb5f540732dea452b2 allows Guice modules to access the Play application's `Environment` and `Configuration`. Hopefully that will address the main need behind this issue. I want to write some more `ApplicationLoader` docs (I'll look over your changes in #4122 first), then hopefully we can close this ticket.

**Comment by benmccann** [comment]
@richdougherty I just tried upgrading our app to Play 2.4-RC1 and I got stuck here. We have some Guice modules that take constructor parameters of other types. Some of the modules we could edit to make them take Configuration objects instead of their current parameters. But some of the modules are coming from other projects where we don't control it or it doesn't make sense to introduce a dependency on Configuration

**Comment by jroper** [comment]
@benmccann modules are of course not DI injected. if you want to use a module that has constructor dependencies, then you have to manually instantiate it, that means writing a custom application loader, and using the `GuiceApplicationBuilder`, with the `bindings` method to add your custom instantiated module.

**Comment by benmccann** [comment]
Yeah, I wasn't suggesting we DI the modules :-)  Just that writing an ApplicationLoader is incredibly difficult and undocumented

**Comment by benmccann** [comment]
I sent a PR for this here: https://github.com/playframework/playframework/pull/4291

**Comment by benmccann** [comment]
I'm going to close this. I think it's fixed with @richdougherty 's PR

**Comment by richdougherty** [comment]
Agreed.
