### ISSUE TITLE
[2.4.0-M2] Dashes in URL gave unexpected results

### ISSUE THREAD

**Issue by igmar** [playframework/playframework#4111]
Hi,

route : 

GET         /v1/game/:id               controllers.GameController.getGame(id: java.util.UUID, lang: F.Option[String])

and URL : 
http://gameservice.beta.coolgames.com/v1/game/ab6b779b-acdf-45de-950d-c0e7322318ab&lang=en
give me 

For request 'GET /v1/game/ab6b779b-acdf-45de-950d-c0e7322318ab&lang=en' [Cannot parse parameter id as UUID: For input string: "c0e7322318ab&lang=en"] 

If I change the route to : 

GET         /v1/game/

and put id in the query param, it works. Is this expected behaviour, or am I missing something ?

**Comment by jroper** [comment]
You're missing a `?` in your URL, you have an `&`:

    /v1/game/ab6b779b-acdf-45de-950d-c0e7322318ab&lang=en

It should be:

    /v1/game/ab6b779b-acdf-45de-950d-c0e7322318ab?lang=en

The error message looks like that because Play is taking the error message from the exception thrown by the JDK UUID parser, which is `For input string: "c0e7322318ab&lang=en"`, presumably the parser has split the String by dashes, and is complaining about the last part of it.  The fact that the JDK UUID parser outputs such garbage messages is not something we can really do something about in Play.

**Comment by igmar** [comment]
Indeed, I totally missed that one. Sorry for wastinh youre time on this.
