### ISSUE TITLE
[2.4.0-M2] .recover() in Promise not working

### ISSUE THREAD

**Issue by igmar** [playframework/playframework#4124]
Hi,

This doesn't compile : 

```Java
public F.Promise<Result> show() {
        return F.Promise.promise(() -> {
            return ok();
        }).recover(throwable -> {
            return badRequest();
        });
}
```

If you ask me, it should. It complain that it wants a play.mvc.Result, where badRequest gives a play.mvc.Results.Status

I have no idea how to handle this, or work around this. Any fixes welcome, it makes the error handling complex.

**Comment by igmar** [comment]
Ok.. This does work : 

```Java

public F.Promise<Result> show() {
        return F.Promise.promise(() -> {
            Result r = ok();
	    return r;
        }).recover(throwable -> {
            return badRequest();
        });
}
```

**Comment by igmar** [comment]
Reopened: I would like to know why it works without a Lambda / using a Function().

**Comment by cchantep** [comment]
Hi, Looks like better to be discussed on the [Mailing List](https://groups.google.com/forum/#!forum/play-framework).

**Comment by igmar** [comment]
It seems to pre Promise related, so this might be a real bug.

**Comment by jroper** [comment]
If you ask me, it should compile too.  If you want it to compile, go and raise a bug on the Java compiler.  It doesn't work because Java's type inference is terrible, and Java also doesn't support covariance or contravariance in its generics.  So you need to put lots of hints all over the place in Java to tell it what type it has to use.  If you don't like that, then I would suggest using Scala, which supports covariance/contravariance in generics and also has excellent type inference support.

**Comment by igmar** [comment]
Clear answer James. Scala is a bit of of my league, I got scared by all the _ stuff :-)
