### ISSUE TITLE
Don't mess with class loaders... or do it gently

### ISSUE THREAD

**Issue by Eilie** [playframework/playframework#4159]
Issue is described in following thread:
https://groups.google.com/forum/#!topic/finaglers/snRvOYwljbI
Basically Play's auto-reloading breaks Finagle's reflection based API.

**Comment by jroper** [comment]
If Play didn't "mess" with classloaders, it would be impossible for us to implement hot reloading, you would have to stop your app, recompile, and restart, every time you changed your code.

The problem here seems to be that Finagle is using Class.forName, which assumes that the class it's trying to load is in its own classloader.  That is a very bad assumption for any library to make, if Finagle is going to dynamically load classes that are not its own, it should at very least allow the classloader it uses to be provided through its API.  It could also use the context classloader, which would work in this instance, but the better solution is to have it provided explicitly.  It's Finagle that is behaving badly with classloaders here, not Play.

**Comment by Eilie** [comment]
@jroper Thanks for a great explanation! Will create an issue in Finagle repository then.

**Comment by mosesn** [comment]
@jroper when you say the "context" ClassLoader, do you mean: `Thread.currentThread().getContextClassLoader()`?  Could you elaborate on why that will work?  Also, what do you mean by "dynamically load classes that are not its own"?  Do you just mean "dynamically load classes" or are you concerned that finagle might be trying to load classes that need to be loaded with a special ClassLoader?

**Comment by jroper** [comment]
Let's say finagle has a class itself called `com.twitter.finagle.Client`.  It is safe for finagle to do `Class.forName("com.twitter.finagle.Client")`, because `Class.forName` uses the classloader of the calling class.  But for any classes not provided by finagle (and more accurately, not provided by a library that finagle depends on), such as a class name that a user of finagle has given to finagle, then it's not safe, because that class could well be in a child of the classloader that loaded finagle, which finagles own classloader won't be able to find.

Now, the context classloader is a kind of hack, implemented to solve this problem for JEE, where whatever is managing the threads (eg, the servlet container), sets the applications classloader in a thread local, before invoking application code.  Play does, to some extent, also try to ensure that the context classloader is the applications classloader, but because Play is asynchronous, and requests bounce between threads all the time, this is not always possible, especially if you use your own thread pools.  So, using the context classloader will work in some situations.

But, the thing about reflection is that it sucks, and you should avoid it.  But if you have to use it, then you can't just pretend that everything is magic, classes come from classloaders, when you look up a class, you need to look it up from the right classloader, and so any code that does reflection must pay the price for the suckiness it's introducing, and make sure that the classloader is always explicitly selected.  What many libraries do is provide overloaded methods, one that accepts a classloader, so the user can say which classloader the classes they're going to request and loaded from, and one that uses the context classloader.  The more important one to provide is always the one with the explicit classloader parameter.

**Comment by joantune** [comment]
I keep having nasty classloading issues with hot reloading and the latest Play version 2.6.6 and Play-pac4j derived classes that I'm using for authentication.

I keep getting Class A cannot be cast to Class A, because there are different classloaders. I tried following the advice of getting the `Application`'s classloader and loading the classes with `classloader.loadClass(` where those errros occur, as well as changing the Thread's context class loader to match the application one) but to na.

I stopped using Deadbolt's global state 'hack' and as a result I'm pretty much injecting lots of the Twirl templates with `@this`

Still I don't know what's causing the problem (and actually those two shots at trying to solve it were obviously shots in the dark, something that I usually don't do, but seen that global state is deprecated I thought I might as well do it even if it wasn't the issue)

My question is:

Any tips on how to debug this? I'm now thinking: keep track who spawns classloaders (breakpoint on `java.lang.ClassLoader` constructors) and which classloaders are at play when I get the error. Is that the best course of action? any tips?
