### ISSUE TITLE
Transitive dependencies - licensing issues

### ISSUE THREAD

**Issue by sander24** [playframework/playframework#4197]
Hi,
I assume Play2 is looking to be an open-source project and preferably be compatible with the OSD definition (http://opensource.org/licenses/alphabetical).

During a legal review for an enterprise sales deal for software that embeds Play2, some things came out:

- com.typesafe.play:play-java_2.10:2.3.8 pulls in org.reflections:reflection:0.9.8. This is licensed under some Do What The Fuck You Want Public License, that's probably supposed to be funny, but it is not an OSD-compatible license. Creates need for explanations, special attention, etc...

- com.typesafe.play:build-link:2.3.8 pulls in old Javassist, 3.18.2-GA. Javassist up until version 3.19 was licensed under Mozilla Public License 1.1, which is also not OSD-compliant and is discouraged. Upgrading to Javassist 3.19 would solve this problem, as this is also dual-licensed under apache2.

Thanks!

**Comment by megazord** [comment]
Play is already using [Javassist 3.19](https://github.com/playframework/playframework/blob/master/framework/project/Dependencies.scala#L52). I can't find anything related to WTFPL license, besides it being [submitted to approval more than 6 years ago]( http://crynwr.com/cgi-bin/ezmlm-cgi?17:mss:634:200902:aglgcgbhmfcheffmdgon). Maybe you can ask the Reflections developers to change the license or have a dual-license approach.

Moreover, I think that Playframework follows the [license guidelines defined by Typesafe](https://typesafe.com/legal/licenses). Not sure if they will change their policies.

**Comment by jroper** [comment]
Play's dependencies, and the licenses of each, have been scrutinised with a fine-tooth comb by Typesafe's legal team, to ensure that they can be commercially supported and can be safely included in commercial software.  That is to say, we ensure that every library that Play depends on is commercial friendly, which presumably means that we have the same goals.

In this context, OSD compatibility is not very helpful, because OSD includes many licenses that are not commercial friendly, for example, if any library that Play depended on were GPL, this would mean that if you embedded Play in your software, you would need to release your software under the GPL or a GPL compatible license.  And, technically, the same may also apply to LGPL, because the exclusions added by LGPL are defined in the context of linking binary executables, and whether or how they apply to the JVM classpath and JVM bytecode is not at all clear.  Sun's lawyers definitely didn't think LGPL was appropriate to apply to the JVM classpath or bytecode, so when they released Java as open source, rather than using the existing LGPL, they defined their own license based on the GPL but with a classpath exception.  For that reason, we steer well clear of LGPL too.

As for reflections, I'll have a look, I'm not 100% sure whether we still need it or not, it is likely still required by play-ebean, but play-java might not need it.

**Comment by sander24** [comment]
* build-ling:2.3.8 is using javassist 3.18.2-GA, this is not OSD-compatible. Understandable that it is hidden deep in a sub-project and not so easy to spot.. run "sbt dependency-dot" or something similar on some play project.
* What James says might be true for GPLv1, but this version is also not accepted by OSD (and nowadays nearly not used). GPLv2 is okay for commercial stuff. But that goes away from the original topic, anyway.
* I wasn't saying that all the licenses in the OSD list are perfect, but the contrapositive of this: the licenses _not_ in the OSD list should be avoided, as their harded to get accepted/approved in enterprise sales.

**Comment by rashi04** [comment]
Hi,
I need the list of licenses of all the jars being used in Playframework 1.3.1. How do I get them?

**Comment by jroper** [comment]
For a start, you should raise Play 1 issues on the Play 1 issue tracker.  But this is not an issue, it's a question, so you're better off asking on the mailing list.

**Comment by marcospereira** [comment]
Looks like there is no action to be taken here.

**Comment by coverbeck** [comment]
@jroper, did you find out any more about reflections.jar, as you mentioned in your comment from Aug 2015? Although WTFPL license seems fine to me, a non-lawyer, and to your legal team, my company's lawyers are not happy with that license. Is it possible to remove it from our distributions of our Play app?

**Comment by gslowikowski** [comment]
Reflections library v. `0.9.9` used by Play! Framework in versions `2.4.x` is dual licensed:

Fragments from `pom.xml` file:
```xml
    <groupId>org.reflections</groupId>
    <artifactId>reflections</artifactId>
    <version>0.9.9</version>
...
    <licenses>
        <license>
            <name>WTFPL</name>
            <url>http://www.wtfpl.net/</url>
        </license>
        <license>
            <name>The New BSD License</name>
            <url>http://www.opensource.org/licenses/bsd-license.html</url>
        </license>
    </licenses>
```
Maybe it will help, provided that upgrading Play! Framework version is acceptable option for you.

**Comment by coverbeck** [comment]
Thanks @gslowikowski.

Upgrade might be tricky, but we'll see.
