### ISSUE TITLE
[PROJECT] - Clarify Guidelines for Project Members

### ISSUE THREAD

**Issue by lazaridis-com** [playframework/playframework#4228]
This is an enhancement request, and I **choose**  to **not** discuss it on the mailing-list.

The project guidelines should be revised, in order to contain strict policies which disallow project members and contributors to behave in a "wild-west" manner on the project resources, especially on the central **public** issue-tracker of Play!

An example, from #4219 

>Hi @lazaridis-com, thanks for your interest in Play. Obviously you are free to evaluate Play. Please consider contribution rules and first use the Mailing List to discuss changes which are not bug

**Problems:**

* @cchantep **revokes** after his statement the comment privileges, which is simply rude.
* the role of cchantep is unclear. His behavior reflects negatively on the play-project.
* cchantep is obviously treating **guidelines** as **rules** (which is of course a terrible mistake)
 

It is one thing to have **guidelines**, another thing to have **rules** and yet another to have so called **brute-force-rules**.

If the Play! team likes to have **brute-force-rules**, and if the Project-Lead and Typesafe Technical Lead agrees with the behaviour shown by cchantep, then at least **update the guidelines** for contributing, thus they are clearly stated as **strict rules**.

### A personal note

All this adds to the very bad usability experience with the Typesafe website and with the Play Framework itself. I cannot express in words how terrible I feel about all this.

A very promising platform is beeing ruined by missing organisation and structure. Hope the decision-takers will manage to see the deep problems (although it seems that they are very busy with high-profile projects/clients).

Anyway, I've decided to go with Pivotal's Spring Platform.

Have fun.

**Comment by nafg** [comment]
On Mon, Apr 13, 2015, 3:33 PM Lazaridis <notifications@github.com> wrote:

This is an enhancement request, and I *choose* to *not* discuss it on the
mailing-list.

 Um why?

I think not taking into account community customs is a bit selfish?

The project guidelines should be revised, in order to contain strict
policies which disallow project members and contributors to behave in a
"wild-west" manner on the project resources, especially on the central
*public* issue-tracker of Play!

An example, from #4219
<https://github.com/playframework/playframework/issues/4219>

Hi @lazaridis-com <https://github.com/lazaridis-com>, thanks for your
interest in Play. Obviously you are free to evaluate Play. Please consider
contribution rules and first use the Mailing List to discuss changes which
are not bug


*Problems:*

@cchantep <https://github.com/cchantep> *revokes* after his statement the
comment privileges, which is simply rude.the role of cchantep is unclear.
His behavior reflects negatively on the play-project.cchantep is obviously
treating *guidelines* as *rules* (which is of course a terrible mistake)

It is one thing to have *guidelines*, another thing to have *rules* and yet
another to have so called *brute-force-rules*.

If the Play! team likes to have *brute-force-rules*, and if the
Project-Lead and Typesafe Technical Lead agrees with the behaviour shown by
cchantep, then at least *update the guidelines* for contributing, thus they
are clearly stated as *strict rules*.

*A personal note*

All this adds to the very bad usability experience with the Typesafe
website and with the Play Framework itself. I cannot express in words how
terrible I feel about all this.

A very promising platform is beeing ruined by missing organisation and
structure. Hope the decision-takers will manage to see the deep problems
(although it seems that they are very busy with high-profile
projects/clients).

Anyway, I've decided to go with Pivotal's Spring Platform.

Have fun.

--
Reply to this email directly or view it on GitHub
<https://github.com/playframework/playframework/issues/4228>.<img src="
https://ci4.googleusercontent.com/proxy/tW44aNHy0n2P4JLWeA8tZD0-M509slTl9UDscOIvC5Rdi-YNI76rSujNzNtqTeEuwgrxgB4sf_IOD4vFGgc30LFGequFStAAuGj9oIagsBD-Yatume-iBvi4ji15yPACvPbPF9spYjP6Z_xZOCs0CMSgs1ELmw=s0-d-e1-ft#https://github.com/notifications/beacon/AAGAUEAYGWspuVe0HZg9la0LdyHZts_Uks5n_BGggaJpZM4D_qxw.gif
">

**Comment by lazaridis-com** [comment]
@nafg, have a good night!

**Comment by jroper** [comment]
Hi @lazaridis-com, I'm sorry that you've had a terrible experience.

Please understand, we're concurrently working on many issues in the issue tracker at once, it's a massive task keeping the list of open issues down to something sane.  I spend up to 4 hours every day just triaging, responding to, and reviewing issues on GitHub.  To you, this may be a medium that you feel you can use in whatever way you want, and no one can stop you from raising issues as you please.  To me, GitHub is a project management tool that I use to manage/work with a team of 10 very active and several hundred more occasionally active geographically distributed developers, and to interface to a community of over a hundred thousand developers.  In order for this to work, we publish some guidelines that we request all members of the community to follow, these are designed to keep the issue tracker focussed on tangible concrete tasks that we believe should be done.  When they aren't followed, if the issue looks like it's not going to be a concrete task but rather a potentially long conversation with many actionable items, we close the issue and redirect the user to the mailing list.  To you it may just be a few issues, but if the whole community ignored the guidelines, the noise in this issue tracker would make it impossible for us to get any value out of using it.  So we have to be reasonably strict about enforcing these guidelines, to prevent that from happening.

You may think that because they are called "guidelines" that that means they are optional, I assure you that is not true.  The guidelines also state that all code must be well tested and documented, and that also isn't optional.  They are called guidelines because they are not 100% rigid, sometimes there are exceptions, sometimes feature requests are raised that don't need to be discussed on the mailing list first because the value of the feature and path to implementing it is so straight forward that everyone agrees.  We make a judgement call on this on a case by case basis.  The issues you raised here are not exceptions to the guideline to discuss new features and improvements on the mailing list first, and so we closed them.

@cchantep is a community volunteer and part of the Play core team, shown here: https://playframework.com/code.  He was acting within the boundaries of what we expect from all the Play core team members, and according to our contributor guidelines.

**Comment by megazord** [comment]
Here is my two cents, not as a project member, but as a contributor. 

The [contributions guidelines explicitly recommends](https://github.com/playframework/playframework/blob/master/CONTRIBUTING.md#reporting-issues) that:

> If you have a feature request, **please raise it on the developer mailing list first**. The mailing list is the best forum to discuss new features, and it may be that Play already provides something to achieve what you want to achieve and you didn't realise. - 

I think this is a very practical (and good) decision since it keeps the issue tracking focused on things to do, instead of things to discuss. If you want to get relevant feedback from project members and contributors, there is a separated mailing list for that:

https://groups.google.com/forum/#!forum/play-framework-dev

So why not use it? Of course these are just guidelines, but people won't need to treat them as rules if you just behave polite.

**Comment by lazaridis-com** [comment]
@jroper & @megazord - People, please get serious and try to impress some kiddos about project management. I'm finished with assessing the project (that this issue was closed gives it the rest) and my time-budget is anyway gone. Note that I've not read your messages, exept the first and the last sentences. Just go on with you "polite" way, and you'll ruine this great platform even more.

As said, I'm out and will go with Pivotal.
