### ISSUE TITLE
why play2.4-RC1 do not support java 6 ?

### ISSUE THREAD

**Issue by yinyousong** [playframework/playframework#4414]
I use play framework for more than two years,and use play for several types of banks project,currently in use play-2.2.1. thanks for play team！
       when released a new version of play 2.4.X,I am looking forward to the new characteristics of play.
but the play must use the Java8, Java 6 and Java 7 was dropped.
       eh,Java8 is good,but the technical team of bank.tell me you must use the java6.eh,play2.4.x can support  java 6?
       thanks for play support.

**Comment by jroper** [comment]
Java 7 was end of lifed last month, Oracle are no longer publishing updates
for it, not even security fixes.  Java 6 was end of lifed over 2 years
ago.  You could argue that it's negligent of any technical team at a bank
*not* to upgrade to Java 8, since security fixes are no longer going to be
published for it.  Banks of all organisations should be diligent about
upgrading, unless they don't care about security...

So anyway, you can't expect us to support versions of Java that Oracle
themselves refuse to support.

We dropped Java 6 support because there is a lot of good stuff in Java 8,
new date time APIs, new functional APIs, etc etc, that we really wanted to
take advantage of in Play.

If you're happy staying on an unsupported end of lifed version of Java,
then what problem have you got staying on an old version of Play?  Play 2.3
still works on Java 6, you can use that.

On 8 May 2015 at 21:36, jacksong <notifications@github.com> wrote:

>    I use play framework for more than two years,and use play for several types of banks project,currently in use play-2.2.1. thanks for play team！
>    when released a new version of play 2.4.X,I am looking forward to the new characteristics of play.
>
> but the play must use the Java8, Java 6 and Java 7 was dropped.
> eh,Java8 is good,but the technical team of bank.tell me you must use the
> java6.eh,play2.4.x can support java 6?
> thanks for play support.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playframework/playframework/issues/4414>.
>



-- 
*James Roper*
*Software Engineer*

Typesafe <http://typesafe.com/> – Build reactive apps!
Twitter: @jroper <https://twitter.com/jroper>

**Comment by mkurz** [comment]
@jroper As far as I know it's possible to buy commercial support from Oracle to get security updates even for (public) end-of-life JDK's.

**Comment by jroper** [comment]
It's also possible to buy commercial support for Play :)

**Comment by hepin1989** [comment]
yes,akka support java6 for akka 2.4 in commercial too.:)
