### ISSUE TITLE
Null JsValue cannot be cast as JsNull

### ISSUE THREAD

**Issue by mslinn** [playframework/playframework#4425]
`JsValue` can contain a `null`:

````
scala> Json.toJson(System.getenv("asdf"))
res88: play.api.libs.json.JsValue = null
````

But you cannot cast a `JsValue` containing null to a `JsNull`:

````
scala> Json.toJson(System.getenv("asdf")).as[JsNull]
<console>:14: error: not found: type JsNull
              Json.toJson(System.getenv("asdf")).as[JsNull]

<console>:14: error: ambiguous implicit values:
 both object IntReads in trait DefaultReads of type play.api.libs.json.Reads.IntReads.type
 and object ShortReads in trait DefaultReads of type play.api.libs.json.Reads.ShortReads.type
 match expected type play.api.libs.json.Reads[<error>]
              Json.toJson(System.getenv("asdf")).as[JsNull]
                                                   ^
````

Would it make sense to be able to do this?

**Comment by jroper** [comment]
`JsNull` is not a type, it's an object, the correct syntax is:

```scala
Json.toJson(System.getenv("asdf")).as[JsNull.type]
```

This fails to compile because we don't provide a deserialiser for `JsNull`. That's possibly one thing we should do.  But then it won't run, because `Json.toJson(System.getenv("asdf"))` is not returning `JsNull` or `null`, it's returning `JsString` with the value string set to null:

```
scala> Json.toJson(System.getenv("asdf")) match {
     |   case JsString(null) => println("matched")
     |   case _ => println("not matched")
     | }
matched
```

There's a reason for this, since you're passing something of type String to `Json.toJson`, the `Writes[String]` gets passed to it, and it doesn't make any assertions on the string itself.  Anyway, if something is of type `JsString`, that's saying it's a json string, not null, not anything else but a json string. So, even if we provided a `JsNull` deserialiser, I would always expect:

```scala
Json.toJson(System.getenv("asdf")).as[JsNull.type]
```

to throw an error, because something of type `JsString` cannot be converted to `JsNull`.  Perhaps we could modify the `Writes[String]` implementation to do a `null` check, that way `Json.toJson(System.getenv("asdf"))` would rightly fail.  Anyway, I think the error is in your example there, not in the Play code.

**Comment by mslinn** [comment]
Thanks for the explanation. I now understand the logic of why Play JSON's null handling works the way it does. On a related note, I expect it would be most useful to Play programmers if the above, and the following, did not require casts.

````
scala> import play.api.libs.json._
import play.api.libs.json._

scala> Json.toJson("Blah")
res0: play.api.libs.json.JsValue = "Blah"

scala> Json.toJson("Blah").as[JsString]
res1: play.api.libs.json.JsString = "Blah"

scala> Json.toJson(42)
res2: play.api.libs.json.JsValue = 42

scala> Json.toJson(42).as[JsNumber]
res3: play.api.libs.json.JsNumber = 42

scala> Json.toJson(false)
res4: play.api.libs.json.JsValue = false

scala> Json.toJson(false).as[JsBoolean]
res5: play.api.libs.json.JsBoolean = false
````
The Play JSON library does not seem to support the expectations that a user is likely to have. With respect to the above, for example, should not `Json.toJson(42)` return a `JsNumber` instead of a `JsValue`, a `Json.toJson(false)` return a `JsBoolean`, and a `JsValue` containing a `null` be returned as a `JsNull`?

**Comment by mslinn** [comment]
Thanks for the explanation. I now understand the logic of why Play JSON's null handling works the way it does. On a related note, I expect it would be most useful to Play programmers if the above, and the following, did not require casts.

````
scala> import play.api.libs.json._
import play.api.libs.json._

scala> Json.toJson("Blah")
res0: play.api.libs.json.JsValue = "Blah"

scala> Json.toJson("Blah").as[JsString]
res1: play.api.libs.json.JsString = "Blah"

scala> Json.toJson(42)
res2: play.api.libs.json.JsValue = 42

scala> Json.toJson(42).as[JsNumber]
res3: play.api.libs.json.JsNumber = 42

scala> Json.toJson(false)
res4: play.api.libs.json.JsValue = false

scala> Json.toJson(false).as[JsBoolean]
res5: play.api.libs.json.JsBoolean = false
````
The Play JSON library does not seem to support the expectations that a user is likely to have. With respect to the above, for example, should not `Json.toJson(42)` return a `JsNumber` instead of a `JsValue`, a `Json.toJson(false)` return a `JsBoolean`, and a `JsValue` containing a `null` be returned as a `JsNull`?

ps: ditto for `JsObject`:

````
scala> Json.toJson(Map("Hello" -> "World"))
res8: play.api.libs.json.JsValue = {"Hello":"World"}
````

**Comment by mslinn** [comment]
After looking around for a bit, I think you are right about `JsNull` handling. [Here is a good writeup that supports what you said](http://blog.bdoughan.com/2012/04/binding-to-json-xml-handling-null.html) and shows why `JsNull` is a separate non-value.

The other coercions are therefore an unrelated issue. Perhaps the Play Framework should return more precise types whenever possible, so the casts would not be required.

**Comment by richdougherty** [comment]
> On a related note, I expect it would be most useful to Play programmers if the above, and the following, did not require casts.

@mslinn, would you mind raising a separate issue for this? We'd probably need another type variable in `Writes` to encode the type of `JsValue` it creates, e.g. `Writes[T,J <: JsValue]` means we can write a `T` to a `J`, which is a type of `JsValue`. I'm not sure if that could be done in a backwards compatible way, but it's worth considering.

**Comment by gmethvin** [comment]
@mslinn If you're going to create the issue, it'd also be good to have some examples of where it'd be useful in real code. For the value types like `JsString`, `JsNumber`, etc., I haven't personally encountered any cases where the more specific type would be useful. In one or two situations I've wanted to tack on an extra property to something that serializes to a `JsObject` though.

That said, I like the simplicity of the current API is with respect to `Writes`. I think 99% of the time you don't care about the subtype since you're using it where only a `JsValue` is required (for example, in an HTTP response), and it's nice to use the type class syntax like `def doSomething[A: Writes](thing: A)`.

**Comment by jroper** [comment]
I'm not sure if it could be done at all - what if I defined the following:

```scala
implicit val myNumberWrites = Writes[Number] { number => JsString(number.toString) }

Json.toJson(42)
```

In that case, the statement there will return `JsString("42")`, not `JsNumber(42)`, and that's exactly what we want, we want the json serialisation to be customisable, that's the whole point of having a `Writes` type class, we don't want it hardcoded that a number should return a `JsNumber`.

Also, note that there is no cast going on here:

```scala
Json.toJson(42).as[JsNumber]
```

What's happening rather is that 42 is being converted to Json, and then that Json is being converted back to domain object - it's just that you've specified the domain object to be the `JsNumber` type.  If we were to rename the methods `toJson` and `as` to make it clearer, and explicitly pass the implicit reads/writes, this is what you would get:

```scala
val domainObject: Int = 42
val json: JsValue = Json.domainObjectToJson(domainObject)(Writes.intWrites)
val newDomainObject: JsNumber = json.asDomainObject(Reads.jsNumberReads)
```

As @gmethvin says, what's the use case here, because the example you've given is a very convoluted way of achieving this:

```scala
JsNumber(42)
```

I can't think of any real world use case where you'd want to use the code that you're using.

**Comment by mslinn** [comment]
The "convoluted code" is taken from the [Play-JSON docs](https://www.playframework.com/documentation/2.4.0-RC1/ScalaJson#Using-Writes-converters). All I did was show the return values, and noted that the type is always `JsValue`. I wondered why the type specificity of the returned value did not match the type specificity of the JSON input. I then showed that the `as` method could yield a more precise JSON equivalent of the original basic type. I am not proposing that the use of `as` is a best practice, I'm wondering how this "downcasting" to `JsValue` helps a programmer work with Play-JSON.

With respect to this code:

    Json.toJson(42).as[JsNumber]

You say "What's happening rather is that 42 is being converted to Json, and then that Json is being converted back to domain object". Do you actually mean that 42 is converted to a JSON AST?

BTW, the [Lift JSON docs](https://www.assembla.com/wiki/show/liftweb/JSON_Support) show a nice diagram, some of which might be applicable to Play-JSON. The diagram is helpful for orientation, which was my impetus for posting this issue:

![Lift JSON](https://github.com/lift/framework/raw/master/core/json/json.png)

**Comment by mslinn** [comment]
Here is a use case for returning the most specific subclass of JsValue. This code may look familiar:

````
scala> Json.toJson(System.getenv("asdf")) match {
     |    case JsString(null) => "Environment variable was a null string"   
     |    case v: JsString => s"Environment variable has value $v"
     |  }
````
If the result of this `Json.toJson` was a `JsString` instead of a `JsValue`, the result would be "Environment variable was a null string", and there would be no compile warning. Instead, we get the following warning:

````
<console>:11: warning: match may not be exhaustive.
It would fail on the following inputs: JsArray(_), JsBoolean(_), JsNull, JsNumber(_), JsObject(_)
              Json.toJson(System.getenv("asdf")) match {
                         ^
res71: String = Environment variable was a null string
````

**Comment by gmethvin** [comment]
@mslinn `Json.toJson` is intended to be used when you want to serialize something for output as JSON. I don't see the point of converting to JSON in your above use case. Most people would just do:
```scala
Option(System.getenv("asdf")) match {
  case Some(v) => s"Environment variable has value $v"
  case None => "Environment variable was a null string"
}
```

**Comment by richdougherty** [comment]
Don't worry about making a new issue, looks like we're committed to this one. :)

I'd just replace your example with `JsString(System.getenv("asdf"))`, since you know both the input type and you know that you want a `JsString` as output.

I'd use `Json.toJson` when you need to be generic on the input type, in which case you usually don't know the output type you expect either, so `JsValue` is quite appropriate.

There are counter examples to this statement, when you want to be generic on the input type but _do_ know the output type. An example would be if you match on several different numeric types, and so you know you're going to get out a `JsNumber` as output, but I don't think these examples are very common.
