### ISSUE TITLE
Arrays aren't merged when merge configurations

### ISSUE THREAD

**Issue by aparamonov** [playframework/playframework#4444]
I have 2 play configurations:
```
play {
  modules {
    enabled += "module1"
    enabled += "module2"
  }
}
```
and
```
play {
  modules {
    enabled += "module3"
    enabled += "module4"
  }
}
```

Let's open the project REPL:

scala> import com.typesafe.config.ConfigFactory
import com.typesafe.config.ConfigFactory

scala> import play.api._
import play.api._

scala> Configuration(ConfigFactory.load("app1.conf"))
res0: play.api.Configuration = blabla

scala> Configuration(ConfigFactory.load("app2.conf"))
res1: play.api.Configuration = blabla

scala> res0.getConfig("play.modules")
res2: Option[play.api.Configuration] = Some(Configuration(Config(SimpleConfigObject({"disabled":[],"enabled":["play.api.db.slick.SlickModule","play.filters.csrf.CSRFModule","play.filters.cors.CORSModule","play.filters.headers.SecurityHeadersModule","play.filters.gzip.GzipFilterModule","play.api.inject.BuiltinModule","play.api.i18n.I18nModule","module1","module2"]})))) // There we can find module1 and module2 declarations

scala> res1.getConfig("play.modules")
res3: Option[play.api.Configuration] = Some(Configuration(Config(SimpleConfigObject({"disabled":[],"enabled":["play.api.db.slick.SlickModule","play.filters.csrf.CSRFModule","play.filters.cors.CORSModule","play.filters.headers.SecurityHeadersModule","play.filters.gzip.GzipFilterModule","play.api.inject.BuiltinModule","play.api.i18n.I18nModule","module3","module4"]})))) // There we can find module3 and module4 declarations

scala> (res0 ++ res1).getConfig("play.modules")
res5: Option[play.api.Configuration] = Some(Configuration(Config(SimpleConfigObject({"disabled":[],"enabled":["play.api.db.slick.SlickModule","play.filters.csrf.CSRFModule","play.filters.cors.CORSModule","play.filters.headers.SecurityHeadersModule","play.filters.gzip.GzipFilterModule","play.api.inject.BuiltinModule","play.api.i18n.I18nModule","module3","module4"]})))) // There I expect to see module1, module2, module3 and module4 declarations, but unfortunately we can only find module3 and module4 declaration

**Comment by jroper** [comment]
The problem is, you can't do that.  Typesafe config has two phases to its loading, first phase, it parses, second phase, it resolves it.  To see the difference between the two:

```
scala> val unresolved = ConfigFactory.parseResources(classloader, "app1.conf")
unresolved: com.typesafe.config.Config = Config(SimpleConfigObject({"play":{"modules":{"enabled":${?play.modules.enabled}["module1"],"enabled":${?play.modules.enabled}["module2"]}}}))

scala> val resolved = unresolved.resolve
resolved: com.typesafe.config.Config = Config(SimpleConfigObject({"play":{"modules":{"enabled":["module1","module2"]}}}))
```

You can see, the first version, the append means that it references the existing value.  Once you resolve it, it no longer does.  So if you merge two configs at that point, they override each other.  Now you're using `ConfigFactory.load` to load the config, this does both the parse and resolves it.  There's nothing Play's `Configuration` object can do at this point, it doesn't have the unresolved configuration so array appends cannot work.

It also has some other unintended effects, because it will also load `reference.conf`, so anything in `app1.conf` that overrides something in `reference.conf` will be overwritten when you merge it with what you've loaded from `app2.conf`, since it will also load `reference.conf`, and that will take priority.

So, to solve your problem, use `parseResources` instead, this will load just the config file you want, without loading the `reference.conf` files or system properties or anything, and won't resolve it.  Then fallback to a fully resolved config:

```scala
scala> val enabledModules = ConfigFactory.parseResources(classloader, "app2.conf").withFallback(ConfigFactory.load(classloader, "app1.conf")).resolve.getStringList("play.modules.enabled")
enabledModules: java.util.List[String] = [play.api.inject.BuiltinModule, play.api.i18n.I18nModule, module1, module2, module3, module4]
```

**Comment by aparamonov** [comment]
I see, thanks!
