### ISSUE TITLE
Fix performance regression in 2.3

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#4476]
#4435 caused a 10% performance regression due to reading configuration on each request. Performance dropped from about 50k req/s down to 45k req/s. See the 2.3.x branch results on http://playframework.github.io/prune/ at around May 12.

cc @fernandezpablo85, @julienrf.

**Comment by marcospereira** [comment]
PR #4437 is also related with this change. I was thinking if being `lazy val` wasn't enough to solve the problem. Or maybe the filter described in the issue #4434 could use a `lazy val` instead. I don't know for sure how we are prioritizing performance regressions, but as an user, my expectation is that new releases are faster.

**Comment by fernandezpablo85** [comment]
A possible solution would be to cache the value **if** the current application is defined (not `None`).

**Comment by fernandezpablo85** [comment]
If you guys think that's a viable solution I can start working on a patch for it. It would be great to know how to run those perf tests (at least the ones involved in this ticket) locally to confirm that the issue is gone after applying the patch.

**Comment by richdougherty** [comment]
You could do the same thing we do in Play 2.4. We use a type of cache that caches a single value. Every time the cache is used it checks if the application has changed. If the application is still the same then it uses the cached value. If not it clears the cache and recalculates the value.

This is really fast for the common case when the application doesn't change very often, because there's no need to do any complicated lookups. But it also works when the application changes often, e.g. during tests.

Here's the class to backport:
https://github.com/playframework/playframework/blob/2.4.x/framework/src/play/src/main/scala/play/utils/InlineCache.scala

Here's some wrapper code that uses this class to cache some configuration:
```scala
private[play] def configurationCache[A](getConfig: Option[Configuration] => A): Application => A = {
  new InlineCache((app: Application) => getConfig(app.configuration))
}
```

Here's how you'd use the wrapper code:

```scala
private val cookieNameCache = configurationCache { optConfig: Option[Configuration] =>
  optConfig.flatMap(_.getString("session.cookieName")).getOrElse("PLAY_SESSION")
}
private val maxAgeCache = configurationCache { optConfig: Option[Configuration] =>
  optConfig.flatMap(_.configuration.getMilliseconds("session.maxAge")
    .map(Duration(_, MILLISECONDS).toSeconds.toInt))
}
private val httpOnlyCache = configurationCache { optConfig: Option[Configuration] =>
  optConfig.flatMap(_.getString("session.httpOnly")).getOrElse(true)
}

def COOKIE_NAME = cookieNameCache(Play.maybeApplication)
override def maxAge = maxAgeCache(Play.maybeApplication)
override def httpOnly = httpOnlyCache(Play.maybeApplication)
```

If you do this it would be really great if there are tests for how the caching works with no current application, tests with an application and tests for when the application changes. We want to be really careful about bugs on the stable branch!

**Comment by jroper** [comment]
There's always been a compromise between whether we should do these expensive lookups per request, thus allowing them to be reloaded, or whether we should cache it in a val, thus not allowing it to be reloaded.  The solution to this has been fully implemented in Play 2.4 (the lookups are no longer expensive).  For 2.3, I think we should back out the fix, it's not worth the performance hit, and not worth the risk of major changes to this core part of the code in order to properly solve it.

Also, the original code that demonstrated this issue:

```scala
object ExpiredSession extends Filter {

  val redirectHome = Results.Redirect(controllers.routes.Application.home).withNewSession

  def apply(next: (RequestHeader) => Future[Result])(request: RequestHeader) = {

      if (sessionExpired)
        Future.successful(redirectHome)
      else
        next(request)
  }
}
```

The fix doesn't actually solve it, the above code still has a problem even with the fix, that being the result stored in the `val redirectHome` uses an incorrectly configured session - the problem is only moved when the cookie configuration is changed to def, instead of lazy val, it's not fixed.  The only real fix to the above problem is to change `redirectHome` to be a `def`.  So I don't think the above code is a good example of why the problem should be fixed, since the fix doesn't fix it.

**Comment by fernandezpablo85** [comment]
@jroper the scope of the problem is bigger than that single request having bad config values.

The **real issue** is that if you happen to have code like that (honestly, is not that weird) every other `.withSession` call, throughout your **entire codebase will have wrong config values**. I believe this is serious since the place where the bug is, and the place where the code fails are probably different and unrelated files (it took me a while to find it and I thought it might save other developers time).

Again, I understand the perf tradeoff and I'm still willing to backport the 2.4 cache classes if you guys are OK with that.

**Comment by jroper** [comment]
I'm very aware of what the real issue is. But as to its seriousness - this code has existed for over 2 and a half years, and this is the first time someone has raised it. It is fixed in 2.4, it's not like I'm saying "this isn't an issue that should be fixed". It's trivial for you to work around the issue in your own code. Given all this, according to our [backporting policy](https://playframework.com/contributing), the fix is not a candidate for backporting. Note that people who are using 2.3.x today in production are using it successfully, and are not impacted by this issue. Tomorrow there might be a security vulnerability that they need to urgently upgrade to. It's our responsibility to them to ensure that the only changes that go into the 2.3.x branch are low risk, so that they can confidently upgrade to the latest 2.3.x at any time. Backporting the cache is just too high risk for not enough value.

**Comment by fernandezpablo85** [comment]
Seems reasonable not to fix the issue given that it's not as common as I thought. I would only like to add two comments to this line: 

>  It's trivial for you to work around the issue in your own code. 

* it is a trivial fix but it's not at all trivial to find out what's going on. Hopefully if someone runs into this problem he/she will find this ticket and how to fix it. The discussion was worth it after all.

* my own code was already fixed before reporting the issue or sending the pull request, it was just for preventing someone else the hours of bug hunting through Plays source (something not every user is willing to do).

Anyway, it's great to see that you keep the quality bar this high, and have this level of commitment with the framework. Keep up with the good work! :smile:

**Comment by richdougherty** [comment]
Is it OK to close this ticket now? The actual regression is fixed.
