### ISSUE TITLE
2.4.0-RC3: FakeApplication doesn't take into account 'play.application.loader' setting

### ISSUE THREAD

**Issue by aparamonov** [playframework/playframework#4482]
For example, if I have custom configuration management in the loader, the expected configuration will not be loaded during test initialisation.

**Comment by jroper** [comment]
FakeApplication *is* the application. The application loader doesn't get used because how can it be? You have already loaded an application when you invoked the FakeApplication constructor, if it uses the application loader, then you'd have two applications, the FakeApplication that you constructed, and the one from the application loader, which one should be used?

ApplicationLoader is just intended for Play to load your application. In your tests, it's your responsibility to load the application. If you want to reuse logic from your application loader in your tests, then you should factor it in such a way that it can be reused from tests.

**Comment by aparamonov** [comment]
You can construct FakeApplication using loader and then set Fake* instances to it.

Btw, if so, how can I disable a module and enable another module for tests that's use FakeApplication?
I see only options to enable/disable plugins that are should be obviously deprecated.

**Comment by marcospereira** [comment]
Hello @aparamonov, 

Do you mind discuss this using the mail list? This way other users can participate. 

Thanks.

**Comment by jroper** [comment]
@aparamonov don't use `FakeApplication`, use `GuiceApplicationBuilder`, as shown in:

https://www.playframework.com/documentation/2.4.0-RC3/JavaTestingWithGuice
https://www.playframework.com/documentation/2.4.0-RC3/ScalaTestingWithGuice

As @marcospereira said, please raise this on the mailing list and discuss there.
