### ISSUE TITLE
PropertiesEnhancer doesn't produce calls to self-written accessors (play-2.3.9)

### ISSUE THREAD

**Issue by aschiffmann** [playframework/playframework#4504]
**Problem**:
When writing a getter or a setter for a field in a Java-class the `PropertiesEnhancer` fails to modify usages of the regarding property in that way that the self-written accessor is being used automatically. Instead the property will be used *directly*.
One big problem of this behaviour is for example, that in this case Ebean's lazy loading won't work: Ebean enhancement only is applied to usages of a property *in its class itself* and not when the property is accessed directly from another class.

**How to reproduce**
The issue can easily be reproduced with the example from the [play-1.2 documentation](https://www.playframework.com/documentation/1.2/model). I have also created a little [git-hub repository](https://github.com/aschiffmann/play-enhancement-bug) for it. 

**Workaround**
The repsitory also contains a branch *"workaround"* that shows, how the expected automatic call of a custom accessor can be forced, by adding the annotation `@PropertiesEnhancer.GeneratedGetAccessor` to the regarding field.

**Bug?**
The issue is being discussed on [stackoverflow](http://stackoverflow.com/questions/30314715/play-frameworks-propertiesenhancer-custom-getters-setters-wont-be-called) without any result so far.
I am not 100% sure whether the behaviour is intended or not. The only documentation about this topic can be found for play-1.2 [where it says](https://www.playframework.com/documentation/1.2/model), that
> Of course you can define the getter and setter methods yourself. If a method exists Play will use the existing accessors.

If the behaviour has changed between play-1.2 and play-2.x at least this has to be documented!

**Comment by jroper** [comment]
Bug on Play enhancer should be raised here:

https://github.com/playframework/play-enhancer

But I don't think it's a bug, if you're writing your own accessors, you can use your own accessors.  As for whether it should be documented - Play 2 is a rewrite from Play 1, they are different frameworks. To describe this as a change would be the same as describing the differences between Django and Play as changes - they're not changes, they're differences. That's why there's no migration guide for moving from Play 1 to Play 2, you don't upgrade from Play 1 to Play 2, you rewrite your app to use the new framework.
