### ISSUE TITLE
[2.3.9] Extremely slow tests execution when there is no internet connection

### ISSUE THREAD

**Issue by mgibowski** [playframework/playframework#4536]
I have discovered this issue in the project that was using play 2.2.1 and then checked the newest version 2.3.9 - the problem remains.

I'm using Mac OS X 10.10.2 and these are the steps:

1) Connect to the Internet
2) Create a new project with activator based on play-scala template
3) Build the project and run the tests - they finish in 5 seconds:

> [activator-test] $ test
...
[info] 2 examples, 0 failure, 0 error
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3
[success] Total time: 5 s, completed 2015-05-25 13:44:12

4) Disconnect with the Internet and run the tests - they finish in 40 seconds:

>[activator-test] $ test
...
[info] 2 examples, 0 failure, 0 error
[info] Passed: Total 3, Failed 0, Errors 0, Passed 3
[success] Total time: 40 s, completed 2015-05-25 13:44:58

In a real-world project with hundreds of tests their execution time gets so long that it's impossible to run them. It makes it really difficult to work on play projects offline, which is sometimes necessary (travels, etc...).

I've checked the timings for other basic activator templates to check if it's only a play issue. For the template "minimal-scala" there is no difference in timing between being connected to the internet or not. For the template "minimal-akka-scala-seed" there exists a difference, but it's a lot smaller - 5 seconds.

I tried to see with nettop any connections established with the outer world during the tests execution, but I didn't see any.

**Comment by jroper** [comment]
Which test is taking a long time?

I see no difference between them on my machine, however, the likely cause is that the index page, which gets rendered by a browser in the tests, does call out to the internet, it makes a request to playframework.com to find out what the latest version of Play is and announce it.  This could be what's causing the problem, and if that's the case, it's not really a problem, since the first thing you do when you create a new Play app is change the index page to be something other than the Play welcome page.

Feel free to reopen if you find it to be anything other than that.
