### ISSUE TITLE
Play 2.4 TestServer problem in ScalaTest+Play's tests

### ISSUE THREAD

**Issue by cheeseng** [playframework/playframework#4569]
Hi all, 

We are working on releasing a ScalaTest+Play final release version that works with Play 2.4.0 final, but unfortunately we have one last problem that we could not figure out what's wrong, it seems TestServer's behavior has somehow changed, let me describe the problem below.

This is failing test suite file: 

https://github.com/scalatest/scalatestplus-play/blob/master/src/test/scala/org/scalatestplus/play/MixedFixturesWsScalaTestClientSpec.scala

I think we can just minimize it to just look at the first scope: 

```
"used with MixedFixtures Server" must {

      "have wsUrl works correctly" in new Server(app) {
        val futureResult = wsUrl("/testing").get
        val body = futureResult.futureValue.body
        val expectedBody =
          "<html>" +
            "<head><title>Test Page</title></head>" +
            "<body>" +
            "<input type='button' name='b' value='Click Me' onclick='document.title=\"scalatest\"' />" +
            "</body>" +
            "</html>"
        assert(body == expectedBody)
      }

      "have wsCall works correctly" in new Server(app) {
        val futureResult = wsCall(Call("get", "/testing")).get
        val body = futureResult.futureValue.body
        val expectedBody =
          "<html>" +
            "<head><title>Test Page</title></head>" +
            "<body>" +
            "<input type='button' name='b' value='Click Me' onclick='document.title=\"scalatest\"' />" +
            "</body>" +
            "</html>"
        assert(body == expectedBody)
      }

    }
```

The new Server(app) is suppose to start new TestServer for each test, here's the link to the related source code of our Server class (which in turn call Play's TestServer): 

https://github.com/scalatest/scalatestplus-play/blob/master/src/main/scala/org/scalatestplus/play/MixedFixtures.scala#L328

The tests worked before Play 2.4, but now we got the following error when running the second test above: 

The future returned an exception of type: java.io.IOException, with message: Closed. (MixedFixturesWsScalaTestClientSpec.scala:49)

If we comment out the first test, the second test will pass, so we're thinking some mutable state is causing the problem here.

If you would like to reproduce the problem, you can follow the follow step: 

```
> git clone https://github.com/scalatest/scalatestplus-play.git
> cd scalatestplus-play
> git checkout wip-play-2.4
> sbt test
```

We couldn't figure out what's gone wrong and what's we can do from our side to fix the problem, so we eventually give up and decided to ask for help here, we apologize for reporting here after the 2.4 final release.

We appreciate any help or pointer.

Thanks.

**Comment by jroper** [comment]
Thanks @cheeseng, great to hear that you're adding 2.4 support now.  It's Friday evening here now, and I'm flying to Amsterdam on Monday, so it may be a while before I get to look at this, but I just wanted to let you know that I will get to looking at this when I have a chance.

Something else we're interested in doing is "adopting" scalatestplus-play, ie, moving it to the playframework organisation, and including it as part of our nightly builds, so that if we break it, we have to fix it.  We'd still give you commit access to it so that you can make any improvements/scalatest upgrades at any time.  This would be a first step towards making scalatest the default test framework for Play.  Would you be interested in that?

**Comment by gmethvin** [comment]
The exception looks like it's happening because you're reusing a WS client from an app that is already shut down. I think using a different application for each test, i.e. changing your `val app` to a `def`, will fix the tests. Is there a reason you needed it to be the same app?

It may have just been a coincidence that it worked in 2.3. I didn't think it was a supported to reuse an application like that in several different test servers.

**Comment by cheeseng** [comment]
@gmethvin you're right that using new instance for each test fix the failed test, the reason of sharing the FakeApplication was simply to reduce overhead of creating new instance for each test, we were in the thinking that unless we know the same app has mutable state (in the mentioned test actually we know it is immutable and should be safe to share), we should be able to share the application instance to cut the overhead that might incurred, I can't really recall exactly if @bvenners has a user that complained about the overhead of creating new application instance (it could be his application has some heavy startup overhead, and makes their tests run slow), so we were thinking to provide a way for the user to share 'immutable' application instance.

**Comment by cheeseng** [comment]
@jroper yes sure I think that's a good idea, I'll write to Bill to follow up with steps we need to do to moving scalatestplus-play to playframework organization.

**Comment by nemoo** [comment]
The official play 2.4 documentation references scalatestplus https://www.playframework.com/documentation/2.4.x/ScalaFunctionalTestingWithScalaTest. The scalatestplus readme https://github.com/scalatest/scalatestplus-play suggests it has not yet been released. What is the current status on this?

**Comment by bvenners** [comment]
It has not been released final, but a milestone release works for Play 2.4. The version is 1.4.0-M4.

The reason we didn't release it final yet is because we have a few failing tests that we did not yet have time to investigate. Despite our failing tests, however, users seem to have no problems with it. So 1.4.0-M4 should work fine. We have been overwhelmed this past year with the 3.0 release, which was mainly adding Scala.js support to ScalaTest. That's finally about done and we're looking forward to catching up on items like getting a final release out of 1.4.0.

**Comment by nemoo** [comment]
Thanks for the info! Works for me. Looking forward to the release.

**Comment by wsargent** [comment]
Scalatest-Play is upgraded as of 2.5.x, so closing.  @nemoo let me know if this is still an issue in 2.5.x.
