### ISSUE TITLE
[2.4.0] Unable to send DELETE request with json body

### ISSUE THREAD

**Issue by ulejon** [playframework/playframework#4606]
I'm trying to do a DELETE request with a json body. 
However, when trying to get the json body in the backend I get an empty result.

Here is my controller function:

```
def delete = Action { implicit request =>
    request.body.asJson.fold {
        Logger.warn("No json body found!")
        NotFound("No json body found!")
    } { json =>
        val someProp = (json \ "someprop").as[String]
        Ok(s"Prop is: $someProp")
    }
  }
```

When I try do call this api I always get `"No json body found!"` as response.

Here is my curl command: `curl -X DELETE -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{"someprop": "hello"}' http://localhost:9000`

[Here is my sample project](https://github.com/ulejon/play-deletetest.git)

**Comment by gmethvin** [comment]
According to RFC7231 (https://tools.ietf.org/html/rfc7231#section-4.3.5):
> A payload within a DELETE request message has no defined semantics;
sending a payload body on a DELETE request might cause some existing
implementations to reject the request.

I'm not sure where/why it's implemented this way in Play specifically, but since there is no defined semantics for bodies in DELETE requests and the URI is supposed to completely identify the resource to be deleted, I know many servers have chosen to ignore the body (see https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request).

That said, there's no reason I can see why we shouldn't allow you to access the body, given that it's not forbidden by the RFC in any way.

**Comment by jroper** [comment]
Play's default body parser follows the HTTP spec, and ignores the message body for `GET`, `DELETE`, `HEAD` and `OPTIONS` methods.  If you want to force it to parse a body, you can do that by explicitly passing a body parser, eg:

```scala
  def delete = Action(parse.json) { implicit request =>
    val json = request.body
    val someProp = (json \ "someprop").as[String]
    Ok(s"Prop is: $someProp")
  }
```

**Comment by gmethvin** [comment]
Thanks @jroper. Was not aware the default body parser worked that way.

**Comment by mattfeury** [comment]
interesting comment here: i just ran into this and was surprised because my controller tests actually work. i assume FakeRequest maybe does things differently which is why the tests work, but thought it was weird that the tests pass but the code actually does not work to parse a payload
