### ISSUE TITLE
Wrong docs - port does not get set

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#4629]
Have a look at the docs [here](https://www.playframework.com/documentation/2.4.x/Configuration#Using-with-the-run-command): 
`devSettings := Map("play.server.http.port" -> "8080")` is wrong, it does not even compile. It should be either `PlayKeys.devSettings := Seq("play.server.http.port" -> "8080")` or `PlayKeys.devSettings += ("play.server.http.port" -> "8080")`.
But still, even after changing it to the correct syntax it does not work, the http port does not get set.
Is it even possible to set the port in dev mode with this config style?

**Comment by mkurz** [comment]
Maybe somehow related:
https://groups.google.com/forum/?fromgroups=#!topic/play-framework/wqKSbjxYTL4
?

**Comment by mkurz** [comment]
Could someone have a look - thanks?

**Comment by pcboy** [comment]
Nobody cares it seems.

**Comment by marcospereira** [comment]
Hello @mkurz and @pcboy,

First of all, we do care about this issue, but we also have a lot of other stuff to care about and we try really hard to prioritize what issues will have most significant impact on Play users. Of course, we won't be right all the time. ;-)

All that said, lets take a look at the issue here. Looks like `play.server.http.port` is being used by [`ProdServerStart`](https://github.com/marcospereira/playframework/blob/master/framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala#L93-100), but not by `DevServerStart` (or [`Reloader`](https://github.com/marcospereira/playframework/blob/master/framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala#L52-L58)). I don't have time right now to fix this, but this should at least give someone else a better path to solve this issue.

@mkurz, based on the current state of `Reloader` object, looks like `http.port` is a supported configuration. Could you please try to configure the port using `http.port` instead of `play.server.http.port` and tells us if it works?

Thanks!

**Comment by richdougherty** [comment]
> devSettings := Map("play.server.http.port" -> "8080") is wrong, it does not even compile.

Maybe we should change the definition of `devSettings` in `PlayImports.scala` from 

```scala
val devSettings = SettingKey[Seq[(String, String)]]("playDevSettings")
```

to

```scala
val devSettings = SettingKey[Iterable[(String, String)]]("playDevSettings")
```

so that `Map` is supported.

**Comment by jroper** [comment]
The problem with `Iterable` is that there is no `sbt.Append.Value` type class defined for `Iterable`, so you wouldn't be able to use the sbt `+=` and friends with `devSettings`.

**Comment by mkurz** [comment]
@marcospereira  `PlayKeys.devSettings += ("http.port" -> "8080")` does not work either, still listening on 9000... However `activator run -Dhttp.port=8080` does work fine.

**Comment by mkurz** [comment]
Maybe also related:
https://groups.google.com/d/topic/play-framework/EHZA1kpsb_k/discussion

**Comment by wsargent** [comment]
Added a PR for master.
