### ISSUE TITLE
[2.4.0] behaviour of the Json.deepMerge method is different than in playframework 2.3.x

### ISSUE THREAD

**Issue by limuhob** [playframework/playframework#4633]
Hi, 

playframework 2.4.0 has different behaviour of Json.deepMerge method. This code:

    val js1 = Json.parse( """{"property1":"x", "data":["a"]}""")
    val js2 = Json.parse( """{"property1":"x", "data":["a"]}""")
    println(js1.as[JsObject].deepMerge(js2.as[JsObject]))

prints in play 2.4.0: 

    {"property1":"x","data":["a", "a"]} 

However in play 2.3.x it prints: 
    
    {"property1":"x","data":["a"]}

Because that some JSON transformation has different result. See my another issue:

https://github.com/playframework/playframework/issues/4622

**Comment by julienrf** [comment]
Hi,

Thanks for the investigation. To me it seems that the behavior of the 2.4 is better. What should be the result of the following?

~~~ scala
Json.obj(
  "foo" -> Json.arr("a")
).deepMerge(Json.obj(
  "foo" -> Json.arr("b")
))
~~~

**Comment by julienrf** [comment]
Well, according to the Scaladoc, “values of the second object override values of the first object”. So, the answer to my question is `Json.obj("foo" -> Json.arr("b"))` and, indeed, there seems to be a regression in 2.4. What do others think?

**Comment by limuhob** [comment]
Yes, you are right with answer. I think the new behaviour is problematic. Because due to the new behaviour e.g. 

    __.json.update(__.read[JsObject].map(js => js)).reads(Json.obj("foo" -> Json.arr("a")))

doubles items in result. But the operation with json is identity: js => js

**Comment by gmethvin** [comment]
@julienrf @limuhob Making `deepMerge` "work" for arrays was raised as as issue a while back (#3717) and it seemed like @mandubian also agreed it was a good idea. But I can see how changing the behavior might be problematic.

**Comment by gmethvin** [comment]
Since this changes the behavior of the existing reads we created (which use `deepMerge` internally) I think we should consider this a regression and switch it back to the old behavior.

When dealing with arrays there are a number of possible implementations of merging (for example merging each object in one array with the object in the same position in the other array), and which one makes sense depends on the situation. In terms of the API, I think it makes sense for `JsObject#merge` to only care about `JsObject`s. If we're going to deal with merging other types, there should be a different API on `JsValue` or elsewhere.

**Comment by unkarjedy** [comment]
@gmethvin Maybe we could create a separate method "deepMergeWithArrays"? Merge feature with arrays is quite helpful, but currently, I have to use my own Utils method that is just a copy of old Play deepMerge version.
I can create a pull request if it is only a question of time.
