### ISSUE TITLE
[2.4.0] generated routes class only contains controllers of subroute file

### ISSUE THREAD

**Issue by edouardKaiser** [playframework/playframework#4638]
The routes class generated automatically at compilation doesn't contain all the controllers if there is a sub route file in the conf folder.

Situation:
* 2 controllers (controllers.Application and controllers.RpcController)
```java
public class Application extends Controller {
    public Result index() {
        return ok(index.render("Your new application is ready."));
    }
}
```
```java
public class RpcController extends Controller {
    public Result rpcCall() {
        return ok();
    }
}
```
* 2 routes file (conf/routes and conf/rpc.routes)

> ### routes
> GET     /                          controllers.Application.index() 
> GET     /assets/*file         controllers.Assets.versioned(path="/public", file: Asset) 
> ->      /rpc                        rpc.Routes 

and
> ### rpc.routes
> GET     /call             controllers.RpcController.rpcCall()

The root routes file includes rpc.Routes. When we compile the application, the only controller generated in routes.class is RpcController, the Application controller is not present in routes.class:

```java
package controllers;

import rpc.RoutesPrefix;

public class routes {
  public static final controllers.ReverseRpcController RpcController = new controllers.ReverseRpcController(RoutesPrefix.byNamePrefix());

  public static class javascript {
    public static final controllers.javascript.ReverseRpcController RpcController = new controllers.javascript.ReverseRpcController(RoutesPrefix.byNamePrefix());
  }
}
```

**Comment by edouardKaiser** [comment]
For information, it's a regression, because it was working in Play 2.3.8

**Comment by jroper** [comment]
No this wasn't working in Play 2.3.8, having two routes files pointing to controllers in the same package has never been supported in Play. Each routes file is compiled, and outputs a Java reverse router for each package found in the routes file.  If two routes files refer to the same package, one of them will overwrite the other. You may have thought it was working in Play 2.3.8 because by chance the one that was being overwritten didn't contain any controllers that you were using the reverse routes from, and, given that some changes have been made to routes files location in Play 2.4, by chance, the order in which they have compiled has changed, which means now the one that you use the reverse routes from is being overwritten, so it looks like it's broken.

The solution is to move your rpc controller into its own package.

**Comment by edouardKaiser** [comment]
Hi James. thank you very much for the explanation. All makes sense, we were lucky it was working before.

**Comment by zoltanmaric** [comment]
@jroper thanks for pointing this out. We had a really hard time finding this problem. Where in the documentation can we see that "having two routes files pointing to controllers in the same package has never been supported in Play"?
