### ISSUE TITLE
Cookies.decode with one invalid cookie shouldnt make all cookies invalid.

### ISSUE THREAD

**Issue by stephennancekivell** [playframework/playframework#4661]
Hi,

We had an issue where one injected tool on our website broke our login which is based on the PLAY_SESSION cookie. It did this by creating an invalid cookie. This can be seen in the following test.

```
Cookies.decode("invalid cookie name=1;PLAY_SESSION=ImTotallyLoggedIn").to[Set] === Set(
        Cookie(name="PLAY_SESSION",value="ImTotallyLoggedIn", httpOnly = false))
```

The test doesn't pass, it comes back empty.

The code ends up doing a netty CookieDecoder.decode. Maybe the fix would be in there, I'm not sure. I see CookieDecoder has a strict mode, but I couldnt find a way to turn that on, maybe that helps.

Does anyone have any ideas?
Thanks

**Comment by jroper** [comment]
What version of Play?  The netty cookie decoder was fixed to be stricter because its laxness caused a [security vulnerability](https://playframework.com/security/vulnerability/CVE-2015-2156-HttpOnlyBypass) - the problem is precisely around attackers utilising malformed cookies to dupe the server into revealing values of other cookies such as the session cookie.

In Play 2.4, you can set `play.http.cookies.strict=false` in `application.conf` - that is, if you want to live on the wild side where you may end up being vulnerable to similar vulnerabilities when they are found in future.

**Comment by stephennancekivell** [comment]
Thanks James.
Were on 2.3.9.

I dont understand how it relates to httpOnly though. Why would malformed cookies expose correct ones.

What I want is if there is a malformed cookie, the rest of the cookies should be parsed correctly. It even looks like that happens in `io.netty.handler.codec.http.cookie.ServerCookieDecoder` through [CookieDecoder](https://github.com/netty/netty/blob/master/codec-http/src/main/java/io/netty/handler/codec/http/cookie/CookieDecoder.java). See `Skipping cookie because name` `return null;`

I think im looking at the wrong version of netty though. Play is importing from `org.jboss.netty.handler.codec.http`

**Comment by jroper** [comment]
That's Netty 4, Play is on Netty 3.9.

If an attacker has exploited an XSS vulnerability, httpOnly is meant to mitigate this by not allowing cookie values to be read by the attacker (the mitigation is actually incredibly weak, but that's another story).  If the attacker has exploited an XSS vulnerability, then it also means they can set arbitrary cookie values.  So, lets say they set `csrfToken=some malformed garbage`.  Play's CSRF token value gets reflected back into pages.  So if the cookie they set tricks the cookie parser into thinking the session cookie is part of the value of the `csrfToken` cookie, then the attacker can bypass the http only flag on the session cookie.  This is why the parsing was changed to be strict, because the lax parser had completely undefined behaviour that meant in some cases, malformed values would cause the value of the next cookie to be considered part of the current cookie.

**Comment by stephennancekivell** [comment]
Ok, thanks James.

If I really want Ill turn strict to false.
