### ISSUE TITLE
Customization for Json macros

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#4684]
As more people start using the json macros, a lot of people seem to want to customize features slightly. We should come up with a general strategy for doing this. Ideally it should be possible to use several of these customizations at once.

Here are a few features we might want to customize
- Property naming strategy (see #2333)
- Using default values in `Reads` implementation (see #4653)
- Serializing properties for getters (see #3306)
- Renaming/ignoring specific properties

When it comes to the behavior for things like property naming and default values, it should also be easy to use the same conventions across your application.

**Comment by aparo** [comment]
Hi, because I need some of these functionalities in both scala and scalaJS. 
I've created a project to manage some of them. [Play Json Extra](https://github.com/aparo/play-json-extra).

This is very opnionated library. I reused some code of other projects and migrate them to play json 2.3. It only works for scala 2.11, but some of this code can be a good starting pointing for some implementations.

Main Features are:

* Play JSON for ScalaJS 
* **JsonFormat** macro annotation for lazy people
* Default field values populated in missing JSON field
* Field rewrite for Play JSON ("key") 
* +22 field case class formatter and more [Play Json Extension](http://play-json-extra.megl.io/playjsonext.html)
* **Joda Datetime** for Scala and ScalaJS
* [Strong Typed Enum](http://play-json-extra.megl.io/macrame.html) (String and Int) for Scala and ScalaJS
* [Variant Types](http://play-json-extra.megl.io/variants.html)

Full Documentation [here](http://play-json-extra.megl.io).

**Comment by schmitch** [comment]
@gmethvin any thoughts / ideas about "Renaming/ignoring specific properties"?

**Comment by gmethvin** [comment]
@schmitch My thought would be to add an annotation, similar to what Jackson has, e.g. `@jsonProperty( "foo")`

I'm also thinking maybe we should have an extra implicit parameter to the `Json.format` macro. Perhaps we can call it `JsonConfiguration`. We could have a default one you can import, or you can create and import/inject your own version.

Currently, I'm not sure if the core Play team will be able to implement all this for 2.6, so it'd be great if someone from the community wants to take this on.

**Comment by schmitch** [comment]
Actually I try to get some room, but I doubt I can't implement everything on my own.
But I guess it would be great to enhance the Json capabilities.

**Comment by gmethvin** [comment]
Moved to layframework/play-json#7
