### ISSUE TITLE
Replace `play.libs.F.Promise` with Java 8 equivalent

### ISSUE THREAD

**Issue by dotta** [playframework/playframework#4691]
Replace `play.libs.F.Promise` with `java.util.concurrent.CompletionStage`

**Comment by matiwinnetou** [comment]
I know this is planned and somewhat unavoidable but it will have massive impact at least on applications I am overlooking.

**Comment by richdougherty** [comment]
Maybe we can keep F.Promise compatibility for for a version our two.

**Comment by marcospereira** [comment]
@richdougherty That is a good idea. We can just deprecated it for the next major version, instead of remove it.

@dotta why not a [`java.util.concurrent.CompletableFuture`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) instead of `java.util.concurrent.CompletionStage`?

**Comment by gmethvin** [comment]
@marcospereira `CompletableFuture` is a concrete implementation and `CompletionStage` is the interface it implements.

Maybe it'd be best to start by having `Promise` implement `CompletionStage`, which would allow it to interoperate pretty well with `CompletableFuture`.

**Comment by jroper** [comment]
I think making `Promise` implement `CompletionStage` is a good idea.

@marcospereira It's actually, at least in part, my fault that `CompletionStage` exists.  Though I wash my hands clean of the choice of name for it. I raised some concerns on the concurrency interest mailing list that being a concrete class, `CompletableFuture` was inappropriate for use by libraries, since it would not interoperate well with other promise implementations.  A very late change was made to extract the `CompletionStage` interface out of it - by the time that change was made, everyone was writing blog posts on the web about `CompletableFuture`, and consequently, most people have no idea that `CompletionStage` even exists.

**Comment by marcospereira** [comment]
@jroper I knew about `CompletionStage`, but since `F.Promise` is a concrete class, it sounds reasonable to me that it should be replaced by another concrete class. But since programming to interfaces is a good practice and users will have a concrete implementation at hand (`CompletableFuture`), expose `CompletionStage` looks better.

@gmethvin very nice idea to start by having `F.Promise` implement `CompletionStage`. :+1:

**Comment by dotta** [comment]
I'm not against making `F.Promise` inherit from `CompletionStage`. However, if that turns out to be tricky or somewhat suboptimal, then I believe we should not be afraid of replacing `F.Promise` with `CompletionStage`.

Yes, it's a big jump, but after all Play 2.5 release is about making that jump, i.e., fully embrace java8 types and reactive streams. If we can lower the pain to upgrade, let's do it. But supporting three implementations of Futures (Java, Scala, and Play one) may be tricky and it may cost us some extra time to fully cover all use cases within Play. If this turns out to be a valid concern, then I think we should just drop `F.Promise`.

**Comment by matiwinnetou** [comment]
Whenever there is a serious change and lots of code needs to be changed, most people in enterprise communities will suffer. Migrations are rather painful and a lot of people want to focus on solving business problems, not technical migrations.

**Comment by richdougherty** [comment]
I think we should aim for Play 2.4 projects to compile when they're upgraded to Play 2.5. We can break compatibility in a few places if we really have to, but we should try hard to keep compatibility. We don't want it to be too much work for users to upgrade to Play 2.5, otherwise they won't upgrade.

`F.Promise` is so widely used that we should try extra hard to make sure code using `F.Promise` still works. If we can get `F.Promise` to implement `CompletionStage` then that would be great. If we can't get it to implement `CompletionStage` then we should try to find another way to make sure existing code still compiles. E.g. in Play 2.5 we could make all our APIs support both `F.Promise` and `CompletionStage`, to give people a chance to transition their code.

**Comment by jroper** [comment]
I'm working on this at the moment.  Here's the approach I'm taking:

* `Promise` extends `CompletionStage`, and wraps a `CompletionStage`.
* All existing methods on `Promise` are deprecated, with pointers to the `CompletionStage` equivalent.  Methods that take a `Promise`, or a function that returns a `Promise`, have been modified so that they take `CompletionStage`, making all these methods compatible with any API that uses `CompletionStage`.
* All `CompletionStage` methods have been overridden to return `Promise`.  This makes for a smooth migration path, you can change a `map` to `thenApply`, but still call the result a `Promise`.
* I have not deprecated `Promise` - the reason behind this is if you deprecate a class, when someone comes to migrate, they'll see the class is deprecated, and change it `CompletionStage`, but then they'll just get compile errors on `map`/`flatMap` etc.  By not deprecating `Promise`, it encourages the smoother migration path of first changing the deprecated `map`/`flatMap` methods, which have documentation on what the `CompletionStage` alternative is, and then later you can switch from `Promise` to `CompletionStage`.
* For the rest of Play, my approach will be, any method that takes a `Promise` will be changed to take `CompletionStage`, but any method that returns a `Promise` will still return `Promise`.

**Comment by jroper** [comment]
Also, there are three groups of methods on `Promise` that do not have a straight forward equivalent in `CompletableFuture`, they are:

* `sequence`
* `delayed`
* `timeout`

I'm thinking of introducing a new class, `Futures`, that provides these static methods.

**Comment by dotta** [comment]
Hey James, I recently found out that converting a Scala Future into a Java CompletionStage is tricky. The `scala-java8-compat` library we are using does indeed allow to make the conversion with `FutureConverters.toJava(<scala-future>)`, however the returned `CompletionStage` instance cannot be converted into a `CompletableFuture` (in fact, calling `toCompletableFuture` on the returned `CompletionStage` instance will throw an exception. See the scaladoc here https://github.com/scala/scala-java8-compat/blob/master/src/main/scala/scala/compat/java8/FutureConverters.scala#L42-L55).

I'm pointing this out because we have been using the `FutureConverters` in a number of places, but we haven't really documented that the returned `CompletionStage` cannot be converted into a `CompletableFuture`.

Just wanted to put this on your radar since you are working on something somewhat related. But it may be better to open a ticket, so that we don't forget to at least update the documentation. WDYT?

**Comment by gmethvin** [comment]
Unfortunately a lot of the useful methods in the Java APIs (e.g. `CompletableFuture.allOf`) require conversion to `CompletableFuture`, so I'm sure this will be a problem for people. 

If you read the documentation at https://github.com/scala/scala-java8-compat/blob/master/src/main/scala/scala/compat/java8/FutureConverters.scala, the bridge is read-only because there is a race condition if both the `CompletableFuture` and `Promise` are completed at the same time.

I think it'd be more useful to create a special `CompletableFuture` that can only be completed through the Scala promise. We could throw an exception otherwise on `complete()`. I'm not sure if any of the standard Java APIs expect to be able to call that method, though.

**Comment by jroper** [comment]
@dotta Way ahead of you, the issue is already resolved and the `CompletionStage` returned by `FutureConverters` can, as of version 0.7.0, be converted to `CompletableFuture` :) https://github.com/scala/scala-java8-compat/issues/43

**Comment by dotta** [comment]
@jroper Oh, nice!

**Comment by danielgoncalvesti** [comment]
I'm trying to replace F.Promise to CompletionStage after migrating from play 2.4 to 2.5 but I don't know how I can replace in this method:
  ```
  public static F.Promise<Result> getBasicResponsePromise(final boolean status, final String messageId, final int responseCode) {
        F.Promise<Result> promise = F.Promise.promise(
                new F.Function0<Result>() {
                    public Result apply() {
                        BasicResponse response = new BasicResponse();
                        response.status = status;
                        response.message = MessageUtil.getMessage(messageId);
                        return status(responseCode, gson.toJson(response));
                    }
                });
        return promise;
    }
```
Someone has any idea?

**Comment by marcospereira** [comment]
Hello @danielgoncalvesti,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.  

Best.
