### ISSUE TITLE
.deb ${{app_name}} in application.ini not resolved

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#4695]
Just switched my project to play 2.4 and followed the debian native deployment guide at https://www.playframework.com/documentation/2.4.x/Production#Minimal-Debian-settings
But without the PID file configuration this fails to create the pid on startup. (PID config section should be mentioned as mandatory for debian)

So then I followed the PID section at https://www.playframework.com/documentation/2.4.x/Production#Play-PID-Configuration

But the upstart script still fails with the following errors in `/var/log/upstart/my-app.log`
`FileNotFoundException: /var/run/${{app_name}}/play.pid (No such file or directory)`

there is a related (broader) ticket at the sbt-native-packager issue tracker
https://github.com/sbt/sbt-native-packager/issues/602

**Comment by francisdb** [comment]
there is another related issue on sbt-native-packager on this one: https://github.com/sbt/sbt-native-packager/issues/607

**Comment by wsargent** [comment]
Was fixed in the SBT native packer docs at https://github.com/sbt/sbt-native-packager/pull/613

New page is:

http://www.scala-sbt.org/sbt-native-packager/recipes/play.html?highlight=play

Still broken in 2.5.x:

https://www.playframework.com/documentation/2.5.x/Deploying#Play-PID-Configuration

Should have reference to:

```
  // Since play uses separate pidfile we have to provide it with a proper path
  // name of the pid file must be play.pid
  s"-Dpidfile.path=/var/run/${packageName.value}/play.pid",
```
