### ISSUE TITLE
[Play 2.4.1 Scala] Definition of Assets in SBTSubProjects.md

### ISSUE THREAD

**Issue by outsideMyBox** [playframework/playframework#4812]
SBTSubProjects.md states that Assets should be defined as

``` Scala
package controllers.admin
object Assets extends controllers.AssetsBuilder
```

it didn't compile for me. Shouldn't it be instead:

``` Scala
package controllers.admin
import play.api.http.DefaultHttpErrorHandler
object Assets extends controllers.AssetsBuilder(DefaultHttpErrorHandler)
```

**Comment by refond** [comment]
Online documentation at:
  https://www.playframework.com/documentation/2.4.x/SBTSubProjects

States:
```scala
package controllers.admin
import play.api.http.LazyHttpErrorHandler
object Assets extends controllers.AssetsBuilder(LazyHttpErrorHandler)
```
*Note I haven't completed building a 2.4 Play module yet.*

**Comment by akauppi** [comment]
I think the real problem here is the use of `object Assets` instead of `class Assets`. The Play 2.4 documentation [says](https://www.playframework.com/documentation/2.4.0/ScalaRouting#Dependency-Injection) that

> The code samples in Play’s documentation assumes that you are using the injected routes generator.  

However, this does not seem to be the case everywhere. One could run `git grep "object Assets"` and `git grep "object Application"` in the `documentation` folder to see some places worth checking.

Disclaimer: I'm just a Play novice, so I don't feel comfortable suggesting a PR at this stage. Just pointing out what I think is an inconsistency in the `2.4.x` and `master` branches. Hope someone picks this up and corrects the situation. Thanks!

**Comment by cchantep** [comment]
Closing as inactive.
