### ISSUE TITLE
[Play 2.4 Scala] Configuration load

### ISSUE THREAD

**Issue by Hayena** [playframework/playframework#4827]
In Play 2.3 we used the `path` parameter in the `FakeApplication` to set the root path where the configuration would be loaded from. In Play 2.4 the configuration load function goes from a `Environment` to a `Configuration` but it completely ignores the path parameter thus it will not load the configuration we specified.

**Comment by EECOLOR** [comment]
We have this problem in a library where we instantiate the application like this:

`FakeApplication(new File("test"))`

For more context: https://github.com/Rhinofly/play-s3/blob/play_2.4.x/src/test/scala/fly/play/s3/S3SpecSetup.scala#L20

**Comment by wsargent** [comment]
Hi @Hayena can you provide a test case for verification?

**Comment by EECOLOR** [comment]
@wsargent 

1. Create a directory that contains a `conf` directory with an `application.conf`.
2. Start a `FakeApplication(new File(directory))`
3. Try to load any configuration from `application.conf`

**Comment by schmitch** [comment]
Inside Tests? if not or even in them you should replace FakeApplication with GuiceApplicationBuilder build() and also be Aware that in a sbt layout you Need a test /resources directory and not a conf folder.

**Comment by EECOLOR** [comment]
In `play.api.Configuration`
```
@deprecated("Use load(Environment, Map[String,AnyRef]) instead", "2.4.0")
  def load(appPath: File, mode: Mode.Mode = Mode.Dev, devSettings: Map[String, AnyRef] = Map.empty): Configuration
```

As you can see in the previous version of play you were able to supply the `appPath`. This is still evident in the `Environment` class if you read the [documentation](https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.Environment)

The behavior has changed from version 2.3 where this would also determine where play would look for the `conf` directory. Since this issue is more than 6 months old I don't think there is any benefit in trying to recover the old behavior. I would however recommend you update the documentation to clearly state that the `rootPath` only impacts the `getExistingFile` and `getFile` methods.

**Comment by wsargent** [comment]
Hi @EECOLOR -- there isn't an appPath in https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.Environment documentation and it doesn't exist in Play 2.5.x at all.  And since it's a difference between 2.3.x and 2.4.x, I'm not sure what the documentation should look like -- it's been a while since I've looked at those two versions.  If you can write some documentation detailing the change that would be helpful.

**Comment by EECOLOR** [comment]
@wsargent In configuration it was called `appPath`, in `Environment` it's called `rootPath`.

**Comment by wsargent** [comment]
So you want there to be documentation saying "rootPath only impacts the getExistingFile and getFile methods" -- is there anything else?

**Comment by EECOLOR** [comment]
@wsargent What do you mean with 'is there anything else?'
