### ISSUE TITLE
scriptClasspath in sbt breaks play 2.4 classpath

### ISSUE THREAD

**Issue by hewie** [playframework/playframework#4879]
Hi,

if you add `scriptClasspath := Seq("*")` to the build.sbt in play 2.4 the conf folder won't be in the classpath in production mode.

Usually the classpath contains to following path:
app/target/universal/stage/lib/../conf

However when starting the application with `sbt start/stage`, you will get an error that the application.conf can't be found because it's not in the classpath. `sbt run` works like a charm.
I've tested it with https://www.typesafe.com/activator/template/play-scala-intro
It worked with play 2.3.

**Comment by jroper** [comment]
This is because you're overriding the entry that adds the conf folder to the classpath, so of course it's not going to work.  You have two options:

1. Set `PlayKeys.externalizeResources := false` in `build.sbt` so that the resources end up in the jar file (then they won't be put in the `conf` directory either).
2. Set `scriptClasspath := Seq("../conf/", "*")` in `build.sbt`
