### ISSUE TITLE
JPAApi lifecycle management of EntityManager

### ISSUE THREAD

**Issue by johnlcox** [playframework/playframework#4890]
I've been writing some JPA code in Play Java recently, and the way the `JPAApi` class manages the lifecycle of `EntityManager`seems a little odd compared to what I've seen in the past (for instance with servlet containers) and what the Hibernate docs seem to suggest [1].

Generally the advice I have seen is to create an `EntityManager`per request, but from looking at the `DefaultJPAApi` implementation it looks like a new `EntityManager` is created each time `JPAApi.em(String)` is called.

This seems even odder when I consider how this would work along with using the `Transactional` annotation which executes the `JPAApi.withTransaction` methods. The transaction will start a transaction on it's entity manager, but there isn't an obvious way to get that same `EntityManager` instance injected in the code that is actually working with the entities.

Am I just totally misunderstanding how this all works? Is there good documentation or examples somewhere that I am missing?

[1] http://docs.jboss.org/hibernate/orm/4.0/hem/en-US/html/transactions.html#transactions-basics-uow

**Comment by marcospereira** [comment]
Related to #4916 and #4862.

Trying to breakdown this problem:

1. The default JPAApi implementation [creates an `EntityManager` every time the `em(String)` method is called](https://github.com/marcospereira/playframework/blob/master/framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java#L67-L73), no matter if we already have a 
2. So, when users need to access an `EntityManager`, even using [`withTransaction`](https://github.com/marcospereira/playframework/blob/master/framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAApi.java#L45-L59) with a block, `em(String)` creates a new `EntityManager` and users are responsible to properly close it. 
3. The [`JPA`] class has a slightly different behavior:
    1. `JPA.em(String)` works just like `JPAApi.em(String)`
    2. [`JPA.em()`](https://github.com/marcospereira/playframework/blob/master/framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java#L51-L81) returns the `EntityManager` found in `Http.Context` (when using `@play.db.jpa.Transactional` actions) or it fallbacks to a `ThreadLocal`.

So, here is what users can do:
```java
// Consider that jpaApi was injected
jpaApi.withTransaction(
    () -> JPA.em()
             .createQuery("from MyEntity where something = ?1")
             .setParameter(1, parameterValue)
             .getResultList()
);
```
In other words, they need to use both the injected instance of `JPAApi` and `JPA` static methods - which results in a confusing API.

-------------------

### What can we do?

1. Both `JPAApi.em(String)` and `JPA.em(String)` should always return a new `EntityManager` for the given name. This is already working this way.
2. Both `JPA` and `JPAApi` needs to have an `em()` method which returns the `EntityManager` from `Http.Context` or `ThreadLocal` if available.
3. We can have a `JPAApi.withTransaction(Function<EntityManager, T>)` so that users can write code like this:

```java
// Consider that jpaApi was injected
this.withTransaction(em -> {
    return em.createQuery("from MyEntity where something = ?1")
             .setParameter(1, parameterValue)
             .getResultList();
});
```

@jroper @dotta @richdougherty @johdah and @johnlcox, what do you think?

**Comment by johnlcox** [comment]
Coming from guice-persist/onami-persist I was thinking of using an `@Transactional` annotation to use AOP for defining a transactional scope. In order to do this the `JPAApi` would need to store the `EntityManager` in a `ThreadLocal` variable during a transaction and return that instance of the `EntityManager` instead of a new instance whenever `JPAApi.em(string)` is called. I wrote up a really basic implementation for this based on the concept of a `UnitOfWork` from guice-persist/onami-persist.

The way this works is that you can only ever get an instance of an `EntityManager` while a `UnitOfWork` is running. `JPAApi.withTransaction` would start and end a unit of work and there could also be a `@Transactional` annotation that automatically executes annotated methods with a transaction.

The disadvantage to this approach is that you'll get an exception if you simply ask for an `EntityManager` without first starting a unit of work. I haven't fully thought through it, but it may be possible to have some sort of middle ground between these two approaches.

```Java
import play.db.DBApi;
import play.db.jpa.DefaultJPAApi;
import play.db.jpa.JPAApi;
import play.db.jpa.JPAConfig;
import play.inject.ApplicationLifecycle;
import play.libs.F;

import java.util.HashMap;
import java.util.Map;

import javax.inject.Inject;
import javax.inject.Provider;
import javax.inject.Singleton;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

@Singleton
public class ThreadLocalJpaApi extends DefaultJPAApi implements UnitOfWork {
  private final JPAConfig jpaConfig;
  private final Map<String, EntityManagerFactory> emfs = new HashMap<>();
  private final ThreadLocal<Map<String, EntityManager>> threadLocalEntityManagersByPU =
      new ThreadLocal<>();

  public ThreadLocalJpaApi(JPAConfig jpaConfig) {
    super(jpaConfig);

    this.jpaConfig = jpaConfig;
  }

  @Singleton
  public static class JPAApiProvider implements Provider<JPAApi> {
    private final JPAApi jpaApi;

    @Inject
    public JPAApiProvider(JPAConfig jpaConfig, DBApi dbApi, ApplicationLifecycle lifecycle) {
      // dependency on db api ensures that the databases are initialised
      jpaApi = new ThreadLocalJpaApi(jpaConfig);
      lifecycle.addStopHook(
          () -> {
            jpaApi.shutdown();
            return F.Promise.pure(null);
          });
      jpaApi.start();
    }

    @Override
    public JPAApi get() {
      return jpaApi;
    }
  }

  /**
   * Initialise JPA entity manager factories.
   */
  public JPAApi start() {
    for (JPAConfig.PersistenceUnit persistenceUnit : jpaConfig.persistenceUnits()) {
      emfs.put(
          persistenceUnit.name, Persistence
              .createEntityManagerFactory(persistenceUnit.unitName));
    }
    return this;
  }

  @Override
  public EntityManager em(String name) {
    final Map<String, EntityManager> entityManagersByPU = threadLocalEntityManagersByPU.get();
    if (entityManagersByPU == null) {
      throw new IllegalStateException(
          "JPA unit of work is not running for persistence unit " + name);
    }

    EntityManager entityManager = entityManagersByPU.get(name);
    if (entityManager == null) {
      throw new IllegalStateException(
          "JPA unit of work is not running for persistence unit " + name);
    }

    return entityManager;
  }

  @Override
  public <T> T withTransaction(String name, boolean readOnly, F.Function0<T> block)
      throws Throwable {
    boolean previouslyActive = isActive(name);
    if (!previouslyActive) {
      begin(name);
    }

    Throwable originalException = null;
    try {
      return super.withTransaction(name, readOnly, block);
    } catch (Throwable t) {
      originalException = t;
      throw t;
    } finally {
      if (!previouslyActive) {
        try {
          end(name);
        } catch (Throwable t) {
          if (originalException != null) {
            throw originalException;
          }

          throw t;
        }
      }
    }
  }
  
  private EntityManager createEntityManager(String name) {
    EntityManagerFactory emf = emfs.get(name);
    if (emf == null) {
      return null;
    }
    return emf.createEntityManager();
  }

  @Override
  public boolean isActive(String name) {
    return threadLocalEntityManagersByPU.get() != null;
  }

  @Override
  public void begin(String name) {
    if (isActive(name)) {
      throw new IllegalStateException(
          "JPA unit of work was already started for persistence unit " + name);
    }

    Map<String, EntityManager> entityManagersByPu = threadLocalEntityManagersByPU.get();
    if (entityManagersByPu == null) {
      entityManagersByPu = new HashMap<>();
    }

    EntityManager entityManager = createEntityManager(name);
    entityManagersByPu.put(name, entityManager);
    threadLocalEntityManagersByPU.set(entityManagersByPu);
  }

  @Override
  public void end(String name) {
    Map<String, EntityManager> entityManagersByPu = threadLocalEntityManagersByPU.get();
    if (entityManagersByPu != null) {
      try {
        EntityManager entityManager = entityManagersByPu.remove(name);
        if (entityManager != null && entityManager.isOpen()) {
          entityManager.close();
        }
      } finally {
        if (entityManagersByPu.isEmpty()) {
          threadLocalEntityManagersByPU.remove();
        } else {
          threadLocalEntityManagersByPU.set(entityManagersByPu);
        }
      }
    }
  }

  public EntityManagerFactory getEmf(String name) {
    return emfs.get(name);
  }
}
```

**Comment by johdah** [comment]
@marcospereira I like your proposals, that would make the API more logical. I like the idea of it working like your third proposal. But I think the most important thing is that it is being documented well so it's clear how the API is supposed to work.

**Comment by jroper** [comment]
@marcospereira Your proposal makes sense to me.

Another option (which could be done in addition to your proposal) would be to create a new `<T> T withTransaction(Function<EntityManager, T>)` method. This negates the need to rely on thread locals at all, which is the direction we want to take Play in, since the entity manager would be explicitly passed around, while Play handles the cleanup.

**Comment by marcospereira** [comment]
@jroper, 

> Another option (which could be done in addition to your proposal) would be to create a new `<T> T withTransaction(Function<EntityManager, T>)` method.

This is part of what I've proposed. :-)

I'm also thought that having this would avoid ThreadLocals at all, as you said, but if we keep `<T> T withTransaction(Supplier<T>)` and `<T> T withTransaction(Runnable)` then we should probably offer users a way to access the same `EntityManager` when using these methods.

**Comment by marcospereira** [comment]
Guys,

I was thinking about to completely remove `<T> T withTransaction(Supplier<T> block)` and `void withTransaction(final Runnable block)` methods from both `JPAApi` and `JPA`. Since an `EntityManager` will be always necessary at some point, having just `<T> T withTransaction(Function<EntityManager, T> block)` will made this more explicit and intuitive. My only concert here is how much we are loosing in terms of backward compatibility.

What do you think?

**Comment by jroper** [comment]
I think removing them is more of a Play 3 thing.

**Comment by marcospereira** [comment]
See PR #5699.
