### ISSUE TITLE
[2.4.2] Numbers in JSON deserialized as BigInteger

### ISSUE THREAD

**Issue by echipachenko** [playframework/playframework#4897]
I've found that numbers in the request body Json are deserialized as BigIntegers by default. I think this is a bug, as I think the default behaviour should be to deserialize integers into Integer by default. The following code is a snippet which illustrates this bug.

```java
public Result testBigInteger(){
    JsonNode requestBody = request().body().asJson();
    Object x = requestBody.get("number");

    if(x instanceof BigIntegerNode){
        return ok("Yes");
    }
    else{
        return ok("No");
    }
}
```

**Comment by cchantep** [comment]
See #3784

**Comment by echipachenko** [comment]
Do you have any updates?

**Comment by cchantep** [comment]
This is the expected behaviour, to avoid loosing precision with numeric values, whose range is not limited/defined in JSON, contrary to the target Java/Scala datatype `long`/`int`/`double`/`float`. For now you have to use appropriate function on `BigIntegerNode` or `BigDecimalNode` if you want a primitive value. I don't think there is plan to change this behaviour. It can be discussed on the [user MailingList](https://groups.google.com/forum/#!forum/play-framework).

**Comment by echipachenko** [comment]
Are you crazy? We have a big project, working on play (from 2.2.1 to version 2.3.9) and after version 2.4.0 you make an regression issue, after merging https://github.com/playframework/playframework/pull/3784, which crash our project logic. Don't close this issue, there are too many projects which use old logic.

**Comment by cchantep** [comment]
Please be constructive and avoid unpleasant adjectives, Play contributors are volunteers, rather than "crazy".

I can agree that the behaviour of the Java API can be better documented but:

1. The Java API of Play JSON has never states that integer will be returned as `IntNode`.
2. Before the implementation change, there are numeric conversions issues in both the Scala & Java JSON lib, which were reported for projects as important as yours.
3. A code relying on the previous undocumented/fixed behaviour can be easily updated (working with `BigIntegerNode` instead of `IntNode`.

The [user MailingList](https://groups.google.com/forum/m/#!forum/play-framework) is available to discuss about an heuristic able to efficiently determine whether a `BigDecimal` should be converted to a `BigIntegerNode`, `LongNode`, `IntNode` / `BigDecimalNode`, `DoubleNode`, `FloatNode`, and whether it's convenient to then have possibly many cases to handle the `JsonNode`, depending on the precision of the numeric JSON input.

Best regards

**Comment by markpiller** [comment]
@cchantep Your comment make me believe that the Play contributors are not only volunteers but lack basic understanding and best practices about maintaining backward compatibility. When you make such a change you break the trust of other developers who chose Play to build their projects with and most importantly rely on Play. 

Seeing the attitude you demonstrate which can be summed up as "take it or leave it" or better yet "we do not give a f**k" makes me seriously doubt if Play was the right choice for us to begin with. I think the damage this change cause in the way of super bad reviews in blogs and social media will have a lasting effect on the success of Play. 

Regards,
Mark

**Comment by cchantep** [comment]
Hi @markpiller, please avoid attack against the Play contributors, you not agreeing which the change is not a reason.

Again, the change was introduced to fixe some issues.

If there is always ways to do better (as documenting the behaviour), I don't think changing an undocumented/buggy behaviour is a failure, even if you relying on this.

Please consider the projects other than yours which were requiring the previous fix.

Discussion is welcome on the [user Mailing List](https://groups.google.com/forum/#!forum/play-framework) (not on this issue tracker, as indicated in the project guidelines).

Best regards

**Comment by markpiller** [comment]
@cchantep, playing the "God's mode" by locking up comments to shut me up is just lame and does not help in resolving issues. Hope you will grow up one day to understand that..

**Comment by shkhln** [comment]
As far as I can see (I'm not related to the project team in any capacity), locking is supposed to give you a time to cool down a bit.  Now, are there any technical reasons you can't easily update your code?

**Comment by jroper** [comment]
There are 7 different sub classes of `NumericNode`.  Depending on a particular one being used is pretty bad - I mean, if the value is only 10, then why shouldn't Jackson simply use `ShortNode`?  It would be completely free to do that, it would be an optimisation because it would require less memory, and that would also break your code.  By depending on a particular type of `NumericNode` being used, you're depending on implementation details of Play and Jackson, which leaves you open to the exact type of compatibility issues that you are seeing - you shouldn't be doing that.  In fact, casting in general like that is considered bad practice when using Jackson, instead, if you want an int, you should first check if the node is an integer by calling the [`JsonNode.isInt()`](http://fasterxml.github.io/jackson-databind/javadoc/2.3.0/com/fasterxml/jackson/databind/JsonNode.html#isInt()) method, and then access the integer using [`JsonNode.asInt()`](http://fasterxml.github.io/jackson-databind/javadoc/2.3.0/com/fasterxml/jackson/databind/JsonNode.html#asInt()).

**Comment by echipachenko** [comment]
I have suggestion to Play developers team:
Could you make an API to setting custom json ObjectMapper or something like that (looks like this: Json.setObjectMapper(mapper))?
It seems that this should solve the problem.

**Comment by jroper** [comment]
@echipachenko That already exists:

https://www.playframework.com/documentation/2.4.x/api/java/play/libs/Json.html#setObjectMapper-com.fasterxml.jackson.databind.ObjectMapper-

**Comment by echipachenko** [comment]
@jroper yes, but it not use for body deserialization.

When you call request().body().asJson() ---->> play.libs.Json is newer used.
Istead, play use internal ObjectMapper. which located in class https://github.com/playframework/playframework/blob/master/framework/src/play-json/src/main/scala/play/api/libs/json/jackson/JacksonJson.scala (line 206)

**Comment by cchantep** [comment]
Right, that's something better to be discussed for me, rather than discussing about the default behaviour cannot satisfy to %100 everybody.

**Comment by echipachenko** [comment]
@cchantep Totally agree with you. I think it would be very important feature for most of playframework clients, because each client can customize serialization/deserialization to any requirements...

**Comment by marcospereira** [comment]
Looks like this is already doable if you create your own module to provide a `ObjectMapper` instead using the default one:

https://github.com/playframework/playframework/blob/master/framework/src/play-java/src/main/scala/play/core/ObjectMapperModule.scala

You can then disable the module above and enable your own. @echipachenko, what do you think?

**Comment by echipachenko** [comment]
@marcospereira seems, that the ObjectMapperModule inject ObjectMapper object to play.libs.Json class, which is not used in body().asJson() deserialization process...

play.libs.Json is never called, when we call request().body().asJson() 

But we need have an API to customize body parsing  process (deserialization) to json.
(Sorry for my English)

**Comment by cchantep** [comment]
As for as I remember, the `ObjectMapper` used by the JSON body parsers [always/only register the `PlayJsonModule`](https://github.com/playframework/playframework/blob/master/framework/src/play-json/src/main/scala/play/api/libs/json/jackson/JacksonJson.scala#L206) for serializing/deserializing the `JsValue`s.

**Comment by echipachenko** [comment]
I made some investigation of BodyParser.Json class:
```java
public static class Json implements BodyParser {
        public play.api.mvc.BodyParser<Http.RequestBody> parser(int maxLength) {
            return play.core.j.JavaParsers.json(maxLength);
        }
    }
```

In file play.core.j.JavaParsers.json  see `parse.json(Integer.MAX_VALUE)`
Method parse located in ContentTypes.scala, see:
```scala
def json(maxLength: Int): BodyParser[JsValue] = when(
      _.contentType.exists(m => m.equalsIgnoreCase("text/json") || m.equalsIgnoreCase("application/json")),
      tolerantJson(maxLength),
      createBadResult("Expecting text/json or application/json body")
    )
```
next
```scala
    def tolerantJson(maxLength: Int): BodyParser[JsValue] =
      tolerantBodyParser[JsValue]("json", maxLength, "Invalid Json") { (request, bytes) =>
        // Encoding notes: RFC 4627 requires that JSON be encoded in Unicode, and states that whether that's
        // UTF-8, UTF-16 or UTF-32 can be auto detected by reading the first two bytes. So we ignore the declared
        // charset and don't decode, we passing the byte array as is because Jackson supports auto detection.
        Json.parse(bytes)
      }
```
play.api.libs.json.Json in play 2.3.9:
```
def parse(input: Array[Byte]): JsValue = JacksonJson.parseJsValue(input)
```

Seems, that play 2.3.9 and 2.4.x json parsing logic located in JsValue class, and ObjectMapper has private access, so we can't inject custom logic...
(Maybe I'm wrong)

**Comment by cchantep** [comment]
Unless it's possible to make the `PlayJsonModule` register other ser/derser than the default one for `JsValue`, the Play MVC relying on this module it isn't possible to customize that for me.

**Comment by maxkremer** [comment]
Can anyone comment on the status of this issue? @cchantep were you able to confirm if it's possible to configure the ObjectMapper used by Play's body().asJson()?

We've also hit this bug/issue/regression.... I have to echo the frustration from @echipachenko @markpiller .... Not a single play upgrade (even minor versions) has been smooth. Almost all have had some kind regression or backward compatibility breakage (that's not covered in the migration guide).

**Comment by judge123** [comment]
We also ran into this BigInteger issue after upgrading to 2.4.6 from 2.3.8. As others have commented, this breaking change is not documented anywhere. 

I too will have to echo the frustration form @echipachenko and @markpiller and @maxkremer. 

Play changes too much, too fast. Frequent package names and class names changes are one of the example.

We chose play because it was elegant. But these upgrade nightmares make us wonder if we made the right decision.

**Comment by wsargent** [comment]
@maxkremer @judge123 It's not always obvious how users will interact with a given API, so even "under the hood" changes are viewed as breaking API sometimes.  Community involvement is key -- Play needs more people testing the milestone builds and release candidates.  Play 2.5 RC1 should be out the door today, so please try it and let us know what works for you and what doesn't.

**Comment by maxkremer** [comment]
@wsargent I don't want to get into whole semantic argument here but "under the hood" for an API means transparent to user. The moment the behaviour of that API changes its no longer under the hood.

For those reading this thread looking for a solution the fix for this is relatively simple: just register a custom BigInteger Serializer

```
public class BigIntegerSerializer extends JsonSerializer<BigInteger> {
 	
 	@Override
     public void serialize(BigInteger value, JsonGenerator jgen, SerializerProvider provider) throws IOException,
             JsonProcessingException {
     	
     	try {
     		jgen.writeNumber(value.intValueExact());
     		return;
     	} catch (ArithmeticException e) {}
     	
     	jgen.writeNumber(value.longValue());
     }
 }
```

**Comment by wsargent** [comment]
@maxkremer Please review the 2.5.0 RC1 and provide feedback -- it is the best way to address your concerns going forward.

**Comment by judge123** [comment]
@maxkremer  Thanks for the tip. However, I am not sure how to register the serializer into play Json library. All our requests are handled in one place so we fixed it by doing this (really ugly):

WebRequest request = Json.fromJson(Json.parse(body.asJson().toString()), WebRequest.class);

We can't do body.asText() as all apis are annotated with @BodyParser.Of(BodyParser.Json.class) and the client calls come in with content type application/json. 

I would like to be able to use your solution though. Apologize in advanced if I am asking the obvious. 

@wsargent thanks for your response. I understand its not an easy task. Would this behavior be changed in 2.5? I know I can just download it and test it.

**Comment by maxkremer** [comment]
@judge123 ...my bad, forgot that part of this issue is the fact that play's body parser is not configurable, ie its not the Json parser used by Json.fromJson, Json.parse... etc... So what we ended up doing is adding a static method that replaces BigInteger nodes. Here's the code:

```
public static JsonNode replaceBigInteger(JsonNode jsonNode) {
 		if (jsonNode.isObject()) {
 			ObjectNode objectNode = (ObjectNode)jsonNode;
 			Iterator<String> it = objectNode.fieldNames();
 			while (it.hasNext()) {
 				String fieldName = it.next();
 				JsonNode childNode = objectNode.get(fieldName);
 				if (childNode.isObject()) {
 					replaceBigInteger((ObjectNode)childNode);
 				} else
 				if (childNode.isBigInteger()) {
 					objectNode.replace(fieldName, smallestNumericNode((BigIntegerNode)childNode));
 				}
 			}	
 		}
 		return jsonNode;
 	}
```

**Comment by judge123** [comment]
@maxkremer Ahhh... I see. Json.toJson(), Json.fromJson() and Json.parse() have no BigInteger issue. So our solution was to convert the JsonNode returned from body.asJson() to string and parse the string back to JsonNode using Json.fromJson().

We generalizes our requests' json and treat them as generic/dynamic objects (basically extended HashMap). So the same request can be de-serialized by a single action (the action annotation) and then passed to api's controller methods. 

For example, a search api call can be done on different objects in the system. But we use the same request object with different criteria for each object. So when the request is passed to different controller methods for performing search, we expect certain attributes in criteria to be Integer, String, Double, Boolean etc. 

So if something that used to be Integer suddenly becomes BigInteger our type casting fails.

That's where it breaks for us.
