### ISSUE TITLE
[2.4.2] Two slashes in simple URL cause 400 response instead of a 404 one

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#4933]
With a simple play-java project access http://127.0.0.1:9000// (two slashed at the end).
You will get
> Bad request
> For request 'GET //' [**Expected authority at index 2: //**]

Actually it should be a "404 Not Found" response.

Also interesting when adding
```
GET     //                          controllers.Application.twoSlashes()
GET     ///                         controllers.Application.threeSlashes()
```
to the routes file and accessing http://127.0.0.1:9000/// (three slashes) you hit the `oneSlash()` action.
When accessing http://127.0.0.1:9000//// (four slashes) you hit the `twoSlash()` action.

**Comment by jroper** [comment]
Play is actually exhibiting the correct behaviour. According to the URL spec, `//` is not a valid URL (if a URL starts with two slashes, it's a scheme relative URL, and the authority section, ie hostname, should come next), so Play is returning 400 bad request since it's a protocol violation.

**Comment by mkurz** [comment]
Hmm...
This isn't really ideal I think. Also the https://playframework.com// suffers from this behaviour.
In case someone shares a link to the play website and accidently adds a second slash at the end you end up on the 400 page... What bothers me is that I can not intercept the request and redirect the user...

Do you also think it is the correct behaviour to hit the action defined with two slashed in the `routes` files when accessing http://127.0.0.1:9000//// (four slashes at the end).

Isn't there something wrong with a regex instead?

**Comment by mkurz** [comment]
One more observation:
Adding
```
GET     /subpage                         controllers.Application.anypage()
```
and accessing http://127.0.0.1:9000/subpage// (with two slashes at the end) does not give us a 400 but the (in my opinion correct) "404 Not Found" response.

So the behavour also isn't consistent as well as the only case where we get the 400 is on the index route (/) but not on subroutes.

**Comment by jroper** [comment]
Well, `/subpage//` is a valid URL, where `//` is not.  Meanwhile, `//somepage/foo` actually is a URL where `subpage` is the hostname, and `foo` is the path, eg if the request was an http request, the absolute form of that URL is `http://somepage/foo`.

The four slashes hitting the two slashes path is technically not spec compliant, though it makes sense.  Firstly, remember that the browser only sends the path, it doesn't send the host.  The browser is sending `////`, not `http://127.0.0.1:9000////`.  A URL starting with two slashes is scheme relative URL, so adding the scheme, you get an absolute URL of `http:////`.  So, this is a URL with a zero length authority - that's probably not 100% spec compliant, but if you're going to treat it as anything, you end up getting a path of `//`, which is what Play is doing.

The problem here is a combination of the URL spec making it impossible to distinguish between scheme relative URLs, and authority relative URLs that start with two slashes - the URL spec accounts for this by making it illegal to have a path that starts with two slashes.  However, the browsers don't implement that part of the spec, they *should* be sanitising the URLs before sending them, instead, they are sending something that doesn't correlate to what the user wants.

**Comment by cchantep** [comment]
I guess this can be closed for now (and eventually discussed on the MailingList for more details). Besr regards.
