### ISSUE TITLE
Wrong locale are passed into a Formatter's parse and print methods

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#4945]
The `Locale` argument of a `Formatter`'s `parse` or `print` method **always** contains the system locale (see the [`DateFormatter`'s `parse` method](https://github.com/playframework/playframework/blob/2.4.2/framework/src/play-java/src/main/java/play/data/format/Formats.java#L44) for example). I would have expected it to contain the locale which gets set by Play for each request (the one('s) set via `play.i18n.langs`).

The problem is in `Formatters.java` [on line 280](https://github.com/playframework/playframework/blob/2.4.2/framework/src/play-java/src/main/java/play/data/format/Formatters.java#L280) - it uses `LocaleContextHolder.getLocale()` which always returns the system's locale because the locale does not get set anywhere. Also, `LocaleContextHolder` is using a `ThreadLocal` to store the locales which isn't a good thing I guess (see [here](https://github.com/spring-projects/spring-framework/blob/v4.1.6.RELEASE/spring-context/src/main/java/org/springframework/context/i18n/LocaleContextHolder.java#L46-L47)).

I bumped into this when writing my own Formatter for binding BigDecimal values which I use so people can enter money amounts. I would like that people with different locales can enter the currencies in their country specific format (e.g. 59,26 in german which is the same as 59.26 in english).

**Comment by mkurz** [comment]
`LocaleContextHolder` is used a second time [here](https://github.com/playframework/playframework/blob/2.4.2/framework/src/play-java/src/main/java/play/data/format/Formatters.java#L250) as well.

**Comment by jroper** [comment]
Essentially, Springs use of a ThreadLocal here is laziness - rather than threading the locale through the call hierarchies, they set it in a thread local.  That's ok, we can make that work with Play, we just need to ensure that when we do parsing or formatting, we have the thread local set.  I'm not sure where the right place to set it is - for parsing, it's simple, in the form bind method.  For formatting, that may be a bit harder, since perhaps that happens while the template is being rendered?  Not sure...

**Comment by mkurz** [comment]
Actually that's a duplicate of #2065
