### ISSUE TITLE
Set server port number in System configuration in dev mode

### ISSUE THREAD

**Issue by yifanmai** [playframework/playframework#4966]
I have a Play app that needs to know what port it is running on. If the app is run in dev, specifying the port number as a positional argument, retrieving the port number becomes [very difficult](http://stackoverflow.com/questions/14970677/retrieving-port-number-in-play-framework-2-app). This is because `Reloader` parses the positional argument [separately from the named arguments](https://github.com/playframework/playframework/blob/6d61056ed3a64ed6edbeb0681b34a93239d638c2/framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala#L66-L89). While the named arguments get added to the `System` properties, [the positional argument does not]
(https://github.com/playframework/playframework/blob/6d61056ed3a64ed6edbeb0681b34a93239d638c2/framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala#L131-L139). This positional argument isn't stored or exposed anywhere.

To fix this, Play should set the value of the `http.port` configuration, regardless of whether the port number is specified as a positional or named argument.

**Comment by jroper** [comment]
A few things:

* Play doesn't necessarily have a port number - you can start an application without starting an http server.
* Play can have many port numbers.  The most obvious example is when you start it with https and http enabled. But there's also no reason why, programatically, you can't start a Play application listening on many http ports.
* There's no way for a Play application to necessarily know its port number - in prod mode for example, the application is started before the server is started, and then the server is started, it may be automatic by configuration, or programatic, but either way, there's no way for the Play application, and by association, the Play configuration object, to know its port number.

One possible solution (that doesn't address all of the above) is to make the `Server` instance injectable - the http and https ports can be obtained from that.  But in the meantime, I'd suggest passing the port number as a configuration parameter, and if it doesn't exist as a parameter when you read it in the code, to assume a default of 9000, the same way Play does.

**Comment by wsargent** [comment]
Agreed.  If a port number is needed, it's probably best to specify it explicitly as an environment variable / command line system property setting, and then be able to call it out explicitly from inside the app.

I don't think this should be part of core Play functionality (especially with the multiple ports problem).  Closing.

**Comment by michaelahlers** [comment]
I've been fighting with this limitation all day. It'd be extremely helpful if, as @jroper suggested, we could inject `Server` instances. Until then, I'm willing to accept _any_ kind of hack that'd let me discover these at runtime.

**Comment by michaelahlers** [comment]
@yifanmai, I might be embarrassing myself with this response, but it might prove helpful to you.

Let me recap. a few permutations:

`System.getProperty("http.port")` turns up `null` in all cases when Play's dev. server is started with `run 12345`, _or_ with `run` _and_ `PlayKeys.playDefaultPort := 12345` added to project settings—unless that same property's explicitly set. However, starting with `testProd 12345`, or with `testProd` _and_ `PlayKeys.playDefaultPort := 12345` in settings initializes the `http.port` system property as expected.

Personally, I like my own default port preference to be included in the build, and I find the duplicity of _also_ setting a system property a bit cumbersome. A not-too-fragile workaround is to register a `RunHook` in your build as follows:

```scala
PlayKeys.playDefaultPort := 12345,
PlayKeys.playRunHooks +=
  play.sbt.PlayRunHook.makeRunHookFromOnStarted({ address =>
    /* If already set, don't corrupt it; use the existing value. Otherwise, default to the port given by the address. */
    System.setProperty("http.port", System.getProperty("http.port", address.getPort.toString))
  })
```

I write “not-too-fragile” because while it avoids haphazard means of setting the property, it doesn't elegantly handle cases @jroper described where multiple ports are open (as with SSL). However, AFAIK, that hook won't affect a production build.

Should it be filed as a bug that `http.port` isn't set with whatever argument is given `run` or assigned to `PlayKeys.playDefaultPort`?
