### ISSUE TITLE
play framework 2.4.2 client connection remains open

### ISSUE THREAD

**Issue by Abhi11981198** [playframework/playframework#4976]
i am using using activator project which has play 2.4.2 . just for testing i deployed raw project which only listen on port 80 0r 9000 and returning Ok("abc"). but when i check the output of $ sudo lsof -i | wc -l the number increasing gradually with time, and after some time let say 24-48 hours. the server crashes with exception too many file open.

i think this is due to play does not close connection after response.

**Comment by jroper** [comment]
It's true, Play doesn't close the connection after responses - that's the way HTTP is meant to work, the connection stays open, and is closed by the client.

There are some situations where the client can disappear, but the server won't notice, keeping the connection open in Play.  This can be worked around by setting `play.server.netty.option.child.keepAlive=true`, which will enable the OS keep alive, which allows the server to detect this situations, and close the connections.

**Comment by vrshu112** [comment]
Where to add this play.server.netty.option.child.keepAlive=true

**Comment by vinisuarez** [comment]
you should add to application.conf and if you upgrade to play 2.5.x the setting should be:
`play.server.netty.option.child.SO_KEEPALIVE = true`

**Comment by leosimoesp** [comment]
Hi,
I also use play 2.5 and I have the same problem. The application due to lack of new connections.
I tried to use this setting into application.conf but it didn't work. 

netstat -ant | fgrep 2424
tcp        0      0 172.17.0.1:52492        172.17.0.2:2424         ESTABLISHED
tcp6       0      0 :::2424                 :::*                    LISTEN     
tcp6       0      0 127.0.0.1:55498         127.0.0.1:2424          ESTABLISHED
tcp6       0      0 127.0.0.1:2424          127.0.0.1:55498         ESTABLISHED
