### ISSUE TITLE
Play 2.4.2 - play.mvc.Results.redirect doesn't work when application context is configured

### ISSUE THREAD

**Issue by nateww** [playframework/playframework#4977]
If the application global context (play.http.context) configuration is set, the redirect method does not prepend the context to the front of the any urls when an internal redirect is done. This worked properly in Play 2.3, and no longer works in Play 2.4.

https://github.com/nateww/PlayRedirectWithContext

Controllers should be written to be context-agnostic, so configuring (or not configuring) the context should not affect the behavior of the application, other than to change the URLs viewed in the browser.

**Comment by jroper** [comment]
You're storing the URL in a static field - Play initialises the reverse router with the context on startup, if your class is loaded before startup, it'll get the URL without the context, if it's loaded after startup, it'll get the URL without the context.  Essentially, by storing it in a static field, you have made very fragile code that is dependent on class initialisation ordering.  Play 2.4 has changed the way Play apps start up, so I'm not surprised it broke.  Don't store the reverse route in a static field, read it each time it's needed.

**Comment by nateww** [comment]
The example project was a contributed example to show a simple demonstration of the issue.  Even when I remove the static keyword from the field in the controller, it fails, so this issue is less about static and more about initialization order.

Obviously, there is a point when the application creates the controller with the proper url (including context if set).  Is there a way to have an event created at that particular time (not necessarily inside a controller, but inside another component) such that I can fetch the reverse route at that time and it's 'completely' initialized.

In short, I need the register a reverse route in a third party application (callback), and would prefer not to hard-code the existence of the http.context (again, making the code fragile).

How can I ensure that when I grab the reverse route, the application is 'initialized', and not in some early state of initialization where not everything is initialized?

For security and performance reasons, I can't/don't want to continually register the callback over and over (think service discovery), so I need to register the callback once the application is 'up' and the route is settled.

Right now, there are obviously at least two different values for the reverse route.  The first as demonstrated by this application before the context is taken into account, and the second, when the context is taken into account.  I want to know how to know when the latter event has occurred so I can use the reverse route generated at that point to register the existence of the running application with another application (not this one).

**Comment by jroper** [comment]
The best thing to do would be to have an eager singleton component that depends on `play.api.routing.Router`.  Since the router is the thing that initialises the routes prefix, if you have a router injected into your constructor, you can be sure that when you construct a reverse route in your constructor, the routes prefix is initialised.

**Comment by nateww** [comment]
Thanks James, I'll try and put something together that does that!

**Comment by pycloux** [comment]
Injecting play.api.routing.Router is probably not a valid option (= only works in simple applications).
There is a high risk of creating circular dependencies because in Router we have:
```
Some(Reflect.getClass[Router](className.getOrElse("router.Routes"), env.classLoader))
```
And router.Routes references all the controllers.
So if the object which needs the "valid route" happens to be indirectly used by a controller (any controller), we have a circular reference. I just experienced it a few minutes ago and I am really wondering how I can solve this.

**Comment by pycloux** [comment]
I am not sure that injecting play.api.routing.Router is working systematically (actually I juste experienced a case where it is not).
This is because Router contains:
```
Some(Reflect.getClass[Router](className.getOrElse("router.Routes"), env.classLoader))
```
And router.Routes is created by injecting all the controllers in the routes file.
So the result is a high risk of circular reference if the object which needs the valid routes il also used by a controller (even indirectly).

**Comment by jroper** [comment]
Another option then would be to depend on `HttpConfiguration`, and prepend the context yourself:

https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.http.HttpConfiguration

**Comment by pycloux** [comment]
Hi James,
I may indeed but that's "weird" to have the very same code artifact returning two different values at different moment in the application lifecycle. I rather think that the injection of the "context" (meaning the URL prefix) should be done so that we are sure that the routes are systematically correct (at any time) or failing (may be an exception).
One option may be to have Routes (the generated one) being injected with the Configuration and using "play.http.context" as the "default" prefix until the Router is loaded (or simply get rid of the "withPrefix" set by the Router provider in the built-in module).
Please would this be an acceptable workaround ?

**Comment by jroper** [comment]
It certainly is weird, and is one of the problems with having global state - initialisation becomes very hard to reason about.  We're hoping we'll find a solution for Play 3 that allows fully initialised reverse routers to be injected, that will solve this problem.

**Comment by pycloux** [comment]
Thanks James.

May I suggest a simple workaround to the community.

In the configure method of the application module (the first one preferably), once can add:
```
router.RoutesPrefix.setPrefix(configuration.getString("play.http.context"));
```
(where "configuration" is an instance variable taken from the module constructor).

Appart from the initialization of "static" variables with routes (for which there is not must options) this is working.

**Comment by jroper** [comment]
Yes, that is a much better work around.
