### ISSUE TITLE
Text BodyParser should parse as US-ASCII by default

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#4997]
As described in https://github.com/akka/akka/issues/16099, RFC 7231 changes the "default charset" logic from RFC 2616 in the following way:

> The default charset of ISO-8859-1 for text media types has been
> removed; the default is now whatever the media type definition says.
> Likewise, special treatment of ISO-8859-1 has been removed from the
> Accept-Charset header field. (Section 3.1.1.3 and Section 5.3.3)

If you look at https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala#L316 and the note on https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala#L309 you can see the default for `text/plain` is still ISO-8859-1.

**Comment by jroper** [comment]
Hmm... technically RFC 2616 is not yet obsolete, since RFC 7231 is not yet final.

But I think this is a low risk change, text/plain is not that common as a request body.  We should also replace the XML body parser logic, currently we default to `US-ASCII` encoding for `text/xml` without `charset` declaration, the new behaviour, I think, should be default to `UTF-8` (or maybe let the parser detect it?  If you let the parser detect it, it should default to `UTF-8` as per the spec if the charset isn't declared in the document.)

Where it's a higher risk change is in the WS client, when receiving html responses, since html is a very common response type, and servers that send `ISO-8859-1` without setting it in the `charset` parameter are going to suddenly all be breaking the spec.

**Comment by wsargent** [comment]
Well, this is interesting.  Per https://tools.ietf.org/html/rfc6657#section-4 the default for "text/plain" should be "US-ASCII", since that's what it's defined as in the media type definition at https://tools.ietf.org/html/rfc2046#section-4.1.3 

As for text/xml, I think that there shouldn't be a default -- either you send charset explicitly, or the XML document has a charset defined in the document itself, at least as per https://github.com/kennethreitz/requests/issues/2086

**Comment by wsargent** [comment]
Oh crud.  This should have gone into 2.6.0.

**Comment by wsargent** [comment]
Also see https://github.com/playframework/playframework/issues/5334
