### ISSUE TITLE
Error 413 : “Request Entity Too Large" returns 404 in header

### ISSUE THREAD

**Issue by DarkSlice1** [playframework/playframework#5002]
play 2.4.2

https://github.com/playframework/playframework/blob/2.4.x/framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala#L740

for some reason returns

Got an unsuccessful response with code '404' and body '{"code":413,"message":"Request Entity Too Large"}'

I lowered the entity size via

play.http.parser.maxMemoryBuffer = 1K

**Comment by jroper** [comment]
Hi @DarkSlice1, we have tests that verify that it returns 413, so the problem is likely in your setup, maybe a proxy is doing that, or maybe you have a custom error handler that's doing that.  To discuss further, please ask on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).
