### ISSUE TITLE
Cannot load keystore through play.server.https.keyStore config parameters in Play 2.4.2

### ISSUE THREAD

**Issue by djriffel** [playframework/playframework#5009]
I'm not sure if I'm doing something wrong here, but after much struggling with the configuration parameters listed at https://www.playframework.com/documentation/2.4.x/ConfiguringHttps I was unable to get my java keystore to load via application.conf. I was able to load the same keystore via the -Dhttps.keyStore and -Dhttps.keyStorePassword parameters when launching from the command line, however.

Is this expected behavior? I noticed some documentation as recent as 2.3.x only references the command line parameter method of loading a keystore for SSL. I'm not sure if what I'm experiencing is due to inaccuracies in the 2.4.x documentation or the result of a bug.

I am currently running development on Windows 7 with Java 8.

**Comment by jroper** [comment]
Is this in dev mode, or in production mode?

In dev mode, you can only configure https by system properties.  This is because in dev mode, the server outlives the application (every time you make a change, the application is reloaded, but the HTTP/HTTPS port stays active), and is in fact started before the application is loaded, therefore, configuration pertaining to the server such as HTTPS can't be read from `application.conf`, since that's only loaded when the application is loaded.

**Comment by djriffel** [comment]
I think that's what it was. I had been doing some preparation to make the switch to staging/prod while I was running under dev mode. After switching to production mode it looks like those parameters work as expected. Thanks for the clarification.
