### ISSUE TITLE
Unused close() method in Concurrent.unicast

### ISSUE THREAD

**Issue by alanyst** [playframework/playframework#5071]
The `close()` method defined at https://github.com/playframework/playframework/blob/2.4.x/framework/src/iteratees/src/main/scala/play/api/libs/iteratee/Concurrent.scala#L461 does not appear to be used anywhere.

**Comment by jroper** [comment]
Interesting.

**Comment by hearnden** [comment]
+1.  

`unicast()` seems like something that would frequently be used in websocket handlers.  A side effect of this issue is that when the server initiates a close via `Channel.eofAndEnd()`, no `Input.EOF` gets sent, and the websocket remains open.

Composing the enumerator returned by `unicast` with `Enumerator.eof` seems to be a viable workaround.

**Comment by wsargent** [comment]
May want to move to https://github.com/playframework/play-iteratees

**Comment by wsargent** [comment]
There is no Concurrent.unicast in Play any more, so this should be moved to https://github.com/playframework/play-iteratees
