### ISSUE TITLE
Content type of png files is not correctly identified 

### ISSUE THREAD

**Issue by scalabilitysolved** [playframework/playframework#5089]
It seems that Play Framework (2.4 and previous versions such as 2.3.8) using Java 8 does not ascertain correctly the content type when uploading files of type png. It works with other formats such as jpg and gif.

With a method such as:

`@BodyParser.Of(value = BodyParser.MultipartFormData.class)
	public Result upload() {
		Http.MultipartFormData body = request().body().asMultipartFormData();
		final Http.MultipartFormData.FilePart filePart = body.getFile("file");
		return ok("{\"fileType:\":" + filePart.getContentType() + "}");
	}`

I'd expect when uploading a png that the content type of the filePart would be `image/png` however instead it is `application/octet-stream`.  When uploading other files such as jpgs or gifs it works correctly.

I made a sample project with a small write up and example curl requests that show the issue being reproduced here https://github.com/scalabilitysolved/png-issue

Any additional information that you need just let me know, thanks!

**Comment by jroper** [comment]
The content type returned by Play is the value of the `Content-Type` header set on the file part by the client (eg, by the web browser). If the client sets `image/png`, Play will return `image/png`. If the client sets `application/octet-stream `, Play will return `application/octet-stream`. If the client doesn't set the header at all, Play will return null. The fact that Play is returning `application/octet-stream` means that's what the client is setting in the `Content-Type` header, and it would be wrong for Play to return anything else. So the problem is in your client, if you want to fix it, you must fix it in the client.

**Comment by nafg** [comment]
Note that if you want to work around it, Java has some content type
detection functions somewhere. I don't have the specifics with me
unfortunately.
