### ISSUE TITLE
Issue with Play 2.4.2 JPA persistent submodules

### ISSUE THREAD

**Issue by sakshamgupta** [playframework/playframework#5092]
I have a project built on Play! 2.4.2 that uses an auth subproject (auth in itself is a Play! 2.4.2 project). The auth subproject is included in the master project as a module (under the modules directory). All the module bindings in routes and build.sbt are correct.

I'm using hibernate for JPA in both projects. Individually, both, auth and master have their persistence.xml defined. On running the master project, none of the @Entity classes in the master project get mapped. On debugging, I saw that the only @Entity classes that are being mapped are from the submodule and none of the master project. To fix this, I removed the persistence.xml in auth (submodule), and now all the classes get mapped. So Play! either needs to ignore the persistence.xml's in submodules, or the maintainers of the master project will have to remove them manually. I believe the former approach is much more sane.

The issue is easily reproducible. Just have a project included as a submodule and use Hibernate for JPA. Now hit a controller action that persists an @Entity class in the master project. To fix the issue, remove the persistence.xml file from the submodule.

**Comment by jroper** [comment]
Play isn't doing anything here, Play doesn't even come with a JPA provider out of the box.  It's hibernate that is finding and locating the `persistence.xml` files.  To put simply - there is nothing Play *can* do to fix this.  The problem is, you have multiple `persistence.xml` files on your classpath, and you probably are using the same persistence unit name for them.  JPA doesn't work that way, you can only have one `persistence.xml` per persistence unit on the classpath path, if you had multiple, which one would it use?  So, your auth sub module should define it's own unique persistence unit and use that, or it shouldn't define a persistence unit at all.
