### ISSUE TITLE
playUpdateSecret command only replaces the secret if the key is represented as a path

### ISSUE THREAD

**Issue by kpmeen** [playframework/playframework#5131]
Configurations like this:

```
play {
  crypto.secret = "changeme"
}
```
or this:
```
play {
  crypto {
    secret = "changeme"
  }
}
```

end up with the "updated" key on top of the file
```
play.crypto.secret = "some generated secret"
play {
  crypto.secret = "changeme"
}
```

**Comment by jroper** [comment]
This could probably be fixed by loading `application.conf` manually using typesafe config, without falling back to any `reference.conf`, looking up the secret `ConfigValue`, and then using the `ConfigOrigin` from that to determine which line its on.  Then, the file can be loaded, that line located, and the original value replaced with the new value.

**Comment by gmethvin** [comment]
To be more specific, first you actually want to remove `application.secret` if it exists, then replace or add `play.crypto.secret`.
