### ISSUE TITLE
Race-condition fails with No Entity Manager

### ISSUE THREAD

**Issue by patrik7** [playframework/playframework#5139]
Hi,

We are usign Play 2.4.2 with java and JPA. After upgrading to 2.4 from 2.2 we started getting ugly race conditions when the flow is split into multiple futures.

```
@Transactional
public static F.Promise<Result> authenticate(final String originUrl) throws Throwable {
    ... //some code
    return authenticateWithIdAndToken(...);
}
```

```
private static F.Promise<Result> authenticateWithIdAndToken(final FacebookAuth fbAuth) throws Throwable {
    return getOrCreateFacebookUser(fbAuth.facebookId(), fbAuth.facebookToken(), fbAuth.facebookProfile()).map(user -> JPA.withTransaction(() -> {
        ... //some code
        ... //this is the code that has to access DB and sometimes fails with No EM, on different places
        return finishAuthenticationRedirect(..); //this returns a Result
    }));
}
```

After reading the discussions here:
https://groups.google.com/forum/#!topic/play-framework/th-Q29BWqs0
and here:
https://github.com/schaloner/deadbolt-2-java/issues/7

It sounds to me (and I am not an expert) that Entity Manager is now assigned to http context (since 2.4) instead of the thread. (I think it's a step in right direction). But it get's closed after the first controller call finishes, at the end of authenticate. Which doesn't make much sense to me. It would be great if the same Entity Manager and Db transaction was maintained until all Futures in the flow finish.

Are we using the API in a wrong way or is this a bug? I no longer know how to split handling into multiple Futures.

**Comment by twiho** [comment]
+1

**Comment by jroper** [comment]
The problem with closing it when the future completes is that that introduces deadlocks, and this impacted quite a number of people in production.  Consider the case where the connection pool has exhausted, and all the requests holding connections are currently doing asynchronous things in futures.  Then a number of requests come in, and they block on the connection pool because it's exhausted, until now the thread pool is exhausted, with all threads blocked on the connection pool.  The requests holding the connections then finish whatever asynchronous things they're doing, and so new tasks to do the map/flatMap tasks, including returning the connections to the pool, are passed to the thread pool, but can't get executed because there's no threads to execute them.  And so the connections can't be returned to the connection pool because there's no threads to do so, and there's no threads to do so because all the threads are waiting on connections to be returned to the connection pool.

The only way to solve this really is to get an asynchronous connection pool, but we don't have that.  Without that, the only safe way for you to write your app is to only use the connection on one thread.

**Comment by patrik7** [comment]
Hi James,

Thanks for the reply - I understand the deadlock problem. But I am not sure what you are suggesting is the solution. If there's no async connection pool (and I guess this is not matter of days) what to do?

I am happy to break down execution flow to have one EM/transaction per future (this is how it worked in 2.2 using JPA.withTransaction), but it looks like this is not easy to achieve anymore.

Currently, as I understand it, JPA.withTransaction gives non deterministicly either new EM or a request bound EM that will sees to exist. Could you please point me to a good solution. Should we have our own EM factory to handle this?

https://groups.google.com/forum/#!topic/play-framework/th-Q29BWqs0
What this guy suggests works. However, I need to keep the context to be able to manipulate toher request properties.

Any help will be apretiated. Regards

**Comment by patrik7** [comment]
Hi James,

Thinking about this a bit more - I am not sure if "asynchronous connection pool" helps at all. If you want to have whole request handled within a single transaction, you need unlimited number of parallel transactions, which most* DB servers will not handle. It feels like different connection pool would just push the problem to different component in the hierarchy.

Have you considered using an intelligent prioritizing of Futures execution in akka - Futures returning a Result would get high priority - as they close a transaction. Similarly, Futures starting request handling would have the lowest priority. I believe this, in conjuction, with guidelines on Future(s) spawning while executing a request could solve the problem.

**Comment by jroper** [comment]
You're right, so what's actually needed is an asynchronous database API.

The prioritisation is not really an option.  What is an option is careful use of [managed blocking](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ForkJoinPool.ManagedBlocker.html), this would have to be done both in the transactional annotation, and in user code.

Though, to implement consistency in a scalable and resilient way, transactions are terrible.  It's much better to implement idempotent operations than to use transactions - this is fundamental to the tenets of reactive programming.

**Comment by twiho** [comment]
I didn't quite understand the idempotent operations. Can you, please, provide an example or otherwise elaborate? (I do understand idempotency itself.)

How about the solution (that I believe was used in previous play versions) that the entity manager is bound to the current thread? No longer can the requests be atomic (which they weren't in our case anyway) and no longer can you re-use managed entities between futures, but each future can acquire it's own transaction and re-fetch it's ebeans?

**Comment by twiho** [comment]
Also, somewhat relevant, I'm trying to inject our own version of JPAApi implementation, but I don't understand one thing:

from https://github.com/playframework/playframework/blob/master/framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java

```
    /**
     * Get the EntityManager for specified persistence unit for this thread.
     */
    public static EntityManager em(String key) {
        EntityManager em = jpaApi().em(key);
        if (em == null) {
            throw new RuntimeException("No JPA EntityManagerFactory configured for name [" + key + "]");
        }

        return em;
    }

    /**
     * Get the default EntityManager for this thread.
     */
    public static EntityManager em() {
        Http.Context context = Http.Context.current.get();
        if (context != null) {
            EntityManager em = (EntityManager) context.args.get(CURRENT_ENTITY_MANAGER);
            if (em == null) {
                throw new RuntimeException("No EntityManager found in the context. Try to annotate your action method with @play.db.jpa.Transactional");
            }
            return em;
        }
        // Not a web request
        EntityManager em = currentEntityManager.get();
        if(em == null) {
            throw new RuntimeException("No EntityManager bound to this thread. Try wrapping this call in JPA.withTransaction, or ensure that the HTTP context is setup on this thread.");
        }
        return em;
    }
```

Why does `em(String key)` delegate to the injection while `em()` does not and implements in place?
 
We've been using `play.db.jpa.JPA.em()` throughout our application and to change the behaviour we have to rewrite each single occurrence with our implementation and, moreover, be cautious not to use play.db.jpa.JPA.em() in future.

**Comment by sam2013** [comment]
Hi, I am facing similar issue. 

Getting an exception while doing db operations. 

`java.lang.RuntimeException: No EntityManager found in the context. Try to annotate your action method with @play.db.jpa.Transactional
`
Below is the code 

```
    paymentResponse.onRedeem(response -> persistTransaction(response, buyerInformation.getCustomerId()));
    paymentResponse.onRedeem(response -> completeProductOrder(response, buyerInformation));
    paymentResponse.onRedeem(response -> postSuccessfulProcess(response, purchasePayload, buyerInformation));
```


persistTransaction and postSuccessfulProcess are doing db update transactions using something like below

    JPA.withTransaction(() -> {

I am new to play framework. Can you please suggest me some remedy for this issue.

how did you resolve your issue?

**Comment by patrik7** [comment]
Hi sam2013,

Yes, that's essentially it. You need to do JPA.withTransaction inside each of the functions that are called in the Future context.

Maybe you are missing a re-fetch? If you want to work with model that was fetched inside a different JPA Transaction, you need to refetch it: Model newModel = Model.fetchById(sameModel.id)

**Comment by wsargent** [comment]
Connected with https://github.com/playframework/playframework/issues/6489

**Comment by mkurz** [comment]
I think its safe to close this. #7253 explains how to work with the `JPAApi` in regards to custom execution contexts.
Also `@Transactional` shouldn't be used anymore but instead inject the `JPAApi`. Also upcoming #8616 deprecates `@Transactional` (and any methods which rely on a ThreadLocal) altogether since IMHO it's of no use anymore.
