### ISSUE TITLE
cors filter fails from cordova mobile app

### ISSUE THREAD

**Issue by Enalmada** [playframework/playframework#5193]
When making a rest call to a cors enabled play server from javascript on a cordova/phonegap mobile app, it sends the URI as 'file://', the domain/host of the URI is null so new URI in cors filter code throws an error and then Play returns a 403 error here:

https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala#L322

Can the code be changed so that adding allowedOrigins = ["file://"] to the play filter would work?

See: http://stackoverflow.com/questions/32509118/play-2-4-how-to-allow-cors-from-origin-file

**Comment by jroper** [comment]
Allowing `file://` origins seems like a really bad idea to me.  If your site also has a web interface, and an attacker could convince a user to download then open an HTML file, then boom, the attacker can access your site as that user.

The simple fact is that phonegap applications don't need to use CORS, and so shouldn't be sending CORS headers - I haven't used phonegap myself, but it seems that either something you've configured is wrong, or there is a problem in phonegap, because it shouldn't be setting these headers, they don't make sense, there's no cross origin requests happening here.

Have you whitelisted your domain?  See http://stackoverflow.com/questions/21297169/cors-and-phonegap-apps for more details.

**Comment by Enalmada** [comment]
Based on your advice I started digging into this and think I have reproduced the real problem completely independent of phonegap.    
Try this post request on a cors filter enabled play server:
```
curl -H "Origin: file://" -H "Access-Control-Request-Method: POST" --verbose localhost:9000
```
Play will give you a 403 (for any url) if the method is post and origin is file://.
If you remove cors filter, it will continue processing correctly.  GET is fine, so something with the combination of origin file:// and post is always triggering cors to 403 even though it shouldn't?

**Comment by jroper** [comment]
I wouldn't call that producing the problem independent of phonegap - you've just emulated the same request that phonegap makes using curl.  You would never send a CORS header like `Origin` or `Access-Control-Request-Method` from curl in real life, because you are in complete control of what requests you visit with curl, so the solution with curl is simply don't send those headers.  CORS is all about solving the problem where you want a web browser to make requests to a site from a different origin to your site.  By default, browsers prevent this, but CORS allows web browsers to safely discover what requests they can and can't make on a cross origin server.  Since phonegap is not a web browser, it doesn't need to implement any cross origin resource policy, and so therefore shouldn't be sending any cross origin resource sharing headers.

**Comment by Enalmada** [comment]
I'm sold.  Now I need to convince phonegap to stop sending that header and your feedback should really help.  Thanks for your expert advice and helping me get from A to B on this.

**Comment by enrimr** [comment]
What about Electron apps? The Origin is also set to "file://" so it's impossible to return any response different from 403. Any idea? Thanks.

**Comment by aBuder** [comment]
Hi I write an http intercepter in in angular and I set set the origin in each header to https://example.com

**Comment by afief** [comment]
@aBuder how do you do that?
I can't set Origin header using $http.defaults.headers.common['header']. its always forbidden
