### ISSUE TITLE
Play Framework server is not working when start as background.

### ISSUE THREAD

**Issue by cailhuiris** [playframework/playframework#5222]
When I try to run play server with `activator run &` or `activator start &`,
This command is not working..

**Comment by gmethvin** [comment]
Hi @cailhuiris,

I'm closing this issue because it seems like you're looking for help, and this tracker is specifically for reporting bugs in Play Framework itself.

I'd suggest posting to the [mailing list](https://groups.google.com/forum/#!forum/play-framework) and/or on stack overflow. Make sure to provide more information on your environment, what you've tried, and the error messages you're getting.
