### ISSUE TITLE
how can i use the gradle or maven to use play

### ISSUE THREAD

**Issue by Ive4** [playframework/playframework#5234]
i don't want use sbt
can i use the gradle to write play app?
like maven i could choose the jar what i want
i know the gradle had play-plugins but it's not good work in idea
i'm a idea fans and my only one ide is idea
i like play 2 years ago,but i could found a good tools to write it

**Comment by gmethvin** [comment]
Hi @Ive4,

There is nothing preventing you from using gradle with Play. It is not officially supported by the Play team, but there is a third party [Play plugin for gradle](https://docs.gradle.org/current/userguide/play_plugin.html).

I'm closing since this is not an issue with Play. If you'd like to discuss more you can create a post on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).
