### ISSUE TITLE
Use canonical link so that Google shows latest documentation

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#5256]
Whenever I do a search for the documentation I get results for old versions like 2.0 instead of 2.4. It'd be really nice to fix this

http://stackoverflow.com/questions/29603839/versioned-urls-how-can-i-tell-search-engines-about-more-recent-versions-of-the

**Comment by wsargent** [comment]
This should be on https://github.com/playframework/playframework.com -- Google should be getting the sitemap updated so that it has more of an idea of how the process works.

https://github.com/playframework/playframework.com/blob/4c180c6414fa6ced515a0179497f45b86f5ae3d9/public/sitemap-index.xml

https://github.com/playframework/playframework.com/issues/22

https://github.com/playframework/playframework.com/issues/8

**Comment by wsargent** [comment]
Migrated to https://github.com/playframework/playframework.com/issues/43
