### ISSUE TITLE
format-like macro for QueryStringBindable

### ISSUE THREAD

**Issue by yawnt** [playframework/playframework#5259]
I think it'd be real useful (considering how much of a boilerplate it is) to write macros which generate a QueryStringBindable[T], akin to what `Json.format[T]` does 

I couldn't find anything, feel free to point me to it, in case I missed.

Thanks!

**Comment by gmethvin** [comment]
Can you give me an example of how you'd use it and what the query string would look like?

**Comment by yawnt** [comment]
it's useful when you want to represent complex data, and you end up with querystrings such as `[][a]=b`

my use case is that I have a REST endpoint that needs this level of granularity, and of course, it's not possible to just switch from GET to POST without violating REST principles
Rails and other Node.js frameworks all support this

**Comment by gmethvin** [comment]
Why wouldn't you use the body if you're using a POST request? That's why I was asking for an example use case.

Either way, If you think other people would find it useful, I'd encourage you to write it and open source it. It's not actually necessary to integrate it with Play core for it to be useful.

**Comment by yawnt** [comment]
no no, I'm using a GET request, not a POST .. i can't change it to POST because it would violate REST principles 

I think Play core is where it should be, doesn't mean I can't try and fix this issue myself and send a PR of course!

**Comment by gmethvin** [comment]
Hi @yawnt,

You're welcome to submit a PR but I still don't quite understand what you're trying to do. Could you please provide a simple example of how you would use this in your project?

From my experience, GET endpoints in REST APIs either allow you to get a single entity by its id or allow you to get a list entities using a few different query parameters (which may or may not map to fields in the model).

**Comment by mhzajac** [comment]
I can see a use case. Often I might use something like `case class Filter(text: String, orderBy: String, ascending: Boolean, ..)` where a `Filter` would be used to help a table on the front-end map a group of query parameters to the router. It's much nicer to have controller methods with a signature of `def list(filter: Filter)` than it is to have some with several parameters, especially if the `Filter` class is re-used in many places.

**Comment by Mumutu** [comment]
macro can really save time when turn a `case class T` to a `QueryStringBindable[T]` instance since most of the code is boilerplate

**Comment by schmitch** [comment]
Actually I've taken a Look on that, however I doubt the implementation would be great if we do this before Scala 2.12 since the Macro needs some implicit binders available which would result in:

``
implicit def myQueryStringBindable(implict e0: QueryStringBindable[Int], e1: QueryStringBindable[String]) = Macro....
``

For Scala 2.12 it would only be:

``
@QueryStringBindable
case class Filter(key: String, orderBy: String, ascending: Boolean)
```

**Comment by julienrf** [comment]
I think you should implement this kind of thing with Shapeless.
