### ISSUE TITLE
[2.4.3] Stackoverflow with compile time DI when injecting `application`

### ISSUE THREAD

**Issue by godenji** [playframework/playframework#5295]
Sample [project here](https://github.com/godenji/play-di-boom) illustrating the problem.

Are we not meant to DI the `application` into controllers? If not, how do we transition from global state to DI? Several areas in my production app require access to the configuration and the old approach `import play.api.Play, play.api.Play.current` relies on global state.

Trying to switch to full DI here but above issue is a complete show stopper.

Thanks for clues and/or explanation as to what is happening here.

**Comment by godenji** [comment]
On gitter @nafg suggested passing injected component by-name.

This compiles but has a couple of drawbacks: 
1) by-name is less efficient than by-value
2) Stackoverflow when accessed outside of a def Action; i.e. when accessed in controller class body.

What's puzzling is that I can `application.configuration.getString(...).foreach(println)` from within `AppLoader` class, so why the need for by-name passing into applicable components?

**Comment by wsargent** [comment]
Hi @godenji -- Github is for bugs in the framework itself.  Please use the mailing list at https://groups.google.com/forum/#!forum/play-framework for application issues.

**Comment by godenji** [comment]
@wsargent I actually consider it a bug that one must pass `application` by-name with compile time DI. Furthermore, not being able to access it within controller class body makes matters worse since one cannot cache the by-name passed `application` in a val.

Put differently, in what way is this issue not a bug? The linked sample project above clearly illustrates the issue.

**Comment by wsargent** [comment]
Hi @godenji, so... right now it's not a bug because you haven't filed it as a bug -- you're asking for clues / explanation.

in order to be considered a bug, you need to specify:

* the sequence of steps to follow,
* the expected result,
* the actual result,
* why you think this is a bug, rather than a design decision (design decisions are typically discussed on play-framework-dev).  

You need to do all of this inside the issue text itself, and provide the reproducing project or case as a supplement.  As an example, please see https://github.com/AsyncHttpClient/async-http-client/issues/1027 for how to make a case.

**Comment by godenji** [comment]
@wsargent oh, thanks, I see what you mean now wrt to asking on the mailing list ;-)

Still trying to find the root cause, *seems* like a bug. Will post back here if I find anything definitive.
