### ISSUE TITLE
Use/support Scala cache as caching mechanism

### ISSUE THREAD

**Issue by mdedetrich** [playframework/playframework#5296]
Scalacache can be seen here
https://github.com/cb372/scalacache/issues/34

Reasons for
1. Abstracts away many backends, not just ehCache. As an example, just newly added support for Java's new Caffeine cache
2. Using the cache on functions is ridiculously easy with the memoize function
3. Is config free, so its really easy for Play to provide their own config (using typesafe config) ontop of ScalaCache
4. High performance with use of macros
5. Is effortless to use. For any function that returns something of `Future[T]`, you can simply wrap the function in a `memoize` block.
6. Great use of implicits mean that doing very fine grained caching mechanisms, with their own creation/destruction/TTL behaviours means that this is painless

Reasons against
1. Only supports Scala 2.11 (due to Macros)
2. Only written in Scala which means that calling it from Java can cause problems (although I believe the basic cache API, which is a `k/v` store, which they also provide, should be able to be called from Java fine). Not sure if they new function interface with JDK 8 + Scala 2.12 will change things.
3. An external dependency that needs to be managed

**Comment by gmethvin** [comment]
It seems like it'd be pretty straightforward to write a ScalaCache wrapper that implements the Play CacheAPI. You just need to bind a `CacheAPI` that wraps your `ScalaCache` so the framework and Play modules would use the same cache.

The CacheAPI in play is intentionally designed to be very simple, so it is easy to use in both Java and Scala and works well for lots of different types of caches.

**Comment by ben-manes** [comment]
Hey Greg,

Ehcache is unfortunately [very slow](https://github.com/ben-manes/caffeine/wiki/Benchmarks) and, in v3, they reduced the hit rate for small caches by taking an MRU-heavy sample (~10pt lower) which is then LRU sorted. For large caches, oddly running a trace takes minutes instead of seconds due to spending all of its time in their cache's random sampling method. In comparison, Caffeine uses a [near optimal eviction policy](https://github.com/ben-manes/caffeine/wiki/Efficiency) which does not add significant time or space overhead.

A more interesting question is what the impact of caching is in Play applications, if Ehcache exhibits the same problems outside of synthetic tests, and if the default provider should be reevaluated.

**Comment by mdedetrich** [comment]
There is a subset of ScalaCache which pretty much mirrors what the Play cache looks like. The main benefit of ScalaCache is the fact that it supports many more backends than the current cache in Play, and its integration should be quite painless

**Comment by gmethvin** [comment]
@ben-manes Yes, it would be worth re-evaluating the default cache implementation in Play. Caffeine might be a good choice for many users. It would be interesting to see some benchmarks with different cache implementations for common cache use cases like caching action results.

It would probably be better to discuss details on the [mailing list](https://groups.google.com/forum/#!forum/play-framework).

**Comment by ben-manes** [comment]
I was playing around with Ehcache with traces and found that as the cache size increases its performance degrades. I knew that small caches had a poor hit rate and larger have random, but I hadn't noticed the cost in execution time previously. The larger the cache size is the more time Ehcache spins taking a random sampling (I assume due to iterating vs. array indexing). The ARC paper's P8 trace with a maximum of `65,536` entries is shown below. If Play users have large caches this could be an observable overhead.


```
╔══════════════════╤══════════╤════════════╤════════════╤════════════╤═════════╗
║ Policy           │ Hit rate │ Hits       │ Misses     │ Requests   │ Time    ║
╠══════════════════╪══════════╪════════════╪════════════╪════════════╪═════════╣
║ linked.Lru       │ 36.10 %  │ 15,249,933 │ 26,993,852 │ 42,243,785 │ 4.493 s ║
╠══════════════════╪══════════╪════════════╪════════════╪════════════╪═════════╣
║ sampled.Random   │ 33.36 %  │ 14,093,695 │ 28,150,090 │ 42,243,785 │ 7.128 s ║
╠══════════════════╪══════════╪════════════╪════════════╪════════════╪═════════╣
║ product.Caffeine │ 50.43 %  │ 21,302,116 │ 20,941,669 │ 42,243,785 │ 16.18 s ║
╠══════════════════╪══════════╪════════════╪════════════╪════════════╪═════════╣
║ product.Ehcache2 │ 36.16 %  │ 15,275,313 │ 26,968,472 │ 42,243,785 │ 1.566 m ║
╠══════════════════╪══════════╪════════════╪════════════╪════════════╪═════════╣
║ product.Ehcache3 │ 33.07 %  │ 13,968,421 │ 28,275,364 │ 42,243,785 │ 4.187 m ║
╚══════════════════╧══════════╧════════════╧════════════╧════════════╧═════════╝
```

**Comment by cb372** [comment]
Hey there. I just spotted this. Let me know if you need any help with integration.

I know of at least a couple of people who are using ScalaCache with Play, but proper integration is something I've been meaning to get around to for a while. (Did I really make that issue all the way back in March?)

**Comment by wsargent** [comment]
I agree that ScalaCache's API is far preferable to Play's Cache API, but a direct integration isn't a Play bug / feature -- also, in order to get this to work right, we need to rewrite the Cache API and the Cached action handler, after which this would be an external module implementing `BetterCacheApi`.  So... regretfully closing.

**Comment by ben-manes** [comment]
Note that Ehcache 3 has, knowingly, further reduced the hit rate since my last post. For the above trace the hit rate is 25.50% (3.0rc1) and a similar large drop is seen across other workloads. While I understand they're motivation to incentivizing users to upgrade to their commercial product, it feels dirty and dishonest. At some point Play will need to revisit its default cache and should validate the integrity of the implementors.

**Comment by mdedetrich** [comment]
@wsargent Would a pull request be more convincing? I believe Play being backed by scalacache (with a seperate API for Java) would probably be better off in the long term for Play, especially considering the amount of backends it supports (including Caffeine)

**Comment by gmethvin** [comment]
@mdedetrich If you want to use scalacache as a backend, you can create a play module for it. See cb372/scalacache#34.

It's unlikely we would want to use the scalacache API directly in Play, since its API is not consistent with the way things are done elsewhere in Play (e.g. wrt use of implicits to pass components), so at most we're using it as a caching backend layer. At that point I'd think we'd be better off just creating the cache implementations ourselves on our current API instead of having another level of indirection.

**Comment by cb372** [comment]
Speaking as the creator of ScalaCache, I agree that it doesn't really make sense to integrate it into Play directly, i.e. make Play depend on ScalaCache. A looser integration would be preferable, whereby on the ScalaCache side I provide a Play module/cache API implementation/etc, and Play gives a nod to it in the official docs. A few small changes in the Play APIs to accommodate ScalaCache might turn out to be helpful, I'm not sure yet.

Even now, with zero direct support for Play in ScalaCache, I know of a few people who are using it as a Cache API implementation, so I think it can be done pretty easily.
