### ISSUE TITLE
[Play 2.4.4] 'Invalid forwarded header' on form submit if running behind a reverse proxy

### ISSUE THREAD

**Issue by DorianGrey** [playframework/playframework#5299]
I've recently tried to update to 2.4.4 (from 2.4.3) and faced a curious error on form submission:
```
2015-11-23 08:10:08,670 [error] p.c.s.n.PlayDefaultUpstreamHandler : 
  Cannot invoke the action
play.api.PlayException: Invalid forwarded header[Forwarding header '::1' supplied by trusted proxy
ConnectionInfo(/127.0.0.1,false) could not be parsed: failure: string matching regex `_[\p{Alnum}\._-]+' expected but `:' found: fix proxy header or
remove proxy from play.http.forwarded.trustedProxies config entry]
	at play.core.server.common.ForwardedHeaderHandler.scan$1(ForwardedHeaderHandler.scala:93) ~[play-server_2.11-2.4.4.jar:2.4.4]
	at play.core.server.common.ForwardedHeaderHandler.remoteConnection(ForwardedHeaderHandler.scala:116) ~[play-server_2.11-2.4.4.jar:2.4.4]
	at play.core.server.common.ForwardedHeaderHandler.remoteConnection(ForwardedHeaderHandler.scala:57) ~[play-server_2.11-2.4.4.jar:2.4.4]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$1.remoteConnection$lzycompute(PlayDefaultUpstreamHandler.scala:111) ~[play-netty-server_2.11-2.4.4.jar:2.4.4]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anon$1.remoteConnection(PlayDefaultUpstreamHandler.scala:108) ~[play-netty-server_2.11-2.4.4.jar:2.4.4]
```
The application is running behind a nginx, which is configured like:
```
upstream application1 {
    server localhost:8999;
}
server {
    location / {
        proxy_pass http://application1;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        add_header X-Frame-Options SAMEORIGIN;
    }
    # Some more detailed stuff which is not relevant here.
}
```
This error did **not** occur on 2.4.3, and only affects POST requests on form submission. All other POST or GET requests work fine.

**Comment by gmethvin** [comment]
@richdougherty Looks like this was caused by #5266

**Comment by richdougherty** [comment]
Would you mind giving headers for a working and non-working request? I can reproduce if I set headers to:
```
X-Forwarded-For: ::1
``` 

I think the reason is that we are now actually parsing the `X-Forwarded-For` header value. Maybe we need to make the parsing lazy, so we only actually parse if we need to check that an address is a trusted proxy. The reason the parsing is failing is that we are expecting IPv6 addresses to follow the format in RFC7239, i.e. `[::1]` not `::1`.

You may be able to fix this by changing your settings to:

```
proxy_set_header X-Forwarded-For $remote_addr;
```

This will tell Play that you forwarded the connection for the given `$remote_addr` and Play will use that value as the request's `remoteAddress` property. It will also remove the troublesome `::1` entry from the `X-Forwarded-For` header. Play ignores the `X-Real-IP` header so there's no point setting it.

**Comment by gmethvin** [comment]
I think we should only parse this header if we need to check trusted proxies. I'm sure there are a lot of people with this nginx configuration. At most we should log a warning here.

**Comment by DorianGrey** [comment]
>  I'm sure there are a lot of people with this nginx configuration. At most we should log a warning here.

Unfortunately, yes - especially those who are [moving from Apache](https://www.nginx.com/resources/wiki/start/topics/examples/likeapache/).

> The reason the parsing is failing is that we are expecting IPv6 addresses to follow the format in RFC7239 i.e. [::1] not ::1.

Hm ... I've found something in the RFC which mentions that this format [is not always expectable](https://tools.ietf.org/html/rfc7239#section-7.4):
> Note that IPv6 addresses may not be quoted in X-Forwarded-For and may not be enclosed by square brackets, but they  are quoted and enclosed in square brackets in "Forwarded".

I.e. it's valid to not use brackets within the X-Forwarded-For header - the brackets are only required in the "Forwarded" format.
> You may be able to fix this by changing your settings to: [...]

This does not work either - it fails with the same exception.

> Would you mind giving headers for a working and non-working requests? [...]

The list is from a working request:
```
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate
Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:423
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:PLAY_SESSION=11bae7158f94ba7504fdbf9d39f74d360b0bc9f8-clientId=0ea18743-5a69-4bb1-954c-bb7de45b0089
DNT:1
Host:localhost:9000
Origin:http://localhost:9000
Referer:http://localhost:9000/
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36
X-Requested-With:XMLHttpRequest

Remote Address:[::1]:9000
Request URL:http://localhost:9000/login
Request Method:POST
```
And this one from the failing version:
```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Cache-Control:max-age=0
Connection:keep-alive
Content-Length:73
Content-Type:application/x-www-form-urlencoded
Cookie:PLAY_SESSION=11bae7158f94ba7504fdbf9d39f74d360b0bc9f8-clientId=0ea18743-5a69-4bb1-954c-bb7de45b0089
DNT:1
Host:localhost:9000
Origin:http://localhost:9000
Referer:http://localhost:9000/
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36

Remote Address:[::1]:9000
Request URL:http://localhost:9000/query?clientId=147a0935-3908-483d-ad3e-c132c542072f
Request Method:POST
```
The corresponding routes are define like:
```
POST        /login    @controllers.UserController.checkLogin
POST        /query    @controllers.ClientController.query(clientId: String)
```
The only valuable difference is that the XHR is working, while the other is not.

**Comment by richdougherty** [comment]
I'll change the code to be more lazy and forgiving and to log warnings instead of throw errors.

Thanks for the headers. From the exception message I assume both of these requests come via a proxy on 127.0.0.1 connecting via HTTP. I also assume you're using [default settings for trusted proxies](https://www.playframework.com/documentation/2.4.x/HTTPServer#Configure-trusted-proxies), not doing anything special.

I think the reason it works for one request, but fails for another, is that the failing request will be trying to read the request's `remoteAddress` or `secure` flag, whereas the working request won't be accessing these values. The header parsing is lazy so it should only occur when `remoteAddress` or `secure` is accessed. Can you look at the stack trace and check that the code accessing `remoteAddress` and `secure` is your application code and not something that Play is doing automatically. If you can verify this then that will explain why one request is working and the other request is failing. If you're not sure, maybe you can paste more of the stack trace here.

**Comment by DorianGrey** [comment]
> I assume both of these requests come via a proxy on 127.0.0.1 connecting via HTTP. I also assume you're using default settings for trusted proxies, not doing anything special.

Both is correct - the nginx proxy in front only takes care of serving several static assets, especially the versioned one within the production environment. For development, this setup would not be required, but it's useful to mirror the production environment's behavior to detect things like this issue before they even get a chance to cause problems there.

> Can you look at the stack trace [...]

I fear that what I've posted already _is_ the whole stacktrace that occurs in the logs.
> [...] and check that the code accessing `remoteAddress` and `secure` is your application code and not something that Play is doing automatically [...]

It seems that our code causes this -  `request.remoteAddress` get accessed on the login hook, but not on the hook that deals with the XHRs. This access is not that relevant and might be removed (and the login works if I do so, of course). However, we've got other hooks accessing the remote address field for performing some checks on it, and I must not change these.

**Comment by richdougherty** [comment]
Thanks for confirming both of those points.

I think you can get more stack trace by adjusting your logback settings: https://www.playframework.com/documentation/2.4.x/SettingsLogger#Default-configuration.

**Comment by richdougherty** [comment]
I've submitted a fix to this issue now, you may want to review it: #5306.

**Comment by DorianGrey** [comment]
Done.
