### ISSUE TITLE
request.body.asText returns null if Content-Type is application/json

### ISSUE THREAD

**Issue by gleeb** [playframework/playframework#5315]
This is annoying as hell, JSON format IS TEXT!!!!! it is just formatted. 
there is absolutely no reason why this shouldn't work.

**Comment by benmccann** [comment]
I just ran into this too. I think the only way to make it work is to annotate your method with `@BodyParser.Of(BodyParser.TolerantText.class)`. See https://www.playframework.com/documentation/2.5.x/JavaBodyParsers

`request().body().asRaw()` also returns null, which was also surprising to me. Can we make that method always return the bytes of the request? And then make the other methods parse into text, json, etc. from it when they're called? I do think that'd be a lot more intuitive from an API perspective. It'd also be a lot more concise as it'd remove the need for `@BodyParser.Of(BodyParser.TolerantText.class)`, which is a bit redundant since I'm already specifying I want it parsed as text by calling `request().body().asText()`.

**Comment by richdougherty** [comment]
It's a bit tricky. Play's model always parses the request body before the action executes. The default parser reads the request `Content-Type` to work out which type of parsing to do.

To keep this model, and also support `asRaw` or `asText` calls within the action we'd need to cache the original raw body bytes along with the parsed body. I don't think we could just keep the parsed body, because we can't recover the original body from converted JSON, etc.

If we want to support `asRaw`/`asText` we'd probably need to delay parsing until these calls are made. Obviously this has different semantics to the current parser, because the parser would be lazy rather than eager.

**Comment by benmccann** [comment]
Yeah, I was suggesting making it lazy rather than eager. I'm not sure if there'd be problems that I'm not aware of if we tried that

**Comment by richdougherty** [comment]
I'm not sure if this is a show stopper, but the memory used would often be higher. We'd always need to read the whole body into a `Seq[Array[Byte]]` or `RawBuffer` before the action runs. We couldn't incrementally build a `String` as the request comes in. I think this would be OK, but something to be aware of.

**Comment by benmccann** [comment]
True. It does potentially require some extra memory. Thinking about this some more, perhaps there's another way to get the request body with less API confusion and without the extra overhead, which would solve some more important issues for me. See https://github.com/playframework/playframework/issues/5317

**Comment by wsargent** [comment]
I think this best handled by turning the JSON into a string, rather than doing it in the body parser:

``` scala
class MyController extends Controller  {
   def index = Action { implicit request =>
      request.contentType match {
      case Some(MimeTypes.JSON) =>
        val json = request.body.asJson()
        val text = Json.stringify(json)
     case ... =>
    }
}

**Comment by abhijitsarkar** [comment]
@wsargent What if I wanted to verify a HMAC signature and needed the original bytes?

**Comment by schmitch** [comment]
then you can use `parse.raw`to your Controller which actually gives back a `ByteString`.

**Comment by phelps-sg** [comment]
In my case I want process data that is `x-www-form-urlencoded` but only if a signature calculated over that same data is valid.  I can't figure out a way to do this through action composition because ActionBuilder has no access to the actual body.
