### ISSUE TITLE
Update master to use latest async-http-client 2.0 RC

### ISSUE THREAD

**Issue by dotta** [playframework/playframework#5404]
Currently, the latest ahc 2.0.0 release is 2.0.0-RC2 (but check [here](https://github.com/AsyncHttpClient/async-http-client/releases) if the information is not outdated when you start working on this ticket). It would be great if we could upgrade the Play master codebase to it before ahc 2.0 goes final.

\cc @slandelle

**Comment by slandelle** [comment]
(disclaimer: I'm AHC's dev)

Actually, latest is currently RC2 :)

As things go for major versions, AHC2 breaks AHC1 APIs.
And sadly, changes are not properly documented atm. Please keep in mind that from my pov, AHC is "just" the HTTP client Gatling uses internally.

Upgrading Play would be a proper test to list all the changes and document a migration path. I can help there in providing guidance and answer your questions.

The bad news for Play is that I'm 100% you won't be able to retain backward compatibility.
Most of your WS APIs are designed to mirror the AHC ones, and some were definitively broken and fixed in AHC2, such as `ProxyServer`.

**Comment by dotta** [comment]
> Actually, latest is currently RC2 :)

LOL. I've updated the description. Thanks for catching the error :-)

**Comment by wsargent** [comment]
RC5 as of 12 days ago

**Comment by slandelle** [comment]
Expect RC6 by the end of the week ;-)

**Comment by wsargent** [comment]
https://github.com/AsyncHttpClient/async-http-client/releases/tag/async-http-client-project-2.0.0-RC7

**Comment by wsargent** [comment]
Okay, am ready for code review.

**Comment by slandelle** [comment]
@wsargent That went smoother than I expected, great!
