### ISSUE TITLE
Consider an error message if config file can't be found

### ISSUE THREAD

**Issue by kristian-lange** [playframework/playframework#5408]
It's one of these little mistakes everyone does every now and then. 

After starting with `activator -Dconfig.file=conf/wrongName.conf` Activator/Play doesn't give any error message that it could not load the configuration from the given file. Instead it tries to start and then follow many errors e.g. JPA missing, Guice not configured - all that would have been set up in the config.

This little error message could have saved me half a day of frustration. :(

Thanks!

**Comment by wsargent** [comment]
Hi @kristian-lange this is a feature of Typesafe Config: 

* https://github.com/typesafehub/config#standard-behavior
* https://www.playframework.com/documentation/2.5.x/ConfigFile

Play can look at the config.file and see if there's something there, but a true fix would look at all missing resources.  What we've done instead in 2.5.x is add a comment so that you can see where config is getting its information:

https://github.com/playframework/playframework/blob/master/templates/play-common/conf/application.conf#L24-L36

However, there isn't a "Debugging Configuration" page, and the above text should be included there as well.

You can also file a bug with https://github.com/typesafehub/config/issues for the underlying config.file functionality.

**Comment by kristian-lange** [comment]
Hi @wsargent!
Thank you for your advice!
Although your link to https://github.com/playframework/playframework/blob/master/templates/play-common/conf/application.conf#L24-L36 seem to be about Akka configuration.
But anyway it's an Typesafe Config issue. Play can't help here.
Thank you anyway!

**Comment by wsargent** [comment]
@kristian-lange Both Play and Akka use Typesafe Config.  The akka setting exposes the typesafe config to logging.

**Comment by kristian-lange** [comment]
@wsargent I didn't know that. Thanks again!

**Comment by mslinn** [comment]
[An issue](https://github.com/typesafehub/config/issues/121) was filed some time ago for Config, however there is nothing stopping Play from doing a check to see if the specified config file is present, and reporting or throwing if not
