### ISSUE TITLE
TestServer to assign a random default port

### ISSUE THREAD

**Issue by delitescere** [playframework/playframework#5473]
``` scala
  /**
   * The port to use for a test server. Defaults to 19001. May be configured using the system property
   * testserver.port
   */
  lazy val testServerPort = Option(System.getProperty("testserver.port")).map(_.toInt).getOrElse(19001)
```

At https://github.com/playframework/playframework/blob/master/framework/src/play-test/src/main/scala/play/api/test/Helpers.scala#L96, the default port is `19001`. This causes failures when multiple tests are running at once where the developer has not specified a port in the test code (e.g. `WithBrowser(port = 19002)`, as a `org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:19001` exception is thrown.

Whilst not eliminating the possibility of conflicts, the suggestion is to change the code to:

``` scala
  /**
   * The port to use for a test server. Defaults to a random port in the range 19000-19099. May be configured using the system property
   * testserver.port
   */
  lazy val testServerPort = Option(System.getProperty("testserver.port")).map(_.toInt).getOrElse(19000 + Random.nextInt(100))
```

Thoughts?

**Comment by gmethvin** [comment]
Another possibility is to use a static AtomicInteger that you increment each time. With a large enough port range that would provide a more deterministic way to avoid conflicts.

**Comment by delitescere** [comment]
That doesn't take into account ports that are bound by non-Play apps :)

**Comment by gmethvin** [comment]
@delitescere Neither scheme really takes into account non-Play apps.

My thought was that with a sequential scheme that wraps around, you could almost guarantee that tests running in the same JVM would not interfere with one another. If you have 100 ports, you'd only have a problem if you start 100 servers in series and server 0 and server 100 both want to run at the same time.

**Comment by delitescere** [comment]
That's probabilistically true for a random number, too, especially if test 0 happens to run longer than any of the tests 1 through 98, which is a 1-in-2 chance of being true :)

I considered taking into account non-Play apps, which can be done with an appropriate exception handling at port-binding time, but that's in a different place to the port number selection, so I wanted to solve the main problem first, and doing so without contributing to more global mutable state within Play.

**Comment by gmethvin** [comment]
@delitescere Since there is no universal solution to this, why not just extend the trait and override the testServerPort yourself? That way you can use any scheme you want.

**Comment by jroper** [comment]
There is a better solution that I'd like to gradually move to, and that we already use in many parts of Play's test.

When you use a port number of `0`, that says to the socket API "choose a free ephemeral port".  This is the normal case when you make a client connection - you specify the remote port, but you say that the local port is 0, and then the OS assigns are free port (which for TCP is defined by any port that isn't already being used to talk to that remote ip/port) to use for that connection.  But, you can also use it when binding a server socket.  After you've bound the server socket, you can then ask the socket API what port it's bound to.

An example of doing this can be shown here:

https://www.playframework.com/documentation/2.4.x/ScalaTestingWebServiceClients

Play's `Server` API will use port 0 by default:

https://github.com/playframework/playframework/blob/master/framework/src/play-server/src/main/scala/play/core/server/Server.scala#L139

And then it passes the port that was chosen to the callback.  I just haven't got around to making all Play's test APIs use this yet.  You can consider this server api the new way of doing things, and favour using it where possible in your own tests.  My thought for the long term plan for `play-test` is actually to deprecate it, if Play's APIs are so complex that you need helpers to write tests to use them, then that should be fixed by improving the APIs.

**Comment by delitescere** [comment]
Thanks @jroper that is the best solution. :100: Looking forward to it in the The Next.

**Comment by gmethvin** [comment]
@jroper I wish I had thought of that earlier. Obviously the best solution. We can close this once we update all the test APIs.

**Comment by virusdave** [comment]
Any updates on this?  I started the "use an ephemeral port by using 0" approach but i don't want to go far down the rabbit hole if this is nearing completion already.

**Comment by mkurz** [comment]
Since I ran into a problem in the play-samples (https://github.com/playframework/play-samples/pull/176) I am very tempted to finally set the default port in tests to random (=0). Also need to change the docs (mentioned in #11173

Someone wants to provide a pull request?

**Comment by mkurz** [comment]
Again, when working on scalatestplus-play (https://github.com/playframework/scalatestplus-play/pull/373), I ran into problems regarding the default port number for tests. In Play 2.9 M2, because of #11173, the port by default changed to 19001 (instead of being random) when using `DefaultTestServerFactory`:
https://github.com/playframework/playframework/blob/21339e6ec98265c62b1e3d0641bb35e5d466e796/testkit/play-test/src/main/scala/play/api/test/Helpers.scala#L142
Now when running tests in parallel, of course some fail because the port 19001 is already in use. Now that is a problem of course and will break apps/tests.

What's interesting is: As a workaround I tried to set `-Dtestserver.port=0`, trying to restore the old behaviour. But that caused other problems... Now the tests which failed launched on random ports, like in Play 2.8.x. However there exist other tests that read the [testport variable](https://github.com/playframework/scalatestplus-play/blob/9e4ccaa625fd633703fcc144c5cadb539ff952ab/module/src/main/scala/org/scalatestplus/play/MixedFixtures.scala#L266) when trying to [access](https://github.com/playframework/scalatestplus-play/blob/9e4ccaa625fd633703fcc144c5cadb539ff952ab/module/src/test/scala/org/scalatestplus/play/examples/guice/mixedfixtures/ExampleSpec.scala#L52) urls on a launched testserver. Now that variable is set to 0 now (since it was overriden by the java property) not the port that was actually choosen by the OS... So the tests are unable to access an url on the launched test server...
As a workaround I didn't set the Java property but "fixed" the `DefaultTestServerFactory` itself, restoring old 2.8 behaviour, so the variable keeps returning 19001, but the `DefaultTestServerFactory` starts on random ports: https://github.com/playframework/scalatestplus-play/pull/373/commits/cfb517bf09fe0f3ed6ac717d35e333d847d684e0
I had to [do the same in play-samples](https://github.com/playframework/play-samples/commit/23e4c2be11c5bae676a01d858513a60dec7e58ae) already.

So I think the solution is that the `testServerPort` should be set to `0` (`....getOrElse(0)`) by default to use random ports. But we have to make sure that the apis to accesss the ports don't return 0 but the actual port choosen by the OS.

**Note for scalatestplus-play**: The code that needs to be fixed is inside `MixedFixtures`, starting [here](https://github.com/playframework/scalatestplus-play/blob/9e4ccaa625fd633703fcc144c5cadb539ff952ab/module/src/main/scala/org/scalatestplus/play/MixedFixtures.scala#L264). I quickly tried to come up with something [here](https://github.com/mkurz/scalatestplus-play/tree/port_problem_approach-1), but didn't finish it.
EDIT: Actually I just saw that tests that use `ServerProvider` probably should work, because the port is taken from `runningServer` instead of the port variable. I guess we have to fix `MixedFixtures` in a similiar way.

Not sure what other API's in Play + ecosystem needs to be fixed to make port 0 work correctly.

**Comment by mkurz** [comment]
Related to this issue we might want to think about if we really want to listen to the https port by default when spinning up a test server, see: https://github.com/playframework/playframework/issues/11209#issuecomment-1081091857

**Comment by mkurz** [comment]
(Kind of) related: #11179
