### ISSUE TITLE
[improvement] Java API for Akka Scheduler

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#5569]
The Akka Scheduler requires the user to use several Scala classes: `scala.concurrent.Duration`, `scala.concurrent.FiniteDuration` and `scala.concurrent.ExecutionContext`. I think we should provide a nicer to use wrapper around the Scheduler that only uses Java classes: `java.util.concurrent.TimeUnit` and `java.util.concurrent.Executor`.

i.e. change the [example in the docs](https://www.playframework.com/documentation/2.4.x/JavaAkka#Scheduling-asynchronous-tasks) from:
```
system.scheduler().scheduleOnce(
    Duration.create(10, TimeUnit.MILLISECONDS),
    () -> file.delete(),
    system.dispatcher()
);
```
to this:
```
scheduler.scheduleOnce(
   10, TimeUnit.MILLISECONDS,
    () -> file.delete(),
    executor // obtained through dependency injection
);
```

**Comment by naferx** [comment]
Please some guidance about it

**Comment by gmethvin** [comment]
It would also be nice to integrate it with the Play lifecycle so those tasks are automatically cancelled when the app shuts down (is there a situation in which you wouldn't want to do this?).

**Comment by gmethvin** [comment]
It's interesting that in Akka's scaladoc there are methods marked as "Java API" that use Scala's `FiniteDuration` type.

We could also use the `java.time.Duration` type for the Java API:
```java
system.scheduler().scheduleOnce(Duration.ofMillis(10), file::delete, executor);
```

**Comment by wsargent** [comment]
FiniteDuration is a Scala class, but it's used throughout Akka's Java's API, and that's fine in itself.  As far as the scheduler goes, you actually *want* to use the system dispatcher in this case as you want to use Akka's dedicated thread pool even if the app is loaded, to reduce system jitter.  

I don't see the need for a wrapper here given that it's an Akka, rather than a Play class.  Closing.
