### ISSUE TITLE
[Play 2.4.x] Javascript reverse router escapes "?"

### ISSUE THREAD

**Issue by BonarBeavis** [playframework/playframework#5584]
When using jQuery to make a jsonp request with the play javascript reverse router.

```javascript
jQuery.getJSON(jsRoutes.controllers.App.foo("?"), function(){});
```
The route is not:
http://localhost:9000/foo?callback=?
but:
http://localhost:9000/foo?callback=%3F

Which breaks the jsonp callback.

**Comment by gmethvin** [comment]
Hi @BonarBeavis,

This is expected behavior. The "?" is the value of a query string parameter, so special characters like ? should be escaped. The `callback=?` is a special syntax supported by jQuery which (as far as I know) is not supported directly by the JavaScript router.

There are many ways to do this and I would suggest asking on the [mailing list](https://groups.google.com/forum/#!forum/play-framework) to help find the best solution.
