### ISSUE TITLE
[Play 2.4.x] Domain is lost when a cookie is read

### ISSUE THREAD

**Issue by loicdescotte** [playframework/playframework#5590]
With a simple controller like this 

```scala
def index = Action { request =>
    val existingCookie = request.cookies.get("test")
    val cookie = existingCookie.getOrElse(Cookie("test", "justATest", domain = Some("localhost")))
    Ok(views.html.index("Your new application is ready.")).withCookies(cookie)
 }
```

When I set a cookie on localhost, manually in my browser or using a functional test, when I print `existingCookie` value, the result of the print is : `Some(Cookie(test,justATest,None,/,None,false,true))`
This cookie has no domain.

The can be reproduced by this test. The last statement fails : 

```scala
"Application should" {
  "keep cookie" in new WithApplication{
      val cookie = Cookie("test", "justATest", domain = Some("localhost"))
      val home = route(FakeRequest(GET, "/").withCookies(cookie)).get
      val responseCookie = cookies(home).get("test")
      responseCookie.map(_.value).get must contain("justATest")
      responseCookie.flatMap(_.domain) must beSome("localhost") // fails
  }
}
```

To make it work, I have reset the domain in the controller : 
```scala
Ok(views.html.index("Your new application is ready.")).withCookies(cookie.copy(domain=Some("localhost")))
```

But if the cookie is set by the controller, and not reused from the request, everything is working, without the 'copy' hack : 
```scala
 "set cookie" in new WithApplication{
      val home = route(FakeRequest(GET, "/")).get    
      val responseCookie = cookies(home).get("test")    
      responseCookie.map(_.value).get must contain("justATest")
      responseCookie.flatMap(_.domain) must beSome("localhost") // OK
  }
```

**Comment by jroper** [comment]
The reason for this is that the request [`Cookie`](https://tools.ietf.org/html/rfc6265#section-4.2) header is completely different to the response [`Set-Cookie`](https://tools.ietf.org/html/rfc6265#section-4.1) header.  The `Cookie` header just has `name=value` pairs, while the `Set-Cookie` header includes path, domain, secure and other cookie meta data.  That is to say, the browser never sends the domain/path/other meta data, only the server sends that meta data when it sets the cookie.

We use the same data object for requests and responses for convenience, but a more correct API we'd have two different data objects, a `Cookie` data object that just had a name and value, and a `SetCookie` data object that included the domain/path etc.

In your above example, when you add a `Cookie` to a request, that sets the `Cookie` header on the request, and since the `Cookie` header only contains `name=value` pairs, all the domain/path etc info is dropped, there's simply no place to put it because the `Cookie` header doesn't support it.

**Comment by loicdescotte** [comment]
Thanks for the very clear answer :)   
I thought it was a regression because the test was passing with Play 2.3.   
Maybe a bug in the FakeRequest or something related to tests in 2.3.x?
