### ISSUE TITLE
ObjectMapper not working with Jackson's Mr Bean

### ISSUE THREAD

**Issue by mancvso** [playframework/playframework#5617]
Upstream reference: https://github.com/FasterXML/jackson-modules-base/issues/5

I'm using the Play! framework in Java with an interface like

```java
public interface AbstractMsg {
	public String getValue();
}
```

And registered mapper modules at startup
```java
ObjectMapper mapper = play.libs.Json.mapper();
mapper.registerModule(new ParameterNamesModule());
mapper.registerModule(new MrBeanModule());
play.libs.Json.setObjectMapper(mapper);
```

And when trying to "materialize" the interface with JSON content
```json
{ "value" : "did it work?" }
```

I get a nice Exception
```
akka.actor.OneForOneStrategy - com.fasterxml.jackson.databind.JsonMappingException: Failed to load class 'com.fasterxml.jackson.module.mrbean.generated.models.mensajes.AbstractMsg': models/mensajes/AbstractMsg
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Failed to load class 'com.fasterxml.jackson.module.mrbean.generated.models.mensajes.AbstractMsg': models/mensajes/AbstractMsg
...
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Failed to load class 'com.fasterxml.jackson.module.mrbean.generated.models.mensajes.AbstractMsg': models/mensajes/AbstractMsg
```

I have to mention that the "materialization" on the interface is happening inside an Actor, which can run in a different thread from which the ObjectMapper and this module was instantiated.

I have tried different combinations and could not find the cause, but I suspect the class loader of the framework is not available to Jackson, but I'm only speculating.

Java: 1.8
Play: 2.4, 2.5
Module version 2.6.0, 2.6.1, 2.7.1

**Comment by jroper** [comment]
Play uses a complex classloader hierarchy in order to implement hot reloads in dev mode, anything that uses classloaders needs to use Play's classloader.  It looks like the `MrBeanModule` allows you to set this classloader by using the constructor that takes an `AbstractTypeMaterializer`, passing in one that has been constructed with the constructor that accepts a `ClassLoader`.  The classloader that you pass there must be the one that comes from `play.Environment`.  The simplest way to do this is probably to do the object mapper setup in a Play module that accepts the environment as a constructor parameter:

https://www.playframework.com/documentation/2.4.x/JavaDependencyInjection#Configurable-bindings
