### ISSUE TITLE
[2.5.0-RC1] Different headers in Test mode for Ok.sendFile

### ISSUE THREAD

**Issue by avdv** [playframework/playframework#5777]
## Play Version (2.5.x / etc)

2.5.0-RC1

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Linux claudio-think 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
openjdk version "1.8.0_74"
OpenJDK Runtime Environment (build 1.8.0_74-b02)
OpenJDK 64-Bit Server VM (build 25.74-b02, mixed mode)
```

### Expected Behavior

I would expect that a Result returned from an Action has the same headers independent from the mode. Ie.  when running my tests, I want to confirm the CONTENT_LENGTH and the CONTENT_TYPE, but cannot because the headers are missing.

This is a different behavior than with 2.4.x where this actually worked.

Running in Dev mode produces these headers:

```
Content-Disposition: inline; filename="test_en.json"
Content-Length: 12794
Content-Type: application/json
Date: Thu, 25 Feb 2016 07:43:45 GMT
X-ExampleFilter: foo
```

### Actual Behavior

In Test mode, the header are:

```
Content-Disposition: inline; filename="test_en.json"
```

### Reproducible Test Case

See #5776

**Comment by jroper** [comment]
It is the same in independent of the mode, the problem is, you're comparing apples to oranges here.

If you start the dev HTTP server and make a request, you get all the headers as shown above.  If you start the test HTTP server, and make a request (eg using the WS client), you will get exactly the same headers as shown above - it's the same in dev mode and test mode.  But in your test, you're not starting the HTTP server, so what you're doing can't be compared to dev mode, it's not an apples to applse comparison.

Invoking the the action directly, without going through the test server, you're missing a stack of processing that Play does, so of course it's going to be different.  But that doesn't mean you can't achieve what you're trying to achieve, if you want to confirm the content length, you can do (roughly) this:

```scala
val result = Await.result(myAction.apply(fakeRequest()), 5.seconds)
result.body.contentLength must beSome(12345)
```

For a more detailed discussion on why invoking the action directly shouldn't add the `Content-Length` header, see https://github.com/playframework/playframework/pull/5778#issuecomment-191145225.

**Comment by avdv** [comment]
Thanks, @jroper. Got it.
