### ISSUE TITLE
[2.5.x] WsTestClient uses deprecated WS.client factory method

### ISSUE THREAD

**Issue by kubukoz** [playframework/playframework#5833]
in `package play.api.test`

**Comment by gmethvin** [comment]
I think maybe we should just deprecate those methods and recommend everyone use `withClient`. What do you think?

**Comment by wsargent** [comment]
The methods in question are: https://github.com/playframework/playframework/blob/master/framework/src/play-ws/src/main/scala/play/api/test/WSTestClient.scala#L28

```
  def wsCall(call: Call)(implicit port: Port, client: WSClient = WS.client(play.api.Play.privateMaybeApplication.get)): WSRequest = wsUrl(call.url)

  def wsUrl(url: String)(implicit port: Port, client: WSClient = WS.client(play.api.Play.privateMaybeApplication.get)) = {
    WS.clientUrl("http://localhost:" + port + url)
  }
```

Deprecating these methods is a good idea, but using withClient is very expensive because it creates and destroys an ActorSystem, so it's slower than it needs to be, and it also has non-standard behavior -- it's not quite the same thing as `app.injector.instanceOf[WSClient]` for example.

**Comment by gmethvin** [comment]
You're right @wsargent; we probably want to encourage re-use of the same WSClient if possible. An easy solution is to deprecate those and have another set of methods that take WSClient as the first explicit argument.

Another alternative is to create extension methods for WSClient so you can call `ws.wsCall(call)`.

**Comment by cchantep** [comment]
Is that still pending after the recent deprecation/cleanup

**Comment by wsargent** [comment]
It is not.
