### ISSUE TITLE
Content type issues in play 2.5

### ISSUE THREAD

**Issue by mriehl** [playframework/playframework#5873]
### Play Version

2.5.0

### API

scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

`Linux isdeblnnl084 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
```

### Library Dependencies

Specs2

### Expected Behavior

1. I have a controller that sets `.withHeaders("Content-Type" → "text/csv")` on the result
2. I have a test that creates a request on this controller, using the play test API:
```scala
val response: Future[Result] = route(FakeRequest(GET, routes.MyController.test.url)).get
```
3. I assert that the content type is the value I set, which should work.
```scala
contentType(response) must beSome("text/csv")
```

### Actual Behavior

The content type is `text/plain`, according to the assertion. Looking at the implementation of `contentType`, I found out that:

* `result.body.contentType` is set to `text/plain` with UTF-8 charset.
* In `result.header.headers` there is a content type header and it is set to `text/csv`

Why is `contentType()` not working for me?

**Comment by gmethvin** [comment]
Basically the `result.body.contentType` property is getting the "native" content type of the `HttpEntity` being sent. You can override this using the `Result#as(contentType: String)` method. Setting the headers manually doesn't work because the `withHeaders` doesn't (and probably shouldn't) have any special logic for translating headers to properties of the `HttpEntity`.

I suppose the test helper does violate your expectations, but Play doesn't really intend for you to set the content type manually as a header. By keeping the content type on the `HttpEntity`, we make sure the content type and the content cannot easily get out of sync.

So I would recommend either using `.as(contentType)` or perhaps creating a `Writeable` for your CSV type that takes care of setting the right content type on the `HttpEntity`, instead of just converting it to a string.

Once Play moves to a more type-safe header scheme, it should be easier to have a more consistent API in this regard.

**Comment by mriehl** [comment]
Wow, that was fast. Thanks a lot. Using `as` works for me, closing this issue.
