### ISSUE TITLE
Update I18N docs to not use deprecated methods

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#5966]
https://www.playframework.com/documentation/2.5.x/JavaI18N#Externalizing-messages still uses `Messages.get`.

**Comment by almothafar** [comment]
Any solution for this, i could use before document updating.

Messages seems could not injected too.

**Comment by marcospereira** [comment]
@almothafar you must inject `MessagesApi` instead.

**Comment by almothafar** [comment]
@marcospereira  this one : https://www.playframework.com/documentation/2.5.x/api/java/index.html ?
there is no at method, and the get need Lang, need to inject that ?

**Comment by marcospereira** [comment]
@almothafar This one:

https://www.playframework.com/documentation/2.5.x/api/java/play/i18n/MessagesApi.html

This could be injected and used like this:

```java
public MyController extends Controller {

    private final MessagesApi messagesApi;

    @Inject
    public MyController(MessagesApi messagesApi) {
        this.messagesApi = messagesApi;
    }

    public Result someAction() {
        play.i18n.Lang lang = Http.Context.current().lang();
        String msg = messagesApi.get(lang, "my.message.key");
        return ok(msg);
    }
}
```

See Lang docs too: https://www.playframework.com/documentation/2.5.x/api/java/play/i18n/Lang.html

**Comment by timscarborough** [comment]
Instead of passing in the language to the MessagesAPI.get function, I got the Messages object using the preferred language like so:

`Messages messages = messagesApi.preferred(request());
messages.at("my.message.key");`

**Comment by almothafar** [comment]
The old way was get the language inside by default : 

> The current language is found by looking at the lang field in the current Context. If there’s no current Context then the default language is used.

Wonder why I need to do that now? and is this work with something like service layer that i made, not in controller, just something between entities and controllers, because I tried to get something from request() before and I just have to pass it from controller.

Inside my service I throw some custom exceptions e.x: "BusinessException" , "ApplicationException", and i get message because in case its "BusinessException" the controller will return that fail message to view (that I use ionic for mobile, and angular for web).

**Comment by almothafar** [comment]
I just want to say i have problem with new API, not sure if I have to write it here, but when I use ActorSystem and then `system.scheduler()` and inside that method a service that use messages Api I get :

`java.lang.RuntimeException: There is no HTTP Context available from here.`

**Comment by franzgranlund** [comment]
I have a project with tons of templates, containing tons of `Messages.get("the_string")`. What is the correct way to replace the deprecated methods? Do I need to pass a `Messages` object from `messagesApi.preferred(request())` to all my templates?

**Comment by almothafar** [comment]
@franzgranlund for me I created a util class with method:

```
@Inject
private MessagesApi messagesApi;

public String getMessage(String key, Object... args) {
   return messagesApi.get(Lang.defaultLang(), key, args);
 }
```

And i call this method in my class with something like:

```
@Inject
AppUtils appUtils;

```
then `appUtils.getMessage("KEY"); `

**Comment by franzgranlund** [comment]
@almothafar Thank you for your suggestion, but that doesn't help me with my `Messages.get()` in the twirl templates I think. I would have to pass the instance to the template as a parameter.

I noticed I could get an instance of `Messages` in the templates using `ctx().messages().at("hello")`. but I'm not sure that it is recommended to do so, or?

**Comment by wsargent** [comment]
@franzgranlund we're working on this: 

https://github.com/playframework/playframework/pull/6438

It'd be great to get your feedback on how the Java API should look -- there's nothing like an actual user to provide feedback on APIs.

As far as designs go, I've been using a wrapped request for the messages in the past:

https://github.com/playframework/play-rest-api/blob/master/app/post/PostAction.scala

And since Twirl 1.2.0 has come out with injectable templates, you can upgrade:

addSbtPlugin("com.typesafe.sbt" % "sbt-twirl" % "1.2.0")

You should add the @Inject annotation to the constructor of the generated template classes by adding this to build.sbt:

TwirlKeys.constructorAnnotations += "@javax.inject.Inject()"

And pull the template from dependency injection:

``` java
public class MyController {
    @Inject
    public MyController(views.html.index template) {
       template.render(ctx().request());
    }
}
```

with the template defined as:

```
@this(messagesApi: MessagesApi)

@()(implicit request: Request[_])
```

**Comment by franzgranlund** [comment]
@wsargent Thank you for your help. Nice to see that you guys are working on it. 

As for feedback, I think that the original way, just using `Messages.get()` directly in the templates is by far the easiest and most straight forward from a user perspective. With methods to override if needed for another language, like `Messages.getByLang(lang, string)` or similar. One should bind what instance/class to use for `Messages` in `Modules.java`. 

But until this is resolved, and there actually was a solution to this, wouldn't it be best just to remove the deprecated flag from the `Messages.get()` in the API? I mean, it is working, the documentation says to use it and there isn't any other good way to do it.

I'm sorry my feedback might be a bit naive, since I don't fully grep what plans there are for templates, MessagesAPI and DI etc. =)

**Comment by wsargent** [comment]
@franzgranlund Ah, sorry, I assumed you wanted an injected MessagesApi and didn't want `ctx.messages.at`.  Yes, you can do that -- in fact, anything in `Http.Context.Implicit` is automatically imported into a template, so you don't need the `ctx` in front of it:

https://github.com/playframework/playframework/blob/2.5.x/framework/src/play/src/main/java/play/mvc/Http.java#L347

```
@messages.at("hello.world")
```

**Comment by franzgranlund** [comment]
@wsargent Nice! Thank you very much!
