### ISSUE TITLE
play2.5.1 no response every 5 hous

### ISSUE THREAD

**Issue by Z-starts** [playframework/playframework#6016]
@jkutner hi,i have a problem about play,my application will no response every 5 hours,I dont know how to fix it ,any one help me?thanks a lot!!!
![7e v42yz 7pnyd g qc4nkn](https://cloud.githubusercontent.com/assets/1948235/14415155/8e57a636-ffce-11e5-9323-a306c63acfbc.png)

**Comment by marcospereira** [comment]
Hello @Z-starts,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

Also, since you specifically citing @jkutner here, maybe you should get in contact with Heroku support.

**Comment by Z-starts** [comment]
ok

**Comment by Z-starts** [comment]
anyone help me!!! thanks a lot
https://groups.google.com/forum/#!msg/play-framework/vMGdTKdgX48/OXE5OJPZJAAJ
