### ISSUE TITLE
WSRequest withBody should perform case-insensitive header check

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#6057]
Play Version 2.5.2

We have a node.js based client to a play application that performs load balancing. Headers coming in from the node app seem to be transformed to lowercase:
https://github.com/nodejs/node-v0.x-archive/issues/1954
And as https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html prescribes header names should be handled case-insensitive.

The `WSRequest.withBody[T](body: T)(implicit wrt: Writeable[T])` call does a case sensitive check for the the `Content-Type` header an as a result we end up with 2 Content-Type headers: `Content-Type` and `content-type`.

I guess a review for more of these kinds of errors could yield some more bugs...

**Comment by wsargent** [comment]
Hi @francisdb can you provide a repeatable test case (either as a JUnit / Scalatest case or as a public github project) that we can look at?

Also, can you provide the information specified in the Play Issue Template (Platform version, JDK, Scala / Java API etc)?

**Comment by gmethvin** [comment]
@wsargent I just tried modifying some of the `Content-Type` headers in `AhcWSSpec` to lowercase, and it triggers the bug.

**Comment by gmethvin** [comment]
Also one of the tests is wrong: https://github.com/playframework/playframework/blob/master/framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala#L210

Both `Content-Type` headers are sent (regardless of the case), but the test only gets the first one in the list. This is unsurprising, since `withHeaders` is a generic mechanism that supports multiple header values per key.

**Comment by francisdb** [comment]
This is a reproducer:

```scala
    val req = ws.url("http://localhost")
      .withMethod("POST")
      .withHeaders("content-type" -> "application/json")
      .withBody("{}")

    req.headers.foreach(println)
    // (content-type,List(application/json))
    // (Content-Type,List(text/plain; charset=utf-8))
```

the second header should not have been added

**Comment by francisdb** [comment]
@gmethvin do I understand correctly that with this change headers.contains("Content-Type") will now do a case-insensitive check?

**Comment by gmethvin** [comment]
Yes, the code you wrote above should work as expected, and in general keys in the map will be compared case insensitively.

**Comment by rajeshetty** [comment]
We are on 2.3.x and have similar issue where our nodejs client sending headers in a case-insensitive fashion which causes us our platform code (play 2.3.x) to fail since its looking for case-sensitive headers. We can change that by turning header names that we are looking into a right case. But my question is how can we have Play 2.3.x itself return headers in a case-insensitive fashion , is there any way to do that inside Http.java class or in the implementation of request header?

**Comment by rajeshetty** [comment]
here is what I have to do in our code to hack it.

`Map<String, String[]> headersCIS = new TreeMap<>((Comparator<String>) String::compareToIgnoreCase);
`headersCIS.putAll(getCurrentRequest().headers());

This will solve the problem, but now the issue is I'm doing this on every single incoming call to turn all request headers in to case insensitive compartor, so that .get() or .containsKey() call on the map would actually be case insensitive. 

It would be great if this happened inside request headers creation inside play framework itself. 

Any thoughts ?
