### ISSUE TITLE
[2.5.x][Logging] Application doesn't pick up conf/logback.xml

### ISSUE THREAD

**Issue by manuelkiessling** [playframework/playframework#6120]
### Play Version (2.5.x / etc)
2.5.3

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Mac OS 10.11.4

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

### Expected Behavior
Honor `application.log` file path change in `conf/logback.xml`.

I've put my own `logback.xml` file into folder `conf/`. I've changed the line that defines the file output path to `application2.log` (see https://github.com/manuelkiessling/play25-logback-issue/blob/master/conf/logback.xml#L6).

According to https://www.playframework.com/documentation/2.5.x/SettingsLogger, I'd expect the change to be picked up automatically.

When I start the server via `sbt`, then `run`, then opening `http://localhost:9000`, I expect the log messages to be written to file `logs/application2.log`.

### Actual Behavior
Messages are still written to file `logs/application.log`.

### Reproducible Test Case
Clone https://github.com/manuelkiessling/play25-logback-issue, `sbt`, `run`, open `http://localhost:9000` in browser, inspect folder `logs`.

**Comment by manuelkiessling** [comment]
Never mind, adding `LoggerConfigurator(context.environment.classLoader).foreach { _.configure(context.environment) }` to the `load` method of my dedicated application loader, as mentioned in https://www.playframework.com/documentation/2.5.x/Migration25#Logging, fixed it.

**Comment by sleshJdev** [comment]
Hi!
I faced same problem and  https://www.playframework.com/documentation/2.5.x/Migration25#Logging didn't help me. I did following loader to make logger configuration:

`class SimpleApplicationLoader extends ApplicationLoader {
  override def load(context: Context): Application = {
    LoggerConfigurator(context.environment.classLoader).foreach {
      _.configure(context.environment)
    }
    new GuiceApplicationLoader().load(context)
  }
}`  

Play picked SimpleApplicationLoader, because I can debug it.

But logging still doesn't pick up conf/logback.xml ... When I downgraded to play 2.4.2 it works correct. 
My config: play: '2.5.8', scala: '2.11', java: '1.8'. Any help will be great. Thanks for advance!

**Comment by marcospereira** [comment]
@sleshJdev can you create a reproducible test case/project for this problem?

**Comment by sleshJdev** [comment]
@marcospereira yeah, [here is](https://github.com/sleshJdev/imaster/tree/log-fixing) branch I restored  configuration with  nonworking logging. Could you please pull that branch, after it you should  
1. execute `gradle runapi`
2. exucte request using curl `curl -i -X GET http://localhost:9000/api/log/test-log-message-here` 

In the LogController is a couple log lines with debug and info levels. These log message are always displaying in the log regardless of logback.xml config changes.  
To do logging I use extra dependencies represented by logback-core, logback-classic, slf4j-nop, because I cannot use logging of play framework out of the box as described [here](https://discuss.gradle.org/t/gradle-play-plugin-doesnt-add-some-packages-of-play-framework/21056?u=sleshjdev)
