### ISSUE TITLE
Injector.instanceOf[A] fails to resolve parameterized types

### ISSUE THREAD

**Issue by mysticfall** [playframework/playframework#6174]
### Play Version (2.5.x / etc)
2.5.3

### The Problem

For instance, if we bind `Sihlouette[A]` as:
```scala
bind[Sihlouette[BearerTokenEnv]].to[SihlouetteProvider[BearerTokenEnv]]
```
`injector.instanceOf[Sihlouette[BearerTokenEnv]]` fails with the message, _"No implementation for com.mohiva.play.silhouette.api.Silhouette was bound."_, while the underlying Guice injector can resolve the bound service properly with the help of `TypeLiteral` (as explained in [Guice Faq](https://github.com/google/guice/wiki/FrequentlyAskedQuestions#how-to-inject-class-with-generic-type)) :
```scala
injector.findBindingsByType(new TypeLiteral[Silhouette[BearerTokenEnv]]() {})
```
Even this problem does not manifest in resolving constructor arguments of DI managed services, as it is processed internally by Guice API, it can still make writing unit tests much more difficult if it involves obtaining a reference to a parameterized service (like it is the case with Sihlouette API).

**Comment by gmethvin** [comment]
I don't think the Play injector/binding library was designed to support that. It could be added, but I think some of the motivation was to support the lowest common denominator of DI libraries. I'm not sure if this is an actual problem right now, but if there were DI libraries that didn't support binding parameterized types, the Play bindings would no longer be compatible.

I think maybe the real solution to your problem is to use the Guice injector instead of the Play injector in your tests. Our documentation and testing libraries like scalatestplus-play should probably make that easier to do though.

**Comment by cchantep** [comment]
Could be first discussed on the [Mailing list](https://groups.google.com/forum/m/#!forum/play-framework).

**Comment by EnverOsmanov** [comment]
@mysticfall Did you resolve this issue somehow?
This one
```Scala
bind[Sihlouette[BearerTokenEnv]].to[SihlouetteProvider[BearerTokenEnv]]
``` 
works for me when I extend my module with `import net.codingwell.scalaguice.ScalaModule`.
Still I couldn't handle this in unit tests, so I just create my own traits without type parameters:
```Scala
trait SilhouetteEnv extends Silhouette[DefaultEnv]
```

**Comment by cchantep** [comment]
Please use the [Mailing List](https://groups.google.com/forum/m/#!forum/play-framework)
