### ISSUE TITLE
play.akka.config doesn't work as documented

### ISSUE THREAD

**Issue by gmethvin** [playframework/playframework#6183]
The [documentation](https://www.playframework.com/documentation/2.5.x/ScalaAkka#Changing-configuration-prefix) on setting a custom config prefix for Akka seems to indicate that setting `play.akka.config = "my-akka"` will allow you to use `my-akka` in place of the `akka` key to configure your actor system. Instead, this is just used as the root of the configuration passed to the ActorSystem, so Akka will look for an `akka` key inside that. So you need to use `my-akka.akka` instead.

The relevant code is https://github.com/playframework/playframework/blob/2.5.3/framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala#L293.

Also the documentation fails to make it clear that the configuration will fall back to the root configuration defined in the `akka` key.

**Comment by patriknw** [comment]
I just run in to this when investigating why the Lightbend Config Checker is confused by the configuration of Lagom systems. I agree, that the [documentation](https://www.playframework.com/documentation/2.8.x/JavaAkka#Configuration) is wrong.

I would also suggest that we remove this line when default "akka" is used as `play.akka.config`:

https://github.com/playframework/playframework/blob/eede96629f260d5c2a9c361adbaa4a271b456fde/core/play/src/main/scala/play/api/libs/concurrent/Akka.scala#L220

Otherwise the full configuration ends up in a structure like:

```
actor {
}
cluster {
}
akka {
  actor {
  }
  cluster {
  }
}
```

**Comment by mkurz** [comment]
@gmethvin

> Also the documentation fails to make it clear that the configuration will fall back to the root configuration defined in the `akka` key.

I had a look at this and to be honest I don't know why there even is a fallback. I mean does that even make sense? [The docs say](https://www.playframework.com/documentation/2.8.x/JavaAkka#Changing-configuration-prefix):

> In case you want to use the `akka.*` settings for another Akka actor system, you can tell Play to load its Akka settings from another location.

So clearly if I set `play.akka.config = "my-akka"` I do not want to use the settings from `akka.*`, which I want to use for a completly different actor system, so why should we fall back to it? I would expect to have two totally different actorsystems. 
I think the fallback can even cause problems: If I change something in the `akka.*` config suddenly also the actorsystem defined in `my-akka.akka.*` will be effected (if it does not override the changed key anyway).
IMHO having both, the setting `play.akka.config = "my-akka"` _and_ the fallback, does not really make sense...
