### ISSUE TITLE
Bug: default charset utf-8 not set the same way as read

### ISSUE THREAD

**Issue by ideadapt** [playframework/playframework#6280]
### Play Version (2.5.x / etc)
Play 2.5.4

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

OSX Yosemite

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

### Library Dependencies

-

### Expected Behavior

1. Controller returns `Results.ok(someJSONNode);`
2. In my functional test: `assertThat(result.charset().get()).isEqualTo("utf-8");`
3. Assertion success

### Actual Behavior

1. Assertion fails with `java.util.NoSuchElementException: No value present`

That is because .get() tries to access an empty Optional value.

### Reproducible Test Case

-

I think that is because in StatusHeader.java:344 you set `Optional.of("application/json;charset=" + charset)`, but in Result.java you check against `if (h.contains("; charset=")) {`. There is a blank character in front of charset, which is missing in the set value.

This issue seems to be related to https://github.com/playframework/playframework/issues/5873

**Comment by marcospereira** [comment]
Hi @ideadapt, first of all, thanks for your time to find and report the problem. Do you mind submitting a pull request to fix this problem?

**Comment by gmethvin** [comment]
@ideadapt I do think we should fix in the way you describe this for the general case, but actually there is another bug: the charset parameter actually doesn't mean anything for `application/json`, and the JSON spec requires all responses to be Unicode.

JSON parsers are supposed to detect which unicode charset it is (UTF-8, UTF-16, etc.) based on the first four octets. So by specifying a charset like ISO-8859-1 in `StatusHeader#sendJson` you can actually create an incorrect JSON response, since a conforming parser would completely ignore the charset.

**Comment by gmethvin** [comment]
I created a new issue for the JSON problem: #6282.
