### ISSUE TITLE
WSResponse.asXml() not work with no UTF-8 encoding

### ISSUE THREAD

**Issue by guofengzh** [playframework/playframework#6316]
I use WSClient to access a remote service. I got the following response:

Transfer-Encoding: chunked
Content-Type: application/xml;charset=euc-kr

When I use
     Document doc = response.asXml() ;
for this resposne, I got:

application - org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 81; Invalid byte 1 of 1-byte UTF-8 sequence.
...
Caused by: org.xml.sax.SAXParseException: Invalid byte 1 of 1-byte UTF-8 sequence.
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at play.libs.XML.fromInputSource(XML.java:76)
        at play.libs.XML.fromInputStream(XML.java:56)
        at play.libs.ws.ahc.AhcWSResponse.asXml(AhcWSResponse.java:127)
 
It is right that at column 81 starting the Korean character.

If I use response.getBody() to get the string representation, and then pass the string to Jaxb unmarshall, everything works as exptected.

**Comment by guofengzh** [comment]
I use Play 2.5.4, Java 8

**Comment by gmethvin** [comment]
The bug is that the charset is [hard-coded to UTF-8](https://github.com/playframework/playframework/blob/2.5.4/framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSResponse.java#L127).

This bug is not present in the [Scala API](https://github.com/playframework/playframework/blob/2.5.4/framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala#L533), since it reads directly from the parsed  body, which does take into account the charset properly.
