### ISSUE TITLE
Unable to set the ObjectMapper (Play 2.5)

### ISSUE THREAD

**Issue by agasvina** [playframework/playframework#6318]
I've tried to update the ObjectMapper for the play 2.5 built-in JSon by following the step in the [documentation](https://www.playframework.com/documentation/2.5.x/JavaJsonActions#Advanced-usage). However, it won't update the ObjectMapper accordingly. I assume that the `ObjectMapperModule.class` override my configuration. 

Kindly advice.

**Comment by marcospereira** [comment]
Hello @agasvina,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

About this problem, did you configured [your custom application loader](https://www.playframework.com/documentation/2.5.x/JavaDependencyInjection#Advanced:-Extending-the-GuiceApplicationLoader)?

**Comment by agasvina** [comment]
@marcospereira, I think this can be considered as an issue. 
First of all, I've created an `ObjectMapperApplicationLoader` as mentioned in the documentation. 

```
public class ObjectMapperApplicationLoader extends GuiceApplicationLoader {
    @Override
    public GuiceApplicationBuilder builder(Context context) {
         DateFormat dateFormat = new SimpleDateFormat(dateFormat);
         dateFormat.setTimeZone(TimeZone.getTimeZone(timezone));
         ObjectMapper mapper = Json.newDefaultMapper()
         mapper.setDateFormat(dateFormat);
        Json.setObjectMapper(mapper);
        return super.builder(context);
    }
}
```

I also add the loader configuration in **application.conf**:
`play.application.loader = "ObjectMapperApplicationLoader"`

I have this in my controller:
`return ok(Json.toJson(result));`


However, the date is not returned with the correct format.

**Comment by schmitch** [comment]
Actually you could just create a Guice "Module" which binds it i.e.:

```java
public class MyModule extends AbstractModule {

public void configure() {
bind(BindMapper.class).asEagerSingleton();
}

}

@Singleton
public class BindMapper {
public BindMapper() {
// your mapper code
Json.setObjectMapper(mapper);
}

}
```

**Comment by agasvina** [comment]
I did implement that @schmitch. However, why does my application loader is not properly loaded?

**Comment by gmethvin** [comment]
Okay. I'm pretty sure this is an issue but with the documentation. You need to disable the default object mapper module:
```
play.modules.disabled += "play.core.ObjectMapperModule"
```

Also, as @schmitch says you can do it as a Guice module, but it still will only work properly after disabling the built-in one. Actually, it might work (I haven't checked) if that module happens to be initialized after the default one, but that's not something we should count on.

I think it would be better to show the module in the documentation instead of the custom ApplicationLoader. Essentially you'd write your own Guice version of [ObjectMapperModule](https://github.com/playframework/playframework/blob/2.5.x/framework/src/play-java/src/main/scala/play/core/ObjectMapperModule.scala). This is also nice as it binds ObjectMapper like the default module does, which is useful to have, but more importantly Guice will make sure you only have one ObjectMapper bound.

I'm reopening since we still need to update the docs.
