### ISSUE TITLE
[scala-doc] Update the document of "Streaming HTTP responses"  to use Akka Stream's API

### ISSUE THREAD

**Issue by joymufeng** [playframework/playframework#6370]
### Play Version (2.5.x / etc)

2.5.4
### API (Scala / Java / Neither / Both)

Scala
### Expected Behavior

Update this document [Streaming HTTP responses](https://www.playframework.com/documentation/2.5.x/ScalaStream) to use new akka stream's API.
### Actual Behavior

This document page is currently written using the old Enumerator/Iteratee API.

**Comment by arlowhite** [comment]
I'm a Java developer new to Play and Scala; just starting with 2.5. (I'm programming in Scala)

I have the simplest kind of JSON controller method working with:
`Ok(Json.toJson(result))`

But I was interested and curious about using Streams, which is supposed to be one of Play's strengths. As I understand it, a stream design should be more efficient than Json.toJson(). However, I've been frustrated by the documentation on Streams.

I want Play to stream out JSON from an SQL query.
**Chunked responses** seemed like a good approach, but Ok.chunked is deprecated as this doc issue highlights.

However, I hoped I could figure out the new Play 2.5 way of doing things by reading about the new classes.

https://www.playframework.com/documentation/2.5.x/StreamsMigration25
Seems to indicate I should somehow use HttpEntity.Chunked, or...

> If you choose to migrate to the new API, you can create a chunked result by calling the chunked method on a StatusHeader object and providing an Akka Streams Source object for the stream of chunks.

So then I searched for **StatusHeader**
But there aren't any search results on playframework.com besides the migration guides.

I looked at the StatusHeader source code, and noticed the **sendJson** method. However, searching for that didn't yield anything helpful. I'm not sure how to use it.

It seems like these are used by constructing a Result, which I've read about here:
https://www.playframework.com/documentation/2.5.x/ScalaActions#Results
However, there isn't any example of constructing a Result with an Akka Source on this page. :(

So I still have no idea in what context I can call the "chunked method on a StatusHeader object"
Ok().chunked??? Ok(Source).chunked??? I'm just not finding the examples.

**Akka docs are overwhelming!**
> Akka Streams provides a good balance between safety, simplicity and familiarity.

Oh man is this not true for Java developers coming to Play for the first time.
I started to read the Akka docs, but the Quick Start is ridiculously verbose.
http://doc.akka.io/docs/akka/2.4.4/scala/stream/stream-quickstart.html#stream-quickstart-scala
Do I really need to learn about the concept of "Back-pressure" the first time I learn about Akka?

There are about 20 possible Akka dependencies listed here:
http://akka.io/docs/

http://doc.akka.io/docs/akka/2.4/scala.html has 9 major sections, each with about 10 articles.

This makes me want to run away from Akka as fast as I can. It makes RxJS Observables look easy.

**Conclusion**

I like Play and Scala and still want to use them, but if you're going to recommend Akka I think the Play documentation really needs to ease new developers into using Akka. Don't tell them to read the Akka docs because their heads will explode.

**Action Items**

- [Actions, Controllers and Results](https://www.playframework.com/documentation/2.5.x/ScalaActions) is a bit light on examples. I don't understand how the StatusHeader class is involved or how to compose more advanced Results. There are only a few scattered examples on other pages.
- [JavaStream](https://www.playframework.com/documentation/2.5.x/JavaStream) has an Akka Source example, but [ScalaStream](https://www.playframework.com/documentation/2.5.x/ScalaStream) does not.
- Basic to intermediate examples of Akka Stream composition with web developers in mind. i.e. Cool things you can do with Streams or where Streams are the best solution.

For example. I want to run an SQL Anorm query, then filter out certain objects, then stream it out as chunked JSON.

**Comment by schmitch** [comment]
> But I was interested and curious about using Streams, which is supposed to be one of Play's 
> strengths. As I understand it, a stream design should be more efficient than Json.toJson().

Actually Json can't be streamed "directly".
If you look at the akka-http page:

> http://doc.akka.io/docs/akka/2.4/scala/http/routing-dsl/source-streaming-support.html#json-streaming

It's more like that you can stream multiple objects over a single wire. Like the elasticsearch Bulk:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html

Where you wrap your JsValue in a Outer JsArray object or have a common denominator. The problem with Streaming Json, is that it's not a format to Stream since you need the whole payload to finally decode it.


Also `Ok.chunked` Takes a `Source[ByteString, Any]` so you can use it with akka-streams. There is no need to go to the `HttpEntity` level.

**Comment by arlowhite** [comment]
@schmitch  Thanks for the links. Sorry for the long frustrated post above, but hopefully it helped in some way.

Once I come-up with a solution, I'll see if I can help contribute to the documentation in some way.

**Comment by wsargent** [comment]
This is fixed in 2.6.x https://www.playframework.com/documentation/2.6.x/ScalaStream
