### ISSUE TITLE
Having two controllers.Assets.versioned routes causes compilation issue

### ISSUE THREAD

**Issue by ochrons** [playframework/playframework#6413]
If I have following lines in my routes file, I get template compilation errors:
```
GET     /assets/fonts/*file               controllers.Assets.versioned(path="/public/lib/font-awesome/fonts", file: Asset)
GET     /assets/*file                     controllers.Assets.versioned(path="/public", file: Asset)
```
This leads to errors like:
```
error] D:\work\scalafiddle-web\server\src\main\twirl\views\index.scala.html:16: not enough arguments for method versioned: (path: String, file: controllers.Assets.Asset)play.api.mvc.Call.
[error] Unspecified value parameter file.
[error]         <script src=@routes.Assets.versioned("javascript/gzip.js")></script>
[error]                                             ^
[error] D:\work\scalafiddle-web\server\src\main\twirl\views\index.scala.html:17: not enough arguments for method versioned: (path: String, file: controllers.Assets.Asset)play.api.mvc.Call.
[error] Unspecified value parameter file.
[error]         <link rel="stylesheet" media="screen" href=@routes.Assets.versioned("stylesheets/main.min.css") >
```

changing the first asset line in routes to following fixes the issue:
```
GET     /assets/fonts/*file               controllers.Assets.at(path="/public/lib/font-awesome/fonts", file)
GET     /assets/*file                     controllers.Assets.versioned(path="/public", file: Asset)
```

Play 2.5.3, sbt-digest 1.1.0, Windows 10

**Comment by julienrf** [comment]
The problem comes from the fact that each action must be used for exactly one endpoint (otherwise referencing the action in the reverse router becomes ambiguous).

A workaround could be to use different actions for the two endpoints:

~~~ scala
class FontsAssets(errorHandler) extends Assets(errorHandler)
~~~

~~~
GET    /assets/fonts/*file       controllers.FontsAssets.versioned(path = "/public/lib/font-awesome/fonts", file: Asset)
GET    /assets/*file             controllers.Assets.versioned(path = "/public", file: Asset)
~~~

**Comment by gmethvin** [comment]
@ochrons What behavior would you expect? There's no obvious way to resolve the ambiguity besides requiring you to pass the path parameter.

**Comment by ochrons** [comment]
Ok, I now understand why this happens, but it would be better if this error was pointed out in the `routes` file instead of at call sites.

**Comment by gmethvin** [comment]
@ochrons It makes more sense when you think of the shorter reverse routing syntax `Assets.versioned(file)` as a special case. Normally you would have to specify every parameter in the method, but since it's unambiguous in this case, we compile the reverse route to omit the first parameter. The behavior is described in here also: https://www.playframework.com/documentation/2.5.x/AssetsOverview#Reverse-routing-for-public-assets.

If we wanted the error to appear in the routes file, we'd have to make the routes not compile, which means we have to break some functionality for someone, or introduce some new syntax. If you have any ideas feel free to start a discussion on the dev mailing list.
