### ISSUE TITLE
Issue with stop hooks not being called on Guice application since 2.5.5

### ISSUE THREAD

**Issue by mikesname** [playframework/playframework#6466]
### Play Version (2.5.x / etc)

2.5.5

### API (Scala / Java / Neither / Both)

Scala / Guice

### Expected Behavior

Application stop hooks should be called.

### Actual Behavior

Since 2.5.5 (and specifically 358a38e54f626ac9750e2211992925e972e8d2b8) I'm finding that stop hooks are not getting called at all in some circumstances. It seems to involve state in the `GuiceApplicationLoader`, and `stop()` being called on a different instance of `ApplicationLifecycle` than the hooks are being added to on startup.

Removing the context lifecycle from the GuiceApplicationLoader's `defaultOverrides` [here](https://github.com/playframework/playframework/pull/6449/files#diff-9af1c36f9e100f0ce5f9917afe8bbd4fR54) seems to resolve (or at least mitigate) the issue.

This is the best I can do to make a reproducible case at the moment:

1. create a new play-scala app with the `specs2` dependency
2. inject a `CacheApi` instance into `HomeController`
3. run the following spec:

```scala
import play.api.test.{FakeRequest, PlaySpecification, WithApplicationLoader}

class MySpec extends PlaySpecification {
  sequential

  "my app" should {
    "work once" in new WithApplicationLoader() {
      val home = route(app, FakeRequest(GET, "/")).get
      status(home) must_== OK
    }

    "work twice" in new WithApplicationLoader() {
      val home = route(app, FakeRequest(GET, "/")).get
      status(home) must_== OK
    }
  }
}
```

In 2.5.4 it runs fine, in 2.5.5 it fails at runtime with cache binding errors.

**Comment by schmitch** [comment]
just a small question did this only happen in tests?

**Comment by mikesname** [comment]
It happens at run as well, at least as far as I can see.

**Comment by schmitch** [comment]
actually I tried to add a stop hook to run and it always run my stop hook, thats why I ask.

**Comment by mikesname** [comment]
Yes, I'm confused about that - I think because the specs2 `WithApplicationLoader` creates a new loader per test, whereas ScalaTests `OneAppPerTest` does not, and it seems to be related to the Guice loader (?). 

If I inject an `ApplicationLifecycle` instance into a controller and add a bunch of hooks to it, these do not get called - in 2.5.4 they do. Maybe I'm doing it wrong:

```scala
package controllers

import javax.inject._

import play.api.inject.ApplicationLifecycle
import play.api.mvc._

import scala.concurrent.Future

@Singleton
class HomeController @Inject()(applicationLifecycle: ApplicationLifecycle) extends Controller {

  applicationLifecycle.addStopHook({ () =>
    Future.successful(println("STOPPING App 1!!!"))
  })

  def index = Action {
    Ok(views.html.index("Your new application is ready."))
  }
}
```

**Comment by schmitch** [comment]
You have ({ remove the outer (

Von meinem iPhone gesendet

Am 19.08.2016 um 17:48 schrieb Mike Bryant <notifications@github.com<mailto:notifications@github.com>>:


Yes, I'm confused about that - I think because the specs2 WithApplicationLoader creates a new loader per test, whereas ScalaTests OneAppPerTest does not, and it seems to be related to the Guice loader (?).

If I inject an ApplicationLifecycle instance into a controller and add a bunch of hooks to it, these do not get called - in 2.5.4 they do. Maybe I'm doing it wrong:

package controllers

import javax.inject._

import play.api.inject.ApplicationLifecycle
import play.api.mvc._

import scala.concurrent.Future

@Singleton
class HomeController @Inject()(applicationLifecycle: ApplicationLifecycle) extends Controller {

  applicationLifecycle.addStopHook({ () =>
    Future.successful(println("STOPPING App 1!!!"))
  })

  def index = Action {
    Ok(views.html.index("Your new application is ready."))
  }
}

-

**Comment by schmitch** [comment]
I guess I at least found the bug.
It looks like it's somewhere inside the Play.stop() call:
```
  abstract class WithApplicationLoader2(applicationLoader: ApplicationLoader = new GuiceApplicationLoader(), context: ApplicationLoader.Context = ApplicationLoader.createContext(new Environment(new java.io.File("."), ApplicationLoader.getClass.getClassLoader, Mode.Test))) extends Around with Scope {
    implicit lazy val app = applicationLoader.load(context)
    def around[T: AsResult](t: => T): Result = {
      val x = Helpers.running(app)(AsResult.effectively(t))
      await(context.lifecycle.stop())
      x
    }
  }
```

This should work.

**Comment by mkurz** [comment]
If this completely breaks the stop hooks in production, shouldn't we release 2.5.6 with the fix immediately?

**Comment by lisinge** [comment]
A 2.5.6 release would be great

**Comment by mehmetakiftutuncu** [comment]
I just spent hours trying to figure out what I was doing wrong because exact same configuration was working fine with 2.5.4 in another project. Then I was told on SO about this bug. At least now I know what was the issue. :)

**Comment by mkurz** [comment]
http://stackoverflow.com/q/39102722/810109

**Comment by schmitch** [comment]
Actually this probably bad usage to send a message on stop hook or doing some work other than resource cleanup.
In a production system a stop hook will likely not be called. Since the production system in like 70% of the cases wouldn't terminate with `SIGTERM`. And `SIGKILL` or a crash won't run them and never did, but basically resources attached to the JVM will still be cleaned up (mostly), if you designed your system for that (which play did).

Still we should release a 2.5.6 soon, since it's clearly something that people rely on.

ping @gmethvin

**Comment by gpgekko** [comment]
I stumbled upon this when upgrading because all tests started failing, due
to things in a module not being cleaned. So there is a much used situation
in which applications are started and stopped often in quick succession
within a single JVM where resources do not get cleaned by GC in time to
prevent problems.

Op 23 aug. 2016 17:17 schreef "Schmitt Christian" <notifications@github.com

**Comment by gmethvin** [comment]
2.5.6 is now out; we're announcing soon

/cc @schmitch @gpgekko @mehmetakiftutuncu @lisinge
