### ISSUE TITLE
Extend Maven Support with hot-reload

### ISSUE THREAD

**Issue by jlprat** [playframework/playframework#6474]
As Play is able to be build through Maven, it would a nice feature to be able to have 'hot-reloads' the same way the Lagom team did with their `lagon:runAll` task.

# Expected Behavior
After running some maven task (for example `play:run`) a Play instance should spin up and, every time source changes, it should be compiled and then hot-reload the Play instance. 

At the end, the behavior should be quite similar to the existing `$> activator ~ run` command

**Comment by jroper** [comment]
Just some info here, this is actually is a fair bit harder in Play than Lagom, for the following reasons:

* We'd have to port the routes compiler
* Maven apps would have to configure zinc, since Play's dev mode simply won't work without incremental compilation, and Maven doesn't know what that is.
* JavaScript tooling in Maven runs *really* slowly, no incremental compilation support, so it would no longer be possible to make Play responsible for compiling client side assets. For many this isn't an issue, they can just run grunt/gulp/whatever themselves in watch mode.

**Comment by jlprat** [comment]
Regarding the last point, it's possible to run grunt/gulp/whatever scripts in specific a maven lifecycle via plugins. Given this, it could be possible to have the `play:run` task kicking in just after starting grunt/gulp/whatever in watch mode.

**Comment by cchantep** [comment]
Hi, I think this should be first discussed on the [MailingList](https://groups.google.com/forum/m/#!forum/play-framework). Best regards

**Comment by gmethvin** [comment]
I agree, let's discuss on the mailing list first. Currently we have no plans to support maven with Play but there is considerable community effort, e.g. https://github.com/play2-maven-plugin/play2-maven-plugin.
