### ISSUE TITLE
[2.5.x] Regression: Json.writes no longer handles case classes with multiple param lists

### ISSUE THREAD

**Issue by OlegYch** [playframework/playframework#6476]
### Play Version (2.5.x / etc)

2.5.5

### API (Scala / Java / Neither / Both)

Scala

### Expected Behavior

on 2.5.4
```
case class A(i: Int)(b: Int)
val aw = play.api.libs.json.Json.writes[A]
```
creates a working Writes which only takes in account the first list, consistently with eg generated toString and equals for case classes
### Actual Behavior
on 2.5.5
```
val aw = play.api.libs.json.Json.writes[A]
```
fails with 'No apply function found matching unapply parameters' message

repro: http://scastie.org/21868

**Comment by cchantep** [comment]
As said on #6435, the involved behaviour was not coherent between all the macros before, and has never been documented.

(1) It doesn't break binary or API compatibility, and the more coherent constraint is enforced as error if recompiling. 

About master, there is not for now solution to support both this case et generic case classes. This can be documented in the migration guide. More to be discussed on the MailingList rather than on this issue tracker.

About 2.5.x, the backport can be reverted, if considered (1) to be "breaking".

**Comment by OlegYch** [comment]
if you want coherent reads and writes you'd just use format, wouldn't you?

**Comment by gmethvin** [comment]
The previous behavior was never documented, and in my opinion doesn't make sense (so it's a bug). There's actually not much value I can see in using multiple parameter lists in a case class unless you were doing it specifically to take advantage of that bug.

In any case, we've already released 2.5.5. It doesn't make sense to change this undocumented behavior yet again.

**Comment by elmalto** [comment]
@gmethvin I use scaldi[http://scaldi.org/] for dependency injection and it requires implicit parameters. It would be great if we could handle this use case?

**Comment by gmethvin** [comment]
@elmalto The JSON macros are designed to be used with simple "data" classes, which is why there are such strict requirements on where they can be used. If you have to inject some state into the case class from outside for it to work properly, then it's not pure data.

Depending on what you're doing, a simple fix might be to move the implicit to the method(s) that need it instead of injecting it in the constructor.

Maybe we'll be able to introduce some more flexibility with the new configuration mechanism we're considering in 2.6.
