### ISSUE TITLE
Logging to ELK stack with logging context not possible

### ISSUE THREAD

**Issue by Skyr** [playframework/playframework#6612]
I tried pushing my logs to Elasticsearch via Logstash. With recent versions of Elasticsearch, [dots in fields have been forbidden](https://github.com/elastic/elasticsearch/pull/12068). This causes problems with the [application.home setting in LogbackLoggerConfigurator](https://github.com/playframework/playframework/blob/master/framework/src/play-logback/src/main/scala/play.api.libs.logback/LogbackLoggerConfigurator.scala#L25). If the logback context is logged as well, data cannot be stored in Elasticsearch.

Allowing dots in Elasticsearch field names again [is under discussion](https://github.com/elastic/elasticsearch/issues/15951), but in the meantime, it would be helpful to change `application.home` to e.g `application_home` in LogbackLoggerConfigurator and the default `logback.xml` files.

Play Version: 2.5.x / trunk

Elasticsearch: 2.4.1

**Comment by wsargent** [comment]
Hi @Skyr -- this sounds like a policy decision by ElasticSearch to limit what they'll accept, rather than a technical issue in Play itself.  I'm afraid this isn't something we can fix on our end -- making this change would cause inconvenience to users who are not using that version of Elasticsearch, and changing this one instance would not solve the underlying issue, because properties with dots in them are extremely common and could come from anywhere.   

Play is open source and the PlayLogback module can be disabled and/or replaced, so as a workaround you can use your own LoggerConfigurator which does not use that property setting:

* https://www.playframework.com/documentation/2.5.x/SettingsLogger#Using-a-Custom-Logging-Framework
* https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/main/scala/play/sbt/PlayLogback.scala
* https://github.com/playframework/play-log4j2

**Comment by Skyr** [comment]
Unfortunately, Play makes it very hard to work around that - as I experienced when trying to pin down that problem without modifying Play: I tried to replace LogbackLoggerConfigurator by putting a logger-configurator.properties (referencing my own class) in my application's conf directory. Unfortunately this works only in production mode, in dev mode a ClassNotFoundException is thrown (although my class was properly compiled, the class file was created in target/…).
So making the string "application.home" configurable in some way would be helpful. Otherwise, I'm open to suggestions on how to solve the ClassNotFoundException issue ;-)
