### ISSUE TITLE
Cookie API inconsistency

### ISSUE THREAD

**Issue by 0xbaadf00d** [playframework/playframework#6626]
**Play Version:** 2.5.8 with Activator 1.3.10
**API:** Java
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

```
Linux localhost.localdomain 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```
### Description

The method withMaxAge() accept Integer as **seconds** but `application.conf` use Long as **millisecond**. It could be nice if either Cookie manipulation method and `application.conf` use Long (millisecond) or Integer (second) but not a mixed usage.

```
final Cookie appsCookie = Cookie
                .builder("MY-COOK", "value")
                .withDomain("xxxxxx")
                .withPath(".")
                .withHttpOnly(true)
                .withSecure(false)
                .withMaxAge(
                    this.configuration.getLong("play.http.session.maxAge") / 1000
                )
                .build();
```

**Comment by gmethvin** [comment]
Our configuration defines `maxAge` as a duration type, so you should be able to say something like `100s`. Milliseconds are just the default duration type in config.

Similarly, the max-age property in an HTTP Cookie is defined in seconds, so our cookie model uses seconds there as well.

I think the right solution could be to accept a `Duration` rather than a `Long` here to remove any ambiguity.

**Comment by wsargent** [comment]
+1 Duration -- this has already been done in some other places (like WS)
