### ISSUE TITLE
HTTP filters are executing on the Netty thread pool

### ISSUE THREAD

**Issue by jroper** [playframework/playframework#6670]
It appears that HTTP filters are now executing on the Netty thread pool. I'm not sure if this change was intentional or not, previously we ensured that they only executed on the Akka thread pool. Executing on the Netty thread pool is potentially very dangerous for end users, since Netty 4's threading model is to assign each connection a single thread from the thread pool, and execute all operations for that connection on that thread. The thread will be assigned to many connections at once, and so blocking on this thread will mean that every other connection associated with this thread will be blocked, even if the other threads in the pool are doing nothing. This is quite prone to deadlocks, which is why we probably shouldn't expose this thread pool to end users.

**Comment by schmitch** [comment]
Doesn't this only happen in `EssentialFilter`s? I mean when implementing a `Filter` it will probably use the `ExecutionContext` of [Akka](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/Filters.scala#L44)

So basically (if I understand correctly) we should either change `DefaultHttpRequestHandler` to use the Akka thread pool for *everything* that calls user code or do it in the `PlayRequestHandler.handle` for *everything* that calls user code, right?

**Comment by gmethvin** [comment]
The issue I believe is at the Netty level we are using the trampoline execution context to actually execute the resulting action, rather than Play's default execution context. The relevant code is here: https://github.com/playframework/playframework/blob/master/framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala#L257

Actions can define their own execution context, but EssentialActions cannot, so the actual body of the action will be executed in the same thread.

In 2.4.x the logic was quite different (due to changes in Netty and the move from iteratees to Akka streams). But the important part is that we executed the actual action in Play's default execution context: https://github.com/playframework/playframework/blob/2.4.x/framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala#L210

So, I think we just need to switch the trampoline to Play's default EC in PlayRequestHandler. @jroper does that sound right?

**Comment by schmitch** [comment]
Fixed with https://github.com/playframework/playframework/pull/6673
