### ISSUE TITLE
Make custom error pages overwritable

### ISSUE THREAD

**Issue by rfuerst87** [playframework/playframework#6674]
Currently it is quite cumbersome to set up custom error pages. The only way I found was to create a custom error handler (do I miss something here?). I think it is common that you just want to have error pages in your own layout without any fancy stuff. For those cases it would be desirable to have error pages that do not need a custom error handler. Two options came into my mind:

- **Option A: Make error pages configurable:** Let's introduce a new config key, for example `play.http.defaultpages`. By default this key points to the package that contains all our default pages. Currently this would be `views.html.defaultpages`. If a different package is chosen play will then try to serve error pages defined in this custom package. If there is no view defined for a particular error, it will fall back to the default one provided by play.

- **Option B: Make views.html.defaultpages overwritable**: Similar to option A but without configuration involved. By convention you can define your own views under `/app/views/defaultpages`. On compilation our custom views and those provided by play will be merged. Custom views of course will take precedence over those provided by play.

WDYT? Any other ideas are welcome.

**Comment by gmethvin** [comment]
The main issue I see with this is it'd be easy for a user to screw up. I'm assuming the naming of the views would be by convention. So if you name your page `notfound` instead of `notFound`, it would just default to the Play error page. Since the logic is in Play's code, not yours, it's harder to see what's going wrong.

There's also not a way to do this in a type safe way with different inputs/outputs to the templates. The current "error pages" are really just Scala functions that return `Html`. If I want additional information from the app, I need to add more params and somehow pass those to the template. If I want to return a different content type, Play needs to know how to deal with that as well.

@rfuerst87 If this is a feature you want, what you can do is create a separate library that defines an `HttpErrorHandler` that behaves like this. I'd suggest doing that first before we think about adding anything to Play itself.

**Comment by rfuerst87** [comment]
Thanks for your feedback! I see your point. Indeed people can screw up, but isn't this the case for all convention over configuration frameworks? Also this is really just intended for those very basic cases. No other parameters, HTML output only. I just feel like it is a quite common use case, that people want to switch out error pages without any additional logic involved. IMHO it's rather inconvenient to create a custom error handler if I just want to change the layout on my error pages.
For more complex cases I'm totally with you. Creating a custom `HttpErrorHandler` is perfectly fine.

**Comment by shkhln** [comment]
Wait a minute, where exactly is Play 2.x.x advertised as a convention-over-configuration framework? 

Besides, it's not like `HttpErrorHandler` has any other purpose beyond error page customization. There are no basic or complex cases, there is only one specific use case.

**Comment by rfuerst87** [comment]
I was thinking a little more about this issue. Because of package name clashes having overwritable views as I suggested in Option B is probably not possible. Option A is probably a bit too complicated. Still I believe configurable error views would be a nice addition. However I certainly can live without it. Creating a small plugin as @gmethvin suggested seems like the way to go. Therefore I'm closing this. Thanks for taking care @gmethvin.
