### ISSUE TITLE
Allow setting session cookies path parameter

### ISSUE THREAD

**Issue by umbreak** [playframework/playframework#6694]
* Play Version (2.3.x)
* API Java
* Operating System (Any)
* JDK (Oracle 1.8.0_111)

The property `application.context` (changed to play.http.context in 2.4.x) is used for:
1. Setting the cookie path (as I can see in `Http.Session.CookieBaker`).
2. Setting the prefix for the routes files like explained in [StackOverflow](http://stackoverflow.com/questions/9994917/setting-a-custom-root-url-in-play-2-0#answer-10000664).

I don't know why the same property is used for both situations. 

There might be cases when we want different modules with different **prefix** and they are running under the same domain (or subdomain) so we don't want to limit the cookie to some specific path. From my understanding, route prefixes do not need to be always related with cookies path.

Since this is like that...there is a way I can intercept the response and change this path cookie parameter or that I can extend the cookie builder? Any other suggestion?

**Comment by gmethvin** [comment]
The same property is used in both situations as it's assumed that's the "base" path of your application. So it makes sure the application session should be scoped to your application, and only your application. If you had different settings for each, it would be easy to inadvertently set or unset the cookie for another application on the same domain.

Technically when the cookie is valid across applications I would consider it a distinct type of cookie from the normal Play session cookie, so it seems more appropriate to use a separate CookieBaker for that instead of using the Session.

That said, I could see some value in creating a separate setting for the session cookie, but only if it defaults to `play.http.context` if the value is `null`. Your PR is welcome if you're interested in implementing that.

**Comment by umbreak** [comment]
I did the change for the branch 2.3.x (the one which I am working right now). Can it be approved?
