### ISSUE TITLE
Upgrade documentation to point to sbt 0.13.13

### ISSUE THREAD

**Issue by wsargent** [playframework/playframework#6713]
This is a placeholder issue to say that documentation and internal builds should all reference sbt 0.13.13 (or sbt 1.0 if it comes out soon enough).

**Comment by schmitch** [comment]
Actually I guess I already changed most of them?
this repo is fully on 0.13.13 since https://github.com/playframework/playframework/commit/ab1fcf332ac4a141b726df3593464aabdd0bc96d
play-doc since https://github.com/playframework/play-doc/commit/7176e23b4436ca70984e1226fe9ec33ab778c13e
twirl since https://github.com/playframework/twirl/commit/8e179734e12b4e59ce5304a0224da4a23b0a60cc

interplay was upgraded by you, but I guess there are still deprecated methods, which we might need to change, I will take a look, soon.
omnidoc needs to have a look as well and an upgrade to 0.13.13.

**Comment by marcospereira** [comment]
@wsargent can we close this?

**Comment by wsargent** [comment]
Yes, code shows no references.
