### ISSUE TITLE
Response of FakeRequest does not have Content-Type header

### ISSUE THREAD

**Issue by buaya91** [playframework/playframework#6833]
### Expected Behavior
I am expecting testing of controller should reflect the behaviour when running the app, however in my test, `Content-Type` of response is empty, but it is set properly when I am running my app

### Actual Behavior
There's no Content-Type set in the response header when running unit test

### Reproducible Test Case

I will try to provide a test case (or maybe a fix) later, but I would like to know if this is a bug or feature before that?

**Comment by marcospereira** [comment]
Hi @buaya91, 

If you have the content type when running the app but not when running the tests, then there is something wrong. How are you extracting the content type from the result? Are you using [`Helpers.contentType` method](https://github.com/playframework/playframework/blob/master/framework/src/play-test/src/main/scala/play/api/test/Helpers.scala#L260-L263)?

**Comment by gmethvin** [comment]
Without your test we won't know for sure, but if you are just calling the `Action` defined by your controller method, the `Content-Type` header would generally not be set on the `Result` object, since that would be on the `HttpEntity`. The server reads the `HttpEntity` and writes the `Content-Type` and other headers related to the entity. If you [test with a server](https://www.playframework.com/documentation/2.5.x/ScalaFunctionalTestingWithScalaTest#testing-with-a-server) you should see the same headers as when you normally run the app.

**Comment by buaya91** [comment]
@marcospereira Nope, I am accessing it directly using 

```
val result = call(Controller.method(), req)
result.map(r => r.header.headers.get("Content-Type") mustBe ...)
``` 

I think this is the expected behaviour judging from @gmethvin comments

I'll close this issue, thanks
