### ISSUE TITLE
Custom filters class is ignored when custom application loader is used

### ISSUE THREAD

**Issue by jeffmath** [playframework/playframework#6837]
### Play Version (2.5.x / etc)

2.5.10

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

### Expected Behavior

1.  Run app
2.  Visit localhost:9000  
3.  Console outputs "Found custom filters class"
4.  Uncomment application.conf line which says: play.application.loader = "MyApplicationLoader"
5.  Wait for app to reload
6.  Visit localhost:9000 
7.  Console outputs "Found custom filters class"

### Actual Behavior

Same, except:
7.  Console does *not* output "Found custom filters class"

### Reproducible Test Case

Please download my Play app using this [link](http://reliantsoftwareeng.com/TestApp.zip).  I tried to create the simplest possible app which exhibits the issue.

**Comment by gmethvin** [comment]
If you're using `BuiltInComponents`, you can specify filters by overriding the `httpFilters` lazy val from `BuiltInComponents`. We need to clarify this in the docs in a few different places so I opened up a new issue: #6838.

This was an intentional design choice, since the goal of using the components traits is to avoid needing to load classes via reflection. You need to be using some kind of runtime reflection based application loader (like Guice, Spring, Scaldi, etc.) for that to work.

**Comment by jeffmath** [comment]
Thank you for the explanation.  I am glad you are calling for the documentation to be updated, as I spent the better part of two work days trying to narrow down what was causing my issue.
