### ISSUE TITLE
play framework 2.5.X client connection remains open

### ISSUE THREAD

**Issue by leosimoesp** [playframework/playframework#6844]
Hi,
I use play 2.5 and Netty dosen't close connections after client usage. The application due to lack of new connections.
I tried to use play.server.netty.option.child.SO_KEEPALIVE = true setting into application.conf but it didn't work. I saw #4976 issue.

netstat -ant | fgrep 2424
tcp 0 0 172.17.0.1:52492 172.17.0.2:2424 ESTABLISHED
tcp6 0 0 :::2424 :::* LISTEN
tcp6 0 0 127.0.0.1:55498 127.0.0.1:2424 ESTABLISHED
tcp6 0 0 127.0.0.1:2424 127.0.0.1:55498 ESTABLISHED

How to solve this ?

Thanks

**Comment by vinisuarez** [comment]
Is hard to know without knowing more details of your code, this problem was really annoying for us too but the setting on the application.conf did the trick for us. Other thing we changed ( if you use akka ) was exchange the java serializers for the kyro ( but not sure this is related).
Otherwise try to check what headers your client is sending.
If nothing of that helps maybe it is not your controller that are leaving the connection open. try to check for external HTTP calls that your application is doing, maybe there is a leak somewhere.
Hope this help. 
Cheers

**Comment by leosimoesp** [comment]
I've used this play params:

play.server{
  provider = "play.core.server.NettyServerProvider"
  netty {
    log.wire = true
  }
}


play.server.netty.transport="native"
play.server.netty.option.child.SO_KEEPALIVE=true
play.server.netty.option.child.SO_BACKLOG=128
play.server.netty.option.child.TCP_NODELAY=true
play.server.netty.option.child.TCP_USER_TIMEOUT=5
play.server.netty.option.child.CONNECT_TIMEOUT_MILLIS=5 

The connection was closed after 60 min but only work becauce I updated play netty deps into build.sbt. 
I have no idea how this happened or where that time was set. I try to set CONECTION Close into header too without success.

**Comment by marcospereira** [comment]
Hello @leosimoesp,

The [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. If we confirm that there is a bug/problem, then we can reopen this issue.
