### ISSUE TITLE
@RequireCSRFCheck throws 500 if no token is present

### ISSUE THREAD

**Issue by kdazzle** [playframework/playframework#6879]
### Play Version (2.5.x / etc)

Java 2.5.10

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

MacOS 10.12

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_91"

### Expected Behavior

1. Create a controller method with the @RequireCSRFCheck decorator
2. Try to POST to that controller without a CSRF token
3. A 403 Unauthorized response is returned

### Actual Behavior

Instead of a 403 being returned, I get a `java.lang.RuntimeException: No CSRF token present!`, leading to a 500 response.

**Comment by kdazzle** [comment]
It seems like this has already been discussed on #5627. The argument made there is that the view that generates the form should have a CSRF token - so if a view requiring a CSRF token doesn't find it, then there is an error.

However, I think there are lots of cases where two views might not be used together. For example, tests where you're testing what happens when there isn't a token. Or clients that are POSTing to an endpoint without rendering a form first. Those don't seem like server errors, but like unauthorized requests.

**Comment by gmethvin** [comment]
The only place where an exception is thrown with that error message is from the view helpers: https://github.com/playframework/playframework/blob/2.5.x/framework/src/play-filters-helpers/src/main/scala/views/html/helper/CSRF.scala#L18

The exception happens because no token has been added to the request. It has nothing to do with `@RequireCSRFCheck`. You should be using `@AddCRSFToken` on the action displaying the form, or use a properly-configured CSRF filter.

**Comment by gmethvin** [comment]
Let me just clarify that the error means no token has been generated on the **server side** (which is done by the CSRF filter and by `@AddCSRFToken`). It has absolutely nothing to do with whether the client has passed a CSRF token. Perhaps the error message should be made more clear.

**Comment by gmethvin** [comment]
Since no additional information has been provided to suggest this is a Play bug. @kdazzle If you can provide a reproducible test case we can reopen.
