### ISSUE TITLE
Functional test doc recommends using deprecated method

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#6935]
This page https://www.playframework.com/documentation/2.5.x/JavaFunctionalTest contains the following code snippet under **Creating Application instances for testing**:

`Application fakeAppWithGlobal = fakeApplication(new GlobalSettings() { ... });`

But `Helpers.fakeApplication(GlobalSettings)` is deprecated.

On a related topic, should all of the variants of the `Helpers.fakeApplication()` method be deprecated?  They all  create `FakeApplication` objects and the `FakeApplication` class itself is deprecated.

**Comment by gmethvin** [comment]
The method was deprecated because it takes `GlobalSettings` and you're right the documentation should have been changed. The example has been changed in the 2.6.x docs: https://www.playframework.com/documentation/2.6.x/JavaFunctionalTest

The other methods all have `Application` as the return type, so `FakeApplication` isn't part of the public API. I guess the implementation should have been changed in 2.5.x to use `GuiceApplicationBuilder` instead of  `FakeApplication` (PRs welcome) but for a user of the API it shouldn't make a difference.

**Comment by Shruti9520** [comment]
Hi,
@gmethvin @benmccann @marcospereira Can I work on this issue? :)

**Comment by gmethvin** [comment]
@Shruti9520 Sure. Note that this is only in the 2.5.x docs (not in master) so you have to submit your pull request there. I think we can just remove the GlobalSettings example.

**Comment by Shruti9520** [comment]
@gmethvin My PR's Travis CI test is failed. I am getting errors like- Internal server error, the application secret has not been set, and we are in prod mode, your application is not secure etc. Is it because I submitted a PR in branch- 2.5.x and the tests are written for the latest version (2.6.x)? Will you please help me out, it is my first PR ? :)

**Comment by marcospereira** [comment]
@Shruti9520 the build failure was not related to your changes. The PR was merged and we can now close this issue.

Thank you!
