### ISSUE TITLE
Play 2.6: Add ability to use configurable dispatcher for EventLoopGroup in NettyServer

### ISSUE THREAD

**Issue by plokhotnyuk** [playframework/playframework#6987]
Starting from Netty 4.1 we have ability to create NioEventLoopGroup or EpoolEventLoopGroup with custom executor:
https://netty.io/4.1/api/io/netty/channel/epoll/EpollEventLoopGroup.html
https://netty.io/4.1/api/io/netty/channel/nio/NioEventLoopGroup.html

Please use them to replace internal Netty threads by reusable instance of dispatcher (preferably backed by F/J pool from JDK) which can be easy converted to Executor by a bridge from @viktorklang :
https://gist.github.com/viktorklang/5245161

It will allow to use less threads and process requests faster with less blocking, context switches and cache misses.

**Comment by schmitch** [comment]
This is quite a big behavior change and somewhat related to https://github.com/playframework/playframework/pull/6912
Currently the way it is handled now is netty -> akka threads, always.

If we change it, yes there is no context switch. However it would change the behavior of an application drastically.
I actually don't know exactly why play switches of the netty thread *always*. as written in the PR it might be benefitical to do so.

well since play 2.6.x uses `akka-http` which basically also runs everything on the executor service of the actor system. and since it's a new major version we can/or maybe we could change it.
not sure what the others say tough.

**Comment by marcospereira** [comment]
Maybe also related to #5895.

**Comment by plokhotnyuk** [comment]
Sorry for posting issue w/o understanding that selector tasks are loops with blocking waiting which are ends only on EventLoopGroup shoutdown.

Now I see that this option will be useless and can lead for unexpected blocking for users.

**Comment by schmitch** [comment]
@plokhotnyuk well it's not useless in particular.
See the PR I linked.
And also akka-http does not switch threads. Which means if the default akka thread is exhausted play will just do nothing.

/cc @gmethvin WDYT about that? Especially when thinking about changing to akka-http: how does it relate with netty (i.e. there is a great documentation about it here: http://doc.akka.io/docs/akka-http/10.0.3/scala/http/handling-blocking-operations-in-akka-http-routes.html#handling-blocking-operations-in-akka-http)

**Comment by wsargent** [comment]
@schmitch we should integrate  http://doc.akka.io/docs/akka-http/10.0.3/scala/http/handling-blocking-operations-in-akka-http-routes.html#handling-blocking-operations-in-akka-http with https://www.playframework.com/documentation/2.5.x/ThreadPools
