### ISSUE TITLE
Error in default implementation for JPAApi.

### ISSUE THREAD

**Issue by fjtorres** [playframework/playframework#7037]
I detected an error in `DefaultJPAApi` class, when the entityManager isn't found in `withTransaction` method the code throws a `RuntimeException`. When this exception is throwed the call to `entityManagerContext.pop` in the finally instruction throw another exception because the `entityManagerContext.push` never was called.

**Comment by marcospereira** [comment]
Hey @fjtorres, could you please provide a project that shows this problem?

**Comment by fjtorres** [comment]
I will create a new project with this problem during the day but you can use the next code:

```
jpaApi.withTransaction("default", false, () -> {
   return null;
});
```

Change the datasource name from default to another string (that not exist).

**Comment by fjtorres** [comment]
I created this project for check the issue: https://github.com/fjtorres/play-jpaapi-error

The project was created from activator template named "play-java-intro-preview", I updated play version and minor changes to use dependency injection and JPAApi.

**Comment by marcospereira** [comment]
Thanks @fjtorres,

Yes, the exception that occurs while removing the `EntityManager` is hiding the original one. Since the `pop` method is only called by `withTransaction`, I think we can change its behavior to not throw an exception, but instead just return if the context is empty.

The relevant code is here:

https://github.com/playframework/playframework/blob/2.5.13/framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAEntityManagerContext.java#L77-L79

Do you want to submit a pull request to fix this issue?

**Comment by mkurz** [comment]
Duplicate #6041 ?

**Comment by fjtorres** [comment]
@marcospereira I think that another option is moving the line with the call to pop method to the next "if".

Move this line:
https://github.com/playframework/playframework/blob/38abd1ca6d17237950c82b1483057c5c39929cb4/framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java#L156

To this line:
https://github.com/playframework/playframework/blob/38abd1ca6d17237950c82b1483057c5c39929cb4/framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java#L157

@mkurz Yes, it is the same issue.

**Comment by marcospereira** [comment]
@mkurz I agree that this is a duplicated of #6041, so I'm closing this.

@fjtorres both solutions looks reasonable to me. Do you want to submit a PR?

**Comment by fjtorres** [comment]
@marcospereira I created a pull request for this issue.
