### ISSUE TITLE
[2.3.x] Assets programatically and gzip crashes

### ISSUE THREAD

**Issue by umbreak** [playframework/playframework#7041]
### Library Dependencies
addSbtPlugin("com.typesafe.sbt" % "sbt-gzip" % "1.0.0")

### Expected Behavior

Accessing a resource from a controller in the following way:
```java
    @Restrict(@Group(ADMIN))
    public play.api.mvc.Action<play.api.mvc.AnyContent> createResource(){
        return Assets.at("/public", "some/math/to/file/file.htmll", false);
    }
``` 

Should return the resource, in this case a HTML file.

### Actual Behavior

It works when not using gzip in the pipelineStages. However, when gzip support is added, it shows the following error through browsers:
**net::ERR_CONTENT_DECODING_FAILED**

And the following through curl:
_curl -v 'http://localhost:9000/path/to/resource' -H 'accept-encoding: gzip, deflate' --compressed_
**curl: (61) Error while processing content unencoding: invalid block type**

So it seems to me that there is some problem gzipping this file though the controllers call. It should not be a matter of the encoding of the file either.

**Comment by gmethvin** [comment]
It looks like the problem is the file name: it ends in `.htmll` (maybe a typo?). sbt-gzip only works for certain extensions: https://github.com/sbt/sbt-gzip#filters

Also, you may already be aware of this, but the annotations only work on Java action methods, which must return `Result` or `CompletionStage<Result>` (`Promise` in 2.3).

You can also use the GzipFilter to enable gzip for all requests when possible: https://www.playframework.com/documentation/2.3.x/GzipEncoding
