### ISSUE TITLE
2.6.0-M2 http request times out after 20 seconds, returns response when it should continue waiting

### ISSUE THREAD

**Issue by ScalaWilliam** [playframework/playframework#7067]
### Play Version (2.5.x / etc)
2.6.0-M2

### Expected Behavior
No time out as in 2.5.x. I was hoping Issue #6992 would fix this but doesn't appear to have fixed it.

### Actual Behavior
Long response times out after 20 seconds, returns:
```
HTTP/1.1 503 Service Unavailable
Date: Sat, 11 Mar 2017 01:44:28 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 105

The server was not able to produce a timely response to your request.
Please try again in a short while!%
```

### Reproducible Test Case

https://github.com/ScalaWilliam/play-akka-timeout-test

**Comment by zvuki** [comment]
`akka.http.server.request-timeout=120 s` helped me, not sure if it's a "idiomatic" solution though.

**Comment by marcospereira** [comment]
So, Akka Http default value for request timeout is 20 seconds, [according to the docs](http://doc.akka.io/docs/akka-http/current/scala/http/common/timeouts.html#request-timeout). The default value is [overridden by Play in `AkkaHttpServer`](http://doc.akka.io/docs/akka-http/current/scala/http/common/timeouts.html#request-timeout) if the the properties  `play.server.akka.http.idleTimeout` ([defaults to 75 seconds](https://github.com/playframework/playframework/blob/2.6.0-M2/framework/src/play-akka-http-server/src/main/resources/reference.conf#L16-L19)) and `play.server.akka.http.requestTimeout` are configured.

#6992 just declared a necessary property, but it did not give it a default value and then the Akka Http default is being used.

@ScalaWilliam can you confirm that configuring `play.server.akka.http.requestTimeout` is possible and then the problem is solved?

I'm not sure if we have a default value for Netty Server in 2.5.x, but if we have, we can keep that behavior for 2.6.0.

**Comment by marcospereira** [comment]
As observed in #7172, the correct properties are:

1. `play.server.http.idleTimeout` (or `https`) for server idle timeout and
2. `play.server.akka.requestTimeout` for request timeout.

We should correct the docs and also make these configuration more consistent.

**Comment by almothafar** [comment]
@gmethvin @marcospereira
I'm getting the same error now on play version 2.6.9 but back to 2.6.7 there is no problem.

It is ignoring my settings at all:
```
play.server {
  akka: {
    requestTimeout = 180s
  }
  http {
    idleTimeout = 180s
  }
}
```
