### ISSUE TITLE
FormFactory bindFromRequest overwrites POST parameter with querystring parameter

### ISSUE THREAD

**Issue by kdazzle** [playframework/playframework#7070]
### Play Version (2.5.x / etc)

2.5.12

### API (Scala / Java / Neither / Both)

Java

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

### Expected Behavior

Binding a form from a request ignores the querystring of a url. Or, if the querystring is supposed to be included, any POST value will override that.

### Actual Behavior

If I am POSTing to a form at url `http://localhost:9000/?emailAddress=foo@bar.com`, and there is a form field that is also called `emailAddress`, the following lines of code will result in a bound form which gets its `emailAddress` value from the GET parameter instead of the POST.

```
Form<User> form = formFactory.form(User.class);
form = form.bindFromRequest();
```

**Comment by mkurz** [comment]
I had a quick look into this:

We could easily change this behaviour in here:
https://github.com/playframework/playframework/blob/2.6.0-M2/framework/src/play-java-forms/src/main/java/play/data/Form.java#L167-L202
We could e.g. just ignore the [query string](https://github.com/playframework/playframework/blob/2.6.0-M2/framework/src/play-java-forms/src/main/java/play/data/Form.java#L199) for `POST` requests. But what about `PUT`, `PATCH`, `DELETE`, `HEAD` and `OPTIONS` requests? When to ignore the query string and when to ignore the values parsed from the body? Or just move the referenced line to the top so a value received from the request body overrides the querystring instead?

Also when changing this for Java Forms we should change it for the scala version because it handles this the same way right now (querystring overrides body values): https://github.com/playframework/playframework/blob/2.6.0-M2/framework/src/play/src/main/scala/play/api/data/Form.scala#L86

So the question is what behaviour is correct (or how do we want our forms to get filled)?

**Comment by kdazzle** [comment]
Hey @mkurz - thanks for taking a look at this!

I can't think of any instance in which I'd want query string parameters effectively being injected into my post/put/delete/patch bodies. Not sure about head or options because I don't use those very often, but my guess would be that they shouldn't be special cases.

**Comment by mkurz** [comment]
I would like to hear other opinions from other Play (core) members before.

**Comment by mkurz** [comment]
@kdazzle `DELETE` has no body, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

**Comment by mkurz** [comment]
See #7104

**Comment by kdazzle** [comment]
Thanks for the quick fix!

**Comment by mkurz** [comment]
@kdazzle This will be availabe with the 2.6 release.

**Comment by kdazzle** [comment]
Yeah, I saw that
