### ISSUE TITLE
feature: make it easy to create a per-request-actor

### ISSUE THREAD

**Issue by domdorn** [playframework/playframework#7183]
For some time now, I have this idea in my had that I want to fully embrace Akka in my Play Projects. 
Unfortunately, Play and Akka are still somehow separated quite a lot. 

At the moment, we only support creating "per request actors" for websockets. 

For people who would like to work with Akka instead of the traditional layered architecture (at least for some actions), its quite cumbersome to do so... at the moment, they would need to create the actor-class as (inline)class, create/spawn the actor manually in the method, parse the request information manually, transform that into a request message, and ASK the actor for an answer. 

Ideally, we would have something like

```
class MyController @Inject() (@Named("myBackendActor") be : ActorRef) extends Controller {


def myActorAction : Future[Result] = withActor {
 implicit out => 

 def receive = {
   case x : RequestIn => val someObject = doSomething(x); be ! CustomMessage(someObject) 
   case x : BeResponse => val something : Result = doSomething(x); out ! something
 } 

}

```

What do you think about that?

**Comment by wsargent** [comment]
I think that's probably better done as a Play module -- that way you can have your own release cycle on top of Play.

**Comment by wsargent** [comment]
I don't think this is actually a framework problem, because a "per request actor" would be run using a custom ActionBuilder, and then you would have the ActionBuilder provide a  `WrappedRequest` containing the ActorRef.  You could do this with dependency injection as well by injecting `@Named("myBackendActor")` into the `ActorActionBuilder`.  See MessagesRequest for example of custom action builder and wiring it into the Controller framework:

https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/MessagesRequest.scala

The receive method is not something that is planned -- you'd have to use the usual combination of ask / pipeTo to work between actors and Future.
