### ISSUE TITLE
Config loader does not load application.conf in multi module project

### ISSUE THREAD

**Issue by akkie** [playframework/playframework#7310]
### Play Version (2.5.x / etc)

2.5.14

### API (Scala / Java / Neither / Both)

Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Run the tests `sbt test`
2. Tests should pass

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

1. Run the tests `sbt test`
2. Tests fail

### Reproducible Test Case

https://github.com/setusoft/play-config-bug

**Comment by margussipria** [comment]
This is not a bug, not even play related. Configuration can't magically appear to module scope if it isn't given directly in that module or any modules it is using.

sbt does not allow circular depencies even if you would like to use code from `main` ( `compile`) stage when running tests.

And for tests you should use different configuration, that is loaded example form: `auth/src/test/resources/application.conf`

**Comment by akkie** [comment]
If I run a test for an application (WithApplication), then I would expect that the test runs under the same premise as the application itself.

I've updated the tests to show that this issue does not only affects the configuration. The messages(i18n) component and the router are also affected by this issue. Neither of the tests runs successful. But if I start the application, then all actions will be executed successful.

Play doesn't have a built-in method to organize messages files in sub modules. There is also no way to test sub routes with the `route` helper method. 

So if this isn't a bug, then it should be documented that the `route` helper cannot be used in sub modules, because it cannot resolve the routes. It should also be documented that it's not possible to test i18n related code in sub modules, because it cannot find the messages files which must be located in the root module.

Maybe I miss something or my tests are wrong. So it would be great if a core developer could say something about the issue.

**Comment by gmethvin** [comment]
This is not a Play bug.. But it seems rooted in a lack of clarity in how Play/SBT modules work, which could be remedied with better documentation.

> I've updated the tests to show that this issue does not only affects the configuration. The messages(i18n) component and the router are also affected by this issue. Neither of the tests runs successful. But if I start the application, then all actions will be executed successful.

In a multi-module build, each module is separate unless you tell it to depend on something else. In your example, `modelerAuth` does not depend on `root` (in fact, the opposite is true), so there is no reason to expect it to be able to access resources from `root`. The `messages` file, `application.conf`, and the generated router (at least the one configured by default) are all in the `root` project. If you're actually trying to test the integration of `modelerAuth` with the `root` project, then you should have a separate integration test project that depends on both.

> Play doesn't have a built-in method to organize messages files in sub modules.

This is somewhat true. You can add `messages` files anywhere, but by default Play just aggregates all the files on the classpath, so it doesn't give you any way to layer the `messages` file from one project on top of the other without writing custom code. This describes a more sophisticated solution: https://github.com/adrianhurt/play-multidomain-seed#internationalization-how-to-split-messages-files.

> There is also no way to test sub routes with the route helper method.

For the routes you can set `play.http.router = admin.Routes`. You are probably confused because by default, Play tries to load a file called `Routes` in the root package, so you don't need to configure this for the `routes` file.

> So if this isn't a bug, then it should be documented that the `route` helper cannot be used in sub modules, because it cannot resolve the routes.

It can resolve the routes, but you have to configure it. This is mentioned briefly in the note with `devSettings` but not really made clear: https://www.playframework.com/documentation/2.5.x/SBTSubProjects#Splitting-the-route-file

> It should also be documented that it's not possible to test i18n related code in sub modules, because it cannot find the messages files which must be located in the root module.

Does the documentation suggest that messages files only can be in the root module?

I opened #7389 to cover the documentation issues here. Please comment with anything you think we should clarify.

If you're looking for general guidance on how to structure your project, it'd be best to move this to the mailing list.
