### ISSUE TITLE
Session clear is not working (using AuthenticatedAction)

### ISSUE THREAD

**Issue by joaocraveiro** [playframework/playframework#7328]
**Play Version** 
2.6.0-M5

**API (Scala / Java / Neither / Both)**
Java

**Expected Behavior**
After migrating to 2.6 my session.clear() calls stopped working

**Comment by gmethvin** [comment]
Can you provide sample code or a test?

**Comment by joaocraveiro** [comment]
Sample project here: https://github.com/joaocraveiro/versus

**Comment by gmethvin** [comment]
Thanks. Seems like a bug in `AuthenticatedAction`, since removing `@Authenticated` from the action makes it work.

See also #7331, which proves `session.clear()` by itself works.

**Comment by gmethvin** [comment]
Okay found the root cause: `Context#withRequest` creates a copy of the context, including the session and flash, but it doesn't carry over the `isDirty` property from there. In the `new Context` constructor, the session is passed, but it's treated as a regular map, so the values are copied, but not the state: https://github.com/playframework/playframework/blob/2.6.0-M5/framework/src/play/src/main/java/play/mvc/Http.java#L418

Another reason why I don't like having stateful APIs...

**Comment by gmethvin** [comment]
Okay found the real root cause.

Context#withRequest creates a copy of the context, and makes a deep copy of the session and flash. In the new Context constructor, the session is passed, but it's treated as a regular map, so the values are copied. In `JavaAction`, we expect the `session` in the context to be the same reference as in the beginning, but it is not because `Context.withRequest` makes a deep copy.
