### ISSUE TITLE
[doc] Play-WS migration doc confuses with new standalone version

### ISSUE THREAD

**Issue by huntc** [playframework/playframework#7484]
The [Play 2.6 migration guide for WS](https://playframework.com/documentation/2.6.x/WSMigration26) incorrectly lists the dependencies for WS standalone. The dependency should be:

```
"com.typesafe.play" %% "play-ahc-ws" % "2.6.0"
```

**Comment by gmethvin** [comment]
Generally, if you're using the Play SBT plugin, you want to use:
```sbt
libraryDependencies += ws
```
as described in https://playframework.com/documentation/2.6.x/ScalaWS#Adding-WS-to-project. That hasn't changed since 2.5.x, but `ws` now points to the `play-ahc-ws` module.

The confusing thing is that the migration guide gives dependencies for `play-ahc-ws-standalone`, but you still want `play-ahc-ws` if you're using it within a Play app. That provides the bindings and other Play-specific configuration. We probably need to do a better job explaining the differences.
