### ISSUE TITLE
Incorrect Filename when downloading from Play 2.6 application  Ask Question

### ISSUE THREAD

**Issue by atul-acharya** [playframework/playframework#7501]
### Incorrect downloaded filename

I downloaded [Play 2.6 Scala Starter Example](https://example.lightbend.com/v1/download/play-scala-starter-example) from [playframework.com](https://www.playframework.com/download#seeds).

Added route to `conf/routes`
```
GET     /readme                    controllers.AsyncController.readme
```
Added _Action_ to `app/controllers/AsyncController.scala`
```
  def readme = Action {
    Ok.sendFile(
      content = new java.io.File("README.md"),
      inline = false)
  }
```
When I try to `http://localhost:9000/readme`, I'm expecting file **README.md** to be downloaded, instead I get **utf-8"README.md".
[Related question on stackoverflow](https://stackoverflow.com/questions/44733090/incorrect-filename-when-downloading-from-play-2-6-application)

### Play Version (2.5.x / etc)

**2.6.0**

### API (Scala / Java / Neither / Both)

**Scala**

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

**Windows 10**

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

```
### Library Dependencies

**None**

### Expected Behavior

Downloaded filename should be **README.md**.

### Actual Behavior

Downloaded filename is **utf-8"README.md**.

### Reproducible Test Case

**Comment by atul-acharya** [comment]
There are these spurious characters (**utf-8''**) on line 410, **play.api.mvc.Results.scala"".
```
s"""$dispositionType; filename="$name"; filename*=utf-8''${UriEncoding.encodePathSegment(name, StandardCharsets.UTF_8)}"""
```
I removed those and checked with local build, and the file-name is proper.

The line needs to be changed to 
```
s"""$dispositionType; filename="$name"; filename*=${UriEncoding.encodePathSegment(name, StandardCharsets.UTF_8)}"""
```

**Comment by richdougherty** [comment]
I'll take a look at this.

**Comment by richdougherty** [comment]
Tested with `curl -v http://localhost:9000/readme`. I see:

```
Content-Disposition: attachment; filename="utf-8''README.md"
```

Can you please confirm what header value you see?

The expected behaviour in https://tools.ietf.org/html/rfc6266#section-4.3 is to send both the `filename` and `filename*` parameters. According to the spec, the filename parameter encoding should (probably) be ISO-8859-1 . The `filename*` parameter supports arbitrary character sets, and the `utf8''` prefix is the correct way of specifying a UTF-8 encoding.

Here is the expected response:

```
Content-Disposition: attachment; filename="README.md"; filename*=utf-8''README.md
```

Our code should already be sending both `filename` and `filename*` parameters, hopefully correctly, so I'm not sure why I'm seeing only a `filename` parameter and no `filename*` parameter. I'm also not sure why the `filename` parameter value is the `filename*` parameter, but quoted... Maybe Akka HTTP is parsing then re-encoding the header value incorrectly? :)

I'll continue investigating.

**Comment by richdougherty** [comment]
Further notes:
* Since #6042 the filename code no longer does escaping, it is just (`filename="$name"`) . This means it probably doesn't handle filenames with quotes (`"`), special characters (like newlines!), etc. We may need to process the name string to remove dangerous characters.
* We should support `filename*` in our multipart `BodyParser`.

**Comment by richdougherty** [comment]
I believe this is an Akka HTTP bug: https://github.com/akka/akka-http/issues/1240

**Comment by richdougherty** [comment]
Verification for issue. This test works in Netty but not in Akka HTTP.

https://github.com/richdougherty/playframework/commit/4ce3a808c2ea5104706e6b3fd1f80cf31af8fad4

**Comment by richdougherty** [comment]
Hi @atul-acharya, this issue is now addressed in Play 2.6.1 if you want to try it out.

**Comment by atul-acharya** [comment]
Hi @richdougherty,
Checked with 2.6.1, worked as expected.

Thanks much!

**Comment by richdougherty** [comment]
You're welcome. Glad it works! :)

**Comment by jayasharma8** [comment]
Hi Guys,

Need small help. when we try to download any file from the UI, File name is appended to the URL and it's vulnerable. Hackers can put any ../ OR ..%2e%2e%2f OR 
%c0%af represents ../  in the url. which is detected during security scan. Can any one let me know the existing methods which can rectory it.
We are taking file name in string. so can't work with file methods and picking the file from a particular location.

 We have a FileDownloadServlet.java,
