### ISSUE TITLE
PlayProject depends on PlayNettyUtilsProject even when using akka-http

### ISSUE THREAD

**Issue by mkurz** [playframework/playframework#7554]
When checking the dependencies of a project (via [`sbt dependencyTree`](https://github.com/jrudolph/sbt-dependency-graph)) I found out that there still is a dependency on `com.typesafe.play:play-netty-utils:2.6.0` even tough I don't use netty anymore. 

See https://github.com/playframework/playframework/blob/2.6.0/framework/build.sbt#L81

**Comment by marcospereira** [comment]
Yep, that is not ideal.

But apparently, we are using `Play-Netty-Utils` just as an API to handle cookies encoding. Also, notice that there is no dependency on Netty itself.

```
sbt Play-Netty-Utils/dependency-tree

...

[info] com.typesafe.play:play-netty-utils:2.7.0-SNAPSHOT
[info]   +-org.slf4j:jcl-over-slf4j:1.7.25
[info]   | +-org.slf4j:slf4j-api:1.7.25
[info]   |
[info]   +-org.slf4j:jul-to-slf4j:1.7.25
[info]   | +-org.slf4j:slf4j-api:1.7.25
[info]   |
[info]   +-org.slf4j:slf4j-api:1.7.25
```
So, maybe we should rename this project to something like `play-cookie-encoding`? Or maybe move the code to `Play` project, since this is the only project which depends directly from `Play-Netty-Utils`.

What do you think?

**Comment by mkurz** [comment]
I would probably just rename it and move the src out of the `play.core.netty.utils` package.

**Comment by mkurz** [comment]
(I mean rename the package to something else)
