### ISSUE TITLE
[2.6.x] Action not found when enable HTTP2

### ISSUE THREAD

**Issue by btnguyen2k** [playframework/playframework#7596]
### Play Version (2.5.x / etc)
Play 2.6.1

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.12

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### Expected Behavior
When accessing an URL with query string (e.g. https://host:port/action?param=value) the corresponding action is invoked.

### Actual Behavior
When HTTP2 is enabled, the 404 error was returned instead:
"Action Not Found"
"For request 'GET https://localhost:9443/action%3Fparam=value'"

### Reproducible Test Case
Create a simple route rule in routes file like this:

`GET /action controllers.MyController.action(param: String)`

The link `http://localhost:9000/action?param=value` works with http
Also, `https://localhost:9443/action?param=value` works WITHOUT HTTP2 enabled.
But `https://localhost:9443/action?param=value` does NOT work when HTTP2 is enabled. Instead error 404 is returned:
"Action Not Found"
"For request 'GET https://localhost:9443/action%3Fparam=value'"

**Comment by richdougherty** [comment]
Hmm, that doesn't sound good. I'll take a look at this.

**Comment by richdougherty** [comment]
I've replicated this bug now. I'll work on getting it fixed. @btnguyen2k, thanks for testing out the experimental HTTP/2 support and reporting this issue!

**Comment by richdougherty** [comment]
The problem seems to be that Akka HTTP sends different info for HTTP/1.1 vs HTTP/2 requests.

For example, here is a working HTTP/1.1 request:

```
request = {HttpRequest@22648,…,HttpProtocol(HTTP/1.1))"
 method = {HttpMethod@20503} "HttpMethod(GET)"
 uri = {Uri$$anon$1@22655} "http://localhost:9000/test?param=s"
 headers = {$colon$colon@22656} "::" size = 11
  …
  1 = {Raw$minusRequest$minusURI@22664} "Raw-Request-URI: /test?param=s"
```

And here is a failing HTTP/2 request:

```
request = {HttpRequest@22599} "HttpRequest(…,HttpProtocol(HTTP/2.0))"
 method = {HttpMethod@20503} "HttpMethod(GET)"
 uri = {Uri$$anon$1@22603} "https://localhost:9443/test%3Fparam=s"
 headers = {Vector@22604} "Vector" size = 9
  <<<no Raw-Request-URI header in Vector>>>
…
```

There are two differences I can see:
1. The `HttpRequest`'s `uri` field is different for both. For the HTTP/1 request the query parameter is properly separated by a `?`. For the HTTP/2 request the query parameter is shown as part of the path.
2. The `HttpRequest` includes a `Raw-Request-URI` header in the HTTP/1.1 request, but not in the HTTP/2 request. This affects the conversion logic: https://github.com/playframework/playframework/blob/309bbe6d0fa89b449b582516f98e883776ef9452/framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala#L172-L178

Actions:
1. raise bug upstream in Akka HTTP and possibly implement fix
2. if Play actually requires the `Raw-Request-URI` field to be present then it should _require_ it to be present and give an error if it is missing, instead of just falling back to the `HttpRequest` `uri` field.
2. add unit tests to Play for path parsing when using HTTP/2

**Comment by richdougherty** [comment]
I have created an Akka HTTP issue to track this: https://github.com/akka/akka-http/issues/1274
