### ISSUE TITLE
Documentation confusion configuring akka http in dev mode.

### ISSUE THREAD

**Issue by othp** [playframework/playframework#7617]
I was looking to set some custom akka http settings (specifically, akka.http.parsing.max-uri-length) and wanted to test my configuration in dev mode.  

https://www.playframework.com/documentation/2.6.x/SettingsAkkaHttp has a note at the bottom about how the setting wouldn't be picked up in dev mode without some additional work, but the link about other options goes here: https://www.playframework.com/documentation/2.6.x/Configuration#Using-with-the-run-command when it was probably was intended to go here: https://www.playframework.com/documentation/2.6.x/ConfigFile#Using-with-the-run-command.  

I attempted to set 
```sbt
PlayKeys.devSettings := Seq(
  "akka.http.parsing.max-uri-length" -> "1m"
)
```
but this did not work.  Confusingly, this section of the same doc: https://www.playframework.com/documentation/2.6.x/ConfigFile#Using-with-Akka suggests that akka needs to be configured under `play.akka`, but I believe that hasn't been the case since before play 2.4.  

After browsing the dev startup code ([DevServerStart.scala](https://github.com/playframework/playframework/commit/bad893d6ad7bf6a92ef05ee2fd87297e62f44224#diff-58bf6474fbdd7970aeb1630b24c9f7e2R217)), I found that my attempt at overriding the default setting wasn't working because in dev mode akka configuration is pulled from `play.akka.dev-mode`.  As far as I can tell, this isn't documented anywhere outside of the code.  

So to set the max-uri-length such that it would be picked up in dev mode, I actually needed: 
```sbt
PlayKeys.devSettings := Seq(
  "play.akka.dev-mode.akka.http.parsing.max-uri-length" -> "1m"
)
```
If this is how it's going to be, it would be nice if it could be documented and if issues with the existing docs could be cleaned up to make it clearer.

**Comment by ManognaMutyala** [comment]
@marcospereira  I have a  doubt regarding this issue and would like to work on this.Should the documentation https://www.playframework.com/documentation/2.6.x/SettingsAkkaHttp with the note at the bottom   https://www.playframework.com/documentation/2.6.x/Configuration#Using-with-the-run-command  has to be replaced with https://www.playframework.com/documentation/2.6.x/ConfigFile#Using-with-the-run-command? And also any code snippet representing  
**set the max-uri-length such that it would be picked up in dev mode, 
PlayKeys.devSettings := Seq(
  "play.akka.dev-mode.akka.http.parsing.max-uri-length" -> "1m"
)**  
has to be documented?

**Comment by richdougherty** [comment]
Yes the link should be fixed.

From  https://www.playframework.com/documentation/2.6.x/Configuration:

> Note: In dev mode, when you use the run command, your application.conf settings will not be picked up by the server. This is because in dev mode the server starts before the application classpath is available. There are several other options you’ll need to use instead.

This text is partly correct but should be clarified.

"Application" settings are reloaded every time the application code or config changes. "Server" settings are only loaded when dev mode first starts. This is because in dev mode Play the server component has a different lifecycle to the application. The server intercepts web requests and works out whether to compile, restart, etc the application. It stays running throughout the entire run command. It doesn't restart when the application restarts, thus, unlike the application, it cannot reload its configuration if it's changed while the run command is running. However, it does read the application.conf settings when the run command first starts. (I think this is true, but it should be checked.)

If you want Akka specific settings to be picked up they need to be prefixed. This is because in dev mode Play has *two* ActorSystems running. One is used by the server, primarily for running Akka HTTP. The other is used by the application and will be started and stopped whenever the application is reloaded.

1. Reading the configuration - including application.conf: https://github.com/playframework/playframework/blob/0985a85d7798235a9fcf6e4633003e6d617af8a5/framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala#L205
2. Reading a prefixed version of the configuration and passing to Akka: https://github.com/playframework/playframework/blob/0985a85d7798235a9fcf6e4633003e6d617af8a5/framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala#L212-L213

A final point. Some Akka HTTP configuration is read from one location in Play's configuration and then used to modify the Akka configuration before it is passed to Akka HTTP. E.g. look at how this configuration is used: https://github.com/playframework/playframework/blob/0985a85d7798235a9fcf6e4633003e6d617af8a5/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L52-L53

That means that these settings will not need to be prefixed by `play.akka.dev-mode` because they're read from the base configuration and then patched into the Akka configuration later…

If you're working on this it would be a good idea to read `DevServerStart` and `AkkaHttpServer` and do some testing on a real application while you're writing the documentation so that you can be sure it's all working as you expect. It's a bit complicated!
