### ISSUE TITLE
Missing "Latest Release" tag on releases page

### ISSUE THREAD

**Issue by rmcloughlin** [playframework/playframework#7635]
If you visit the github releases page (https://github.com/playframework/playframework/releases) you might think that the latest release is 2.6.0-M2 because it's the one that is shown most prominently.  See screenshot.

![releases](https://user-images.githubusercontent.com/4472381/28264532-672821d8-6ab9-11e7-88c5-bd42772af50d.png)

There is a minimized list of "newer tags" above it but it's very easy to miss.

I think that the problem is that 2.6.1 lacks a "Latest Release" tag which would make it appear at the top.  See the [guava](https://github.com/google/guava/releases) releases page for example.

**Comment by marcospereira** [comment]
Thanks for that.

We usually don't publish the release notes on Github, but instead, the official releases page is here:

https://playframework.com/changelog

Anyway, I think we can also add more information to "releases" page here on Github. The only possible downside is that I don't know how Github will handle releases from distinct branches. For example, when we decide to release 2.5.16, will it appears as the most updated release?

Finally, I'm closing this since I've edit the 2.6.1 release as you suggested. ;-)
