### ISSUE TITLE
Please upgrade spring to 4.3.5 to resolve security issues

### ISSUE THREAD

**Issue by ddevos78** [playframework/playframework#7647]
Play 2.5.x Java

The version of spring that Play 2.5 (and I believe Play 2.6) uses is 4.2.7 which has the current security issues associated with it:
* [CVE-2016-9878](https://nvd.nist.gov/vuln/detail/CVE-2016-9878)
* [CVE-2016-5007](https://nvd.nist.gov/vuln/detail/CVE-2016-5007)

Can we please get the version that Play pulls in, upgraded to 4.3.5 which has the fixes for these issues.

**Comment by richdougherty** [comment]
Hi @ddevos78, we appreciate the report. I just want to check if these are relevant to Play, since we usually wouldn't update a dependency from 4.2.x to 4.3.x in a stable release. However if there's a security issue to resolve then we might work around this rule.

I've read the vulnerability descriptions you linked and both vulnerabilities appear to be related to Spring's URL mappings to its servlets and controllers. Since Play doesn't use Spring's servlets or controllers, I don't think it would be vulnerable. Thoughts?

**Comment by richdougherty** [comment]
@ddevos78, I've just realised that this should be reported to security@playframework.com so that we don't discuss possible vulnerabilities until we've patched them. See https://www.playframework.com/security/vulnerability for more information. Would you mind sending a message to security@playframework.com? Once you've done that I might delete this ticket and we can continue the discussion in private.

**Comment by gmethvin** [comment]
The security vulnerabilities you mentioned do not apply to Play. These are issues in spring-webmvc and spring-security, neither of which Play uses. Play only uses Spring components for its Java form validation (specifically spring-core, spring-context, and spring-beans). Play does not use any Spring components for URL pattern mappings or mapping requests to controllers.

Security issues should be reported to security@playframework.org. This is described on our [security vulnerability page](https://www.playframework.com/security/vulnerability).

**Comment by ddevos78** [comment]
No worries, email with additional information sent.. you can go ahead and delete this issue.

**Comment by richdougherty** [comment]
Thanks @ddevos78!

**Comment by richdougherty** [comment]
Issue "removed" by editing/deleting comments, as agreed.

**Comment by richdougherty** [comment]
Info is still visible on the issue, I will contact Github support.

**Comment by ddevos78** [comment]
After speaking with your security team, they were able to confirm that these vulnerabilities actually effect *different* spring jars, from what Play bundles.. so play itself isn't actually vulnerable.
