### ISSUE TITLE
The session module doesn't work after LegacyCookiesModule is enabled.

### ISSUE THREAD

**Issue by joymufeng** [playframework/playframework#7659]
### Play Version 
2.6.2

### API
Scala

### Operating System 
Windows 10

### JDK 
Oracle 1.8.0_72
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
Paste the output from `java -version` at the command line.

### Expected Behavior
The session module works normally after LegacyCookiesModule is enabled.

### Actual Behavior
After LegacyCookiesModule is enabled, the session cookies of results are encoded by CookiesModule, but not LegacyCookiesModule.

### Reproducible Test Case
This issue occurs after LegacyCookiesModule is enabled in application.conf.
```
play.modules.disabled += "play.api.mvc.CookiesModule"
play.modules.enabled += "play.api.mvc.LegacyCookiesModule"
```

**Comment by joymufeng** [comment]
This issue is fixed by [#7660](https://github.com/playframework/playframework/pull/7660).

**Comment by richdougherty** [comment]
Hi @joymufeng, this issue should be fixed in Play 2.6.3. If you get a chance, it would be great if you could check out the release and confirm that your fix is working properly.

And thanks for the fix! You'll notice you got a mention in the Credits at the end of the release post: https://blog.playframework.com/play-2-6-3-released/

**Comment by joymufeng** [comment]
@richdougherty OK, I will check it.

**Comment by joymufeng** [comment]
@richdougherty Checked, it works now.

**Comment by richdougherty** [comment]
👍 Thanks for checking!
