### ISSUE TITLE
CSP headers set by Security filters makes error pages look unstyled

### ISSUE THREAD

**Issue by makkarpov** [playframework/playframework#7662]
CSP headers set by filters does not allow loading of inline icons or styles from error pages.

**Play v 2.6.2**

**Pretty self-descriptive image:**
![image](https://user-images.githubusercontent.com/1329592/28531318-324335e8-709f-11e7-85f1-4e7943b00ac9.png)

**Comment by richdougherty** [comment]
Thanks for the report.

A fairly direct fix for this would be to add an `img-src data:` into the headers for error responses. [Adding `data` sources is generally not recommended](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src), so we may want to think of something else, [perhaps a nonce like Google does](https://security.googleblog.com/2016/09/reshaping-web-defenses-with-strict.html).

**Comment by gmethvin** [comment]
The other option here is to find a way to special-case the error pages so they always work in dev mode regardless of the CSP. Considering these are dev errors it's probably ok to remove the CSP header only in that case. But we'd need a mechanism for doing that. We can with `allowActionSpecificHeaders` but would have to change the default.

I also think nonces are a good idea in general, but they aren't a perfect solution here, since it's possible for a user to reconfigure the CSP header to not have a nonce, or to a nonce we don't know about.

**Comment by gmethvin** [comment]
Actually I forgot that we actually have inline styles on the default production error pages too, so we would either need to remove those or do something else.

**Comment by gmethvin** [comment]
I think the easiest thing to do here is just remove the styling/images from the error pages.

**Comment by richdougherty** [comment]
Tagged with 2.6.3 since this should be easy to do. I think we can still probably do some styling if we hardcode it into our HTML using `style` attributes.

**Comment by makkarpov** [comment]
1. Set permissive CSP header explicitly in error pages
2. Tell security filter to ignore response if it already contains CSP headers.

Why this isn't a solution? Since error pages doesn't contain any user content, permissive CSP headers should be not an issue.

**Comment by richdougherty** [comment]
I talked a bit with @gmethvin. Disabling headers is a solution that would work.

The main downside for me is that I don't like adding in a special exception to disable security headers, because it feels like there's a security vulnerability just waiting to happen.

**Comment by gmethvin** [comment]
We already have the option to avoid overriding security headers if they already exist, `allowActionSpecificHeaders`. That in combination with explicitly setting a CSP header would be enough. It defaults to false, though. We could change that default but not sure it's a good idea to change for 2.6.x because that could potentially break other things for users.

We can have a flag on the result to enable that feature, but there's not really a nice way to do that. It would probably have to be a special header name in the response headers.

**Comment by makkarpov** [comment]
Another possibility to fix it is to do something like that:

1. CSP filter should generate a nonce and attach it as an attribute to the `RequestHeader`. This feature would be also useful when used standalone. When it comes to the CSP policy, it should replace some special token like `@nonce@` to the actual nonce value.

2. Error template should include nonce extract from the request in all inline content, so it will pass CSP filter.

**Comment by richdougherty** [comment]
@makkarpov, I've made your suggestion into a new ticket: https://github.com/playframework/playframework/issues/8234. I think what you've suggested is the right approach. 😄
