### ISSUE TITLE
Publish com.typesafe.play:run-support_2.11:2.6.x

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#7687]
run-support is only published for 2.10 since it's only used by SBT. However, it turns out that the Gradle build uses it as well and wants the 2.11 version which disappeared when Play 2.6.0 was released. Would we be able to add it back for Play 2.6.3? This is a blocker for Gradle supporting Play 2.6

**Comment by richdougherty** [comment]
Sure we can do that!

**Comment by marcospereira** [comment]
@benmccann I saw that Gradle is removing the dependency on run-support ( see commit https://github.com/gradle/gradle/commit/d4896083740dd53a8150975bfec96f9cab96ffe6). Is this still necessary (or still a blocking to https://github.com/gradle/gradle/issues/1992)?

**Comment by benmccann** [comment]
Yeah, turns out we probably don't need this after all

**Comment by richdougherty** [comment]
OK, it looks like this issue can be closed. Is that right?

**Comment by stewSquared** [comment]
My team is using run-support in an integration test built with scala 2.11.

This a little inconvenient, because we were upgrading play 2.5 => 2.6 as a separate step from moving to scala 2.12. Fortunately, you did published "2.6.0-M2", which will hopefully serve us fine until the full migration is complete.
