### ISSUE TITLE
CachedSpec fails intermittently

### ISSUE THREAD

**Issue by SethTisue** [playframework/playframework#7729]
seen in the Scala 2.12 community build at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/1794/consoleFull:

```
[play-core] [info] CachedSpec
[play-core] [info] 
[play-core] [info] the cached action should
[play-core] [error]   x cache values using injected CachedApi
[play-core] [error]    '2' != '1' (CachedSpec.scala:37)
```

the problem seems to be intermittent, as the next run was green.

not sure if it's related, but @richdougherty also recently reported an intermittent CachedSpec failure at https://github.com/playframework/playframework/pull/7676#issuecomment-318945603

**Comment by richdougherty** [comment]
Thanks @SethTisue, we'll take a look.

**Comment by mkurz** [comment]
This is not really a bug. Because of #7649 - which made the async cache api really asynchronous - it is now likely that a cache operation runs on a different thread (than the caller of such a cache operation) which might not be finished yet when we call the second cache operation in the tests.

What we need to do here to make the tests pass is add a `Thread.sleep` to make sure the called thread has time to finish it's cache operation - like we did in #7649 in one test:
https://github.com/playframework/playframework/pull/7649/files#diff-c94809c749e1e3a1ed1aa3b96861f95bR89

I can provide a PR tomorrow - I am just too tired right now.

**Comment by richdougherty** [comment]
Thanks @mkurz.

**Comment by mkurz** [comment]
@richdougherty See #7734

**Comment by richdougherty** [comment]
@SethTisue, are you just building the _master_ branch or do you want this fix backported to the stable _2.6.x_ branch too?

**Comment by richdougherty** [comment]
Actually I guess we should make the test more reliable on _2.6.x_ anyway. :)

**Comment by SethTisue** [comment]
we're using master
