### ISSUE TITLE
Fix publishing of microbenchmarks project

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#7743]
See the comment here https://github.com/playframework/playframework/pull/7730#issuecomment-323831963:

> This will also affect other tasks besides publishing. So, for example, play-microbenchmark won't be compiled together with the root project when calling sbt compile. I think publishedProjects name here is misleading.
>
> We must use .enablePlugins(PlayNoPublish) instead, so the project won't be published, but other tasks will run as expected.

**Comment by gmethvin** [comment]
I also wanted to make sure the whitesource task didn't get run for microbenchmarks, since it's not something we actually distribute. It causes trouble because JMH is flagged as "GPLv2" for the license, even though technically it's GPL with classpath exception. Either way I think it's best not to report on libraries/licenses that have no effect on the end product.

**Comment by richdougherty** [comment]
OK @gmethvin thanks for explaining. I would like the microbenchmarks to be part of the main project so that we can ensure they don't rot. I'll try to figure out a way that does this and still works with whitesource.

**Comment by marcospereira** [comment]
I think it would be enough to have `.disablePlugins(PlayWhitesourcePlugin)` in microbenchmarks project.
