### ISSUE TITLE
Dependencies using ehcache cannot be tested

### ISSUE THREAD

**Issue by nemoo** [playframework/playframework#7786]
Scala 
Play 2.6.3 
Windows
jdk 1.8

I am trying write automated tests for my play application. The application contains classes that use the vanilla play cache and ehcache as the default implementation without any tweaks.
This is how I inject the cache: 
`@Singleton
class TaskRepo @Inject()(cache: AsyncCacheApi)
                        (protected val dbConfigProvider: DatabaseConfigProvider) extends DAO{`

The **expected behaviour** would be that I can run automated tests of my play application using Scalatest (or Specs2).

The **actual behaviour** is that the tests throw errors:

```
[info] 6) Error in custom provider, play.api.cache.ehcache.EhCacheExistsException: An EhCache instance with name 'play' already exists.
[info]
[info] This usually indicates that multiple instances of a dependent component (e.g. a Play application) have been started at the same time.
[info]
[info]   at play.api.cache.ehcache.EhCacheModule$$anonfun$$lessinit$greater$1.bindCache$1(EhCacheApi.scala:76):
[info] Binding(interface net.sf.ehcache.Ehcache qualified with QualifierInstance(@play.cache.NamedCache(value=play)) to ProviderTarget(play.api.cache.ehcache.NamedEhCacheProvider@f37e004)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
[info]   while locating net.sf.ehcache.Ehcache annotated with @play.cache.NamedCache(value=play)
[info]   at play.api.cache.ehcache.EhCacheModule$$anonfun$$lessinit$greater$1.bindCache$1(EhCacheApi.scala:77):
[info] Binding(interface play.api.cache.AsyncCacheApi qualified with QualifierInstance(@play.cache.NamedCache(value=play)) to ProviderTarget(play.api.cache.ehcache.NamedAsyncCacheApiProvider@659598e2)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
[info]   while locating play.api.cache.AsyncCacheApi annotated with @play.cache.NamedCache(value=play)
[info]   while locating play.api.cache.AsyncCacheApi
[info]     for the 1st parameter of models.TaskRepo.<init>(Task.scala:31)
[info]   at models.TaskRepo.class(Task.scala:30)
[info]   while locating models.TaskRepo
[info]     for the 2nd parameter of controllers.Admin.<init>(Admin.scala:18)
[info]   while locating controllers.Admin
[info]     for the 3rd parameter of router.Routes.<init>(Routes.scala:34)
[info]   while locating router.Routes
[info]   while locating play.api.inject.RoutesProvider
[info]   while locating play.api.routing.Router
[info]     for the 1st parameter of play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:222)
[info]   while locating play.api.http.JavaCompatibleHttpRequestHandler
[info]   while locating play.api.http.HttpRequestHandler
[info]     for the 6th parameter of play.api.DefaultApplication.<init>(Application.scala:236)
[info]   at play.api.DefaultApplication.class(Application.scala:235)
[info]   while locating play.api.DefaultApplication
[info]   while locating play.api.Application
[info] Caused by: play.api.cache.ehcache.EhCacheExistsException: An EhCache instance with name 'play' already exists.
[info]
[info] This usually indicates that multiple instances of a dependent component (e.g. a Play application) have been started at the same time.
[info]
[info]  at play.api.cache.ehcache.NamedEhCacheProvider$.getNamedCache(EhCacheApi.scala:125)
[info]  at play.api.cache.ehcache.NamedEhCacheProvider.get$lzycompute(EhCacheApi.scala:110)
[info]  at play.api.cache.ehcache.NamedEhCacheProvider.get(EhCacheApi.scala:110)
[info]  at play.api.cache.ehcache.NamedEhCacheProvider.get(EhCacheApi.scala:108)
[info]  at com.google.inject.util.Providers$GuicifiedProvider.get(Providers.java:119)
[info]  at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
[info]  at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
[info]  at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
```

This project on github provides a reproducible test case:
https://github.com/nemoo/play-slick3-example/blob/silhouette/test/models/ModelScalaTestSpec.scala

**Comment by gmethvin** [comment]
Thank you for the example; I was able to identify the problem fairly quickly by looking at your test. The problem is that your `Injector.inject` helper is using `(new GuiceApplicationBuilder).injector()`. In other words, it's creating an entirely new injector with the default settings (as if for a new application) each time you try to `inject` an instance of something.

This means if you `Injector.inject` two things in succession that each need Ehcache, you'll end up with two instances of Ehcache, which is why you get the exception above. If you got both components from the same injector, only one Ehcache instance would be created since the `EhCacheApi` is scoped as Singleton.

The problem here is global state, but it's not Play's global state. It's Ehcache's global state, which I'm not sure it's worth doing much about.

**Comment by nemoo** [comment]
I dont think I fully understand. I thought putting the injector inside of an Injector **object** made sure that a new injector is NOT created on each call of the inject method?
https://github.com/nemoo/play-slick3-example/blob/silhouette/test/testhelpers/Injector.scala

**Comment by gmethvin** [comment]
I'm sorry. I must have misread your code (I thought the `lazy val` in your `Injector` was a `def`). Please disregard my comment.

**Comment by gmethvin** [comment]
It appears that two instances of ehcache are being created in this case: 
 1. Your `Injector` helper creates a new `GuiceApplicationBuilder` and obtains the injector from that, which tries to create an instance of ehcache when needed for your `ProjectRepo`.
 2. Your `WithApplication` block in specs2 or `GuiceOneAppPerTest` in ScalaTest is used to create a new application for each test. Since your application depends on the cache api, a new instance of ehcache is being created for each test.

In particular, the error is happening because, by default, Play will attempt to create all the caches it binds for you in the cache module. This implicitly includes the default cache (named "play"). If you set `play.cache.createBoundCaches = false` that might work. In general, though, ehcache requires global state, and so do some of the components that use it, so you might run into problems if you try to share that state across test applications.

The best solution to this in your tests is to use the injector provided by the application to get your instances, rather than a global static injector instance. For example, you could modify your scalatest code to look something like this:

```scala
class ModelScalaTestSpec extends PlaySpec with GuiceOneAppPerTest with BeforeAndAfterEach {
  var db: Database = _
  var projectRepo: ProjectRepo = _
  
  override def fakeApplication(): Application = {
    val app = super.fakeApplication()
    db = app.injector.instanceOf[DatabaseConfigProvider].get[JdbcProfile].db
    projectRepo = app.injector.instanceOf[ProjectRepo]
    val lifecycle = app.injector.instanceOf[ApplicationLifecycle]
    lifecycle.addStopHook(() => Future.successful(
      Evolutions.cleanupEvolutions(app.injector.instanceOf[DBApi].database("default"))
    ))
    app
  }
  // tests
}
```

**Comment by nemoo** [comment]
Thanks a lot! Your proposed solution work perfectly!

**Comment by todor-kolev** [comment]
What do you do if you have multiple test suites that need to use the cache? Do you need to use a global app for all of them or...?

**Comment by GeReinhart** [comment]
I've found a solution for multiple test suites : 
https://stackoverflow.com/questions/39453838/play-scala-2-5-testing-classes-injecting-cache-leads-to-an-error?answertab=active#tab-top
