### ISSUE TITLE
Reusable block in Play 2.6 cannot render an image from its URL

### ISSUE THREAD

**Issue by raychenon** [playframework/playframework#7920]
### Are you looking for help?

Yes, this issue has been posted on https://stackoverflow.com/questions/46547126/cannot-embed-image-url-in-play-2-6-reusable-block but remained unanswered

Not sure if this is a bug or I miss a configuration.

### Operating System (MacOS 10.10)

MacOS 10.10 on local , Linux on server

### JDK (Oracle 1.8.0_121)

jdk1.8.0_121.jdk
java version "1.8.0_121"

### Expected Behavior

1. go https://testtableofcontents.herokuapp.com/thankyou
2. See the code of this reusable block https://github.com/raychenon/play-table-of-contents/blob/feature/%2318-migration-play-2.6/app/views/thankyou.scala.html

**or**

1. go https://testtableofcontents.herokuapp.com/thankyou
2. press on the button "**Submit**"
3. Notice the images inside iframe cannot be displayed.

### Actual Behavior

In Play 2.5.9 , I could embed images in a reusable block. 
Since migrating to Play 2.6.3 , the same reusable block code cannot display those images .
See https://github.com/raychenon/play-table-of-contents/blob/master/app/views/thankyou.scala.html#L5

###  Please provide a PR with a failing test.
  
The PR with issue https://github.com/raychenon/play-table-of-contents/pull/19

See the code of this reusable block https://github.com/raychenon/play-table-of-contents/blob/feature/%2318-migration-play-2.6/app/views/thankyou.scala.html

Any idea ? I'm pretty sure I miss something in `application.conf`

**Comment by gmethvin** [comment]
As answered on StackOverflow, this is an issue with your `Content-Security-Policy` settings. I can tell because I see these errors in the console in Chrome:

> thankyou:2 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-QuogFfQ9ITWgKU6SvhyJEnSPVaxgC/AsNiuwT7QcD4Q='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
thankyou:6 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-Wi3+8jbn12vus9Oq4FOqEUCOpuRG3clBaVvLZZ2b9Fs='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.
thankyou:3 Refused to frame 'https://ghbtns.com/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
thankyou:4 Refused to frame 'https://ghbtns.com/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.

You probably want to add `ghbtns.com` to your CSP `child-src`.

The enabling of SecurityHeadersFilter by default is described in the [migration guide](https://www.playframework.com/documentation/2.6.x/Migration26#SecurityHeadersFilter).
