### ISSUE TITLE
Evolutions doesn't work when 0 is at the begining of the file

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#7976]
### Play Version (2.5.x / etc)
2.6.6

### API (Scala / Java / Neither / Both)
Neither

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### Library Dependencies
N/A

### Expected Behavior
When evolutions file are named: 01.sql, 02.sql (or even 001.sql) evolutions should work correctly

### Actual Behavior
When files are named 1.sql, 2.sql evolutions work fine, but with 01.sql doesn't work at all

BTW. [Documentation](https://www.playframework.com/documentation/2.6.x/Evolutions#Transactional-DDL) says ```evolutions.autocommit=false``` while it should be ```play.evolutions.autocommit=false```

**Comment by cchantep** [comment]
Hi, BTW the naming is explicitly documented in the page referenced by the mentioned link: 

> The first script is named 1.sql, the second script 2.sql, and so on…

**Comment by cchantep** [comment]
Not having a leading 0 doesn't prevent to go up to 10 and more.

**Comment by eximius313** [comment]
yeah, and every IDE sorts it as:
```
1
10
11
2
20
```
funny as hell ;)

**Comment by cchantep** [comment]
@eximius313 You can find it "funny", but not everybody is using an IDE, nor the same as yours,  moreover the fact that your IDE doesn't list the evolution as you would expect it doesn't mean there is a blocker on Play side about evolution execution/management.

A custom file naming could be discussed as improvement, on the [MailingList](https://groups.google.com/forum/#!forum/play-framework) first as indicated on the [guidelines](https://github.com/playframework/playframework/blob/master/CONTRIBUTING.md).

**Comment by marcospereira** [comment]
Is this "the same" as #6919?

**Comment by mkurz** [comment]
@marcospereira I don't think so. #6919 is about on how to (completely) customize the evolutions scripts filenames - which can already be achieved by implementing your own `EvolutionsReader`. I did assign #6919 to me a while ago because all that needs to be done is to update the documentation with an example of an `EvolutionsReader`.

This issue here is about the "limitation" that Play doesn't accept `1.sql` prefixed with zeros (like `01.sql`, `001.sql`, etc.) *out of the box* by default to have the files ordered nicely in an IDE. Of course you could write your own `EvolutionsReader` to achieve that. However @eximius313 argues that this behaviour should be built-in Play already, which I agree with.

I will provide a pull request :smile:

**Comment by mkurz** [comment]
Pull request: #7978

**Comment by eximius313** [comment]
@mkurz, you understood perfectly what I meant ;)
