### ISSUE TITLE
Please support Project Lombok in Twirl templates

### ISSUE THREAD

**Issue by eximius313** [playframework/playframework#7977]
### Play Version (2.5.x / etc)
2.6.6

### API (Scala / Java / Neither / Both)
Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Windows 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### Library Dependencies
[Project Lombok](https://github.com/rzwitserloot/lombok)

### Expected Behavior
Lombok is widely adopted library that generates all the boilerplate code (that you really don't want to code) for you. 
I know, that PlayFramework has it's Enhancer, but Lombok can do much more and even you are suggesting to use it [for logging](https://github.com/playframework/playframework/search?utf8=%E2%9C%93&q=lombok&type=), so I'd really love to see it working in PlayFramework.

### Reproducible Test Case
When I have my simple class:
```
//@Getter
//@Setter
public class MyClass {
  private String name;
}
```
and I uncomment ```@Getter``` and ```@Setter```, I can immediately use it in my Controller:
```
public Result test() {
    MyClass myClass = new MyClass();
    myClass.setName("Name");
    return ok(myClass.getName());
  }
```
but in Twirl Template:
```
@(myClass: MyClass)

@myClass.getTest
```
I get:
```
value getTest is not a member of myproject.MyClass
```

However if I comment this line:
```@myClass.getTest```
refresh or recompile the project and then uncomment the line - everything works fine.

Unfortunately this makes Project Lombok almost unusable in templates, because if you use your class in 100 templates, after each change in this class you'd comment all 100 lines and then uncomment them again.
Could you please fix it?

**Comment by marcospereira** [comment]
Hi @eximius313,

I'm not a Lombok user, but I suspect this is happening because of the order things are happening:

1. Twirl templates are compiled to Scala code
2. Scala code generated by Twirl is compiled
3. Lombok does its magic

So, since Lombok phase only happens **after** Twirl, then you get an error. As I said, I don't know how Lombok works, but a possible solution here is to move the classes that are annotated with Lombok annotations to a [subproject](https://www.playframework.com/documentation/2.6.x/SBTSubProjects) and add it as a dependency of the project containing the Twirl templates. This way, the phases would be:

1. Compile the subproject (including running the Lombok phase)
2. Twirl templates are compiled to Scala code
3. Scala code generated by Twirl is compiled

Moreover, the [mailing list](https://groups.google.com/forum/#!forum/play-framework) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help.

I'm closing this since it is not an issue in Play itself.

Thanks.

**Comment by mkurz** [comment]
@eximius313 Also see https://github.com/playframework/playframework/pull/4006#issuecomment-81049150 for additional information. Like Marcos said you have to put your classes/models that use lombok and that you want to use in twirl templates into a sub-project so you can use them in the main projects twirl templates.

**Comment by eximius313** [comment]
@marcospereira, what you proposed is clearly just a workaround not a solution, so I'd kindly ask you for reopening this issue.
Forcing someone to create artificial subproject in order to use such a widely adopted library is bad...

**Comment by mkurz** [comment]
@eximius313 
> Forcing someone to create artificial subproject in order to use such a widely adopted library is bad...

I think having the models in a sub-project isn't that bad. We use that approach for some of our projects and it turned out to be a good decision. This allows you to write different frontents(projects) for your models. E.g. think about the "normal" application you offer to your endusers and and admin panel only you should have access to. That could be two completely different applications sharing the same models/business logic via a sub-project. You could run that application on different containers/servers, etc. From a security perspective that is not a bad thing to do I think (enduser can't get access to the admin panel because of programming mistake because it lives in a different app for example).

> Do you think we should fill an issue for Scala compiler? Or can we use something else than "Mixed Mode" in Play?

As you can see from my linked comment I was trying different solutions two years ago and it turned out the sub-project approach is the best you can get right now. If I recall correctly no other compile mode really helped (but you can try).

lombok is an annotation processor which manipulates the Abstract Syntax Tree (AST) at compile time when `javac` kicks in. Eventually from that AST the bytecode will be generated. So the "problem" we have is the Java *source code* file does not expose the methods, etc. which will eventually show up in the *byte code*. As I understand Scala scans/parses Java files *source code* files so it knows about the annotations, methods, fields, etc. that Java *source code* files provides. However since the lombok generated methods, etc. are missing in the *source code* files Scala won't know about that methods of course.
So we need to provide Scala files (like the twirl templates) which access such "manipulated" java files the *byte code* of that java files - which already contains all the methods that lombok generated during the `javac` compilation phase. And right now we can do that only by putting lombok files into a sub-project.

Possible solutions (from scala side) would be that `scalac` implements its own Java compiler and also compiles `.java` files together with the `.scala` files in one step (and don't use a seperate `javac` step) which then also would have to run the annotation processors during that compilation.
Or during scanning/parsing the java files also somehow runs the annotation processors that would run when using `javac` so scala knows that the AST would/will be manipulated which results into different bytecode which may contains methods/field that don't exist in the source file before already.
However I don't think something like that will ever happen just because of lombok. I think it's fair from Scala to assume a Java source files ends up 1:1 in bytecode without any manipulation happening in between. The question is: Is what lombok is doing (manipulating the AST during compilation) a hack? If so then how scala works is completely ok. If it's not considers as hack to manipulate the AST during compilation then yes, scala should change.
However I leave that up to you to discuss with the Scala team since we are happy to just use the sub-project approach.

**Comment by eximius313** [comment]
@mkurz thank you for your very comprehensive reply
I'll go with sub-project

**Comment by domdorn** [comment]
@eximius313 I assume, you tried
`compileOrder in Compile := CompileOrder.JavaThenScala`
? ( http://www.scala-sbt.org/1.x/docs/Java-Sources.html )

**Comment by eximius313** [comment]
@domdorn I've tried, but this prevents you from using Scala-compiled objects (e.g. templates, routes) in Java classes (e.g. Controllers). 
So for obvious reasons this doesn't solve the problem

**Comment by slorber** [comment]
this comment explains better the problem: https://github.com/playframework/playframework/pull/4006#issuecomment-81049150

It looks like there is no good workaround :( creating a subproject would be hard in my case
