### ISSUE TITLE
Play sbt plugin shouldn't affect compiler flags

### ISSUE THREAD

**Issue by mberndt123** [playframework/playframework#8020]
Currently, `play.sbt.Play` contains code like this:
```scala
    PlaySettings.defaultSettings ++
      Seq(
        scalacOptions ++= Seq("-deprecation", "-unchecked", "-encoding", "utf8"),
        javacOptions in Compile ++= Seq("-encoding", "utf8", "-g")
      )
```
While this is certainly well-intended and I don't want to question the merits of these flags, I think it's the project developers who should decide what compiler flags they want to compile their code with, not the Play developers.

We stumbled upon this when trying to migrate to Play 2.6. The problem is that when combined with `-Xfatal-warnings` (which we use), `-deprecation` effectively makes it impossible to use deprecated APIs, and that's not a good thing because developers should be free to decide themselves when to take care of those. It is also highly surprising behaviour. We didn't set the `-deprecation` flag anywhere and it defaults to `false` so we spent some time pulling our hair trying to figure out how it crept into our `scalacOptions`.
Now of course it's possible to work around this, but I don't think that should even be necessary, and I therefore suggest removing these settings completely.

**Comment by gmethvin** [comment]
> We didn't set the -deprecation flag anywhere and it defaults to false so we spent some time pulling our hair trying to figure out how it crept into our scalacOptions.

How are you setting `scalacOptions`? You should be able to override Play's setting completely with `scalacOptions := Seq(...)`? That should allow you to set whatever custom options you want. It's not really a "workaround", just overriding a default.

FWIW, I believe the reason `-deprecation` was added was because otherwise sbt will give a warning like `there were 5 deprecation warnings; re-run with -deprecation for details`, and users are often confused about how to do that. Enabling `-deprecation` is also important for Play since we want to encourage users to upgrade deprecated APIs so we can evolve them quickly.

We could consider removing some of the options from the plugin and adding them to the starter templates instead, but I'd prefer to keep at least `-encoding utf8`. I believe the routes compiler, twirl, and possibly other parts of Play assume that source files should be UTF-8, and that's also a very reasonable thing for Play to be opinionated about.

**Comment by mberndt123** [comment]
Hey @gmethvin,

Thanks for responding. 
yes, I think that the starter templates are a more appropriate place for this. We fixed the problem by adding `scalacOptions -= "-deprecation; scalacOptions += `-deprecation:false` to our build. What I don't like so much about that is that when you start using `-=`, `:=` etc. it suddenly matters where in your .sbt files you put settings. That's not the case if you only use `+=` or `++=`. 

As for the routes compiler, yes, that probably makes sense. And I would argue that the `-encoding utf-8` stuff probably belongs in SbtTwirl or RoutesCompiler.

Anyway, this is not a big deal, I was just a bit annoyed because it took a while to figure out where that flag was coming from…

**Comment by cchantep** [comment]
I guess this can eventually go on with the MailingList, to check whether there is something actionable about.

**Comment by marcospereira** [comment]
Closing. As explained by @cchantep, it would be better first to decide if there is something actionable using our [forums](https://discuss.playframework.com).
