### ISSUE TITLE
AssetsConfiguration always emits warning

### ISSUE THREAD

**Issue by KarelCemus** [playframework/playframework#8092]
### Actual Behavior

1. start the application
2. see application log
3. there is always a warning something like:

```log
08:53:59 [warn] application Using the following cache for assets configuration:
	 enabledCaching = false
	 enabledCacheControl = false
	 defaultCacheControl = public, max-age=3600
	 aggressiveCacheControl = public, max-age=31536000, immutable
	 configuredCacheControl:
```

I suppose that warning logs should be emitted only when there is something wrong. However, PR #7996 introduced [this piece of code](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/controllers/Assets.scala#L262), which always logs the current configuration as a warning without any further explanation. 

I am wondering why. If this is a feature, it should be documented and I haven't found any note about it, thus it would be a documentation bug. Otherwise, I suggest to either remove the log, make it optional, e.g. through a separate logger, which can be turned off, or at least reduce its level.

**Comment by pettyjamesm** [comment]
No updates on this? Logging at WARN is annoying for those of us that want our logs to be useful, especially since INFO is enabled by default in the application logger.

Honestly it feels like this merits be a DEBUG level log entry at best and anyway and unconditionally logging at WARN implies something about the author's confidence in... something. Maybe the default values, the implementation, or likelihood of breaking existing applications.

**Comment by gmethvin** [comment]
I think this was added accidentally. We can remove the log in the next version or move to a lower log level.
