### ISSUE TITLE
[2.6.x] FakeRequest.withCookies/withSession/withFlash does not update headers

### ISSUE THREAD

**Issue by FranklinYinanDing** [playframework/playframework#8101]
### Play Version (2.5.x / etc)

2.6.x

### API (Scala / Java / Neither / Both)

Scala

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Change cookies via `FakeRequest.withCookies`, the new `RequestHeader` should return updated `headers` with updated `Cookie` header via `RequestHeader.headers`. (Same for session and flash)

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

1. The new RequestHeader would return old headers via RequestHeader.headers. (Same for session and flash)

Related to #8100

**Comment by mkurz** [comment]
See #9518

This is not a bug. This is expected since Play 2.6, introduced by #6695.
That pull request also added a small section about the change to the migration guide:
https://www.playframework.com/documentation/2.7.x/Migration26#Calling-FakeRequest.withCookies-no-longer-updates-the-Cookies-header

> ... If you still need the old behavior you can still use `Cookies.encodeCookieHeader` to convert the `Cookie` objects into an HTTP header then store the header with `FakeRequest.withHeaders`.

There is nothing we need to fix here.

**Comment by mkurz** [comment]
Play Java users please have a look here: #9882
