### ISSUE TITLE
Null values in session cause NPE when decoding

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#8114]
This error has been reported to me and I'm recording it here for further investigation. In Play 2.6.7 if you put `null` into a session value then session decoding will fail on subsequent requests.

```scala
context.session().put("idToken", null)
```

Error on decoding follows. In this case it happens when reading the CSRF token from the session.

```
play.api.mvc.DefaultJWTCookieDataCodec - decode: could not decode JWT: null
java.lang.NullPointerException: null
        at play.api.mvc.JWTCookieDataCodec$$anonfun$decode$4.apply(Cookie.scala:595)
        at play.api.mvc.JWTCookieDataCodec$$anonfun$decode$4.apply(Cookie.scala:595)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at play.api.mvc.JWTCookieDataCodec$class.decode(Cookie.scala:595)
        at play.api.mvc.DefaultJWTCookieDataCodec.decode(Cookie.scala:768)
        at play.api.mvc.FallbackCookieDataCodec$class.decode(Cookie.scala:754)
        at play.api.mvc.DefaultSessionCookieBaker.decode(Session.scala:95)
        at play.api.mvc.CookieBaker$class.decodeFromCookie(Cookie.scala:431)
        at play.api.mvc.DefaultSessionCookieBaker.decodeFromCookie(Session.scala:95)
        at play.api.mvc.request.DefaultRequestFactory$$anon$2.create(RequestFactory.scala:115)
        at play.api.mvc.request.DefaultRequestFactory$$anon$2.create(RequestFactory.scala:113)
        at play.api.mvc.request.LazyCell.value(Cell.scala:66)
        at play.api.mvc.RequestHeader$class.session(RequestHeader.scala:227)
        at play.api.mvc.RequestHeaderImpl.session(RequestHeader.scala:368)
        at play.filters.csrf.CSRFActionHelper.getTokenToValidate(CSRFActions.scala:392)
        at play.filters.csrf.CSRFActionHelper.tagRequestFromHeader(CSRFActions.scala:403)
        at play.filters.csrf.CSRFAction.apply(CSRFActions.scala:54)
        at play.filters.csrf.CSRFAction.apply(CSRFActions.scala:38)
        at play.core.server.AkkaHttpServer$$anonfun$13.apply(AkkaHttpServer.scala:250)
```

The code at `Cookie.scala:595` shows the problem:

https://github.com/playframework/playframework/blob/e7c9a45f73bc753fbfd4f7005574bee47d9f2996/framework/src/play/src/main/scala/play/api/mvc/Cookie.scala#L590-L595

Converting the `null` value to a `String` with `v.toString` is what seems to cause the error.

To fix this:
1. Work out what the behaviour was in Play 2.5 - we should probably stick to this behaviour. You can do this by creating a Play 2.5 project and testing a few values.
2. We can probably support nulls by having a null-safe conversion to a string instead of calling `v.toString`. We probably only ever get `String`s out of `claimMap` (but this needs to verified), so we can probably just use a cast. You can verify this behaviour by checking that we only ever put strings into the session, and checking how JWT handles serialization of values, e.g. are they all JSON strings.
3. If we don't support nulls then we should throw a NPE when we insert the null value into the session rather than when we decode the session on subsequent requests. However, I think we should probably support nulls if we can.

**Comment by MouslihAbdelhakim** [comment]
Hello @richdougherty can i work on this?

**Comment by gmethvin** [comment]
@MouslihAbdelhakim Yes, feel free to work on anything tagged "help wanted". If you want to discuss your strategy for solving it you can do so on this issue.

**Comment by MouslihAbdelhakim** [comment]
Hello @gmethvin,

1 - I will try to figure out if this is a bug present from the start or is it a regression, by trying to reproduce it on older versions.

2 - If it is a regression i'll try to re-implement the old behavior. If it is a bug, i will first look at the JWT standard to try and figure out how can we handle null values.

**Comment by MouslihAbdelhakim** [comment]
This issue is not a regression. Support for JWT cookies was added until version 2.6.10 with this commit d0e6bf0dbf04b7f4258fa76ff844f6bc224eb61a.

According to the [JWT standard](https://tools.ietf.org/html/rfc7519#page-5) Claim values can be any [JSON value](https://tools.ietf.org/html/rfc7159#page-5) including the literal name ```null``` the reson JWTCookieDataCodec#decode returns a Map[String,String] instead of Map[String,AnyRef] is because it overrides the CookieDataCodec#decode which is used to decode the output of the CookieDataCodec#encode(data: Map[String, String]): String, so it's reasonable to expect that JWTCookieDataCodec#decode will only process Strings.

To keep support for null values, I have tested two solutions: 
 * a safe solution, return an empty String if NPE is encountered.
```scala
def safeToString(anyRef: AnyRef, defaultValue: String): String = try {
      anyRef.toString
} catch {
      case e: NullPointerException => defaultValue
}
```
```scala
val defaultClaimValue = ""
data.asScala.map{ case (k, v) => (k, toStringOrElse(v, defaultClaimValue)) }(breakOut)
```
 * a more consistent solution, return a null if a null value was found.
```scala
def safeToString(anyRef: AnyRef): String = try {
      anyRef.toString
    } catch {
      case e: NullPointerException => null
    }
```
```scala
data.asScala.map{ case (k, v) => (k, safeToString(v)) }(breakOut)
```


All tests still pass with both solutions, in my opinion the second solution (returning nulls) should be implemented. the user will get what she puts.

which solution do you guys prefer?

**Comment by gmethvin** [comment]
@MouslihAbdelhakim The question @richdougherty was asking is whether the cookie encoding behavior in general is a regression from 2.5.x. JWT-encoded cookies are the default in 2.6.x so if switching cookies to JWT broke something then it is a regression. The 2.5.x behavior should be the same as the implementations provided by the `LegacyCookiesModule` in 2.6.x but I would test both.

The main argument I see for supporting `null` is to match the old behavior. If the legacy cookie encoding supported `null`, we should support it in the new encoding too. If not, it might be better to forbid nulls in a more explicit way, e.g. by checking when the cookie value is set.

Also, if we support nulls,  I would prefer to do an explicit null check, e.g. `if (v == null) null else v.toString` rather than catching `NullPointerException`.

**Comment by MouslihAbdelhakim** [comment]
@gmethvin Thank you so much for the feedback. I have reproduced the crash in multiple play application based on play framework 2.5 and 2.4, using both Java and Scala.

When ever a session contains a null value it crashes the application after an attempt of decoding its cookie.

Java's sessions lets the user:
 * create a session with a null value using:
https://github.com/playframework/playframework/blob/387489afd49b69bb94d8c8da3af42f0ce4dc1296/framework/src/play/src/main/java/play/mvc/Http.java#L2081-L2083
    
  * add a null value to a session using:
https://github.com/playframework/playframework/blob/387489afd49b69bb94d8c8da3af42f0ce4dc1296/framework/src/play/src/main/java/play/mvc/Http.java#L2098-L2101

Scala's sessions lets the user create a session with a null value,
https://github.com/playframework/playframework/blob/387489afd49b69bb94d8c8da3af42f0ce4dc1296/framework/src/play/src/main/scala/play/api/mvc/Session.scala#L19-L20



but adding a null value to a session throws an IllegalArgumentException.
https://github.com/playframework/playframework/blob/387489afd49b69bb94d8c8da3af42f0ce4dc1296/framework/src/play/src/main/scala/play/api/mvc/Session.scala#L42-L45


Should we throw an ```IllegalArgumentException("Cookie values cannot be null")``` when ever a user create or insert a null value into a session?

**Comment by gmethvin** [comment]
Thanks for the analysis @MouslihAbdelhakim!

Since it seems like we've never supported nulls before, I think it makes sense to check the values inserted into the session and throw `NullPointerException` immediately on nulls.

This is especially important in the Java API since nulls are an accepted convention in Java, whereas in Scala they are considered bad practice.

**Comment by gaurang-sawhney** [comment]
Is this issue already fixed by the require statement [here](https://github.com/playframework/playframework/blob/4de771202fabe90a6ab7f64ab56c46ce6c699696/framework/src/play/src/main/scala/play/api/mvc/Session.scala#L61).
Similarly Flash also have this check.

**Comment by mkurz** [comment]
@gaurang-sawhney is correct, this has been fixed, for both flash and session cookies, by #8832, which was even backported to 2.7.x: https://github.com/playframework/playframework/pull/8832/files#diff-66b1571391b621b37b6768a9ccc7f8aaae8c1a120a5330f1ebe26ffb944fd0d8R51
