### ISSUE TITLE
Latest Release under Github Releases Tab is 2.6.7

### ISSUE THREAD

**Issue by jlprat** [playframework/playframework#8139]
When going to the Releases tab in Github for the Playframework, the one flagged as latest release is 2.6.7. However, there are 3 newer releases but they are hidden and have no information nor links to changelog or the corresponding milestone.

**Comment by marcospereira** [comment]
Should be okay now.

Adding Github releases is not part of our automated release process, so I'm not sure it is something we need/should maintain.

**Comment by jlprat** [comment]
Thanks!
I was surprised because it was not consistent among releases.

**Comment by pettyjamesm** [comment]
I think the changelog is valuable for users that don't want to have to tail the github pulse and parse each PR for potentially relevant changes. Especially when the PRs don't tend to describe the "executive summary" level of detail. That said, since the changelog was also abandoned, at least using github releases is something.
