### ISSUE TITLE
Fix char encoding issues with sbt-header plugin

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework#8150]
On Windows I always get a `UnmappableCharacterException` when building Play. This is probably due to the recent upgrade to the new version of sbt-header. See https://github.com/sbt/sbt-header/issues/58. I can workaround the issue by adding `-Dfile.encoding=UTF8` into a `.jvmopts` file.

I also hear from @gmethvin that this issue can occur during a Play release, with the release still proceeding despite the error (or something confusing happens anyway). Note that I think he was using Linux for the release.

This is something that would be good to resolve. It may require a patch to sbt-header.

**Comment by mkurz** [comment]
IMHO this is not relevant anymore, because we now set 
https://github.com/playframework/playframework/blob/3a56c2a4efec9057aff6ccdb2ce394a5ddbc1198/.sbtopts#L6
(since Play 2.9 with this commit: https://github.com/playframework/playframework/commit/484b320f8ef07b8691449a1a4abe2c939b2fd782)

Also newer Java version default to UTF-8, so this problem will solve itself in a while: https://openjdk.org/jeps/400
