### ISSUE TITLE
[Enhancement] Make headers as TreeMultimap instead of Map<String, List>

### ISSUE THREAD

**Issue by PromanSEW** [playframework/playframework#8264]
I think this can be replaced with [Guava `TreeMultimap`](https://github.com/google/guava/wiki/NewCollectionTypesExplained#multimap):
https://github.com/playframework/playframework/blob/7bf56fef7711f9c40ec6995bc1885f6bd8647248/framework/src/play/src/main/java/play/mvc/Http.java#L514
What do you think?
I know that this change is breaking, so you can refuse this suggestion.

**Comment by martin-g** [comment]
I'd suggest to stay away from Guava as much as possible! Especially to use it in public APIs.

Guava is famous with its API breaks and removals of deprecated APIs in short time.
This is not bad thing but many other 3rd party libraries do not upgrade to latest Guava because some of the functionality is now missing and this leads to huge headaches.

**Comment by gmethvin** [comment]
Yeah, I think we should avoid relying on Guava for things, especially in the public API.
