### ISSUE TITLE
ProvisionException: Unable to provision, see the following errors

### ISSUE THREAD

**Issue by dhavaldesai1609** [playframework/playframework#8311]
ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, Configuration error: Configuration error[Cannot load class filters.ExampleFilter]
  at play.api.http.EnabledFilters.<init>(HttpFilters.scala:68)
  at play.utils.Reflect$.bindingsFromConfiguration(Reflect.scala:58):
Binding(class play.api.http.EnabledFilters to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)
  while locating play.api.http.EnabledFilters
  while locating play.api.http.HttpFilters
    for the 4th parameter of play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:222)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for the 6th parameter of play.api.DefaultApplication.<init>(Application.scala:236)
  at play.api.DefaultApplication.class(Application.scala:235)
  while locating play.api.DefaultApplication
  while locating play.api.Application

1 error

**Comment by gmethvin** [comment]
@dhavaldesai1609 It looks to me like you're trying to load a `filters.ExampleFilter` and that class does not exist. This is not a class provided by Play, but perhaps you copied configuration from an example that uses an `ExampleFilter` class.

Closing since this does not look like a bug in Play. You can use the discussion forum to get more general help: https://discuss.lightbend.com/c/play

**Comment by mthadian** [comment]
comment all 'ExampleFilter' in the application.conf file
