### ISSUE TITLE
Assets.scala assetAt(path: String, file: String, aggressiveCaching: Boolean) forget to closeUrlConnection when Resources.isUrlConnectionADirectory(connection) is false 

### ISSUE THREAD

**Issue by chinesejie** [playframework/playframework#8324]
Play Version (2.5.x / etc)
2.3.10

API (Scala / Java / Neither / Both)
Scala

Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
MacOS 10.10

JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Oracle 1.8.0_72

Library Dependencies
N/A

Expected Behavior
when use Resources.isUrlConnectionADirectory to open zip/jar file resource,  remember to  close the inputstream and then close the zipfile. 
Resources.scala#ZipResourceDirectory() do the right thing. 
But, when use Resources.scala#isUrlConnectionADirectory  to open zip/jar file resource, it only close the inputstream  and then return false, then the method of closeUrlConnection will never be used. 

If the jarfile has not been closed finally, java.util.zip.Inflater#end() will not be called. Native memory leak will happen. 

Actual Behavior
Assets.scala assetAt(path: String, file: String, aggressiveCaching: Boolean) forget to closeUrlConnection when Resources.isUrlConnectionADirectory(connection) is false

**Comment by marcospereira** [comment]
Hi @chinesejie, 

Unfortunately, we are not maintaining Play 2.3.x anymore since this is a pretty old release. Currently, only Play 2.6 and 2.5 are receiving updates and fixes.

Anyway, I took a look at the current code and it looks correct to me. There are two places where we call `url.openConnection`. First is: 

https://github.com/playframework/playframework/blob/20add4ca4000ead7791c23e98fdc1f09b6465892/framework/src/play/src/main/scala/play/api/controllers/Assets.scala#L545-L552

As you can see, there is a `finally` block closing the input stream for that URL connection. Second is:

https://github.com/playframework/playframework/blob/20add4ca4000ead7791c23e98fdc1f09b6465892/framework/src/play/src/main/scala/play/api/controllers/Assets.scala#L815-L834

Here the input stream is being closed by Akka Streams, after the source is consumed.

Given that, I'm closing this issue, but feel free to comment if you think we need to open it again. ;-)

**Comment by chinesejie** [comment]
hi, @marcospereira 
The problem is the second place. The code only close the input stream after the source is consumed.  
But Inside Resources.isUrlConnectionADirectory
`  def isUrlConnectionADirectory(urlConnection: URLConnection) = urlConnection match {
    case file: FileURLConnection => new File(file.getURL.toURI).isDirectory
    case jar: JarURLConnection =>
      if (jar.getJarEntry.isDirectory) {
        true
      } else {
        // JarEntry.isDirectory is rubbish....
        val is = jar.getJarFile.getInputStream(jar.getJarEntry) // 
        if (is == null) {
          true
        } else {
          is.close() // only close inputstream, the jarfile.close() has not been not called. Native memory leak of java.util.zip.Inflater will happen.  
          false
        }
      }
    case other => false
  }`


How do you think ?
