### ISSUE TITLE
Parameters are not properly parsed in play 2.6.x [&amp]

### ISSUE THREAD

**Issue by zafarella** [playframework/playframework#8362]
### Play Version
* 2.5.14
* 2.6.13

### API (Scala / Java / Neither / Both)

* Scala 2.11.8

### Operating System

* MacOS 10.13.3 

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

`"1.8.0_162"`

### Setup
routes file
```
GET  /*path/test  com.controllers.MyController.test(path: String, a: String, b: String)
```
Controller code:
```scala
 def test(path: String, a: String, b: String) = Action.async {
    Future {
      Ok(
        s"""
         a = ${a}
         b = ${b}"""
      )
    }
  }
```

### Expected Behavior
When you hit:

`http://localhost:9000/testpath/test?a=someVal&amp;b=123`

Using play `2.5.14` all is working as expected and the output is correct:
```
a = someVal
b = 123
```
However,
### Actual Behavior

When same endpoint hit using play `2.6.13`
it returns
```
Bad Request
For request 'GET /testpath/test?a=someVal&amp;b=123' [Missing parameter: b]
```
> `http://localhost:9000/testpath/test?a=someVal&b=123` works as expected on both versions.

Is it bug, or expected behaviour? It was really convenient though when it was working at `2.5.14`

**Comment by gmethvin** [comment]
This is probably just different behavior of the Akka HTTP server (now the default) when it comes to the separator for query parameters. I assume Akka follows the standard for [url encoded form data](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#url-encoded-form-data) when parsing the query string, only allowing `&` as a separator, whereas the Netty server allows both `&` and `;` as suggested in the [HTML 4.01 spec](https://www.w3.org/TR/html401/appendix/notes.html#h-B.2.2).

So before you had `a=someVal`, `amp` (empty value), and `b=123` treated as separate parameters, and now you have `a=someVal`, and `amp;b=123`. It's clearly a mistake that the HTML entity `&amp;` was sent in the URL instead of a plain `&`, so you should try to fix that.

I think the breaking change was probably unintentional, but I'd consider the new behavior "expected". At this point it's probably not worth trying to make semicolon as a separator work. This is the first time I've heard of that being a problem since the 2.6 release so I suspect few people were relying on that feature.

**Comment by cchantep** [comment]
Agree using `&amp;` instead of `&` shouldn't have been accepted as parameter separator, new behaviour is right.
