### ISSUE TITLE
Feature Request: RequestHandler should support async calls

### ISSUE THREAD

**Issue by tikheshaileshn** [playframework/playframework#8411]
### Current Behavior

`play.api.http.HttpRequestHandler` has method `def handlerForRequest(request: RequestHeader): (RequestHeader, Handler)`

Because of this user is forced make blocking calls in `handlerForRequest` method during request authentication. Request-authentication can be moved to Filter or Action itself, but RequestHandler is executed prior to Filters so that server doesn't need to process request-body if RequestHandler declines request. RequestHandler seems to be more appropriate where authentication can be implemented.

### Expected Behavior

 `def handlerForRequest(request: RequestHeader): Future[(RequestHeader, Handler)]`

This will allow developers to write async code in RequestHandler.

**Comment by schmitch** [comment]
actually a `RequestHandler` is not suitable for authentication. Also a `Filter` does not need to process the request-body.
You can just use `EssentialFilter` and it would work perfectly fine, without ever processing the request-body. 

Example:
```

import play.api.libs.streams.Accumulator
import play.api.libs.typedmap.{TypedEntry, TypedKey, TypedMap}
import play.api.mvc.{EssentialAction, EssentialFilter, Results}

object Authilter {
  case class User(username: String)
  val UserAttr: TypedKey[User] = TypedKey[User]("user")
}

class Authilter extends EssentialFilter {
  override def apply(next: EssentialAction): EssentialAction = {
    EssentialAction { requestHeader =>
      if (requestHeader.headers.get("Authorization").contains("123")) {
        next(
          requestHeader.withAttrs(
            TypedMap(TypedEntry(Authilter.UserAttr, Authilter.User("demo")))))
      } else {
        Accumulator.done(Results.Unauthorized)
      }
    }
  }
}
```

Having `def handlerForRequest(request: RequestHeader): Future[(RequestHeader, Handler)]` might not be suitable, because `Handler` most often already represents a action/stage that might be a async caller.
Also request handler is more suitable for having some kind of custom routing logic.

**Comment by wsargent** [comment]
Seconding @schmitch -- the only thing a requesthandler should do is return a `Handler` for a request. This should be all inside the same thread and the async boundary should be at the handler.
