### ISSUE TITLE
Upgrade to Akka HTTP 10.1.2

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#8464]
The Akka-HTTP team is [releasing `10.1.2` soon](https://github.com/akka/akka-http/pull/2058). This release introduces few interesting improvements.

I particularly would be interested to use:

 * `"Introduces "Graceful" Server Termination"`
 * almost all in `"Fixes and improvements in akka-http2-support"` (e.g. `Allow Http2 without negotiation/TLS`)

**Comment by schmitch** [comment]
this is blocked until akka-* and akka-http `2.13.0-M3` is released 

/cc @raboof

**Comment by bantonsson** [comment]
Found this issue while looking for a `2.13.0-M3` build of play. Both akka `2.5.12` and akka-http `10.1.2` are available for Scala `2.13.0-M3`.

Is there a Play release for Scala `2.13.0-M3`?

**Comment by schmitch** [comment]
actually the current master of play is on `2.13.0-M3`.

Which can be used with the snapshot repositories:

* https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/sbt-plugin_2.10_0.13/2.7.0-2018-06-12-8ef9e47-SNAPSHOT/
* https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play_2.13.0-M3/

(and this issue is about `akka-http` 10.1.x which play does only support on the master branch)

**Comment by mkurz** [comment]
`akka-http` was updated to version 10.1.3 on master via #8473 already.
