### ISSUE TITLE
502 and 504 errors experienced with load of 200 requests per second. 

### ISSUE THREAD

**Issue by dilipmys** [playframework/playframework#8512]
### Are you looking for help?

This is an issue tracker, used to manage and track the development of Play. It is not a support system and so it is not a place to ask questions or get help. If you're not sure if you have found a bug, or if you have a feature request, the best place to start is with either the [Discuss Play Forum](https://discuss.playframework.com) or [Stack Overflow](http://stackoverflow.com/questions/ask?tags=playframework).

### Play Version (2.5.x / etc)
2.6

### API (Scala / Java / Neither / Both)

Java

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Redhat 7

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

OpenJDK 1.8

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. HTTP status 200
2.
3.

### Actual Behavior

When we load 200 requests per second, the server returns HTTP status 502. The time out setting are made as below. 
play.server.http.idleTimeout = 180s
play.server.akka.requestTimeout = 300s 

Play server log reports no error. However, the nginx proxy server shows below error. 
recv() failed (104: Connection reset by peer) while reading response header from upstream, 
### Reproducible Test Case

Please provide a PR with a failing test.  

If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

**Comment by marcospereira** [comment]
Hi @dilipmys,

Our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. 

When starting a discussion in https://discuss.playframework.com, it would be useful to provide some code, how you are running the application and also how you are loading test it.

I'm closing this since, as explained above, it looks more like a discussion than an issue.

Best.
