### ISSUE TITLE
Unify and publish all common tools for play/lagom scripted tests

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#8588]
Both Play and Lagom scripted tests have custom tasks created to help assert the code reloads, make an HTTP/S request and check the response ([here](https://github.com/lagom/lagom/blob/f5ed4f1f2a0b05f6948489275793573238dab72a/dev/sbt-scripted-tools/src/main/scala/com/lightbend/lagom/sbt/scripted/ScriptedTools.scala#L28) and [here](https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/project/Build.scala)), validate file contents and more...

Lagom already groups and reuses some of them in `lagom-sbt-scripted-tools`.

**Comment by marcospereira** [comment]
Play situation is a little worse since we don't have something like `sbt-scripted-tools`. Because of that, there is code duplication between scripted tests, for example [here](https://github.com/playframework/playframework/blob/master/framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/project/Build.scala#L25), [here](https://github.com/playframework/playframework/blob/master/framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/project/Build.scala#L25), [here](https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/project/Build.scala#L31) and [here](https://github.com/playframework/playframework/blob/master/framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/project/Build.scala#L31).

A good solution here is to have `sbt-scripted-tools` in Play, publish it as an artifact and use/extend it in Lagom.

WDYT?

**Comment by ignasi35** [comment]
related to https://github.com/lagom/lagom/pull/2316
