### ISSUE TITLE
Moved files are getting deleted after moving from the temporary files

### ISSUE THREAD

**Issue by Sivabalarajan** [playframework/playframework#8788]
### Play Version (2.5.x / etc)
2.6.20

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Mac OS

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

### Library Dependencies
```
name := """play-scala-slick-example"""
version := "2.6.x"
lazy val root = (project in file(".")).enablePlugins(PlayScala)
scalaVersion := "2.12.6"
scalacOptions += "-deprecation"
scalacOptions += "-feature"
crossScalaVersions := Seq("2.11.12", "2.12.4")
libraryDependencies += guice
libraryDependencies += "com.typesafe.play" %% "play-slick" % "3.0.3"
libraryDependencies += "com.typesafe.play" %% "play-slick-evolutions" % "3.0.3"
libraryDependencies += "mysql" % "mysql-connector-java" % "8.0.13"
libraryDependencies += "com.typesafe.play" %% "play-mailer" % "6.0.1"
libraryDependencies += "com.typesafe.play" %% "play-mailer-guice" % "6.0.1"
libraryDependencies += specs2 % Test
libraryDependencies += ws
```

### Expected Behaviour
I want to upload the files and move the temporary files into a different location. The files moved to a new location should exist always

### Actual Behavior
I am uploading files and moving them into a different location using the given source code. I am able to move the file however the moved files are getting deleted after sometimes.

Used method: 
`picture.ref.moveTo(Paths.get(filePath).toFile, replace = true)`

Complete source code
// Ref:  [](https://stackoverflow.com/questions/50940871/how-to-carry-out-fileupload-in-playscala)
```
 def upload = Action(parse.multipartFormData) { implicit request =>
    Log.log(s"Upload: ${request.body.files.head}")
    val key = request.body.files.head.key
    request.body.file(key).map { picture =>
      val filename = Paths.get(picture.filename).getFileName
      val dataFolderPath = config.get[String]("datafolderpath")
      val filePath = s"$dataFolderPath$key"
      val dirFile = new java.io.File(filePath)
      createDirectoryIfNeeded(dirFile)
      picture.ref.moveTo(Paths.get(filePath).toFile, replace = true)
      Ok("File uploaded")
    }.getOrElse { // Redirect(routes.ScalaFileUploadController.index).flashing("error" -> "Missing file")
      Ok("File is missed")
    }
  }
```

### Reproducible Test Case
The source code is given above

**Comment by wsargent** [comment]
This is not a bug -- the moved files are still using the same inode.  You need to copy the file.

**Comment by Sivabalarajan** [comment]
I think we can replace 

`picture.ref.moveTo(Paths.get(filePath).toFile, replace = true)`

with 

`picture.ref.renameTo(Paths.get(filePath).toFile)`

in the documentation

**Comment by wsargent** [comment]
The delete will work on the filehandle, so since it's still using the same inode, a rename won't stop it from being deleted.  You need `Files.copy` here.

https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#copy(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.CopyOption...)

**Comment by Sivabalarajan** [comment]
Great and thanks for your help.

**Comment by wsargent** [comment]
Also see https://github.com/playframework/playframework/pull/4281

**Comment by snemarch** [comment]
@wsargent, this is a breaking change in 2.6.20 compared to previous versions. It also goes against the usage from the documentation – i.e. the ScalaFileUpload which @Sivabalarajan linked to shows using ref.moveTo, and has text like "Any temporary files that _are not moved_ are deleted" (emphasis mine).

I guess the documented behaviour was a bug fixed by #8614? Would it be possible/desirable to make ref.moveTo remove the file from the reaper's list?

**Comment by wsargent** [comment]
@snemarch It's not #8614, it's https://github.com/playframework/playframework/pull/8881#issuecomment-447430110 and https://github.com/playframework/playframework/issues/8885 at issue here.

**Comment by mkurz** [comment]
> It's not #8614, it's inode behavior of #4281 as described in [#8881 (comment)](https://github.com/playframework/playframework/pull/8881#issuecomment-447430110) -- the PR for this is #8885.

@wsargent @marcospereira I think your analysis here and in Marcos comment referenced above was wrong. I think this has nothing to do with the Inode and also not with the file reaper.

First: If I move or copy a file out of the play temp folder, the file reaper does not matter anymore, since it just lists the files in the play temp folder, checks the age of the files and deletes them if they are old enough.
If I did move a file out of this folder and the reaper starts seconds later, the file is just not there anymore, no matter if a moved file keeps the same Inode. The file reaper just missed the file.

The problem why the moved or newly copied file still gets deleted *after a while* is, because we also hold a "finalize" reference even to the newly created file (no matter if moved or copied). Therefore as soon as no reference is found anymore to the `TemporaryFile` and the GC kicks in, even the newly created file will be deleted (that is not desired probably if you moved the file out of the play temp folder).

I created #8954 with more details.
