### ISSUE TITLE
Publish Play using Scala 2.12.7+

### ISSUE THREAD

**Issue by NthPortal** [playframework/playframework#8792]
### Play Version (2.5.x / etc)

2.6.20-

### API (Scala / Java / Neither / Both)

Scala

--------

Due to a bug in scalac, Play has one or more bad classfiles (see scala/bug#10880 for details). The bug was fixed in Scala 2.12.7; however, [Play needs to be published using scala 2.12.7](https://github.com/scala/bug/issues/10880#issuecomment-390657643) (or higher) in order to not have bad classfiles.

**Comment by dwijnand** [comment]
Thanks for the ticket, @NthPortal!

We're in the process of releasing Play 2.6.21 and 2.7.0-RC1.

Due to https://github.com/scala/bug/issues/11207, which affects Akka (see the warning in Akka's 2.5.18 [release notes](https://akka.io/blog/news/2018/10/07/akka-2.5.18-released)) we were planning on staying on 2.12.6.

But that other Scala ticket makes things less clear.

🤔

I'll see what the various teams think.  If you have any suggestions/thoughts would love to hear them.

**Comment by NthPortal** [comment]
@dwijnand it looks like 2.12.8 should be out within a couple weeks (https://contributors.scala-lang.org/t/2-12-8-release/2594) - perhaps after that?

**Comment by dwijnand** [comment]
We decided to use Scala 2.12.7 for Play 2.7.0-RC1, and are thinking of postponing Play 2.6.21 until Scala 2.12.8 is out (preceded by an Akka release, and followed up on by a Lagom release - the Lightbend release train!)

**Comment by NthPortal** [comment]
It looks like Akka 2.5.19 (which was released a few days ago) was built using Scala 2.12.8

**Comment by dwijnand** [comment]
Yeah we should release Play 2.6.21...

**Comment by renatocaval** [comment]
@NthPortal, we are going to release 2.6.21 built with Scala 2.12.8. 

I'm closing this issue, therefore. Thanks.
