### ISSUE TITLE
[2.7.0-RC3]: Deadlock when running with `runProd` and trying to `kill` the process

### ISSUE THREAD

**Issue by marcospereira** [playframework/playframework#8805]
### Play Version

Play 2.7.0-RC3 (it was reported initially by @TimMoore for 2.7.0-M2).

### API

Scala & Java.

### Expected Behavior

When using `sbt runProd` on any sample application, and then trying to `kill` the process by its id, it should die.

1. `sbt runProd`
2.  `jps` and get the pid for `ProdServerStart`
3. `kill $pid`
4. Process dies.

### Actual Behavior

There is a deadlock.

1. `sbt runProd`
2. `jps` and get the pid for `ProdServerStart`
3. `kill $pid`
4. Deadlock.

See a thread dump here:

https://gist.github.com/marcospereira/35c692b3590c0d243054748a7ef6e846

### Reproducible Test Case

Reproducing with any sample application is possible.

**Comment by mkurz** [comment]
Is #8384 related somehow? (I didn't have a closer look)

**Comment by marcospereira** [comment]
@mkurz we need to verify that #8384 is valid. As far as I remember, it was working as expected:

1. For dev mode, we don't want to exit the JVM when the app's actor system terminates. That is because the actor system terminates for each reload.
1. For prod, the application is stopping when the actor system terminates.

Anyway, need to verify that for 2.6.x and 2.7.x to confirm it is invalid or not.

**Comment by ignasi35** [comment]
> It may be related to this override:

Actually, I think it's related to _this_ override:

https://github.com/playframework/playframework/blob/6b6ad962a2718e4dc4e19cd617e13554de4fecbe/framework/src/play/src/main/resources/reference.conf#L895

```
    # The dev mode actor system. Play typically uses the application 
    # actor system, however, in dev mode, an actor system is needed 
    # that outlives the application actor system, since the HTTP 
    # server will need to use this, and it lives through many 
    # application (and therefore actor system) restarts.
    dev-mode {
      akka {
        # Since Akka 2.5.8 there's a setting to disable all Akka-provided JVM shutdown
        # hooks. This will not only disable CoordinatedShutdown but also Artery or other
        # Akka-managed hooks.
        # See also ProdServerStart#start for overrides specific to Mode.Prod
        jvm-shutdown-hooks = on
...
```

I wonder if `runProd` is reading `play.akka.dev-mode.akka` settings instead of plain `akka`.

**Comment by ignasi35** [comment]
Even when using Coordinated Shutdown, Play remains the responsible to run the JVM shutdown hooks:

https://github.com/playframework/playframework/blob/5b4a2e0d4e88b7b8a54335e32fd2c8bf064263be/framework/src/play/src/main/resources/play/reference-overrides.conf#L63-L74

@marcospereira see (in the comments on the snippet above) the particular cases when `exit-jvm` should be `on`. I think thhe comment and implemntation are wrong.

Consider this note from the [`java.lang.Runtime#exit` docs](https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#exit-int-):

> If this method is invoked after the virtual machine has begun its shutdown sequence then if shutdown hooks are being run this method will block indefinitely. If shutdown hooks have already been run and on-exit finalization has been enabled then this method halts the virtual machine with the given status code if the status is nonzero; otherwise, it blocks indefinitely.)

I think a `SIGTERM` triggers the [execution of Play's JVM shuhtdown hook](https://gist.github.com/marcospereira/35c692b3590c0d243054748a7ef6e846#file-thread-dump-txt-L193) which causes Coordinated Shutdown to [run](https://github.com/playframework/playframework/blob/e07050ef0e7eaff7637bf2a7483a6483b96f7f85/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L393) and, [because Akka is setup to `exit-jvm` (but not the JVM hooks)](https://github.com/akka/akka/blob/fafc59b19d9b6fb6371c08cc16039caf64bdb05c/akka-actor/src/main/scala/akka/actor/CoordinatedShutdown.scala#L217) it [deadlocks](https://gist.github.com/marcospereira/35c692b3590c0d243054748a7ef6e846#file-thread-dump-txt-L284) on the [shutdown monitor](https://gist.github.com/marcospereira/35c692b3590c0d243054748a7ef6e846#file-thread-dump-txt-L205).

**Comment by ignasi35** [comment]
BTW: there's a [`scripted`](https://github.com/playframework/playframework/blob/38ef3ebb8bc7ba115bc91eafbc8da3f2233a1511/framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown/test#L4-L5) test covering a few shutdown scenarios.

**Comment by marcospereira** [comment]
> As a consequence, I'm not sure when should Akka have `exit-jvm` enabled.

I'm in doubt about it too. It looks like `off` is the best option here since Play is in control of application/process lifecycle.

**Comment by dwijnand** [comment]
@ignasi35 said he's going to work on this tomorrow.

**Comment by ignasi35** [comment]
I think the solution for this issue should be:

1. Play always overrides Akka defaults to completely take over the JVM shutdown hook (as is)
2. Play always overrides Akka defaults to disable `exit-jvm` (this is the actual change required). This means: update [the comment](https://github.com/playframework/playframework/issues/8805#issuecomment-439507082) in `reference.conf` and remove the actual override in `ProdServerStart`.
3. Lagom uses Akka's [reason-overrides](https://github.com/akka/akka/blob/master/akka-actor/src/main/resources/reference.conf#L1100-L1112) feature to enable `exit-jvm` [on cluster downing](https://github.com/lagom/lagom/blob/93cbacd98b1950b8f96e0ff3b7d0ea10451f9441/cluster/core/src/main/scala/com/lightbend/lagom/internal/cluster/JoinClusterImpl.scala#L37-L61).
4. [Document](https://www.playframework.com/documentation/2.6.x/JavaAkka#Akka-Cluster) how Play needs to be setup when using Akka Cluster on a Play Application (the steps would be same as implemented in Lagom on step 3.)
