### ISSUE TITLE
Add comprehensive test suite to how routers handle trailing slash

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#8850]
### Play Version (2.5.x / etc)

2.7.0-RC3

### API (Scala / Java / Neither / Both)

Java (at least) 

### Expected Behavior

In [play-java-rest-api-example](https://github.com/playframework/play-java-rest-api-example), invoking `http://localhost:9000/v1/posts` or `http://localhost:9000/v1/posts/` produces the same result. Note that application uses routes composition:

```
# conf/routes
GET     /                           controllers.HomeController.index
->        /v1/posts             posts.Routes
``` 

```post.routes

GET    /                     v1.post.PostController.list(request:Request)
POST   /                     v1.post.PostController.create(request:Request)

GET    /:id                 v1.post.PostController.show(request:Request,id)
PUT    /:id                 v1.post.PostController.update(request:Request, id)
```

### Actual Behavior

`curl http://localhost:9000/v1/posts` produces 404

**Comment by ignasi35** [comment]
Not a bug. See https://github.com/playframework/playframework/pull/8048

**Comment by dwijnand** [comment]
So an expected change in behaviour?  Is it documented sufficiently, would you say?

**Comment by ignasi35** [comment]
Could only find https://www.playframework.com/documentation/2.7.x/Migration27#Router#withPrefix-should-always-add-a-prefix

I'm still undecided but I understand the motivation in #8048 was to _fix_ a bug and with that mindset the current behavior is _the correct one_ (not a change, but a fix). Then, users relying on `/v1/posts` were actually exploiting a bug. Hmmm...

**Comment by dwijnand** [comment]
I've looked less than you, but I think using `/v1/posts` to get posts is hardly "exploiting a bug".

**Comment by ignasi35** [comment]
I think there's no other route (other than routes resulting from composition as described above) in Play that supports `missing trailing slash` by default. the only exception being the first `/ ` in the path segment which is mandatory in HTTP and clients will add if users doesn't:

```
$ curl -v http://localhost:9000
* Rebuilt URL to: http://localhost:9000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET / HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.60.0
> Accept: */*
```

I think #8048 was fixing an inconsistency caused by the routes composition.

I understand your point about "using /v1/posts to get posts" not being an exploit but it's inconsistent. Users preferring `/v1/posts` over `/v1/posts/` could rewrite the snippet above to:

```
# conf/routes
GET     /                           controllers.HomeController.index
->        /v1             posts.Routes
```
```
# conf/post.routes
GET    /posts                     v1.post.PostController.list(request:Request)
POST   /posts                     v1.post.PostController.create(request:Request)
...
```

But that doesn't scale well as we add more `conf/xyz.routes` route files as in:
```
# conf/routes
GET     /                           controllers.HomeController.index
->        /v1             posts.Routes
->        /v1             inventory.Routes ## this doesn't  work
```

-----------------

Maybe the solution should be to support:

```
# conf/routes
GET     /                           controllers.HomeController.index
->        /v1/posts             posts.Routes
->        /v1/inventory     inventory.Routes
```
```
# conf/post.routes
GET    /*                     v1.post.PostController.list(request:Request)
POST   /*                     v1.post.PostController.create(request:Request)
...
```
Where `*` indicates `/` is an optional character.

**Comment by dwijnand** [comment]
Yeah on the face of it I think we should provide a way to migrate that doesn't break every URL, but also allows for the posts + inventory routes composition.

Maybe `/*`, maybe a magic `ROOT`, or `[/]`, or an empty string, that is:

```
# conf/post.routes
GET                           v1.post.PostController.list(request:Request)
GET    /                      v1.post.PostController.list(request:Request)
POST   /                      v1.post.PostController.create(request:Request)
...
```

**Comment by ignasi35** [comment]
I've been discussing offline with @marcospereira and this sounds more and more like a regression we need to fix before 2.7.0

**Comment by ignasi35** [comment]
I think we need a PR to the `2.6.x` branch with a comprehensive test-suite. Then, we can forward-port it on a separate PR (with proper fixes) to the `2.7.x` and `master` branches.

**Comment by dwijnand** [comment]
Sounds like the right strategy.

**Comment by gmethvin** [comment]
#8854 restores the 2.6.x behavior, though I agree we should add more tests on both and decide on a proper way to handle trailing slashes in general.

**Comment by marcospereira** [comment]
> decide on a proper way to handle trailing slashes in general.

I see the following scenarios:

## Plain `conf/routes` file:

In other words, you are not composing routers but instead just using the generated one. So we can have:

```
GET    /                  controllers.HomeController.index
GET    /posts/list        controllers.PostsController.list
GET    /assets/*file      controllers.Assets.at(path="/public", file)
```

Here we should respect if there is or not a trailing slash. In the case of `*file`, today we document that it spans several `/`, so it makes sense to me that it matches both with and without a trailing `/`. Another argument in favor of this is that today it is the user responsibility to validate the raw URI segment.

## When composing routers

For example a `conf/posts.routes` and `conf/routes`, similar to what we have in the this issue:

```
# conf/routes
GET    /                  controllers.HomeController.index
GET    /assets/*file      controllers.Assets.at(path="/public", file)

->     /posts             posts.Routes
```

```
# conf/posts.routes
GET    /                  controllers.PostsController.list
POST   /                  controllers.PostsController.create

GET    /:id               controllers.PostController.show(id: Long)
```

Here I think that maintaining the behavior we have for 2.6.x is the better option. Meaning that `/posts`, `/posts/1` will match, but `/posts/` and `/posts/1/` won't.

But I doubt what should be the expected behavior if you define the sub-router with a prefix that includes a trailing `/`:

```
->     /posts/             posts.Routes
```

It looks like it should match `/posts/`, but not `/posts/1`. What do you think? Let's try to decide about the corner cases so that I can work on some scripted tests.

**Comment by gmethvin** [comment]
I'm thinking if the prefix is `/posts`, then both `/posts/` and `/posts` should work. If it is `/posts/` then only `/posts/` should work. In other words, the initial slash in the sub-router is "optional", and slashes are collapsed. This is what I did for `SimpleRouter` in #8854, but we ideally should implement it for generated routers as well.

I'm also fine with having both `/posts` and `/posts/` work regardless of whether the prefix has a trailing slash, but maybe some people are more particular about how it works.

**Comment by ignasi35** [comment]
> I'm thinking if the prefix is /posts, then both /posts/ and /posts should work. If it is /posts/ then only /posts/ should work.

This would introduce a small inconsistency. In the scenario:

```
# conf/routes
GET    /inventory                  ... (returns all inventory)
POST   /inventory                  ... (adds one item)
GET    /inventory/:id              ... (retrieves one item)
->     /posts             posts.Routes
```

```
# conf/posts.routes
GET    /                  controllers.PostsController.list
```

Then both `/posts` and `/posts/` works but only `/inventory` (and not `/inventory/`)  works. I find that confusing.

**Comment by ignasi35** [comment]
Unfortunately I don't have enough time these days to get into details with alternative implementations and discuss trade-off's further. :-(

**Comment by marcospereira** [comment]
To me, the ideal decision is the one that generates fewer surprises. The way I see this discussion so far this is the only point where we are not agreeing:

> I'm thinking if the prefix is /posts, then both /posts/ and /posts should work. 

Maybe what we need is a configuration to resolve with/without the trailing slash. Not sure if it should just match both or return a redirect (discussion for another issue?). For now, I'm okay with `-> /posts` matching both `/posts` and `/posts/` given that:

1. The reverse router should prefer the version without the trailing slash, since this is what we had matching for 2.6.x.
1.  And have this behavior consistent in both simple router and the generated router. @gmethvin I thought that #8854 fixed this for both. Is that correct?

**Comment by gmethvin** [comment]
@marcospereira 1 is implemented by #8854 but 2 is not. Supporting an optional slash on the generated router would be a bit more involved, so right now #8854 just matches the 2.6.x behavior of supporting either no slash or slash depending on whether the prefix has a trailing slash. 

The reason it's more involved is that the prefix string with or without the trailing slash is actually in the router's generated code, which is later transformed into a regular expression to match the route. Currently we model path patterns using `PathPattern`s, which contain a list of `PathPart`s. All literal strings, including slashes, are `StaticPart`s, so the prefix is handled by generating a `StaticPart` containing the prefix string and generating an additional `StaticPart` containing a lone slash if there are other path segments following.

There's currently no way to include an optional static part or optional slash, so we have to decide how to support that. We could have an `OptionalSlash` or `OptionalStaticPart` and add some logic for that, at the cost of some additional complexity. Alternatively, I think we could take a similar strategy to the `SimpleRouter` and add the prefix to the request target before passing it into the unprefixed router code, but I believe that would interfere with the `HandlerDef` attributes that are added to the request, so we'd need to make sure the prefix is added back in the tags. Any of these approaches would need to be well tested as well since they're touching lots of internals of routes generation.

**Comment by marcospereira** [comment]
Let's keep this open, but with a different focus on create a test suite for how routers handle trailing slashes.

**Comment by dwijnand** [comment]
Are we running out of issues?

**Comment by marcospereira** [comment]
Be my guest. :-)

**Comment by marcospereira** [comment]
To give a proper answer, I don't see the point of creating a new issue since all the discussion is here. It would just create a new level of indirection to read all the information and conversation regarding this matter.

But feel free to compile a new issue with all the information around here.

**Comment by ignasi35** [comment]
Part of the confusion on this discussion is caused by [a customization](https://github.com/playframework/play-samples/blob/2.7.x/play-scala-rest-api-example/app/RequestHandler.scala#L30) on https://github.com/playframework/play-samples/blob/2.7.x/play-scala-rest-api-example which handles the case of a missing slash.
