### ISSUE TITLE
Possible security issue: request A get result from request B

### ISSUE THREAD

**Issue by 0xbaadf00d** [playframework/playframework#8985]
### Description
When Play is on charge and Action composition is slow for any reasons, Play don't return the right result for a specific request. It could be a security issue and more dangerous if user A get result from user B request.

### Play Version
Play 2.6.21 (Java) with scalaVersion=2.12.8

### Operating System

CentOS 7 x64 and Windows 10 X64 (both up-to date)

### JDK

 java-1.8.0-openjdk-1.8.0.191-1

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. Call multiple URL 
2. Get right result

### Actual Behavior

1. Call multiple URL 
2. Get result from other calls

### Reproducible Test Case

Issue is reproductible by using Ajax calls.

![image](https://user-images.githubusercontent.com/1005086/51627468-77d10380-1f42-11e9-972f-47b2b8d2671d.png)

### Project with unit tests
[play-java-seed-bug-action.zip](https://github.com/playframework/playframework/files/2788559/play-java-seed-bug-action.zip)

Just use `sbt run` and go to `http://127.0.0.1:9000`

**Comment by mkurz** [comment]
You marked `UserSessionRequiredImpl` as `@Singleton`. That's the problem.
```java
@Singleton
public class UserSessionRequiredImpl extends Action<UserSessionRequired> {
```
When you remove the singleton it works correctly.

Because you marked this action as singleton, what happens is, that when getting an instance of a `UserSessionRequiredImpl` action, we always get the **same** instance:
https://github.com/playframework/playframework/blob/9ba5a9d67a561e3c13173fb31ba2530dfc883ffd/framework/src/play/src/main/scala/play/core/j/JavaAction.scala#L109
Instance is created by the injector here:
https://github.com/playframework/playframework/blob/9ba5a9d67a561e3c13173fb31ba2530dfc883ffd/framework/src/play/src/main/scala/play/core/j/JavaAction.scala#L200

You should know that for each action in the action composition chain the `delegate` property needs to be set on each action *instance*, so we know which action comes next (in the case here that would be the action method).

But because your action is singleton, all these concurrent requests set the `delegate` on the **same** instance:
https://github.com/playframework/playframework/blob/9ba5a9d67a561e3c13173fb31ba2530dfc883ffd/framework/src/play/src/main/scala/play/core/j/JavaAction.scala#L112
Now, if timing is right, it's possible that, at the time when calling `action.delegate`, this `delegate` was just modified by a concurrent request and points the final action method of that other request.

### **Conclusion: Never annotate your actions with `@Singleton`!**

I wouldn't count this as bug, but as something we probably should mention in the docs.

**Comment by 0xbaadf00d** [comment]
Thank you @mkurz ! Indeed, it would be interesting to put a big warning about the use of the Singleton annotation on filters and not just a small note

**Comment by mkurz** [comment]
Probably we should also actually log a warning when the singleton annotation is detected...

**Comment by mkurz** [comment]
> ...if user A get result from user B request.

Actually user A would get the path and/or query params from user B. The request/http.context instance should be ok. However still, leaking path/query params to another user is bad. Very bad.

I was thinking about this. I think we should not just warn, but throw an exception if an action is a singleton, given that it would then be possible that data from user A could leak to user B.
In your example project I also removed the thread sleep, and even without it I could reproduce the problem by hitting browser refresh a couple of times. So this clearly is/can be a security issue.

**Comment by mkurz** [comment]
I will provide a pull request later today...

**Comment by mkurz** [comment]
Turns out there is a note in the docs already:
> _**Note**: Every request **must** be served by a distinct instance of your play.mvc.Action. If a singleton pattern is used, requests will be routed incorrectly during multiple request scenarios._

https://www.playframework.com/documentation/2.6.x/JavaActionsComposition#Composing-actions

**Comment by mkurz** [comment]
See #8989
