### ISSUE TITLE
Logger swallows file and line numbers

### ISSUE THREAD

**Issue by benmccann** [playframework/playframework#909]
Using Play's Logger class instead of using Logback directly means that all log messages are shown as coming from Logger instead of the application code that invokes the logging. You can reproduce by changing the logging pattern in application-logger.xml to include the file and line number by putting %F:%L in the &lt;pattern&gt; section.

**Comment by dxxvi** [comment]
<i>the biggest reason we provide our own logger API is to make the log message lazily evaluated</i>: didn't slf4j already provide this feature with all the {}'s?
Your suggestion of using slf4j directly works perfectly for me. Now I can write <code>logger.debug("I am {} years old.", 2)</code> instead of <code>logger.debug("I am {} years old.", 2.asInstanceOf[AnyRef])</code> and have the correct line numbers.

**Comment by jroper** [comment]
Yes, but `logger.debug(s"I am $age years old")` is *much* nicer than writing `logger.debug("I am {} years old", age)`.  The first one reads fluently, the second one doesn't.  Plus, the first one performs much better than the second one, since the log message doesn't have to be parsed - it's parsed at compile time by the compiler.
