### ISSUE TITLE
Web Commands no longer working on 2.7.0 DevMode

### ISSUE THREAD

**Issue by mgilbertnz** [playframework/playframework#9107]
### Play Version (2.5.x / etc)
Play 2.7.0

### API (Scala / Java / Neither / Both)
Scala API

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Linux 4.20.14-200.fc29.x86_64

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)

### Library Dependencies
Play-Flyway 5.2.0 is affected by this issue
https://github.com/flyway/flyway-play

### Expected Behavior

When running in Dev mode, I expected the flyway-play web commands to be called.  Upon debugging the flyway-play sbt plugin I discovered that the hook that calls web command handlers has been removed.

Running the flyway-play test app in 2.6.20 the web command handler is called.
Running the flyway-play test app in 2.7.0 the web command handler is not called.

Debugging it's clear that this is caused by the removal of the following override in DevServerStart.scala
https://github.com/playframework/playframework/blob/master/transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala

The following override at Line 133 is present in 2.6.20 and has been removed in 2.7.0
```
override def handleWebCommand(request: play.api.mvc.RequestHeader): Option[Result] = {
  currentWebCommands.flatMap(_.handleWebCommand(request, buildLink, path))
}
```

Apologies for not providing a failing test, hopefully the above helps.

Cheers

**Comment by mkurz** [comment]
The WebCommands feature was not removed. It was moved inside application code, see: #7986
This means that now an the application will be started and _afterwards_ the webcommands will be called.

Because of that change we also had to do some modifications to Play's evolutions feature, see: #8592 and its fix #8875.
We also added an `ApplicationEvolutions.upToDate` method in #8943 which indicates if all evolutions where applied successfully already, please have a look how that works in the docs [here](https://www.playframework.com/documentation/2.7.x/Migration27#Application-starts-when-evolutions-scripts-need-to-be-applied-in-DEV-mode).

I guess Play-Flyway will have a similar problem and maybe needs something like `upToDate` as well?

**Comment by mgilbertnz** [comment]
Thanks for the quick and helpful reply!

**Comment by mkurz** [comment]
@mgilbertnz Could you fix your problem?

**Comment by mgilbertnz** [comment]
Hi @mkurz, @tototoshi has updated flyway-play and it's working now.

I'll close this issue as it isn't an issue with Play Framework.  Thanks again for your help earlier!

**Comment by mkurz** [comment]
Great! Good to hear it is working :+1:
