### ISSUE TITLE
Add ActorRef[T] JSON serialization for persistence command replyTo

### ISSUE THREAD

**Issue by dwijnand** [playframework/playframework#9345]
In Akka Persistence Typed the actor ref to respond to (old "sender") is now part of the message.  This means that it must be possible to serialise such an `ActorRef[T]`.

Part of #9278 ("Introduce a Play CQRS / Event Sourcing (write-side) incubating module")

**Comment by ignasi35** [comment]
This problem is solved in `akka-jackson` but needs solving for `play-json` users.

**Comment by renatocaval** [comment]
Some more info explain the current situation in Lagom.

---
Lagom handles serialization different for Scala and Java. 

For Java, it uses a marked interface (`Jsonable`) and behind the scenes use Jackson.

For Scala, we have the `JsonSerializerRegistry`. When defining a `PersistentEntity` the user has to provide a serializer registry. 

In Play, we could default to Jackson for both Scala and Java, but offer some facilities for integration with `play-json`. 

The serializers are trickier than we could think. Lagom takes care of the whole application setup. Lagom passes the serializer to the ActorSystem via `ActorSystemSetup`. To do the same in Play, we will need to have a hook where user code could declare some `ActorSystemSetup`. We need to think how we could do that I a way that would allow optional modules to use the hook. 

Such hook system will also be useful to add akka-management health-checks that requires dependency injection. That's another task, but again we need to keep it in mind when designing.

Than, on top of that, we need to know if Akka is already providing a Jackson serializer for `ActorRef[T]`. For `play-json`, I have built [one in the experiment](https://github.com/renatocaval/shopping-cart-scala/blob/akka-persistence-typed/shopping-cart/src/main/scala/com/example/shoppingcart/impl/AkkaTypedJsonSerializers.scala) which is not working because of the issue with `ActorSystemSetup` but that should be fixable.

**Comment by renatocaval** [comment]
On a chat with @ignasi35, we considered the option to have Lagom's PlayJsonSerializer moved into Play so users can optionally choose it over Akka's default - this should support serialization of `ActorRef[T]` + document migration concerns

**Comment by renatocaval** [comment]
The current decision is to let Scala users fallback to Akka Jackson for commands with a `replyTo:ActorRef[Reply]` and use `play-json` for the other cases.

There is a hidden case here, that we need to verify. Inter-node command serialization will go through Akka Jackson, but when returning the `Reply` at service level, we most probably will need a `play-json` serializer for it.

**Comment by renatocaval** [comment]
Issue https://github.com/lagom/lagom/issues/2371 to track it in Lagom.
