### ISSUE TITLE
Unable to change default 'max-uri-length' within play 2.6

### ISSUE THREAD

**Issue by ranjithv** [playframework/playframework#9356]
### Play Version (2.5.x / etc)
2.6.21

### API (Scala / Java / Neither / Both)
Scala

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Mac OS - Darwin Kernel Version 18.6.0

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_192"

### Library Dependencies
None

### Expected Behavior

max-uri-length setting should take effect in play 2.6.21 and allow characters more than `2048` default length

### Actual Behavior

Below config in my application conf. max-header-value-length is working fine but not the max-uri-length. I tried multiple combinations like `akka.parsing.max-uri-length` and `akka.http.parsing.max-uri-length` and still not working.
```
play.server {

  #The server provider class name
  provider = "play.core.server.AkkaHttpServerProvider"
  akka {
    max-uri-length = 8k // is not working
    max-header-value-length = 32k // seems to take effect and tested
  }
}
````

Error:
```
WARN [application-akka.actor.default-dispatcher-3] a.a.ActorSystemImpl [Slf4jLogger.scala:77] Illegal request, responding with status '414 Request-URI Too Long': URI length exceeds the configured limit of 2048 characters
```

More details - 
1) https://github.com/akka/akka/issues/17422
2) https://stackoverflow.com/questions/45249694/play-2-6-uri-length-exceeds-the-configured-limit-of-2048-characters

### Reproducible Test Case

Write a simple controller and test using curl to supply a very long request uri more than `2048 `characters length

**Comment by marcospereira** [comment]
`play.server` prefix does not translate to all Akka HTTP configurations, so what you need is to use Akka HTTP's configuration `akka.http.parsing.max-uri-length` as documented here:
https://doc.akka.io/docs/akka-http/current/configuration.html?language=scala
It is also possible that you need to configure it like explained here:
https://www.playframework.com/documentation/2.7.x/ConfigFile#Using-with-the-run-command

So that it will work as expected when running in dev mode.

Finally, our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Best.

**Comment by ranjithv** [comment]
Thanks @marcospereira! I figured it out from another stackoverflow but this below doc confused me. It would be better to explicitly mention for other akka settings use `akka.` directly.

https://www.playframework.com/documentation/2.7.x/ConfigFile#Using-with-Akka:
"In Play, Akka reads it's settings from within the play.akka setting, not from the akka setting."
