### ISSUE TITLE
sbt 1.3.0-RCx manual testing

### ISSUE THREAD

**Issue by ignasi35** [playframework/playframework#9504]
As part of the acceptance testing for sbt 1.3.0 there are a few areas worth looking into with manual tests (e.g.Play does some classloader magic in dev mode to implement hot reload):

- [ ] use the [`play-java-ebean`](https://github.com/playframework/play-samples/tree/2.7.x/play-java-ebean-example) to try out Play _evolutions_
- [ ] test code changes (with and without errors):
  - [ ] In Java/Scala code
  - [ ] in Twirl templates
  - [ ] In `application.conf` files
- [ ] Dist and then run in production mode
  - [ ] Locally
  - [ ] In a docker container

related https://github.com/lagom/lagom/issues/2112

**Comment by renatocaval** [comment]
@eed3si9n, similar to https://github.com/lagom/lagom/issues/2112, but for Play.

**Comment by eed3si9n** [comment]
@renatocaval I have issue here https://github.com/sbt/sbt/issues/4891.

Specifically for Play, there's a pending issue https://github.com/sbt/zinc/issues/690 that's failing on Community Builds as well (which may or may not be fixed during RC of 1.3.0 since it seems to also exist in 1.2.8), so I'm more interested in the result of play-samples.
