### ISSUE TITLE
Result returned by the fakeRequest() doesn't have Play session cookie

### ISSUE THREAD

**Issue by sasankad** [playframework/playframework#9518]
### Play Version (2.5.x / etc)
2.7.x

### Expected Behavior

**We had IntegrationTest Class which extends WithServer. With 2.5.x when we execute a fakeRequest, the Result had the play session cookie.** 

### Actual Behavior

**But once upgraded to play 2.7.3, the Result doesn't have session cookie.**

**Comment by renatocaval** [comment]
@sasankad, thanks for reporting this. 

I added this issue to the backlog, but it can take sometime before someone can find time to pick it. Would you be interested in sending a PR?

**Comment by marcospereira** [comment]
Hey @sasankad, even better if you can provide a reproducer.

**Comment by flostadler** [comment]
Hey I'd like to tackle this issue. Any heads up on where to start?

**Comment by marcospereira** [comment]
Hey @flostadler, I think the best way to start is trying to create a reproducer where you can debug the problem and see the differences between 2.5.x and 2.7.x. You can see in the docs how to write an integration test that uses `WithServer` and `fakeRequest`.

Let me know if you need some more help with it.

Best.

**Comment by mkurz** [comment]
This is not a bug. This is expected since Play 2.6, introduced by #6695.
That pull request also added a small section about the change to the migration guide:
https://www.playframework.com/documentation/2.7.x/Migration26#Calling-FakeRequest.withCookies-no-longer-updates-the-Cookies-header

> ... If you still need the old behavior you can still use `Cookies.encodeCookieHeader` to convert the `Cookie` objects into an HTTP header then store the header with `FakeRequest.withHeaders`.

There is nothing we need to fix here.

**Comment by mkurz** [comment]
Also see #8101

**Comment by dirkhillbrecht** [comment]
I'm stumbling upon this right now. The migration doc mentioned above says: "If you still need the old behavior you can still use Cookies.encodeCookieHeader to convert the Cookie objects into an HTTP header then store the header with FakeRequest.withHeaders." What does that mean? What is "Cookies.encodeCookieHeader"? Config setting? Static method? Where??? I mean, I have some code like this in Play 2.5 (Java):

```
/** Helper method */
public static RequestBuilder buildCall(Call call,Cookies cookies) {
  RequestBuilder retval=new RequestBuilder().method(call.method()).uri(call.url());
  if (cookies!=null)
    for (Cookie cookie:cookies)
      retval=retval.cookie(cookie);
  return retval;
}

/** Unit test calls */
Result result = Helpers.route(app,buildCall(routes.Contr.login(),null).bodyForm(form));
Assert.assertEquals(OK,result.status());
Cookies cookies=result.cookies();
result = Helpers.route(app,buildCall(routes.Contr.setOrga(x),cookies));
```

How do I rewrite this unit test code so that it runs on Play 2.6? How do I pass the session cookie in such a unit test between the calls?

**Comment by vasica38** [comment]
@dirkhillbrecht have you managed to solve the problem ?

**Comment by dirkhillbrecht** [comment]
No, @vasica38 , but I opened https://github.com/playframework/playframework/issues/9882 . You might add yourself there, so far nothing happened...

**Comment by schub** [comment]
> This is not a bug. This is expected since Play 2.6, introduced by #6695.
> That pull request also added a small section about the change to the migration guide:
> https://www.playframework.com/documentation/2.7.x/Migration26#Calling-FakeRequest.withCookies-no-longer-updates-the-Cookies-header
> 
> > ... If you still need the old behavior you can still use `Cookies.encodeCookieHeader` to convert the `Cookie` objects into an HTTP header then store the header with `FakeRequest.withHeaders`.
> 
> There is nothing we need to fix here.

@mkurz Sorry, if this is a stupid question, but the doc is about how to send a cookie along with a request. What I need to know is, how can a get a cookie from a response after a login endpoint is called.

**Comment by mkurz** [comment]
@schub If you question is still relevant, can you please give me more details? What do you mean with "...from a response after a login endpoint is called..."? You can call `request.getCookie("cookiename")` to get a cookie from a request....

**Comment by mkurz** [comment]
For Scala users the answer to this issue was given in https://github.com/playframework/playframework/issues/9518#issuecomment-547604774 already.

For Java users the problem is there is no obvious Java API available right now, please see https://github.com/playframework/playframework/issues/9882#issuecomment-776613577 for a workaround. (@vasica38 and @schub)
Let's continue the discussion in #9882
