### ISSUE TITLE
Why is there no Chinese document?

### ISSUE THREAD

**Issue by qq727127158** [playframework/playframework#9522]
![image](https://user-images.githubusercontent.com/22268134/62188436-fcdc2000-b39e-11e9-8253-cd920cbed974.png)

This doesn't seem very friendly to Chinese developers

**Comment by TimMoore** [comment]
Documentation translations rely on contributions from community members. If you'd like to contribute a Chinese translation, we would be very grateful!

You can read the [Play contributor guidelines](https://github.com/playframework/playframework/blob/master/CONTRIBUTING.md) for help on getting started.

**Comment by renatocaval** [comment]
It seems that none of the translations is available right now on the website.

**Comment by marcospereira** [comment]
@renatocaval it depends on the version, for example, https://www.playframework.com/documentation/fr/2.4.x/Home. Right now most of the translations are outdated and stopped in Play 2.4.x.

Anyway, I'm closing this issue since we won't do the translation to Chinese ourselves and this work should be track somewhere else.
