### ISSUE TITLE
 `sbt new playframework/play-scala-seed.g8` directory structure does not follow docs

### ISSUE THREAD

**Issue by patientplatypus** [playframework/playframework#9755]
After initiating a new scala play seed using the command `sbt new playframework/play-scala-seed.g8` I then looked at the next page (going from here: https://www.playframework.com/documentation/2.7.x/NewApplication to here: https://www.playframework.com/documentation/2.7.x/Anatomy) and find that the directory structure that was created is not listed.

For example, `app` has a `controllers` and a `views` folder, but no `models` or `assets` folders. I'm not sure if I can just add them or if this for java only. What am I missing?

**Comment by marcospereira** [comment]
Hey @patientplatypus, yes, you can just add them. :-)

They are documented because they are part of the convention adopted by Play. But they aren't part of the seeds because the seeds are supposed to be minimal.

Moreover, our [forums](https://discuss.playframework.com) would be a better place to discuss this. Github issues are for reporting bugs and feature requests in Play, not for general discussion and getting help. Given that, I'm closing this.

Best.
