### ISSUE TITLE
play.server.websocket.frame.maxLength configuration cannot be overwritten in some environment

### ISSUE THREAD

**Issue by HealthyPeace** [playframework/playframework#9784]
## Abstract
**play.server.websocket.frame.maxLength** configuration cannot be overwritten in some environment.

## Details
I'm writing an app utilizing WebSocket in Environment A shown below and I found WebSocket connections close every time I send binary larger than approx. 64kB.
This keeps the same even when I set **play.server.websocket.frame.maxLength = 256M** in application.conf.

Since 64kB is the default value of  the configuration, it seems that I cannot overwrite it in Environment A.

In Environment B, I can send binary larger than 64kB successfully when I set **play.server.websocket.frame.maxLength = 256M** in application.conf. I can even make WebSocket connections close intentionally by setting a small value to the configuration.

Therefore it seems that I can overwrite the configuration in Environment B.

## Environment A
- sbt 1.3.2
- Scala 2.13.1
- "com.typesafe.play" % "sbt-plugin" % "2.7.3"

## Environment B
- sbt 1.2.7
- Scala 2.11.8
- "com.typesafe.play" % "sbt-plugin" % "2.7.0"

**Comment by mkurz** [comment]
I think it makes sense to use latest Play 2.7.3 in both environments so we can make sure that a minor release is not the caues of this behaviour.

**Comment by HealthyPeace** [comment]
Hi, thank you for your comment.
 
I dug into the problem and found that the key difference is not versions of tools but how I refer the config file (application.conf).

My project structure is like below:
```
<project_root>/conf/application.conf
```
and play.server.websocket.frame.maxLength = 256M is set in application.conf.

## When I refer it with **-Dconfig.resource=application.conf** or without any option
the problem happens.

## When I refer it with **-Dconfilg.file=conf/application.conf**
the problem does NOT happen.

In the both cases 
```
println(configuration.get[Option[String]]("play.server.websocket.frame.maxLength"))
```
prints 
```
Some(256M)
```
but only the latter seems to use the value 256M.

Is this difference expected?

**Comment by mkurz** [comment]
I guess `-Dconfilg.file` was a typo here (should be `-Dconfig.file`)

Are you running your application in PROD mode?

**Comment by HealthyPeace** [comment]
Thank you for pointing the typo and it was fixed.
I'm running my app in DEV mode with IntelliJ IDEA.

**Comment by mkurz** [comment]
@HealthyPeace
First, please have a look at [this part of the documentation](https://www.playframework.com/documentation/2.7.x/ConfigFile#Using-with-the-run-command):
> ...In `run` mode the HTTP server part of Play starts before the application has been compiled. This means that the HTTP server cannot access the `application.conf` file when it starts...

Because in `DEV` mode (not in `PROD` however!) the backend server starts before the Play application starts, the backend server can not access the values defined in `application.conf`. More detailed: Usually, the configuration will be loaded with the classloader of the application. However, because the application was not started yet, it also did not add all the application files like files within the `conf/*` folder or a file defined via `-Dconfig.resource=...` to the classloader yet. Therefore, such config _resource_ will not be available to the backend server via the classloader in `DEV` mode. If you use `-Dconfig.file` however, the classloader does not matter because the file will be accessed directly (via filesystem read instead looking it up via classloader). That is why `-Dconfig.file` does work.
In `PROD` mode, this difference does not matter and everything should work without any problems. (Because in `PROD` the classloader already knows about the files the application provides).
So, `-Dconfig.file` can be seen as exception in what the docs say - it also works in `DEV` (`run`) mode.

So now, the real solution to the problem is to also define the values of the `play.server.*` keys via `PlayKeys.devSettings` in `build.sbt`:
```
PlayKeys.devSettings += "play.server.websocket.frame.maxLength" -> "256M"
```
So you have to define this configs twice: Once in `application.conf`, so they will be used in `PROD` mode (like every other config), and second via `PlayKeys.devSettings` (which will be used _only_ in `DEV` mode, but ignored for `PROD` mode), so the server knows about them even if there is no application started yet.
And once again: This just matters for configs which are under the `play.server.*` key (because this are the only keys used by the server) - all other config keys works as expected, no matter which mode you are in.

I hope that explains what's going on here.

**Comment by HealthyPeace** [comment]
Thank you for your detailed explanation. The problem mentioned in my first post must be a kind of it.

Considering your explanation, using **-Dconfig.file** rather than **-Dconfig.resource** seems much better for me, in that it is free from the necessity of duplicated configuration.

Anyway the problem was solved and I'm to close this issue.
