### ISSUE TITLE
Provide documentation around production hardening of Play apps

### ISSUE THREAD

**Issue by huntc** [playframework/playframework#981]
We don't appear to have this document - the nearest one I could find is:

http://www.playframework.com/documentation/2.1.1/Production

It'd be useful to discuss (for example) how back pressure can be handled e.g.:

    def db(queries: Int) = PredicatedAction(isDbAvailable, ServiceUnavailable) {
      Action {

involves the use of a custom action that composes other actions to check whether a predicate is true. If it is then the action is invoked, otherwise a ServiceUnavailable status is returned. In the above example the database is being checked in terms of its ability to service requests.

**Comment by wsargent** [comment]
Backpressure handling will be addressed through Akka Streams.  As far as generalized production hardening, I'm not sure where we'd start or stop -- setting up TLS, adding a load balancer, adding a security manager, disabling Java serialization, tweaking GC... there's an almost endless list.

There is a release checkilst at http://webdevchecklist.com/play-framework/ and parts of https://tersesystems.com/2013/04/20/play-in-practice/ are still valid, but I don't know that this can be done, realistically, because it's such a stretch goal.

**Comment by wsargent** [comment]
Maybe point people at http://www.atomic-squirrel.net/

**Comment by wsargent** [comment]
Closing... security is a huge project in itself, and as far as system reliabilty / backpressure goes, Lagom is  the answer to that question.

**Comment by nafg** [comment]
On Sat, Mar 19, 2016, 5:44 PM Will Sargent <notifications@github.com> wrote:

> Closing... security is a huge project in itself, and as far as system
> reliabilty / backpressure goes, Lagom is the answer to that question.
>

Huh??

**Comment by wsargent** [comment]
@nafg https://www.lightbend.com/lagom when @huntc was talking about production hardening, being able to respond reactively is a huge part of it.  Lagom is "Industrialized Play".

**Comment by huntc** [comment]
I remember my motivation for this issue. It was as a result of the techinpower benchmarks where I implemented DB integration. When using most DB Toolkits, I had to implement by own form of back pressure control. I don't see that anything has change there other than perhaps Slick having become reactive (which is probably the real solution for this issue).

**Comment by nafg** [comment]
So if you want to use Play in more demanding environments you have to
purchase something??

**Comment by wsargent** [comment]
Lagom's open source.  https://github.com/lagom/lagom

**Comment by schmitch** [comment]
I doubt that everbody needs Microservices. And Lagom is a Framework for Microservices.
However I still think that Hardening Play! can't be documented.
Mostly things just work fine, if you need something special you could built that. Other http framework's don't document such deep technically things, also I think TechEmpower is a pretty pretty bad benchmark since the real world looks very very different.

Actually that's what I like about Play! and other frameworks like play! (i.e. Django etc) you could do everything which pleases you. Hardening a Action against database Backpressure is mostly not needed, actually I doubt if it's even needed since you could do a lot of fancy things, like put your database stuff inside streams, put the inside actors, thead pools, resize your database, offload things, cache or whatever. It really depends on what you are doing. It's situation dependent and people who have issue's with pressure against their app mostly have good solutions for these problems.
