### ISSUE TITLE
[2.8.0] Regression in play.libs.Json.toJson

### ISSUE THREAD

**Issue by PromanSEW** [playframework/playframework#9922]
### Play Version

2.8.0

### API

Maybe both, Java checked

### Operating System

Windows 10 x64 Build 1909

### JDK

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

### Library Dependencies

Ebean

### Expected Behavior

1. Create Ebean model
2. Try to serialize it to JSON using Json.toJson(Object)
3. Get valid JSON object as result

### Actual Behavior

```
com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError)
```
Full stacktrace:
https://gist.github.com/PromanSEW/516b773df32555db821ad14a79f48579

I think this regression is in Jackson, not in Play
I migrated from 2.7.4 to 2.8.0 using migration guide

### Reproducible Test Case

https://github.com/PromanSEW/play-json-issue

**UPDATE:** As of 2.8.3 `StackOverflowError` is gone, but private Ebean fields are still serializing. See #10523

**Comment by PromanSEW** [comment]
Maybe this issue must be moved to `play-json` instead

**Comment by PromanSEW** [comment]
@rbygrave please can you take a look?

**Comment by rbygrave** [comment]
Response on the Ebean google group ... I'll copy it here:

Well it looks to me like the JSON marshalling is including the _ebean_intercept field.  This field in turn has a reference to persistenceContext ... which in turn can reference back to the entity  (so this is creating an infinite loop).

With Ebean enhancement we have the option of enhancing the _ebean_intercept field as transient.

Now generally we can't use Jackson to marshall entity beans into JSON because we usually have circular relationships via ManyToOne and OneToOne.
In general to marshall entity beans into JSON we'd use Ebean to do that (as Ebean handles these circular relationships etc).

e.g. Use Ebeans JsonContext instead of Jackson like:

```java
String asJson = DB.json().toJson(Tour.getTours());
```

**Comment by PromanSEW** [comment]
@rbygrave I try to fix this problem by custom serializer. But earlier all was working fine while serializing this model (TourType in my test case)

**Comment by PromanSEW** [comment]
@rbygrave I try to use `Ebean.json().toJson()` but got empty object without fields :(

**Comment by PromanSEW** [comment]
I fixed the problem by custom serializer
But it is still regression

**Comment by scartech** [comment]
I'm experiencing this same issue - infinite recursion (stack overflow) when using Json.toJson() for code that previously worked. I didn't use any of the RC versions, so I'm not sure if it was present there, but I'm seeing it in 2.8.0.

**Comment by PromanSEW** [comment]
@scartech use custom `JsonSerializer` before this issue will be fixed

**Comment by scartech** [comment]
@PromanSEW, thanks! I don't need to upgrade to 2.8.0 right away, so I think I'll wait for the fix. I've got a fairly large application that's using Json.toJson in quite a few places. It will be more efficient if I just wait to upgrade.

**Comment by marcospereira** [comment]
Thanks for reporting, @PromanSEW. 

> Maybe this issue must be moved to `play-json` instead

It is okay to keep it here. If anything, we can later move to play-ebean repository since it appears to be related to that.

> I'm experiencing this same issue - infinite recursion (stack overflow) when using Json.toJson() for code that previously worked.

Is your application also using Ebean?

**Comment by PromanSEW** [comment]
@marcospereira I provided the reproducible test case, what info do you need?

**Comment by scartech** [comment]
@marcospereira yes, I'm using Ebean also.

**Comment by PromanSEW** [comment]
@marcospereira I think regression is the result of using Akka's `ObjectMapper` in 2.8.0

**Comment by marcospereira** [comment]
> @marcospereira I think regression is the result of using Akka's `ObjectMapper` in 2.8.0

How so? Do you think some specific module is impacting it? It should be possible to confirm that by creating and using your own `ObjectMapper`. Do you have the time to further investigate this in your reproducer?

Best.

**Comment by PromanSEW** [comment]
@marcospereira I provided a reproducible test case with minimal code which have described problem

**Comment by marcospereira** [comment]
> Ebean has its own ObjectMapper for serializing models, and it was used before 2.8.0 by default because of play-ebean, I think.

I don't think that is the case. There is no code in play-ebean to configure `play.libs.json.Json` object mapper.

What I think is happening is that Jackson 2.10.x somehow is not working with Ebean. And your [comment here](https://github.com/playframework/playframework/issues/9922#issuecomment-566512189) makes me think that only using Ebean's `ObjectMapper` won't solve the problem.

>  Now I have to use custom serializer to fix issue

How is this custom serializer?

**Comment by PromanSEW** [comment]
```java
public class TourPrizeSerializer extends JsonSerializer<TourPrize> {
	@Override
	public void serialize(TourPrize prize, JsonGenerator gen, SerializerProvider provider) throws IOException {
		gen.writeStartObject();
		gen.writeNumberField("money", prize.money);
		gen.writeNumberField("exp", prize.exp);
		gen.writeStringField("type", prize.ptype);
		gen.writeStringField("name", prize.name);
		gen.writeNumberField("value", prize.value);
		gen.writeEndObject();
	}
}
```

**Comment by lupari** [comment]
For our project this issue is a blocker for upgrading to 2.8. While our data model is quite large and having relied on play-json's ability to deal with Ebean enhanced POJO's in lots of places, writing dedicated serializers for each case is not something we would like to do. Yes it could be done but I think this should work out of the box while both play-ebean and play-json being part of the same toolset endorsed by framework.

**Comment by scartech** [comment]
I'm in the same boat as @lupari. I have a pretty large application, so writing lots of serializers isn't feasible. We'll have to wait to upgrade until this is resolved unfortunately.

**Comment by marcospereira** [comment]
> writing dedicated serializers for each case is not something we would like to do

Luckily, you don't need to. :-)

A simpler workaround is to annotate your models with `@JsonIgnoreProperties({"_ebean_intercept", "_$dbName"})` so that those properties will be ignored. As @rbygrave, those are the properties that are triggering the circular reference.

I don't know if there is a way in Jackson to globaly ignore such fields, though.

**Comment by rbygrave** [comment]
> _ebean_intercept & _$dbName

As stated previously there is an option for ebean enhancement to add these fields with the transient modifier.  I _suspect_ Jackson would then ignore these fields. I have been considering making a change to the ebean enhancement such that those fields have by default the transient modifier because other serialisation libraries work by ignoring transient fields and it's likely to be the better default setting for this reason.

However, note that as I see it there is a general issue using Jackson with entity models (Ebean or JPA) in that - entity models frequently contain bi-directional relationships (A `@ManyToOne` + `@OneToMany` pair). Jackson is traditionally unable to serialise models like that (circular relationships).  Unless Jackson has introduced detection of that (I don't think it has) people will ONLY be able to use Jackson with models with uni-directional relationships (plus Jackson doesn't know about partially loaded entity beans).

It isn't clear to me that people understand this limitation of using Jackson with entity beans (Ebean or JPA).

> Ebean's ObjectMapper won't solve the problem.

Ebean's JSON marshalling will work in that it is built to deal with these issues (bi-directional relationships and partially populated entity beans etc). Without a doubt it would work.  People could use ebean-jackson when marshalling a mix of plain beans and entity beans - that is more work in that the ebean jackson module needs to be registered with the Jackson ObjectMapper . 

>  I tried to use DB.json().toJson() but got empty object without fields :(

@PromanSEW - You'd need to create an example / test case but LOTs of people use this and there are no known bugs.  Hard to say why you saw an empty result without actually having an example / test case but it is extremely unlikely you have found a bug here with Ebean's JSON marshalling (and more likely there is something wrong with the example).

**Comment by PromanSEW** [comment]
@rbygrave sorry, I mistakely wrote about Ebean's `ObjectMapper`. I tried to serialize `List<Model>` instead of `Model` itself. When I understood this mistake I forgot to edit my answer.

**Comment by PromanSEW** [comment]
@rbygrave what about adding support for serializing collections of beans by Ebean's `ObjectMapper`?
It will be useful when you need to serialize result of `ExpressionList.findList()`

**Comment by rbygrave** [comment]
@PromanSEW ... maybe outline more of what you mean?  Ebean's JsonContext can serialise collections of entity beans already.  

We need to be careful about talking about ObjectMapper as strictly speaking Ebean generally isn't using a Jackson objectMapper (it only uses a Jackson ObjectMapper for non entity bean complex types).

**Comment by PromanSEW** [comment]
@rbygrave I got empty object when I used `DB.json().toJson()` with `List<Model>`
This problem is reproducible in my test case here:

https://github.com/PromanSEW/play-json-issue/blob/4a133e2d0e69c4ad86c94ed2b97e0d27cc7e521b/tests/controllers/RestControllerTest.java#L25

Just uncomment this line and see console input while test is failing

**Comment by rbygrave** [comment]
I'd rather you create an Ebean test that runs without Play framework or review the existing Ebean tests which cover this like:
https://github.com/ebean-orm/ebean/blob/master/src/test/java/io/ebean/text/json/JsonContextTest.java#L44

There are a lot of uses of `DB.json().toJson()` in the Ebean tests.

**Comment by lupari** [comment]
I wonder if this was fixed in play-ebean 6 because I don't seem to be running into this problem any longer now that I got back to this after two months. I guess we were at play-ebean version 5 last time.

**Comment by onilton** [comment]
Hi guys, I may be late to the party, but I still got a problem related to this issue.

In my investigation, I found out that the main issue is related with `ObjectMapper's visibility` for fields. The previous default implementation used by Play 2.7 that came from Jackson was using PUBLIC_ONLY for field detection. 

From https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.10.5/src/main/java/com/fasterxml/jackson/databind/introspect/VisibilityChecker.java#L169 
```
       protected final static Std DEFAULT = new Std(
                Visibility.PUBLIC_ONLY, // getter
                Visibility.PUBLIC_ONLY, // is-getter
                Visibility.ANY, // setter
                Visibility.ANY, // creator -- legacy, to support single-arg ctors
                Visibility.PUBLIC_ONLY // field
                );
```

So
```
public class MyClass { private String myField }
// myField  won't be in the json
```
Now that Play 2.8 is using Jackson Serialization Support [[1]](https://www.playframework.com/documentation/2.8.x/Migration28#ObjectMapper-serialization-change), akka-serialization-jackson seems to be overriding visibility for fields to ALL (even private/protected ones)

From https://github.com/akka/akka/blob/v2.6.10/akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala#L248
```
 mapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)
```

So
```
public class MyClass { private String myField }
// myField  will be in the json
```

You can test that this is the problem by annotating your ebean with `@JsonAutoDetect(fieldVisibility = Visibility.PUBLIC_ONLY)`, the problem will be fixed.

**Comment by onilton** [comment]
Hi guys, I may be late to the party, but I still got a problem related to this issue.

In my investigation, I found out that the main issue is related with `ObjectMapper's visibility` for fields. The previous default implementation used by Play 2.7 that came from Jackson was using PUBLIC_ONLY for field detection. 

From https://github.com/FasterXML/jackson-databind/blob/jackson-databind-2.10.5/src/main/java/com/fasterxml/jackson/databind/introspect/VisibilityChecker.java#L169 
```
       protected final static Std DEFAULT = new Std(
                Visibility.PUBLIC_ONLY, // getter
                Visibility.PUBLIC_ONLY, // is-getter
                Visibility.ANY, // setter
                Visibility.ANY, // creator -- legacy, to support single-arg ctors
                Visibility.PUBLIC_ONLY // field
                );
```

So
```
public class MyClass { private String myField }
// myField  won't be in the json
```
Now that Play 2.8 is using Jackson Serialization Support [[1]](https://www.playframework.com/documentation/2.8.x/Migration28#ObjectMapper-serialization-change), akka-serialization-jackson seems to be overriding visibility for fields to ALL (even private/protected ones)

From https://github.com/akka/akka/blob/v2.6.10/akka-serialization-jackson/src/main/scala/akka/serialization/jackson/JacksonObjectMapperProvider.scala#L248
```
 mapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)
```

So
```
public class MyClass { private String myField }
// myField  will be in the json
```

You can test that this is the problem by annotating your ebean with `@JsonAutoDetect(fieldVisibility = Visibility.PUBLIC_ONLY)`, the problem will be fixed.

The main issue is that there is no mention to this fact in Play's documentation and also there doesn't seem to be a easy way to fix/override this settings. 

You will probably have to create your own module and override the ObjectMapper. By doing this, you will also lose the advantages of having Akka Jackson Serialization (and configs).

**Comment by onilton** [comment]
I am wondering if I should open a new issue for that. :thinking:

**Comment by onilton** [comment]
@marcospereira I am wondering if I should open a feature/bug request in akka (for customization of visibility), or a feature/bug request in playframework (for customization from Play's side).

I think the place we could override this setting in Play is this one:

https://github.com/playframework/playframework/blob/ddf3a7ee4285212ec665826ec268ef32b5a76000/core/play-java/src/main/scala/play/core/ObjectMapperModule.scala#L33

(The Akka is in the comment above)

**Comment by mkurz** [comment]
@onilton 

> I am wondering if I should open a feature/bug request in akka (for customization of visibility)...

I think you should, I think it should be a config in akka's `reference.conf`, so apps can override it. Would be interesting why they included private fields by default...

> ... or a feature/bug request in playframework (for customization from Play's side).

Yes, please also open a new issue in Play as well, so we don't lose track (also because your issue is a different one than the original one discussed here).

**Comment by PromanSEW** [comment]
Did #10508 fixed this issue?

**Comment by onilton** [comment]
@PromanSEW I have tested with the latest snapshot (2.8.3+8-3b197a7e-SNAPSHOT from Mon Nov 02 04:38:57 UTC 2020).

Unfortunately, no, it does not fix the issue.

**Comment by onilton** [comment]
@PromanSEW I was not able to run the tests at https://github.com/PromanSEW/play-json-issue/. The tests won't run.

Did I forgot something?

**Comment by PromanSEW** [comment]
@onilton I will update and check the project tomorrow. I ran tests from IDEA last time and they were worked... Well, they failed of course, but were able to run

**Comment by onilton** [comment]
@PromanSEW I ran directly from sbt. I use Vscode. It seems the tests are not being recognized by sbt

**Comment by PromanSEW** [comment]
@onilton I updated repo with latest deps and set tests directory in `build.sbt`
Tests must run fine now, I checked by `test` command in SBT console

**Comment by onilton** [comment]
@PromanSEW after running the tests I am conviced we are describing different issues, although I can find mine in your PR, it doesn't seem to be the main problem. I will open another issue.

**Comment by PromanSEW** [comment]
@onilton I ran my test and see that `StackOverflowError` gone after update to 2.6.3, but Ebean fields are still in JSON.
So this issue partially fixed in last releases, looks good anyway

**Comment by franzgranlund** [comment]
> .. I will open another issue.

Did you open another issue for this? I also noted the problem with field visibility. Really strange that they decided to serialize private fields..

**Comment by onilton** [comment]
Ok, I've opened a new issue for my problem:

https://github.com/playframework/playframework/issues/10523

**Comment by PromanSEW** [comment]
I think this issue can be closed because `StackOverflowError` is gone, but #10523 is still actual for Ebean fields
