### ISSUE TITLE
SameSite Cookies in Play 2.3.x using netty

### ISSUE THREAD

**Issue by Heyrows** [playframework/playframework#9987]
### Play Version

2.3.10

### API

Scala

### Operating System

Linux - Debian 9.5

### JDK

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### The Issue

Hello, i'm a developper at Prismic.

Chrome 80 is coming out in February 2020 and it will bring some new changes to the way cookies are being handled, the SameSite attributes will be added and mandatory.
The SameSite attribute does not exist yet in Play 2.3.10, the current creation of Cookies is based on the Netty cookie model without the SameSite attribute.
I would like to make a PR which logic is based from the latest version of play to split the Set-Cookie header without using Netty to encode and decode the cookie.
This PR would update the branch 2.3.x so that a new release 2.3.11 could be created.

The code is already done but i'm currently having trouble to test it with my project.
I can't figure out a way to publish Locally a version of play for scala 2.11
Any advice would be welcome.

**Comment by renatocaval** [comment]
Hi @Heyrows, 

The default Scala version in 2.3.x is 2.10, you need to first switch to 2.11 by calling `++2.11.12` inside sbt.

```shell
framework: sbt
++2.11.12
publishLocal
```

Note that Play 2.3.x is a very old version of Play. The latest Play 2.3.x released is from August 2015, 4.5 years ago! We don't make releases for old branches like this one. That said, sending a PR won't make much sense. 

We strongly recommend you to upgrade. I know this will require lots of work because your app is lagging behind. If you can't do it right now, you will have to publish your fork in your own repository and keep maintaining it yourself. Of course, this is NOT the recommended way, but it won't make much difference because the 2.3.x is so old that you won't get updates anyway. 

Again, we recommend you to upgrade as soon as possible. Not only because of that particular issue, but there are also many other improvements and security fixes that you are not getting if you stay in such an old version. Especially the security updates should be a major concern. Software is a living thing, the more you left if behind, the harder it is to upgrade it. You need to keep it in good shape.

**Comment by renatocaval** [comment]
@Heyrows, I will close the issue. As explained above, branch 2.3.x is EOL.

**Comment by kcsham** [comment]
@Heyrows do you have the workaround posted or in a public fork for play 2.3?

**Comment by Heyrows** [comment]
@kcsham I have a fork on my account with a branch called ac/SplitSetHeaderCookie.
I reused what was done in recent versions and modified the encoding of cookies.
To complete it, you need in your project:
- add a cookie on a response like before
- get the header Set-Cookie and modify it to add the samesite attribute (cookies are now parse using ";;")
- set the header Set-Cookie on your response with the new value
- send the response.
